var h;h||=typeof Module != 'undefined' ? Module : {};h.expectedDataFileDownloads||(h.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a=typeof ENVIRONMENT_IS_WASM_WORKER!="undefined"&&ENVIRONMENT_IS_WASM_WORKER;typeof ENVIRONMENT_IS_PTHREAD!="undefined"&&ENVIRONMENT_IS_PTHREAD||a||async function(b){async function c(m,n){h.dataFileDownloads||(h.dataFileDownloads={});try{var t=await fetch(m)}catch(H){throw Error(`Network Error: ${m}`,{e:H});}if(!t.ok)throw Error(`${t.status}: ${t.url}`);var v=[];n=Number(t.headers.get("Content-Length")||n);var C=0;h.setStatus&&h.setStatus("Downloading data...");for(t=t.body.getReader();;){var D;
({done:D,value:G}=await t.read());if(D)break;v.push(G);C+=G.length;h.dataFileDownloads[m]={loaded:C,total:n};var G=D=0;for(var I of Object.values(h.dataFileDownloads))D+=I.loaded,G+=I.total;h.setStatus&&h.setStatus(`Downloading data... (${D}/${G})`)}m=new Uint8Array(v.map(H=>H.length).reduce((H,T)=>H+T,0));I=0;for(let H of v)m.set(H,I),I+=H.length;return m.buffer}async function d(m){m.addRunDependency("datafile_/Users/shenyiwen/projects/hello_world/bin/emscripten/hello_world/hello_world.data");m.preloadResults||
(m.preloadResults={});m.preloadResults["/Users/shenyiwen/projects/hello_world/bin/emscripten/hello_world/hello_world.data"]={pj:!1};k||=await f;await async function(n){if(!n)throw Error("Loading data file failed.");if(n.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+n.constructor.name);n=new Uint8Array(n);for(var t of b.files)m.FS_createDataFile(t.filename,null,n.subarray(t.start,t.end),!0,!0,!0);m.removeRunDependency("datafile_/Users/shenyiwen/projects/hello_world/bin/emscripten/hello_world/hello_world.data")}(k)}
typeof window==="object"?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):typeof process==="undefined"&&typeof location!=="undefined"&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var e=h.locateFile?h.locateFile("hello_world.data",""):"hello_world.data",g=b.remote_package_size,f,k=h.getPreloadedPackage&&h.getPreloadedPackage(e,g);k||(f=c(e,g));h.FS_createPath?d(h):(h.preRun||(h.preRun=[]),h.preRun.push(d))}({files:[{filename:"/assets.dat",
start:0,end:4702074}],remote_package_size:4702074})})();var aa=[],ba=globalThis.document?.currentScript?.src,ca="",da;try{ca=(new URL(".",ba)).href}catch{}da=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var ea=console.log.bind(console),l=console.error.bind(console),fa,ha=!1;class ia{}class ja extends ia{}
function ka(){if(!p?.buffer?.resizable){var a=la.buffer;p=new Int8Array(a);ma=new Int16Array(a);q=new Uint8Array(a);na=new Uint16Array(a);r=new Int32Array(a);u=new Uint32Array(a);w=new Float32Array(a);x=new Float64Array(a);y=new BigInt64Array(a)}}function oa(){var a=h.preRun;a&&(typeof a=="function"&&(a=[a]),pa.push(...a));for(a=pa;a.length>0;)a.shift()(h)}function qa(){var a=h.postRun;a&&(typeof a=="function"&&(a=[a]),ra.push(...a));for(a=ra;a.length>0;)a.shift()(h)}
function z(a){a=`Aborted(${a})`;l(a);ha=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var sa;async function ta(a){if(!fa)try{var b=await da(a);return new Uint8Array(b)}catch{}if(a==sa&&fa)a=new Uint8Array(fa);else throw"both async and sync fetching of the wasm failed";return a}async function ua(a,b){try{var c=await ta(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),z(d)}}
async function va(a){var b=sa;if(!fa)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return ua(b,a)}class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var p,ra=[],pa=[],u;class xa{constructor(a){this.uh=a-24}init(a,b){u[this.uh+16>>2]=0;u[this.uh+4>>2]=a;u[this.uh+8>>2]=b}}
var ya=0,za=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Aa=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=za(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ba=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ca=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],
Da=()=>a=>(crypto.getRandomValues(a),0),Ea=a=>(Ea=Da())(a),Fa=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c=c.charAt(0)==="/"}b=za(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ga=(a,b)=>{function c(f){for(var k=0;k<f.length&&f[k]==="";k++);for(var m=f.length-1;m>=0&&f[m]==="";m--);return k>m?[]:f.slice(k,m-k+1)}a=Fa(a).slice(1);b=Fa(b).slice(1);
a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Ha=globalThis.TextDecoder&&new TextDecoder,A=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(d-b>16&&a.buffer&&Ha)return Ha.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=(e&240)==224?(e&15)<<
12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Ia=[],Ja=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},B=(a,b,c,d)=>{if(!(d>0))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var f=a.codePointAt(g);if(f<=127){if(c>=d)break;b[c++]=f}else if(f<=2047){if(c+1>=d)break;b[c++]=192|f>>6;b[c++]=
128|f&63}else if(f<=65535){if(c+2>=d)break;b[c++]=224|f>>12;b[c++]=128|f>>6&63;b[c++]=128|f&63}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63;b[c++]=128|f>>6&63;b[c++]=128|f&63;g++}}b[c]=0;return c-e},Ka=a=>{var b=Array(Ja(a)+1);a=B(a,b,0,b.length);b.length=a;return b},La=[];function Ma(a,b){La[a]={input:[],output:[],Lg:b};Na(a,Oa)}
var Oa={open(a){var b=La[a.node.jh];if(!b)throw new E(43);a.og=b;a.seekable=!1},close(a){a.og.Lg.dh(a.og)},dh(a){a.og.Lg.dh(a.og)},read(a,b,c,d){if(!a.og||!a.og.Lg.gi)throw new E(60);for(var e=0,g=0;g<d;g++){try{var f=a.og.Lg.gi(a.og)}catch(k){throw new E(29);}if(f===void 0&&!e)throw new E(6);if(f===null||f===void 0)break;e++;b[c+g]=f}e&&(a.node.Ng=Date.now());return e},write(a,b,c,d){if(!a.og||!a.og.Lg.Th)throw new E(60);try{for(var e=0;e<d;e++)a.og.Lg.Th(a.og,b[c+e])}catch(g){throw new E(29);}d&&
(a.node.xg=a.node.ug=Date.now());return e}},Pa={gi(){a:{if(!Ia.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}Ia=Ka(a)}a=Ia.shift()}return a},Th(a,b){b===null||b===10?(ea(A(a.output)),a.output=[]):b!=0&&a.output.push(b)},dh(a){a.output?.length>0&&(ea(A(a.output)),a.output=[])},Ki(){return{ej:25856,gj:5,dj:191,fj:35387,cj:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Li(){return 0},Mi(){return[24,
80]}},Qa={Th(a,b){b===null||b===10?(l(A(a.output)),a.output=[]):b!=0&&a.output.push(b)},dh(a){a.output?.length>0&&(l(A(a.output)),a.output=[])}},F={Jg:null,Bg(){return F.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||(c&61440)===4096)throw new E(63);F.Jg||(F.Jg={dir:{node:{Ag:F.hg.Ag,Mg:F.hg.Mg,fh:F.hg.fh,th:F.hg.th,xh:F.hg.xh,Ah:F.hg.Ah,yh:F.hg.yh,wh:F.hg.wh,zh:F.hg.zh},stream:{Ig:F.ig.Ig}},file:{node:{Ag:F.hg.Ag,Mg:F.hg.Mg},stream:{Ig:F.ig.Ig,read:F.ig.read,write:F.ig.write,
Qh:F.ig.Qh,ji:F.ig.ji}},link:{node:{Ag:F.hg.Ag,Mg:F.hg.Mg,Tg:F.hg.Tg},stream:{}},di:{node:{Ag:F.hg.Ag,Mg:F.hg.Mg},stream:Ra}});c=Sa(a,b,c,d);J(c.mode)?(c.hg=F.Jg.dir.node,c.ig=F.Jg.dir.stream,c.mg={}):(c.mode&61440)===32768?(c.hg=F.Jg.file.node,c.ig=F.Jg.file.stream,c.tg=0,c.mg=F.Ai??(F.Ai=new Uint8Array(0))):(c.mode&61440)===40960?(c.hg=F.Jg.link.node,c.ig=F.Jg.link.stream):(c.mode&61440)===8192&&(c.hg=F.Jg.di.node,c.ig=F.Jg.di.stream);c.Ng=c.xg=c.ug=Date.now();a&&(a.mg[b]=c,a.Ng=a.xg=a.ug=c.Ng);
return c},hg:{Ag(a){var b={};b.zi=(a.mode&61440)===8192?a.id:1;b.Ii=a.id;b.mode=a.mode;b.Ri=1;b.uid=0;b.Fi=0;b.jh=a.jh;J(a.mode)?b.size=4096:(a.mode&61440)===32768?b.size=a.tg:(a.mode&61440)===40960?b.size=a.link.length:b.size=0;b.Ng=new Date(a.Ng);b.xg=new Date(a.xg);b.ug=new Date(a.ug);b.ri=4096;b.si=Math.ceil(b.size/b.ri);return b},Mg(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.tg!=b&&(c=a.mg,a.mg=new Uint8Array(b),a.mg.set(c.subarray(0,
Math.min(b,a.tg))),a.tg=b))},fh(){F.Fh||(F.Fh=new E(44),F.Fh.stack="<generic error, no stack>");throw F.Fh;},th(a,b,c,d){return F.createNode(a,b,c,d)},xh(a,b,c){try{var d=Ta(b,c)}catch(g){}if(d){if(J(a.mode))for(var e in d.mg)throw new E(55);Ua(d)}delete a.parent.mg[a.name];b.mg[c]=a;a.name=c;b.ug=b.xg=a.parent.ug=a.parent.xg=Date.now()},Ah(a,b){delete a.mg[b];a.ug=a.xg=Date.now()},yh(a,b){var c=Ta(a,b),d;for(d in c.mg)throw new E(55);delete a.mg[b];a.ug=a.xg=Date.now()},wh(a){return[".","..",...Object.keys(a.mg)]},
zh(a,b,c){a=F.createNode(a,b,41471,0);a.link=c;return a},Tg(a){if((a.mode&61440)!==40960)throw new E(28);return a.link}},ig:{read(a,b,c,d,e){if(e>=a.node.tg)return 0;d=Math.min(a.node.tg-e,d);b.set(a.node.mg.subarray(e,e+d),c);return d},write(a,b,c,d,e,g){b.buffer===p.buffer&&(g=!1);if(!d)return 0;a=a.node;a.xg=a.ug=Date.now();if(g)a.mg=b.subarray(c,c+d),a.tg=d;else if(a.tg||e){g=e+d;var f=a.mg.length;f>=g||(g=Math.max(g,f*(f<1048576?2:1.125)>>>0),f&&(g=Math.max(g,256)),f=a.mg.subarray(0,a.tg),a.mg=
new Uint8Array(g),a.mg.set(f));a.mg.set(b.subarray(c,c+d),e);a.tg=Math.max(a.tg,e+d)}else a.mg=b.slice(c,c+d),a.tg=d;return d},Ig(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&61440)===32768&&(b+=a.node.tg);if(b<0)throw new E(28);return b},Qh(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new E(43);a=a.node.mg;if(e&2||a.buffer!==p.buffer){d=!0;z();e=void 0;if(!e)throw new E(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);p.set(a,e)}}else d=!1,
e=a.byteOffset;return{uh:e,$i:d}},ji(a,b,c,d){F.ig.write(a,b,0,d,c,!1);return 0}}},Va=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Wa=async a=>{a=await da(a);return new Uint8Array(a)},Xa=null,Ya=async()=>Xa,Za=0,$a=null,ab=()=>{Za||(Xa=new Promise(a=>$a=a));Za++},bb=[],eb=async(a,b)=>{typeof cb!="undefined"&&db();for(var c of bb)if(c.canHandle(b))return c.handle(a,b);return a},fb=null,gb={},hb=[],ib=1,jb=null,kb=!1,lb=!0,E=class{name="ErrnoError";constructor(a){this.lg=a}},mb=class{shared={};node=
null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},nb=class{hg={};ig={};Pg=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Bg=a.Bg;this.id=ib++;this.name=b;this.mode=c;this.jh=d;this.Ng=this.xg=this.ug=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?this.mode|=146:this.mode&=-147}get Oi(){return J(this.mode)}get Ni(){return(this.mode&
61440)===8192}Ti(){}};
function K(a,b={}){if(!a)throw new E(44);b.Kh??(b.Kh=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(k=>!!k);for(var d=fb,e="/",g=0;g<a.length;g++){var f=g===a.length-1;if(f&&b.parent)break;if(a[g]!==".")if(a[g]==="..")if(e=Ba(e),d===d.parent){a=e+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{e=Aa(e+"/"+a[g]);try{d=Ta(d,a[g])}catch(k){if(k?.lg===44&&f&&b.Si)return{path:e};throw k;}!d.Pg||f&&!b.Kh||(d=d.Pg.root);if((d.mode&61440)===40960&&(!f||b.Wg)){if(!d.hg.Tg)throw new E(52);
d=d.hg.Tg(d);d.charAt(0)==="/"||(d=Ba(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new E(32);}function ob(a){for(var b;;){if(a===a.parent)return a=a.Bg.ii,b?a[a.length-1]!=="/"?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function pb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%jb.length}function qb(a){var b=pb(a.parent.id,a.name);a.Yg=jb[b];jb[b]=a}
function Ua(a){var b=pb(a.parent.id,a.name);if(jb[b]===a)jb[b]=a.Yg;else for(b=jb[b];b;){if(b.Yg===a){b.Yg=a.Yg;break}b=b.Yg}}function Ta(a,b){var c=J(a.mode)?(c=rb(a,"x"))?c:a.hg.fh?0:2:54;if(c)throw new E(c);for(c=jb[pb(a.id,b)];c;c=c.Yg){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.hg.fh(a,b)}function Sa(a,b,c,d){a=new nb(a,b,c,d);qb(a);return a}function J(a){return(a&61440)===16384}
function rb(a,b){return lb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function sb(a,b){if(!J(a.mode))return 54;try{return Ta(a,b),20}catch(c){}return rb(a,"wx")}function tb(a,b,c){try{var d=Ta(a,b)}catch(e){return e.lg}if(a=rb(a,"wx"))return a;if(c){if(!J(d.mode))return 54;if(d===d.parent||ob(d)==="/")return 10}else if(J(d.mode))return 31;return 0}function ub(a,b){if(!a)throw new E(b);return a}
function L(a){a=hb[a];if(!a)throw new E(8);return a}function vb(a,b=-1){a=Object.assign(new mb,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!hb[b])break a;throw new E(33);}a.fd=b;return hb[b]=a}function wb(a,b=-1){a=vb(a,b);a.ig?.nj?.(a);return a}function xb(a,b){var c=void 0,d=c?null:a;c??=a.hg.Mg;ub(c,63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new E(22);throw e;}}var Ra={open(a){a.ig=gb[a.node.jh].ig;a.ig.open?.(a)},Ig(){throw new E(70);}};function Na(a,b){gb[a]={ig:b}}
function yb(a,b){var c=b==="/";if(c&&fb)throw new E(10);if(!c&&b){var d=K(b,{Kh:!1});b=d.path;d=d.node;if(d.Pg)throw new E(10);if(!J(d.mode))throw new E(54);}b={type:a,vj:{},ii:b,Qi:[]};a=a.Bg(b);a.Bg=b;b.root=a;c?fb=a:d&&(d.Pg=b,d.Bg&&d.Bg.Qi.push(b))}function zb(a,b,c){var d=K(a,{parent:!0}).node;a=Ca(a);if(!a)throw new E(28);if(a==="."||a==="..")throw new E(20);var e=sb(d,a);if(e)throw new E(e);if(!d.hg.th)throw new E(63);return d.hg.th(d,a,b,c)}
function Ab(a,b=438){return zb(a,b&4095|32768,0)}function M(a,b=511){return zb(a,b&1023|16384,0)}function Bb(a,b,c){typeof c=="undefined"&&(c=b,b=438);return zb(a,b|8192,c)}function Cb(a,b){if(!Fa(a))throw new E(44);var c=K(b,{parent:!0}).node;if(!c)throw new E(44);b=Ca(b);var d=sb(c,b);if(d)throw new E(d);if(!c.hg.zh)throw new E(63);c.hg.zh(c,b,a)}
function Db(a){var b=K(a,{parent:!0}).node;a=Ca(a);var c=Ta(b,a),d=tb(b,a,!0);if(d)throw new E(d);if(!b.hg.yh)throw new E(63);if(c.Pg)throw new E(10);b.hg.yh(b,a);Ua(c)}function Eb(a){var b=K(a,{parent:!0}).node;if(!b)throw new E(44);a=Ca(a);var c=Ta(b,a),d=tb(b,a,!1);if(d)throw new E(d);if(!b.hg.Ah)throw new E(63);if(c.Pg)throw new E(10);b.hg.Ah(b,a);Ua(c)}function Fb(a,b){a=K(a,{Wg:!b}).node;return ub(a.hg.Ag,63)(a)}
function Gb(a,b){a=typeof a=="string"?K(a,{Wg:!0}).node:a;xb(a,{mode:b&4095|a.mode&-4096,ug:Date.now(),mj:void 0})}
function Hb(a,b,c=438){if(a==="")throw new E(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var g=K(a,{Wg:!(b&131072),Si:!0});d=g.node;a=g.path}g=!1;if(b&64)if(d){if(b&128)throw new E(20);}else{if(e)throw new E(31);d=zb(a,c|511,0);g=!0}if(!d)throw new E(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&!J(d.mode))throw new E(54);
if(!g&&(d?(d.mode&61440)===40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=J(d.mode)&&(e!=="r"||b&576)?31:rb(d,e)):e=44,e))throw new E(e);if(b&512&&!g){e=d;e=typeof e=="string"?K(e,{Wg:!0}).node:e;if(J(e.mode))throw new E(31);if((e.mode&61440)!==32768)throw new E(28);if(a=rb(e,"w"))throw new E(a);xb(e,{size:0,timestamp:Date.now()})}b=vb({node:d,path:ob(d),flags:b&-131713,seekable:!0,position:0,ig:d.ig,Yi:[],error:!1});b.ig.open&&b.ig.open(b);g&&Gb(d,c&511);return b}
function Ib(a){if(a.fd===null)throw new E(8);a.Sg&&(a.Sg=null);a.node?.Ti();try{a.ig.close&&a.ig.close(a)}catch(b){throw b;}finally{hb[a.fd]=null}a.fd=null}function Jb(a,b,c){if(a.fd===null)throw new E(8);if(!a.seekable||!a.ig.Ig)throw new E(70);if(c!=0&&c!=1&&c!=2)throw new E(28);a.position=a.ig.Ig(a,b,c);a.Yi=[];return a.position}
function Kb(a,b,c,d,e,g){if(d<0||e<0)throw new E(28);if(a.fd===null)throw new E(8);if((a.flags&2097155)===0)throw new E(8);if(J(a.node.mode))throw new E(31);if(!a.ig.write)throw new E(28);a.seekable&&a.flags&1024&&Jb(a,0,2);var f=typeof e!="undefined";if(!f)e=a.position;else if(!a.seekable)throw new E(70);b=a.ig.write(a,b,c,d,e,g);f||(a.position+=b);return b}
function Lb(a,b){a=typeof a=="string"?a:ob(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Aa(a+"/"+c);try{M(d)}catch(e){if(e.lg!=20)throw e;}a=d}}return d}function Mb(a,b,c,d){a=Aa((typeof a=="string"?a:ob(a))+"/"+b);return Ab(a,Va(c,d))}function Nb(a,b,c,d,e,g){var f=b;a&&(a=typeof a=="string"?a:ob(a),f=b?Aa(a+"/"+b):a);a=Va(d,e);f=Ab(f,a);c&&(typeof c=="string"&&(c=Ka(c)),c.subarray||(c=new Uint8Array(c)),Gb(f,a|146),b=Hb(f,577),Kb(b,c,0,c.length,0,g),Ib(b),Gb(f,a))}
function Ob(a,b,c,d){a=Aa((typeof a=="string"?a:ob(a))+"/"+b);b=Va(!!c,!!d);Ob.hi??(Ob.hi=64);var e=Ob.hi++<<8|0;Na(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,f,k,m){for(var n=0,t=0;t<m;t++){try{var v=c()}catch(C){throw new E(29);}if(v===void 0&&!n)throw new E(6);if(v===null||v===void 0)break;n++;f[k+t]=v}n&&(g.node.Ng=Date.now());return n},write(g,f,k,m){for(var n=0;n<m;n++)try{d(f[k+n])}catch(t){throw new E(29);}m&&(g.node.xg=g.node.ug=Date.now());return n}});return Bb(a,
b,e)}function Pb(a){if(!(a.Ni||a.Oi||a.link||a.mg))if(globalThis.XMLHttpRequest)z("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.mg=(void 0)(a.url)}catch(b){throw new E(29);}}
function Qb(a,b,c,d,e){class g{Kg=!1;qg=[];rg=void 0;eh=0;Xg=0;get(n){if(!(n>this.length-1||n<0)){var t=n%this.ih;return this.rg(n/this.ih|0)[t]}}Ui(n){this.rg=n}hh(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);n.status>=200&&n.status<300||n.status===304||z(`Couldn't load ${c}. Status: ${n.status}`);var t=Number(n.getResponseHeader("Content-length")),v,C=(v=n.getResponseHeader("Accept-Ranges"))&&v==="bytes";n=(v=n.getResponseHeader("Content-Encoding"))&&v==="gzip";var D=1048576;C||(D=
t);var G=this;G.Ui(I=>{var H=I*D,T=(I+1)*D-1;T=Math.min(T,t-1);if(typeof G.qg[I]=="undefined"){var Y=G.qg;H>T&&z(`invalid range (${H}, ${T}) or no bytes requested!`);T>t-1&&z(`only ${t} bytes available! programmer error!`);var O=new XMLHttpRequest;O.open("GET",c,!1);t!==D&&O.setRequestHeader("Range",`bytes=${H}-${T}`);O.responseType="arraybuffer";O.overrideMimeType&&O.overrideMimeType("text/plain; charset=x-user-defined");O.send(null);O.status>=200&&O.status<300||O.status===304||z(`Couldn't load ${c}. Status: ${O.status}`);
H=O.response!==void 0?new Uint8Array(O.response||[]):Ka(O.responseText??"");Y[I]=H}typeof G.qg[I]=="undefined"&&z("doXHR failed!");return G.qg[I]});if(n||!t)D=t=1,D=t=this.rg(0).length,ea("LazyFiles on gzip forces download of the whole file when length is accessed");this.eh=t;this.Xg=D;this.Kg=!0}get length(){this.Kg||this.hh();return this.eh}get ih(){this.Kg||this.hh();return this.Xg}}if(globalThis.XMLHttpRequest){z("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var f=new g;var k=void 0}else k=c,f=void 0;var m=Mb(a,b,d,e);f?m.mg=f:k&&(m.mg=null,m.url=k);Object.defineProperties(m,{tg:{get:function(){return this.mg.length}}});a={};for(let [n,t]of Object.entries(m.ig))a[n]=(...v)=>{Pb(m);return t(...v)};a.read=(n,t,v,C,D)=>{Pb(m);n=n.node.mg;if(D>=n.length)t=0;else{C=Math.min(n.length-D,C);if(n.slice)for(var G=0;G<C;G++)t[v+G]=n[D+G];else for(G=0;G<C;G++)t[v+G]=n.get(D+G);t=C}return t};a.Qh=()=>{Pb(m);z();throw new E(48);};m.ig=a;return m}
var N={},q,Rb=(a,b)=>a?A(q,a,b):"",r,y;function Sb(a,b,c){if(b.charAt(0)==="/")return b;a=a===-100?"/":L(a).path;if(b.length==0){if(!c)throw new E(44);return a}return a+"/"+b}
function Tb(a,b){u[a>>2]=b.zi;u[a+4>>2]=b.mode;u[a+8>>2]=b.Ri;u[a+12>>2]=b.uid;u[a+16>>2]=b.Fi;u[a+20>>2]=b.jh;y[a+24>>3]=BigInt(b.size);r[a+32>>2]=4096;r[a+36>>2]=b.si;var c=b.Ng.getTime(),d=b.xg.getTime(),e=b.ug.getTime();y[a+40>>3]=BigInt(Math.floor(c/1E3));u[a+48>>2]=c%1E3*1E3*1E3;y[a+56>>3]=BigInt(Math.floor(d/1E3));u[a+64>>2]=d%1E3*1E3*1E3;y[a+72>>3]=BigInt(Math.floor(e/1E3));u[a+80>>2]=e%1E3*1E3*1E3;y[a+88>>3]=BigInt(b.Ii);return 0}
var Vb=void 0,Wb=()=>{var a=r[+Vb>>2];Vb+=4;return a},ma,Xb=a=>{var b=Error().stack.toString(),c=b.split("\n");b="";var d=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),e=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),g;for(g of c){var f=e.exec(g);if(f?.length==5){c=f[1];var k=f[2];var m=f[3];f=f[4]}else if(f=d.exec(g),f?.length>=4)c=f[1],k=f[2],m=f[3],f=f[4]|0;else{b+=g+"\n";continue}c=="_emscripten_log"||c=="_emscripten_get_callstack"?b="":a&24&&(a&64&&(k=k.substring(k.replace(/\\/g,"/").lastIndexOf("/")+
1)),b+=`    at ${c} (${k}:${m}:${f})\n`)}return b=b.replace(/\s+$/,"")},Yb=a=>a%4===0&&(a%100!==0||a%400===0),Zb=[0,31,60,91,121,152,182,213,244,274,305,335],$b=[0,31,59,90,120,151,181,212,243,273,304,334],ac=[],x,bc=(a,b)=>{ac.length=0;for(var c;c=q[a++];){var d=c!=105;d&=c!=112;b+=d&&b%8?4:0;ac.push(c==112?u[b>>2]:c==106?y[b>>3]:c==105?r[b>>2]:x[b>>3]);b+=d?8:4}return ac},dc=(a,b,c)=>{b=bc(b,c);return cc[a](...b)},nc=(a,b)=>{ec=a;fc=b;if(!hc)return 1;if(a==0)ic=function(){setTimeout(jc,Math.max(0,
kc+b-performance.now())|0)};else if(a==1)ic=function(){lc(jc)};else{if(!mc)if(globalThis.scheduler)mc=scheduler.postTask.bind(scheduler);else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);mc=d=>{c.push(d);postMessage("setimmediate","*")}}ic=function(){mc(jc)}}return 0},oc=a=>{if(!(a instanceof wa||a=="unwind"))throw a;},yc=(a,b,c,d,e)=>{hc=a;pc=d;var g=qc;jc=function(){if(!ha)if(rc.length>0){var f=rc.shift();f.qj(f.aj);if(sc){var k=sc,m=k%
1==0?k-1:Math.floor(k);sc=f.ij?m:(8*k+(m+.5))/9}h.setStatus&&(f=h.statusMessage||"Please wait...",k=sc??0,m=tc.oj??0,k?k<m?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(f):h.setStatus(""));g<qc||setTimeout(jc,0)}else if(!(g<qc))if(uc=uc+1|0,ec==1&&fc>1&&uc%fc!=0)ic();else{ec==0&&(kc=performance.now());a:if(!ha){for(f of vc)if(f()===!1)break a;wc(a);for(k of xc)k()}g<qc||ic()}};e||(b>0?nc(0,1E3/b):nc(1,1),ic());if(c)throw"unwind";},wc=a=>{if(!ha)try{a()}catch(b){oc(b)}finally{}},
hc=null,ic=null,qc=0,pc=0,ec=0,fc=0,uc=0,rc=[],vc=[],xc=[];function zc(){ic&&(ic=null,qc++)}var Ac=0;function lc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(Ac)for(;b+2>=Ac;)Ac+=1E3/60;else Ac=b+1E3/60;setTimeout(a,Math.max(Ac-b,0))}}var tc={},kc,jc,mc,sc;function Bc(a){var b=P.vg[a];b.target.removeEventListener(b.sg,b.fi,b.Eg);P.vg.splice(a,1)}
function Cc(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var k=0;k<g.length;k++)if(g[k]!=f[k])return!1;return!0}for(var e of P.Og)if(e.Vh==a&&d(e.bi,c))return;P.Og.push({Vh:a,ki:b,bi:c});P.Og.sort((g,f)=>g.ki-f.ki)}function Dc(a){P.Og=P.Og.filter(b=>b.Vh!=a)}function Ec(){return navigator.userActivation?navigator.userActivation.isActive:P.Nh&&P.ui.ai}function Fc(){if(Ec()){var a=P.Og;P.Og=[];for(var b of a)b.Vh(...b.bi)}}
function Gc(a){if(!a.target)return-4;if(a.wg)a.fi=function(c){++P.Nh;P.ui=a;Fc();a.Hg(c);Fc();--P.Nh},a.target.addEventListener(a.sg,a.fi,a.Eg),P.vg.push(a);else for(var b=0;b<P.vg.length;++b)P.vg[b].target==a.target&&P.vg[b].sg==a.sg&&Bc(b--);return 0}function Hc(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var P={bj:0,Mh:0,Oh:0,tj:0,$h:0,Xh:0,Jh:0,kj:0,Rh:0,jj:0,Lh:0,Sh:0,Zh:0,Aj:0,xj(){for(;P.vg.length;)Bc(P.vg.length-1);P.Og=[]},Nh:0,Og:[],vg:[],Wi:(a,b)=>{for(var c=0;c<P.vg.length;++c)P.vg[c].target!=a||b&&b!=P.vg[c].sg||Bc(c--)},yj(a){var b=!1;for(let c=0;c<P.vg.length;++c){let d=P.vg[c];d.target===a.target&&d.zg===a.zg&&d.wg===a.wg&&d.Fg===a.Fg&&(Bc(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled??document.webkitFullscreenEnabled}},Ic=[0,document,window],Q=a=>{a=
a>2?a?A(q,a):"":a;return Ic[a]||document.querySelector(a)},Kc=a=>{var b=Ja(a)+1,c=Jc(b);B(a,q,c,b);return c},Nc=a=>{var b=Lc(),c=Jc(8),d=c+4;a=Kc(a.id);if(a=Q(a))r[c>>2]=a.width,r[d>>2]=a.height;c=[r[c>>2],r[d>>2]];Mc(b);return c},Oc=(a,b,c)=>{a=Q(a);if(!a)return-4;a.width=b;a.height=c;return 0},Pc=(a,b,c)=>{if(a.hj){var d=Lc();a=Kc(a.id);Oc(a,b,c);Mc(d)}else a.width=b,a.height=c},Qc=0,Rc=[],R=a=>{var b=Rc[a];b||(Rc[a]=b=Sc.get(a));return b},Tc=a=>{function b(){if(!(document.fullscreenElement??document.webkitFullscreenElement)){document.removeEventListener("fullscreenchange",
b);document.removeEventListener("webkitfullscreenchange",b);Pc(a,d,e);a.style.width=g;a.style.height=f;a.style.backgroundColor=k;m||(document.body.style.backgroundColor="white");document.body.style.backgroundColor=m;a.style.paddingLeft=n;a.style.paddingRight=t;a.style.paddingTop=v;a.style.paddingBottom=C;a.style.marginLeft=D;a.style.marginRight=G;a.style.marginTop=I;a.style.marginBottom=H;document.body.style.margin=T;document.documentElement.style.overflow=Y;document.body.scroll=O;a.style.imageRendering=
se;a.Zg&&a.Zg.Rg.viewport(0,0,d,e);var Ub=Qc;Ub.mh&&R(Ub.mh)(37,0,Ub.ci)}}var c=Nc(a),d=c[0],e=c[1],g=a.style.width,f=a.style.height,k=a.style.backgroundColor,m=document.body.style.backgroundColor,n=a.style.paddingLeft,t=a.style.paddingRight,v=a.style.paddingTop,C=a.style.paddingBottom,D=a.style.marginLeft,G=a.style.marginRight,I=a.style.marginTop,H=a.style.marginBottom,T=document.body.style.margin,Y=document.documentElement.style.overflow,O=document.body.scroll,se=a.style.imageRendering;document.addEventListener("fullscreenchange",
b);document.addEventListener("webkitfullscreenchange",b)},Uc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Vc=a=>Ic.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},Wc=(a,b)=>{if(b.Uh!=0||b.Ch!=0){Tc(a);var c=b.Xi?innerWidth:screen.width,d=b.Xi?innerHeight:screen.height,e=Vc(a),g=e.width;e=e.height;var f=Nc(a),k=f[0];f=f[1];b.Uh==3?(Uc(a,(d-e)/2,(c-g)/2),c=g,d=e):b.Uh==2&&(c*f<k*d?(g=f*c/k,Uc(a,(d-g)/2,0),d=g):(g=k*d/f,Uc(a,0,(c-g)/
2),c=g));var m;(m=a.style).backgroundColor||(m.backgroundColor="black");let n;(n=document.body.style).backgroundColor||(n.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";b.Ei==1&&(a.style.imageRendering="optimizeSpeed",a.style.imageRendering="-moz-crisp-edges",a.style.imageRendering="-o-crisp-edges",a.style.imageRendering="-webkit-optimize-contrast",a.style.imageRendering="optimize-contrast",a.style.imageRendering="crisp-edges",a.style.imageRendering="pixelated");m=b.Ch==2?devicePixelRatio:
1;b.Ch!=0&&(c=c*m|0,d=d*m|0,Pc(a,c,d),a.Zg&&a.Zg.Rg.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return P.fullscreenEnabled()?-3:-1;Qc=b;b.mh&&R(b.mh)(37,0,b.ci);return 0},Xc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Yc=a=>{var b=document.fullscreenElement??document.webkitFullscreenElement,c=!!b;p[a]=c;p[a+1]=P.fullscreenEnabled();
var d=c?b:P.Vi,e=d?.id??"";B(Hc(d),q,a+2,128);B(e,q,a+130,128);r[a+260>>2]=d?.clientWidth??0;r[a+264>>2]=d?.clientHeight??0;r[a+268>>2]=screen.width;r[a+272>>2]=screen.height;c&&(P.Vi=b)},Zc=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+c*8+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)p[a+c+1040]=b.buttons[c].pressed,x[a+c*8+528>>3]=b.buttons[c].value;p[a+1104]=b.connected;r[a+1108>>2]=b.index;r[a+8>>2]=b.axes.length;r[a+12>>2]=b.buttons.length;B(b.id,q,a+1112,64);B(b.mapping,
q,a+1176,64)},$c=a=>{setTimeout(()=>{wc(a)},1E4)},ad=[];
function db(){function a(){}bd||(bd=!0,bb.push({canHandle:b=>!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(b),handle:async(b,c)=>{var d=new Blob([b],{type:cd(c)});d.size!==b.length&&(d=new Blob([(new Uint8Array(b)).buffer],{type:cd(c)}));var e=URL.createObjectURL(d);return new Promise((g,f)=>{var k=new Image;k.onload=()=>{var m=document.createElement("canvas");m.width=k.width;m.height=k.height;m.getContext("2d").drawImage(k,0,0);URL.revokeObjectURL(e);g(b)};k.onerror=()=>{l(`Image ${e} could not be decoded`);
f()};k.src=e})}}),bb.push({canHandle:b=>!h.noAudioDecoding&&b.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(b,c)=>new Promise(d=>{function e(){g||(g=!0,d(b))}var g=!1,f=URL.createObjectURL(new Blob([b],{type:cd(c)})),k=new Audio;k.addEventListener("canplaythrough",()=>e(k));k.onerror=()=>{if(!g){l(`warning: browser could not fully decode audio ${c}, trying slower base64 approach`);var m="data:audio/x-"+c.slice(-3)+";base64,",n="",t=0,v=0,C;for(C of b)for(t=t<<8|C,v+=8;v>=6;){var D=t>>v-6&63;
v-=6;n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[D]}v==2?(n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],n+="=="):v==4&&(n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],n+="=");k.src=m+n;e(k)}};k.src=f;$c(()=>{e(k)})})}),h.canvas&&document.addEventListener("pointerlockchange",a))}function dd(a){a=a.getContext("2d");if(!a)return null;h.ctx=a;ad.forEach(b=>b());db();return a}
function cd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var cb={},bd,S,ed=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");return a.getSupportedExtensions()?.filter(c=>
b.includes(c))??[]},fd=1,gd=[],U=[],hd=[],jd=[],kd=[],V=[],ld=[],md=[],W=[],nd=[],od=[],pd=[],qd={},rd={},sd=4,td=0,ud=a=>{for(var b=fd++,c=a.length;c<b;c++)a[c]=null;return b},vd=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=S[c](),f=g&&ud(d);g?(g.name=f,d[f]=g):X||=1282;r[b+e*4>>2]=f}},xd=(a,b)=>{a.ih||(a.ih=a.getContext,a.getContext=function(d,e){e=a.ih(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?wd(c,b):0},wd=(a,b)=>{var c=ud(md),d={handle:c,
attributes:b,version:b.Pi,Rg:a};a.canvas&&(a.canvas.Zg=d);md[c]=d;if(typeof b.ei=="undefined"||b.ei)if((a=d)||(a=yd),!a.Hi){a.Hi=!0;b=a.Rg;b.uj=b.getExtension("WEBGL_multi_draw");b.Di=b.getExtension("EXT_polygon_offset_clamp");b.Ci=b.getExtension("EXT_clip_control");b.Zi=b.getExtension("WEBGL_polygon_mode");b.lj=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.rj=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");a.version>=2&&(b.yg=b.getExtension("EXT_disjoint_timer_query_webgl2"));
if(a.version<2||!b.yg)b.yg=b.getExtension("EXT_disjoint_timer_query");for(var e of ed(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},X,yd,zd=a=>{S.bindVertexArray(ld[a])},w,Ad=(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2];S.deleteVertexArray(ld[d]);ld[d]=null}},Bd=(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},Cd=[],Dd=(a,b)=>{for(var c=Cd[a],d=0;d<a;d++)c[d]=r[b+d*4>>2];S.drawBuffers(c)},Ed=(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},Fd=(a,b)=>{vd(a,b,"createVertexArray",
ld)},Gd=(a,b,c,d,e,g,f,k)=>{b=U[b];if(a=S[a](b,c))d=k&&B(a.name,q,k,d),e&&(r[e>>2]=d),g&&(r[g>>2]=a.size),f&&(r[f>>2]=a.type)},Hd=(a,b)=>{u[a>>2]=b;u[a+4>>2]=(b-u[a>>2])/4294967296},Id=()=>{var a=ed(S);return a=a.concat(a.map(b=>"GL_"+b))},Jd=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:c!=0&&c!=1&&(X||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=S.getParameter(34467);d=e?e.length:0;break;case 33309:if(yd.version<2){X||=1282;return}d=Id().length;break;case 33307:case 33308:if(yd.version<
2){X||=1280;return}d=a==33307?3:0}if(d===void 0)switch(e=S.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":X||=1280;return;case "object":if(e===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:X||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||
e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:r[b+a*4>>2]=e[a];break;case 2:w[b+a*4>>2]=e[a];break;case 4:p[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){X||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:X||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:Hd(b,d);break;case 0:r[b>>
2]=d;break;case 2:w[b>>2]=d;break;case 4:p[b]=d?1:0}}else X||=1281},Kd=(a,b,c,d)=>{if(c){b=S.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(b===null)switch(a){case 35983:case 35368:a=0;break;default:X||=1280;return}else if(b instanceof WebGLBuffer)a=b.name|0;else{X||=1280;return}break;default:X||=1280;return}switch(d){case 1:Hd(c,a);break;case 0:r[c>>2]=a;break;case 2:w[c>>2]=a;break;case 4:p[c]=a?1:0;break;default:z("internal emscriptenWebGLGetIndexed() error, bad type: "+
d)}}else X||=1281},Ld=(a,b,c)=>{if(c){a=W[a];b=yd.version<2?S.yg.getQueryObjectEXT(a,b):S.getQueryParameter(a,b);var d;typeof b=="boolean"?d=b?1:0:d=b;Hd(c,d)}else X||=1281},Md=(a,b,c)=>{if(c){a=S.yg.getQueryObjectEXT(W[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;r[c>>2]=d}else X||=1281},Od=a=>{var b=Ja(a)+1,c=Nd(b);c&&B(a,q,c,b);return c},Pd=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),Qd=a=>{var b=a.kh,c=a.mi,d;if(!b){a.kh=b={};a.li={};var e=S.getProgramParameter(a,35718);for(d=0;d<e;++d){var g=S.getActiveUniform(a,
d);var f=g.name;g=g.size;var k=Pd(f);k=k>0?f.slice(0,k):f;var m=a.Yh;a.Yh+=g;c[k]=[g,m];for(f=0;f<g;++f)b[m]=f,a.li[m++]=k}}},Z=(a,b)=>{if(a){var c=a.kh[b];typeof c=="number"&&(a.kh[b]=c=S.getUniformLocation(a,a.li[b]+(c>0?`[${c}]`:"")));return c}X||=1282},Rd=(a,b,c,d)=>{if(c)if(a=U[a],Qd(a),a=S.getUniform(a,Z(a,b)),typeof a=="number"||typeof a=="boolean")switch(d){case 0:r[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+b*4>>2]=a[b];break;case 2:w[c+b*4>>2]=a[b]}else X||=
1281},Sd=(a,b,c,d)=>{if(c)if(a=S.getVertexAttrib(a,b),b==34975)r[c>>2]=a&&a.name;else if(typeof a=="number"||typeof a=="boolean")switch(d){case 0:r[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:r[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+b*4>>2]=a[b];break;case 2:w[c+b*4>>2]=a[b];break;case 5:r[c+b*4>>2]=Math.fround(a[b])}else X||=1281},Td=(a,b,c)=>{Sd(a,b,c,0)},Ud=a=>(a=ld[a])?S.isVertexArray(a):0,na,Vd=a=>{a-=5120;return a==0?p:a==1?q:a==2?ma:a==4?r:a==6?w:a==5||a==28922||
a==28520||a==30779||a==30782?u:na},Wd=(a,b,c,d,e)=>{a=Vd(a);b=d*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT*(td||c)+sd-1&-sd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Xd=(a,b)=>{S.vertexAttribDivisor(a,b)},Yd=(a,b)=>{if(!P.fullscreenEnabled())return-1;a=Q(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Ec()?Wc(a,b):b.yi?(Cc(Wc,1,[a,b]),1):-2:-3:-4},Zd=()=>{try{if(navigator.getGamepads)return(P.ph=
navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},$d=(a,b)=>{var c={target:Q(2),sg:"beforeunload",zg:28,Fg:a,wg:b,Hg:d=>{var e=R(b)(28,0,a);e&&=e?A(q,e):"";if(e)return d.preventDefault(),d.returnValue=e},Eg:!0};return Gc(c)},ae=(a,b,c,d,e,g)=>{P.Jh||(P.Jh=Nd(256));a={target:Q(a),sg:g,zg:e,Fg:b,wg:d,Hg:f=>{var k=f.target.id??"",m=P.Jh;B(Hc(f.target),q,m+0,128);B(k,q,m+128,128);R(d)(e,m,b)&&f.preventDefault()},Eg:c};return Gc(a)},be=(a,b,c,d,e)=>{P.Lh||(P.Lh=Nd(276));return Gc({target:a,
sg:e,zg:19,Fg:b,wg:d,Hg:g=>{var f=P.Lh;Yc(f);R(d)(19,f,b)&&g.preventDefault()},Eg:c})},ce=(a,b,c,d,e)=>{P.Mh||(P.Mh=Nd(1240));b={target:Q(2),ai:!0,sg:e,zg:d,Fg:a,wg:c,Hg:g=>{var f=P.Mh;Zc(f,g.gamepad);R(c)(d,f,a)&&g.preventDefault()},Eg:b};return Gc(b)},de=(a,b,c,d,e,g)=>{P.Oh||(P.Oh=Nd(160));a={target:Q(a),sg:g,zg:e,Fg:b,wg:d,Hg:f=>{var k=P.Oh;x[k>>3]=f.timeStamp;var m=k>>2;r[m+2]=f.location;p[k+12]=f.ctrlKey;p[k+13]=f.shiftKey;p[k+14]=f.altKey;p[k+15]=f.metaKey;p[k+16]=f.repeat;r[m+5]=f.charCode;
r[m+6]=f.keyCode;r[m+7]=f.which;B(f.key??"",q,k+32,32);B(f.code??"",q,k+64,32);B(f.char??"",q,k+96,32);B(f.locale??"",q,k+128,32);R(d)(e,k,b)&&f.preventDefault()},Eg:c};return Gc(a)},ee=(a,b,c)=>{var d=screen.orientation;P.Rh||(P.Rh=Nd(8));return Gc({target:d,sg:"change",zg:18,Fg:a,wg:c,Hg:e=>{var g=P.Rh,f=["portrait-primary","portrait-secondary","landscape-primary","landscape-secondary"],k=["portrait","portrait","landscape","landscape"],m=0,n=window.screen?.orientation;n?(m=f.indexOf(n.type),m<0&&
(m=k.indexOf(n.type)),m>=0&&(m=1<<m),f=n.angle):f=window.orientation;r[g>>2]=m;r[g+4>>2]=f;R(c)(18,g,a)&&e.preventDefault()},Eg:b})},fe=(a,b,c,d)=>{P.Sh||(P.Sh=Nd(257));return Gc({target:a,sg:"pointerlockchange",zg:20,Fg:b,wg:d,Hg:e=>{var g=P.Sh,f=document.pointerLockElement;p[g]=!!f;var k=f?.id??"";B(Hc(f),q,g+1,128);B(k,q,g+129,128);R(d)(20,g,b)&&e.preventDefault()},Eg:c})},ge=(a,b,c,d)=>{P.Xh||(P.Xh=Nd(36));a=Q(a);return Gc({target:a,sg:"resize",zg:10,Fg:b,wg:d,Hg:e=>{if(e.target==a){var g=document.body;
if(g){var f=P.Xh;r[f>>2]=0;r[f+4>>2]=g.clientWidth;r[f+8>>2]=g.clientHeight;r[f+12>>2]=innerWidth;r[f+16>>2]=innerHeight;r[f+20>>2]=outerWidth;r[f+24>>2]=outerHeight;r[f+28>>2]=pageXOffset|0;r[f+32>>2]=pageYOffset|0;R(d)(10,f,b)&&e.preventDefault()}}},Eg:c})},he=(a,b,c)=>{var d=Ic[1];P.Zh||(P.Zh=Nd(8));return Gc({target:d,sg:"visibilitychange",zg:21,Fg:a,wg:c,Hg:e=>{var g=P.Zh,f=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);p[g]=document.hidden;r[g+4>>2]=f;R(c)(21,
g,a)&&e.preventDefault()},Eg:b})},ie=(a,b,c,d)=>{P.$h||(P.$h=Nd(96));return Gc({target:a,ai:!0,sg:"wheel",zg:9,Fg:b,wg:d,Hg:e=>{var g=P.$h;x[g>>3]=e.timeStamp;var f=g>>2;r[f+2]=e.screenX;r[f+3]=e.screenY;r[f+4]=e.clientX;r[f+5]=e.clientY;p[g+24]=e.ctrlKey;p[g+25]=e.shiftKey;p[g+26]=e.altKey;p[g+27]=e.metaKey;ma[f*2+14]=e.button;ma[f*2+15]=e.buttons;r[f+8]=e.movementX;r[f+9]=e.movementY;var k=Vc(a);r[f+10]=e.clientX-(k.left|0);r[f+11]=e.clientY-(k.top|0);x[g+64>>3]=e.deltaX;x[g+72>>3]=e.deltaY;x[g+
80>>3]=e.deltaZ;r[g+88>>2]=e.deltaMode;R(d)(9,g,b)&&e.preventDefault()},Eg:c})},je=["default","low-power","high-performance"],ke={},me=()=>{if(!le){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in ke)ke[b]===void 0?delete a[b]:a[b]=ke[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);le=c}return le},le,ne=(a,b=[])=>{R(a)(...b)},oe=a=>{for(var b of["keydown","mousedown","touchstart"])for(var c of[document,
document.getElementById("canvas")])c?.addEventListener(b,()=>{a.state==="suspended"&&a.resume()},{once:!0})};function pe(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":p[a]=b;break;case "i8":p[a]=b;break;case "i16":ma[a>>1]=b;break;case "i32":r[a>>2]=b;break;case "i64":y[a>>3]=BigInt(b);break;case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":u[a>>2]=b;break;default:z(`invalid type for setValue: ${c}`)}}jb=Array(4096);yb(F,"/");M("/tmp");M("/home");M("/home/web_user");
(function(){M("/dev");Na(259,{read:()=>0,write:(d,e,g,f)=>f,Ig:()=>0});Bb("/dev/null",259);Ma(1280,Pa);Ma(1536,Qa);Bb("/dev/tty",1280);Bb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b||(Ea(a),b=a.byteLength);return a[--b]};Ob("/dev","random",c);Ob("/dev","urandom",c);M("/dev/shm");M("/dev/shm/tmp")})();
(function(){M("/proc");var a=M("/proc/self");M("/proc/self/fd");yb({Bg(){var b=Sa(a,"fd",16895,73);b.ig={Ig:F.ig.Ig};b.hg={fh(c,d){c=+d;var e=L(c);c={parent:null,Bg:{ii:"fake"},hg:{Tg:()=>e.path},id:c+1};return c.parent=c},wh(){return Array.from(hb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.requestAnimationFrame=lc;h.pauseMainLoop=zc;h.resumeMainLoop=function(){qc++;var a=ec,b=fc,c=hc;hc=null;yc(c,0,!1,pc,!0);nc(a,b);ic()};for(let a=0;a<32;++a)Cd.push(Array(a));
h.wasmBinary&&(fa=h.wasmBinary);h.addRunDependency=ab;h.removeRunDependency=()=>{Za--;Za||$a()};h.FS_preloadFile=async(a,b,c,d,e,g,f,k)=>{var m=b?Fa(Aa(a+"/"+b)):a;ab(`cp ${m}`);try{var n=c;typeof c=="string"&&(n=await Wa(c));n=await eb(n,m);k?.();g||Nb(a,b,n,d,e,f)}finally{Za--,Za||$a()}};h.FS_unlink=(...a)=>Eb(...a);h.FS_createPath=(...a)=>Lb(...a);h.FS_createDevice=(...a)=>Ob(...a);h.FS_createDataFile=(...a)=>Nb(...a);h.FS_createLazyFile=(...a)=>Qb(...a);
var cc={518268:()=>{typeof h.SDL3==="undefined"&&(h.SDL3={});var a=h.SDL3;typeof a.Vg==="undefined"&&(a.Vg=function(b){return b});typeof a.Bh==="undefined"&&(a.Bh=function(b){return b>>>2})},518582:()=>{h.SDL3.ah={};h.SDL3.ah.Qg=[];h.SDL3.ah.Qg[0]=void 0;h.SDL3.ah.Qg[1]=void 0},518759:(a,b,c,d,e)=>{var g=h.SDL3.ah;g.Qg[a]!==void 0&&clearInterval(g.Qg[a]);g.Qg[a]=setInterval(function(){ne(d,[e])},b/c*1E3)},518951:a=>{var b=h.SDL3.ah;b.Qg[a]!==void 0&&clearInterval(b.Qg[a]);b.Qg[a]=void 0},519082:a=>
{var b=new URLSearchParams(window.location.search);for(let [d,e]of b)if(d.startsWith("SDL_")){b=Od(d);var c=Od(e);b!=0&&c!=0&&ne(a,[b,c,1]);qe(b);qe(c)}},519423:()=>typeof AudioContext!=="undefined"||typeof webkitAudioContext!=="undefined"?!0:!1,519570:()=>typeof navigator.mediaDevices!=="undefined"&&typeof navigator.mediaDevices.getUserMedia!=="undefined"||typeof navigator.webkitGetUserMedia!=="undefined"?!0:!1,519804:()=>{var a=h.SDL3;typeof a.ng==="undefined"&&(a.ng={});typeof a.jg==="undefined"&&
(a.jg={});a.pg||(typeof AudioContext!=="undefined"?a.pg=new AudioContext:typeof webkitAudioContext!=="undefined"&&(a.pg=new webkitAudioContext),a.pg&&typeof navigator.userActivation==="undefined"&&oe(a.pg));return a.pg!==void 0},520383:()=>h.SDL3.pg.sampleRate,520434:(a,b,c,d)=>{function e(){}function g(k){f.jg.Dg!==void 0&&(clearInterval(f.jg.Dg),f.jg.Dg=void 0,f.jg.Ug=void 0);f.jg.Ph=f.pg.createMediaStreamSource(k);f.jg.Cg=f.pg.createScriptProcessor(b,a,1);f.jg.Cg.onaudioprocess=function(m){f!==
void 0&&f.jg!==void 0&&(m.outputBuffer.getChannelData(0).fill(0),f.jg.Eh=m.inputBuffer,ne(c,[d]))};f.jg.Ph.connect(f.jg.Cg);f.jg.Cg.connect(f.pg.destination);f.jg.stream=k}var f=h.SDL3;f.jg.Ug=f.pg.createBuffer(a,b,f.pg.sampleRate);f.jg.Ug.getChannelData(0).fill(0);f.jg.Dg=setInterval(function(){f.jg.Eh=f.jg.Ug;ne(c,[d])},b/f.pg.sampleRate*1E3);navigator.mediaDevices!==void 0&&navigator.mediaDevices.getUserMedia!==void 0?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):navigator.webkitGetUserMedia!==
void 0&&navigator.webkitGetUserMedia({audio:!0,video:!1},g,e)},522275:(a,b,c,d)=>{var e=h.SDL3;e.ng.Cg=e.pg.createScriptProcessor(b,0,a);e.ng.Cg.onaudioprocess=function(g){e!==void 0&&e.ng!==void 0&&(e.ng.Dg!==void 0&&(clearInterval(e.ng.Dg),e.ng.Dg=void 0,e.ng.Ug=void 0),e.ng.nh=g.outputBuffer,ne(c,[d]))};e.ng.Cg.connect(e.pg.destination);e.pg.state==="suspended"&&(e.ng.Ug=e.pg.createBuffer(a,b,e.pg.sampleRate),e.ng.Ug.getChannelData(0).fill(0),e.ng.Dg=setInterval(function(){typeof navigator.userActivation!==
"undefined"&&navigator.userActivation.hasBeenActive&&e.pg.resume();e.ng.nh=e.ng.Ug;ne(c,[d]);e.ng.nh=void 0},b/e.pg.sampleRate*1E3))},523591:a=>{var b=h.SDL3;if(a){b.jg.Dg!==void 0&&clearInterval(b.jg.Dg);if(b.jg.stream!==void 0){a=b.jg.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.jg.stream.removeTrack(a[c])}b.jg.Cg!==void 0&&(b.jg.Cg.onaudioprocess=function(){},b.jg.Cg.disconnect());b.jg.Ph!==void 0&&b.jg.Ph.disconnect();b.jg=void 0}else b.ng.Cg!=void 0&&b.ng.Cg.disconnect(),b.ng.Dg!==void 0&&
clearInterval(b.ng.Dg),b.ng=void 0;b.pg!==void 0&&b.ng===void 0&&b.jg===void 0&&(b.pg.close(),b.pg=void 0)},524747:(a,b)=>{var c=h.SDL3;a=c.Bh(a);for(var d=c.ng.nh.numberOfChannels,e=0;e<d;++e){var g=c.ng.nh.getChannelData(e);if(g.length!=b)throw"Web Audio playback buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var f=0;f<b;++f)g[f]=w[a+(f*d+e)]}},525280:(a,b)=>{for(var c=h.SDL3,d=c.jg.Eh.numberOfChannels,e=0;e<d;++e){var g=c.jg.Eh.getChannelData(e);
if(g.length!=b)throw"Web Audio recording buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(d==1)for(var f=0;f<b;++f)pe(a+f*4,g[f]);else for(f=0;f<b;++f)pe(a+(f*d+e)*4,g[f])}},525907:a=>(a=navigator.getGamepads()[a])&&a.vibrationActuator&&a.vibrationActuator.effects&&a.vibrationActuator.effects.includes("trigger-rumble")?!0:!1,526153:a=>{a=navigator.getGamepads()[a];if(!a)return 0;if(a.id.indexOf("Vendor: ")>0){let b=a.id.indexOf("Vendor: ")+8;return parseInt(a.id.substr(b,
4),16)}a=a.id.split("-");return a.length>1&&!isNaN(parseInt(a[0],16))?parseInt(a[0],16):0},526618:a=>{a=navigator.getGamepads()[a];if(!a)return 0;if(a.id.indexOf("Product: ")>0){let b=a.id.indexOf("Product: ")+9;return parseInt(a.id.substr(b,4),16)}a=a.id.split("-");return a.length>1&&!isNaN(parseInt(a[1],16))?parseInt(a[1],16):0},527090:a=>(a=navigator.getGamepads()[a])?a.id.toLowerCase().indexOf("xinput")>=0:0,527233:()=>{var a=["Android","Linux","iPhone","Macintosh","Windows"],b=navigator.userAgent;
for(let c=0;c<a.length;c++)if(b.indexOf(a[c])>=0)return c+1;return 0},527443:(a,b,c)=>{if(a=navigator.getGamepads()[a]){var d=a=a.id;a.indexOf(" (STANDARD GAMEPAD")>0?d=a.substr(0,a.indexOf(" (STANDARD GAMEPAD")):a.indexOf(" (Vendor:")>0?d=a.substr(0,a.indexOf(" (Vendor:")):a.indexOf(" (XInput")>0&&(d=a.substr(0,a.indexOf(" (XInput")));var e=a.split("-");e.length>1&&!isNaN(parseInt(e[0],16))&&(d=a.indexOf("-",a.indexOf("-")+1)+1,d=a.substr(d));B(d.trim(),q,b,c)}else B("\x00",q,b,c)},528121:a=>(a=
navigator.getGamepads()[a])&&a.vibrationActuator?!0:!1,528249:(a,b,c,d,e)=>{a=navigator.getGamepads()[a];if(!a)return!1;a.vibrationActuator.playEffect("dual-rumble",{startDelay:0,duration:3E3,weakMagnitude:b/65535,strongMagnitude:c/65535,leftTrigger:d/65535,rightTrigger:e/65535});return!0},528562:()=>window.matchMedia?window.matchMedia("(prefers-color-scheme: light)").matches?0:window.matchMedia("(prefers-color-scheme: dark)").matches?1:-1:-1,528771:()=>{if(typeof h.SDL3!=="undefined"){var a=h.SDL3;
a.Wh.removeEventListener("change",a.Ih);a.Wh=void 0;a.Ih=void 0}},529024:()=>window.innerWidth,529054:()=>window.innerHeight,529085:a=>{h.requestFullscreen=function(){re(a)}},529194:(a,b)=>{a=URL.createObjectURL(new Blob([q.buffer instanceof ArrayBuffer?q.subarray(a,a+b):q.slice(a,a+b)],{type:"image/png"}));b=document.querySelector("link[rel~='icon']");b||(b=document.createElement("link"),b.rel="icon",b.type="image/png",document.head.appendChild(b));b.href&&b.href.startsWith("blob:")&&URL.revokeObjectURL(b.href);
b.href=a},529687:()=>{h.requestFullscreen=function(){}},529761:()=>window.innerWidth,529791:()=>window.innerHeight,529822:a=>{a=document.querySelector(a?A(q,a):"");a.oi=a.style.position;a.pi=a.style.top;a.ni=a.style.left;var b=document.createElement("div");b.id="SDL3_fill_document_background_elements";b.qg=a;b.hh=a.parentNode;b.eh=a.nextSibling;var c=Array.from(document.body.children),d;for(d of c)b.appendChild(d);document.body.appendChild(b);b.style.display="none";document.body.appendChild(a);a.style.position=
"fixed";a.style.top="0";a.style.left="0"},530520:()=>{var a=document.getElementById("SDL3_fill_document_background_elements");if(a){for(a.eh?a.hh.insertBefore(a.qg,a.eh):a.hh.appendChild(a.qg);a.firstChild;)document.body.insertBefore(a.firstChild,a);a.qg.style.position=a.qg.oi;a.qg.style.top=a.qg.pi;a.qg.style.left=a.qg.ni;a.remove()}},531079:()=>{if(window.matchMedia){var a=h.SDL3;a.Ih=function(){te()};a.Wh=window.matchMedia("(prefers-color-scheme: dark)");a.Wh.addEventListener("change",a.Ih)}},
531401:(a,b,c,d,e)=>{a=a?A(q,a):"";b=b?A(q,b):"";c=c?A(q,c):"";d=d?A(q,d):"";var g=e?A(q,e):"";e=document.createElement("dialog");e.classList.add("SDL3_messagebox");e.id=g;e.style.color=d;e.style.backgroundColor=c;document.body.append(e);d=document.createElement("h1");d.innerText=a;e.append(d);a=document.createElement("p");a.innerText=b;e.append(a);e.showModal()},531942:(a,b,c,d,e,g,f,k)=>{a=a?A(q,a):"";b=b?A(q,b):"";g=g?A(q,g):"";var m=f?A(q,f):"",n=k?A(q,k):"",t=document.getElementById(a);if(!t)return!1;
var v=document.createElement("button");v.innerText=b;v.style.borderColor=g;v.style.backgroundColor=m;t.addEventListener("keydown",function(C){d&&C.key==="Enter"?(C.preventDefault(),v.click()):e&&C.key==="Escape"&&(C.preventDefault(),v.click())});t.addEventListener("cancel",function(C){C.preventDefault()});v.onmouseenter=function(){v.style.backgroundColor=n};v.onmouseleave=function(){v.style.backgroundColor=m};v.onclick=function(){t.close(c)};t.append(v);return!0},532951:a=>{a=a?A(q,a):"";return(a=
document.getElementById(a))?a.open:!1},533089:a=>{a=a?A(q,a):"";a=document.getElementById(a);if(!a)return 0;try{return parseInt(a.returnValue)}catch(b){return 0}},533271:(a,b)=>{alert((a?A(q,a):"")+"\n\n"+(b?A(q,b):""))},533328:(a,b,c,d)=>{d=d?A(q,d):"";var e=document.querySelector(d);d=h.SDL3;if(d.ti!==e){d.$g=dd(e);if(!d.$g)return!1;d.ti=e}if(d.w!==a||d.h!==b||d.Gi!==d.$g)d.image=d.$g.createImageData(a,b),d.w=a,d.h=b,d.Gi=d.$g;a=d.image.data;c/=4;d.xi!==a&&(d.wi=new Int32Array(a.buffer),d.xi=a);
a=d.wi;a.set(r.subarray(c,c+a.length));d.$g.putImageData(d.image,0,0);return!0},534077:()=>{var a=h.SDL3;a.mouse_x=0;a.mouse_y=0;a.mouse_buttons=[];for(var b=0;b<5;++b)a.mouse_buttons[b]=!1;document.addEventListener("mousemove",function(c){var d=h.SDL3;d.mouse_x=c.clientX;d.mouse_y=c.clientY});document.addEventListener("mousedown",function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!0)});document.addEventListener("mouseup",function(c){var d=h.SDL3;0<=
c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!1)})},534765:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var f=g.getContext("2d");a=f.createImageData(a,b);e/=4;b=new Int32Array(a.data.buffer);b.set(r.subarray(e,e+b.length));f.putImageData(a,0,0);c=c===0&&d===0?"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=ue(c.length+1);B(c,q,d,c.length+1);return d},535423:a=>{h.canvas&&(h.canvas.style.cursor=a?A(q,a):"")},535506:()=>
{h.canvas&&(h.canvas.style.cursor="none")},535575:()=>h.SDL3.mouse_x,535613:()=>h.SDL3.mouse_y,535651:a=>h.SDL3.mouse_buttons[a],535699:a=>{document.qg&&document.removeEventListener("keydown",document.qg);document.qg=function(b){b.key!="CapsLock"&&b.key!="NumLock"&&b.key!="ScrollLock"&&ve(h.SDL3.Vg(a),b.getModifierState("CapsLock"),b.getModifierState("NumLock"),b.getModifierState("ScrollLock"))};document.addEventListener("keydown",document.qg)},536253:()=>{document.removeEventListener("keydown",document.qg)},
536337:a=>{var b=document;b&&(b.rg=function(c){var d=h.SDL3;c=d.gh(0,0,c);c!=0&&(we(d.Vg(a),c),xe(c))},b.addEventListener("pointerup",b.rg))},536698:a=>{var b=h.SDL3;b.gh===void 0&&(b.gh=function(c,d,e){if(e.pointerType=="mouse")var g=1;else if(e.pointerType=="touch")g=2;else if(e.pointerType=="pen")g=3;else return 0;var f=ue(a);if(f!=0){var k=b.Bh(f);r[k++]=g;r[k++]=e.pointerId;r[k++]=typeof e.button!=="undefined"?e.button:-1;r[k++]=e.buttons;r[k++]=e.type=="pointerdown"?1:0;w[k++]=e.movementX;w[k++]=
e.movementY;w[k++]=e.clientX-c;w[k++]=e.clientY-d;g==3&&(w[k++]=e.pressure,w[k++]=e.tangentialPressure,w[k++]=e.tiltX,w[k++]=e.tiltY,w[k++]=e.twist)}return f})},537690:a=>{a=a?A(q,a):"";try{var b=document.querySelector(a);if(b)return b===document.activeElement}catch(c){}return!1},537856:()=>document.hasFocus(),537888:()=>{var a=document;a&&(a.removeEventListener("pointerup",a.rg),a.rg=void 0)},538070:()=>document.body.clientWidth,538108:()=>document.body.clientHeight,538147:()=>window.innerWidth,
538177:()=>window.innerHeight,538208:()=>window.outerWidth,538238:()=>window.outerHeight,538269:()=>window.pageXOffset,538300:()=>window.pageYOffset,538331:(a,b)=>{var c=document.querySelector(b?A(q,b):"");if(c){var d=h.SDL3;c.Xg=function(e){var g=c.getBoundingClientRect();e=d.gh(g.left,g.top,e);e!=0&&(ye(d.Vg(a),e),xe(e))};c.Kg=function(e){var g=c.getBoundingClientRect();e=d.gh(g.left,g.top,e);e!=0&&(ze(d.Vg(a),e),xe(e))};c.rg=function(e){var g=c.getBoundingClientRect();e=d.gh(g.left,g.top,e);e!=
0&&(Ae(d.Vg(a),e),xe(e))};c.style.touchAction="none";c.addEventListener("pointerenter",c.Xg);c.addEventListener("pointerleave",c.Kg);c.addEventListener("pointercancel",c.Kg);c.addEventListener("pointerdown",c.rg);c.addEventListener("pointermove",c.rg);c.addEventListener("pointerup",c.rg)}},539719:(a,b,c)=>{var d=document.querySelector(b?A(q,b):"");if(d){var e=h.SDL3,g=function(f){var k=ue(c);if(k!=0){var m=k>>2,n=d.getBoundingClientRect();r[m++]=f.clientX-n.left;r[m++]=f.clientY-n.top}return k};e.Gh=
function(f){f.preventDefault();f=g(f);f!=0&&(Be(a,f),xe(f))};d.addEventListener("dragover",e.Gh);e.oh=0;try{M("/tmp/filedrop")}catch(f){}e.Hh=function(f){f.preventDefault();if(f.dataTransfer.types.includes("text/plain"))f=Od(f.dataTransfer.getData("text/plain")),Ce(a,f),qe(f);else if(f.dataTransfer.types.includes("Files")){let k=0,m=f.dataTransfer.files.length;for(let n=0;n<m;n++){let t=f.dataTransfer.files.item(n),v=new FileReader;v.readAsArrayBuffer(t);v.onload=function(C){var D=`/tmp/filedrop/${e.oh}`;
e.oh+=1;var G=`${D}/${t.name}`,I=Od(G);C=new Uint8Array(C.target.result);try{M(D);var H=Hb(G,"w");Kb(H,C,0,C.length,0);Ib(H);De(a,I)}catch(T){}qe(I);++k;k===m&&Ee(a)};v.onerror=function(){++k;k===m&&Ee(a)}}}Ee(a)};d.addEventListener("drop",e.Hh);e.bh=function(f){f.preventDefault();Ee(a)};d.addEventListener("dragend",e.bh);d.addEventListener("dragleave",e.bh)}},542086:a=>{if(a=document.querySelector(a?A(q,a):"")){var b=h.SDL3;a.removeEventListener("dragleave",b.bh);a.removeEventListener("dragend",
b.bh);a.removeEventListener("drop",b.Hh);b.oh=void 0;"/tmp/filedrop";Db("/tmp/filedrop");a.removeEventListener("dragover",b.Gh);b.Gh=void 0;b.Hh=void 0;b.bh=void 0}},542916:a=>{if(a=document.querySelector(a?A(q,a):""))a.removeEventListener("pointerenter",a.Xg),a.removeEventListener("pointerleave",a.Kg),a.removeEventListener("pointercancel",a.Kg),a.removeEventListener("pointerdown",a.rg),a.removeEventListener("pointermove",a.rg),a.removeEventListener("pointerup",a.rg),a.style.touchAction="",a.Xg=void 0,
a.Kg=void 0,a.rg=void 0}},Nd,Fe,xe,ue,qe,ye,ze,Ae,we,Be,Ee,Ce,De,ve,te,re,Ge,Mc,Jc,Lc,la,Sc,Ie={b:(a,b,c)=>{(new xa(a)).init(b,c);ya++;z()},qb:function(a,b,c){try{if(a===b||c&-524289)return-28;var d=L(a);if(b<0||b>=4096)return-8;var e=hb[b];e&&Ib(e);var g=wb(d,b);c&524288&&(g.flags|=524288);return g.fd}catch(f){if(typeof N=="undefined"||f.name!=="ErrnoError")throw f;return-f.lg}},vb:function(a,b,c){try{b=b?A(q,b):"";b=Sb(a,b);if(c&-8)return-28;var d=K(b,{Wg:!0}).node;if(!d)return-44;a="";c&4&&(a+=
"r");c&2&&(a+="w");c&1&&(a+="x");return a&&rb(d,a)?-2:0}catch(e){if(typeof N=="undefined"||e.name!=="ErrnoError")throw e;return-e.lg}},o:function(a,b,c){Vb=c;try{var d=L(a);switch(b){case 0:var e=Wb();if(e<0)break;for(;hb[e];)e++;return wb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Wb(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=Wb(),ma[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(g){if(typeof N=="undefined"||g.name!=="ErrnoError")throw g;return-g.lg}},sb:function(a){try{return L(a),
0}catch(b){if(typeof N=="undefined"||b.name!=="ErrnoError")throw b;return-b.lg}},pb:function(a,b){try{var c=L(a),d=c.node,e=c.ig.Ag;a=e?c:d;e??=d.hg.Ag;ub(e,63);var g=e(a);return Tb(b,g)}catch(f){if(typeof N=="undefined"||f.name!=="ErrnoError")throw f;return-f.lg}},kb:function(a,b){try{if(!b)return-28;var c=Ja("/")+1;if(b<c)return-68;B("/",q,a,b);return c}catch(d){if(typeof N=="undefined"||d.name!=="ErrnoError")throw d;return-d.lg}},cb:function(a,b,c){try{var d=L(a);if(!d.Sg){var e=K(d.path,{Wg:!0}).node;
var g=ub(e.hg.wh,54)(e);d.Sg=g}a=0;var f=Jb(d,0,1),k=Math.floor(f/280),m=Math.min(d.Sg.length,k+Math.floor(c/280));for(c=k;c<m;c++){var n=d.Sg[c];if(n==="."){var t=d.node.id;var v=4}else if(n==="..")t=K(d.path,{parent:!0}).node.id,v=4;else{try{var C=Ta(d.node,n)}catch(D){if(D?.lg===28)continue;throw D;}t=C.id;v=(C.mode&61440)===8192?2:J(C.mode)?4:(C.mode&61440)===40960?10:8}y[b+a>>3]=BigInt(t);y[b+a+8>>3]=BigInt((c+1)*280);ma[b+a+16>>1]=280;p[b+a+18]=v;B(n,q,b+a+19,256);a+=280}Jb(d,c*280,0);return a}catch(D){if(typeof N==
"undefined"||D.name!=="ErrnoError")throw D;return-D.lg}},jb:()=>0,rb:function(a,b,c){Vb=c;try{var d=L(a);switch(b){case 21509:return d.og?0:-59;case 21505:if(!d.og)return-59;if(d.og.Lg.Ki){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Wb();r[e>>2]=25856;r[e+4>>2]=5;r[e+8>>2]=191;r[e+12>>2]=35387;for(var g=0;g<32;g++)p[e+g+17]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.og?0:-59;case 21506:case 21507:case 21508:if(!d.og)return-59;if(d.og.Lg.Li)for(e=
Wb(),a=[],g=0;g<32;g++)a.push(p[e+g+17]);return 0;case 21519:if(!d.og)return-59;e=Wb();return r[e>>2]=0;case 21520:return d.og?-28:-59;case 21537:case 21531:e=Wb();if(!d.ig.Ji)throw new E(59);return d.ig.Ji(d,b,e);case 21523:if(!d.og)return-59;d.og.Lg.Mi&&(g=[24,80],e=Wb(),ma[e>>1]=g[0],ma[e+2>>1]=g[1]);return 0;case 21524:return d.og?0:-59;case 21515:return d.og?0:-59;default:return-28}}catch(f){if(typeof N=="undefined"||f.name!=="ErrnoError")throw f;return-f.lg}},mb:function(a,b){try{return a=a?
A(q,a):"",Tb(b,Fb(a,!0))}catch(c){if(typeof N=="undefined"||c.name!=="ErrnoError")throw c;return-c.lg}},hb:function(a,b,c){try{return b=b?A(q,b):"",b=Sb(a,b),M(b,c&-19),0}catch(d){if(typeof N=="undefined"||d.name!=="ErrnoError")throw d;return-d.lg}},nb:function(a,b,c,d){try{b=b?A(q,b):"";var e=d&256;b=Sb(a,b,d&4096);return Tb(c,e?Fb(b,!0):Fb(b))}catch(g){if(typeof N=="undefined"||g.name!=="ErrnoError")throw g;return-g.lg}},p:function(a,b,c,d){Vb=d;try{b=b?A(q,b):"";b=Sb(a,b);var e=d?Wb():0;c&64&&
(e&=-19);return Hb(b,c,e).fd}catch(g){if(typeof N=="undefined"||g.name!=="ErrnoError")throw g;return-g.lg}},v:function(a,b,c,d){try{b=b?A(q,b):"";b=Sb(a,b);if(d<=0)return-28;var e=K(b).node;if(!e)throw new E(44);if(!e.hg.Tg)throw new E(28);var g=e.hg.Tg(e);var f=Math.min(d,Ja(g)),k=p[c+f];B(g,q,c,d+1);p[c+f]=k;return f}catch(m){if(typeof N=="undefined"||m.name!=="ErrnoError")throw m;return-m.lg}},ab:function(a,b,c,d){try{b=b?A(q,b):"";d=d?A(q,d):"";b=Sb(a,b);d=Sb(c,d);a=b;var e=Ba(a),g=Ba(d),f=Ca(a),
k=Ca(d);var m=K(a,{parent:!0});var n=m.node;m=K(d,{parent:!0});var t=m.node;if(!n||!t)throw new E(44);if(n.Bg!==t.Bg)throw new E(75);var v=Ta(n,f),C=Ga(a,g);if(C.charAt(0)!==".")throw new E(28);C=Ga(d,e);if(C.charAt(0)!==".")throw new E(55);try{var D=Ta(t,k)}catch(H){}if(v!==D){var G=J(v.mode),I=tb(n,f,G);if(I)throw new E(I);if(I=D?tb(t,k,G):sb(t,k))throw new E(I);if(!n.hg.xh)throw new E(63);if(v.Pg||D&&D.Pg)throw new E(10);if(t!==n&&(I=rb(n,"w")))throw new E(I);Ua(v);try{n.hg.xh(v,t,k),v.parent=
t}catch(H){throw H;}finally{qb(v)}}return 0}catch(H){if(typeof N=="undefined"||H.name!=="ErrnoError")throw H;return-H.lg}},bb:function(a){try{return a=a?A(q,a):"",Db(a),0}catch(b){if(typeof N=="undefined"||b.name!=="ErrnoError")throw b;return-b.lg}},ob:function(a,b){try{return a=a?A(q,a):"",Tb(b,Fb(a))}catch(c){if(typeof N=="undefined"||c.name!=="ErrnoError")throw c;return-c.lg}},x:function(a,b,c){try{b=b?A(q,b):"";b=Sb(a,b);if(c)if(c===512)Db(b);else return-28;else Eb(b);return 0}catch(d){if(typeof N==
"undefined"||d.name!=="ErrnoError")throw d;return-d.lg}},wb:()=>z(""),tb:(a,b)=>{b=b?A(q,b):"";a&24&&(b=b.replace(/\s+$/,""),b+=(b.length>0?"\n":"")+Xb(a));a&1?a&4?console.error(b):a&2?console.warn(b):a&512?console.info(b):a&256?console.debug(b):console.log(b):a&6?l(b):ea(b)},$a:a=>a?-52:0,Ya:()=>{throw new ja;},db:function(a,b){a=a<-9007199254740992||a>9007199254740992?NaN:Number(a);a=new Date(a*1E3);if(isNaN(a.getTime()))return 1;r[b>>2]=a.getUTCSeconds();r[b+4>>2]=a.getUTCMinutes();r[b+8>>2]=a.getUTCHours();
r[b+12>>2]=a.getUTCDate();r[b+16>>2]=a.getUTCMonth();r[b+20>>2]=a.getUTCFullYear()-1900;r[b+24>>2]=a.getUTCDay();r[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;return 0},eb:function(a,b){a=a<-9007199254740992||a>9007199254740992?NaN:Number(a);a=new Date(a*1E3);if(isNaN(a.getTime()))return 1;r[b>>2]=a.getSeconds();r[b+4>>2]=a.getMinutes();r[b+8>>2]=a.getHours();r[b+12>>2]=a.getDate();r[b+16>>2]=a.getMonth();r[b+20>>2]=a.getFullYear()-1900;r[b+24>>2]=a.getDay();r[b+28>>2]=
(Yb(a.getFullYear())?Zb:$b)[a.getMonth()]+a.getDate()-1|0;r[b+36>>2]=-(a.getTimezoneOffset()*60);var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();r[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;return 0},fb:function(a){var b=(()=>{var c=new Date(r[a+20>>2]+1900,r[a+16>>2],r[a+12>>2],r[a+8>>2],r[a+4>>2],r[a>>2],0);if(isNaN(c.getTime()))return-1;var d=r[a+32>>2],e=c.getTimezoneOffset(),g=(new Date(c.getFullYear(),6,1)).getTimezoneOffset(),
f=(new Date(c.getFullYear(),0,1)).getTimezoneOffset(),k=Math.min(f,g);if(d<0)d=Number(g!=f&&k==e);else if(d>0!=(k==e)&&(g=Math.max(f,g),c.setTime(c.getTime()+((d>0?k:g)-e)*6E4),isNaN(c.getTime())))return-1;r[a+32>>2]=d;r[a+24>>2]=c.getDay();r[a+28>>2]=(Yb(c.getFullYear())?Zb:$b)[c.getMonth()]+c.getDate()-1|0;r[a>>2]=c.getSeconds();r[a+4>>2]=c.getMinutes();r[a+8>>2]=c.getHours();r[a+12>>2]=c.getDate();r[a+16>>2]=c.getMonth();r[a+20>>2]=c.getYear();return c.getTime()/1E3})();return BigInt(b)},gb:(a,
b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();u[a>>2]=Math.max(g,e)*60;r[b>>2]=Number(g!=e);b=f=>{var k=Math.abs(f);return`UTC${f>=0?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(B(a,q,c,17),B(b,q,d,17)):(B(a,q,d,17),B(b,q,c,17))},ub:function(a,b,c){if(!(a>=0&&a<=3))return 28;y[c>>3]=BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},I:dc,f:(a,
b,c)=>{b=bc(b,c);return cc[a](...b)},a:dc,Kd:(a,b,c)=>{b=bc(b,c);return cc[a](...b)},Ld:()=>{zc();hc=null},A:()=>Date.now(),Sa:()=>{if(!P.fullscreenEnabled())return-1;Dc(Wc);var a=Ic[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},pd:()=>{Dc(Xc);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},O:(a,b,c)=>{a=Xb(a);return!b||c<=0?Ja(a)+1:B(a,q,b,c)+1},i:()=>
devicePixelRatio,c:(a,b,c)=>{a=Q(a);if(!a)return-4;a=Vc(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},Ua:a=>{if(!P.fullscreenEnabled())return-1;Yc(a);return 0},r:(a,b)=>{if(a<0||a>=P.ph.length)return-5;if(!P.ph[a])return-7;Zc(b,P.ph[a]);return 0},Ue:(a,b)=>{a&&(r[a>>2]=ec);b&&(r[b>>2]=fc)},y:()=>performance.now(),ha:()=>P.ph.length,ee:(a,b)=>{r[a>>2]=screen.width;r[b>>2]=screen.height},ya:a=>S.activeTexture(a),xa:(a,b)=>{S.attachShader(U[a],V[b])},md:(a,b)=>{S.beginQuery(a,W[b])},Oa:(a,b)=>{S.yg.beginQueryEXT(a,
W[b])},Vc:a=>S.beginTransformFeedback(a),wa:(a,b,c)=>{S.bindAttribLocation(U[a],b,c?A(q,c):"")},va:(a,b)=>{a==35051?S.Dh=b:a==35052&&(S.Gg=b);S.bindBuffer(a,gd[b])},Sc:(a,b,c)=>{S.bindBufferBase(a,b,gd[c])},Tc:(a,b,c,d,e)=>{S.bindBufferRange(a,b,gd[c],d,e)},ua:(a,b)=>{S.bindFramebuffer(a,hd[b])},ta:(a,b)=>{S.bindRenderbuffer(a,jd[b])},_b:(a,b)=>{S.bindSampler(a,nd[b])},sa:(a,b)=>{S.bindTexture(a,kd[b])},Sb:(a,b)=>{S.bindTransformFeedback(a,od[b])},_c:zd,Ga:zd,ra:(a,b,c,d)=>S.blendColor(a,b,c,d),qa:a=>
S.blendEquation(a),pa:(a,b)=>S.blendEquationSeparate(a,b),oa:(a,b)=>S.blendFunc(a,b),na:(a,b,c,d)=>S.blendFuncSeparate(a,b,c,d),bd:(a,b,c,d,e,g,f,k,m,n)=>S.blitFramebuffer(a,b,c,d,e,g,f,k,m,n),ma:(a,b,c,d)=>{c&&b?S.bufferData(a,q,d,c,b):S.bufferData(a,b,d)},la:(a,b,c,d)=>{var e=q;c&&S.bufferSubData(a,b,e,d,c)},ka:a=>S.checkFramebufferStatus(a),ja:a=>S.clear(a),vc:(a,b,c,d)=>S.clearBufferfi(a,b,c,d),wc:(a,b,c)=>{S.clearBufferfv(a,b,w,c>>2)},yc:(a,b,c)=>{S.clearBufferiv(a,b,r,c>>2)},xc:(a,b,c)=>{S.clearBufferuiv(a,
b,u,c>>2)},ia:(a,b,c,d)=>S.clearColor(a,b,c,d),ga:a=>S.clearDepth(a),fa:a=>S.clearStencil(a),hc:(a,b,c)=>{c=Number(c);return S.clientWaitSync(pd[a],b,c)},Dd:(a,b)=>{S.Ci.clipControlEXT(a,b)},ea:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},da:a=>{S.compileShader(V[a])},ca:(a,b,c,d,e,g,f,k)=>{S.Gg||!f?S.compressedTexImage2D(a,b,c,d,e,g,f,k):S.compressedTexImage2D(a,b,c,d,e,g,q,k,f)},sd:(a,b,c,d,e,g,f,k,m)=>{S.Gg?S.compressedTexImage3D(a,b,c,d,e,g,f,k,m):S.compressedTexImage3D(a,b,c,d,e,g,f,q,m,k)},ba:(a,
b,c,d,e,g,f,k,m)=>{S.Gg||!k?S.compressedTexSubImage2D(a,b,c,d,e,g,f,k,m):S.compressedTexSubImage2D(a,b,c,d,e,g,f,q,m,k)},rd:(a,b,c,d,e,g,f,k,m,n,t)=>{S.Gg?S.compressedTexSubImage3D(a,b,c,d,e,g,f,k,m,n,t):S.compressedTexSubImage3D(a,b,c,d,e,g,f,k,m,q,t,n)},tc:(a,b,c,d,e)=>S.copyBufferSubData(a,b,c,d,e),aa:(a,b,c,d,e,g,f,k)=>S.copyTexImage2D(a,b,c,d,e,g,f,k),$:(a,b,c,d,e,g,f,k)=>S.copyTexSubImage2D(a,b,c,d,e,g,f,k),td:(a,b,c,d,e,g,f,k,m)=>S.copyTexSubImage3D(a,b,c,d,e,g,f,k,m),_:()=>{var a=ud(U),b=
S.createProgram();b.name=a;b.sh=b.qh=b.rh=0;b.Yh=1;U[a]=b;return a},Z:a=>{var b=ud(V);V[b]=S.createShader(a);return b},Y:a=>S.cullFace(a),X:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=gd[d];e&&(S.deleteBuffer(e),e.name=0,gd[d]=null,d==S.Dh&&(S.Dh=0),d==S.Gg&&(S.Gg=0))}},W:(a,b)=>{for(var c=0;c<a;++c){var d=r[b+c*4>>2],e=hd[d];e&&(S.deleteFramebuffer(e),e.name=0,hd[d]=null)}},V:a=>{if(a){var b=U[a];b?(S.deleteProgram(b),b.name=0,U[a]=null):X||=1281}},od:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+
c*4>>2],e=W[d];e&&(S.deleteQuery(e),W[d]=null)}},Qa:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=W[d];e&&(S.yg.deleteQueryEXT(e),W[d]=null)}},U:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=jd[d];e&&(S.deleteRenderbuffer(e),e.name=0,jd[d]=null)}},ac:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=nd[d];e&&(S.deleteSampler(e),e.name=0,nd[d]=null)}},T:a=>{if(a){var b=V[a];b?(S.deleteShader(b),V[a]=null):X||=1281}},ic:a=>{if(a){var b=pd[a];b?(S.deleteSync(b),b.name=0,pd[a]=null):X||=1281}},S:(a,
b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=kd[d];e&&(S.deleteTexture(e),e.name=0,kd[d]=null)}},Rb:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=od[d];e&&(S.deleteTransformFeedback(e),e.name=0,od[d]=null)}},Zc:Ad,Fa:Ad,R:a=>S.depthFunc(a),Q:a=>{S.depthMask(!!a)},P:(a,b)=>S.depthRange(a,b),Hf:(a,b)=>{S.detachShader(U[a],V[b])},Gf:a=>S.disable(a),Ff:a=>{S.disableVertexAttribArray(a)},Ef:(a,b,c)=>{S.drawArrays(a,b,c)},mc:Bd,Ba:Bd,Bb:Bd,Ad:Bd,Cb:Bd,id:Dd,yd:Dd,Ca:Dd,Df:(a,b,c,d)=>{S.drawElements(a,
b,c,d)},lc:Ed,Aa:Ed,zb:Ed,Ab:Ed,zd:Ed,wd:(a,b,c,d,e,g)=>{S.drawElements(a,d,e,g)},Cf:a=>S.enable(a),Bf:a=>{S.enableVertexAttribArray(a)},ld:a=>S.endQuery(a),Na:a=>{S.yg.endQueryEXT(a)},Uc:()=>S.endTransformFeedback(),kc:(a,b)=>(a=S.fenceSync(a,b))?(b=ud(pd),a.name=b,pd[b]=a,b):0,Af:()=>S.finish(),zf:()=>S.flush(),yf:(a,b,c,d)=>{S.framebufferRenderbuffer(a,b,c,jd[d])},xf:(a,b,c,d,e)=>{S.framebufferTexture2D(a,b,c,kd[d],e)},$c:(a,b,c,d,e)=>{S.framebufferTextureLayer(a,b,kd[c],d,e)},wf:a=>S.frontFace(a),
vf:(a,b)=>{vd(a,b,"createBuffer",gd)},tf:(a,b)=>{vd(a,b,"createFramebuffer",hd)},qd:(a,b)=>{vd(a,b,"createQuery",W)},Ra:(a,b)=>{for(var c=0;c<a;c++){var d=S.yg.createQueryEXT();if(!d){for(X||=1282;c<a;)r[b+c++*4>>2]=0;break}var e=ud(W);d.name=e;W[e]=d;r[b+c*4>>2]=e}},sf:(a,b)=>{vd(a,b,"createRenderbuffer",jd)},bc:(a,b)=>{vd(a,b,"createSampler",nd)},rf:(a,b)=>{vd(a,b,"createTexture",kd)},Qb:(a,b)=>{vd(a,b,"createTransformFeedback",od)},Yc:Fd,Ea:Fd,uf:a=>S.generateMipmap(a),qf:(a,b,c,d,e,g,f)=>Gd("getActiveAttrib",
a,b,c,d,e,g,f),pf:(a,b,c,d,e,g,f)=>Gd("getActiveUniform",a,b,c,d,e,g,f),oc:(a,b,c,d,e)=>{a=U[a];if(a=S.getActiveUniformBlockName(a,b))e&&c>0?(c=B(a,q,e,c),d&&(r[d>>2]=c)):d&&(r[d>>2]=0)},pc:(a,b,c,d)=>{if(d)if(a=U[a],c==35393)r[d>>2]=S.getActiveUniformBlockName(a,b).length+1;else{if(a=S.getActiveUniformBlockParameter(a,b,c),a!==null)if(c==35395)for(c=0;c<a.length;c++)r[d+c*4>>2]=a[c];else r[d>>2]=a}else X||=1281},rc:(a,b,c,d,e)=>{if(e)if(b>0&&c==0)X||=1281;else{a=U[a];for(var g=[],f=0;f<b;f++)g.push(r[c+
f*4>>2]);if(a=S.getActiveUniforms(a,g,d))for(b=a.length,f=0;f<b;f++)r[e+f*4>>2]=a[f]}else X||=1281},of:(a,b,c,d)=>{a=S.getAttachedShaders(U[a]);var e=a.length;e>b&&(e=b);r[c>>2]=e;for(b=0;b<e;++b)r[d+b*4>>2]=V.indexOf(a[b])},nf:(a,b)=>S.getAttribLocation(U[a],b?A(q,b):""),mf:(a,b)=>Jd(a,b,4),cc:(a,b,c)=>{c?Hd(c,S.getBufferParameter(a,b)):X||=1281},lf:(a,b,c)=>{c?r[c>>2]=S.getBufferParameter(a,b):X||=1281},kf:()=>{var a=S.getError()||X;X=0;return a},jf:(a,b)=>Jd(a,b,2),Hc:(a,b)=>S.getFragDataLocation(U[a],
b?A(q,b):""),hf:(a,b,c,d)=>{a=S.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;r[d>>2]=a},dc:(a,b,c)=>Kd(a,b,c,1),fc:(a,b)=>{Jd(a,b,1)},Wc:(a,b,c)=>Kd(a,b,c,0),gf:(a,b)=>Jd(a,b,0),Fb:(a,b,c,d,e)=>{if(d<0)X||=1281;else if(e){if(a=S.getInternalformatParameter(a,b,c),a!==null)for(b=0;b<a.length&&b<d;++b)r[e+b*4>>2]=a[b]}else X||=1281},Mb:()=>{X||=1282},ef:(a,b,c,d)=>{a=S.getProgramInfoLog(U[a]);a===null&&(a="(unknown error)");b=b>0&&d?
B(a,q,d,b):0;c&&(r[c>>2]=b)},ff:(a,b,c)=>{if(c)if(a>=fd)X||=1281;else if(a=U[a],b==35716)a=S.getProgramInfoLog(a),a===null&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(b==35719){if(!a.sh){var d=S.getProgramParameter(a,35718);for(b=0;b<d;++b)a.sh=Math.max(a.sh,S.getActiveUniform(a,b).name.length+1)}r[c>>2]=a.sh}else if(b==35722){if(!a.qh)for(d=S.getProgramParameter(a,35721),b=0;b<d;++b)a.qh=Math.max(a.qh,S.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.qh}else if(b==35381){if(!a.rh)for(d=S.getProgramParameter(a,
35382),b=0;b<d;++b)a.rh=Math.max(a.rh,S.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.rh}else r[c>>2]=S.getProgramParameter(a,b);else X||=1281},Ia:Ld,Ka:Md,Ha:Ld,jd:(a,b,c)=>{if(c){a=S.getQueryParameter(W[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;r[c>>2]=d}else X||=1281},Ja:Md,kd:(a,b,c)=>{c?r[c>>2]=S.getQuery(a,b):X||=1281},La:(a,b,c)=>{c?r[c>>2]=S.yg.getQueryEXT(a,b):X||=1281},df:(a,b,c)=>{c?r[c>>2]=S.getRenderbufferParameter(a,b):X||=1281},Ub:(a,b,c)=>{c?w[c>>2]=S.getSamplerParameter(nd[a],
b):X||=1281},Vb:(a,b,c)=>{c?r[c>>2]=S.getSamplerParameter(nd[a],b):X||=1281},bf:(a,b,c,d)=>{a=S.getShaderInfoLog(V[a]);a===null&&(a="(unknown error)");b=b>0&&d?B(a,q,d,b):0;c&&(r[c>>2]=b)},af:(a,b,c,d)=>{a=S.getShaderPrecisionFormat(a,b);r[c>>2]=a.rangeMin;r[c+4>>2]=a.rangeMax;r[d>>2]=a.precision},$e:(a,b,c,d)=>{if(a=S.getShaderSource(V[a]))b=b>0&&d?B(a,q,d,b):0,c&&(r[c>>2]=b)},cf:(a,b,c)=>{c?b==35716?(a=S.getShaderInfoLog(V[a]),a===null&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):b==35720?(a=
S.getShaderSource(V[a]),r[c>>2]=a?a.length+1:0):r[c>>2]=S.getShaderParameter(V[a],b):X||=1281},_e:a=>{var b=qd[a];if(!b){switch(a){case 7939:b=Od(Id().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=S.getParameter(a))||(X||=1280);b=b?Od(b):0;break;case 7938:b=Od(`OpenGL ES 3.0 (${S.getParameter(7938)})`);break;case 35724:b=S.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);c!==null&&(c[1].length==3&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=
Od(b);break;default:X||=1280}qd[a]=b}return b},uc:(a,b)=>{if(yd.version<2)return X||=1282,0;var c=rd[a];if(c)return b<0||b>=c.length?(X||=1281,0):c[b];switch(a){case 7939:return c=Id().map(Od),c=rd[a]=c,b<0||b>=c.length?(X||=1281,0):c[b];default:return X||=1280,0}},ec:(a,b,c,d,e)=>{c<0?X||=1281:e?(a=S.getSyncParameter(pd[a],b),a!==null&&(r[e>>2]=a,d&&(r[d>>2]=1))):X||=1281},Ze:(a,b,c)=>{c?w[c>>2]=S.getTexParameter(a,b):X||=1281},Ye:(a,b,c)=>{c?r[c>>2]=S.getTexParameter(a,b):X||=1281},Qc:(a,b,c,d,
e,g,f)=>{a=U[a];if(a=S.getTransformFeedbackVarying(a,b))f&&c>0?(c=B(a.name,q,f,c),d&&(r[d>>2]=c)):d&&(r[d>>2]=0),e&&(r[e>>2]=a.size),g&&(r[g>>2]=a.type)},qc:(a,b)=>S.getUniformBlockIndex(U[a],b?A(q,b):""),sc:(a,b,c,d)=>{if(d)if(b>0&&(c==0||d==0))X||=1281;else{a=U[a];for(var e=[],g=0;g<b;g++)e.push(Rb(u[c+g*4>>2]));if(a=S.getUniformIndices(a,e))for(b=a.length,g=0;g<b;g++)r[d+g*4>>2]=a[g]}else X||=1281},Ve:(a,b)=>{b=b?A(q,b):"";if(a=U[a]){Qd(a);var c=a.kh,d=0,e=b,g=Pd(b);g>0&&(d=parseInt(b.slice(g+
1))>>>0,e=b.slice(0,g));if((e=a.mi[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else X||=1281;return-1},Xe:(a,b,c)=>{Rd(a,b,c,2)},We:(a,b,c)=>{Rd(a,b,c,0)},Ic:(a,b,c)=>Rd(a,b,c,0),Oc:Td,Nc:Td,Re:(a,b,c)=>{c?r[c>>2]=S.getVertexAttribOffset(a,b):X||=1281},Te:(a,b,c)=>{Sd(a,b,c,2)},Se:(a,b,c)=>{Sd(a,b,c,5)},Qe:(a,b)=>S.hint(a,b),Jb:(a,b,c)=>{for(var d=Cd[b],e=0;e<b;e++)d[e]=r[c+e*4>>2];S.invalidateFramebuffer(a,d)},Ib:(a,b,c,d,e,g,f)=>{for(var k=Cd[b],m=0;m<b;m++)k[m]=r[c+m*4>>
2];S.invalidateSubFramebuffer(a,k,d,e,g,f)},Pe:a=>(a=gd[a])?S.isBuffer(a):0,Oe:a=>S.isEnabled(a),Ne:a=>(a=hd[a])?S.isFramebuffer(a):0,Me:a=>(a=U[a])?S.isProgram(a):0,nd:a=>(a=W[a])?S.isQuery(a):0,Pa:a=>(a=W[a])?S.yg.isQueryEXT(a):0,Le:a=>(a=jd[a])?S.isRenderbuffer(a):0,$b:a=>(a=nd[a])?S.isSampler(a):0,Ke:a=>(a=V[a])?S.isShader(a):0,jc:a=>S.isSync(pd[a]),Ie:a=>(a=kd[a])?S.isTexture(a):0,Pb:a=>S.isTransformFeedback(od[a]),Xc:Ud,Da:Ud,He:a=>S.lineWidth(a),Ge:a=>{a=U[a];S.linkProgram(a);a.kh=0;a.mi={}},
Ob:()=>S.pauseTransformFeedback(),Fe:(a,b)=>{a==3317?sd=b:a==3314&&(td=b);S.pixelStorei(a,b)},Cd:(a,b)=>{S.Zi.polygonModeWEBGL(a,b)},Ee:(a,b)=>S.polygonOffset(a,b),Ed:(a,b,c)=>{S.Di.polygonOffsetClampEXT(a,b,c)},Lb:()=>{X||=1280},Kb:()=>{X||=1280},Ma:(a,b)=>{S.yg.queryCounterEXT(W[a],b)},xd:a=>S.readBuffer(a),De:(a,b,c,d,e,g,f)=>{if(S.Dh)S.readPixels(a,b,c,d,e,g,f);else{var k=Vd(g);f>>>=31-Math.clz32(k.BYTES_PER_ELEMENT);S.readPixels(a,b,c,d,e,g,k,f)}},Ce:()=>{},Be:(a,b,c,d)=>S.renderbufferStorage(a,
b,c,d),ad:(a,b,c,d,e)=>S.renderbufferStorageMultisample(a,b,c,d,e),Nb:()=>S.resumeTransformFeedback(),Ae:(a,b)=>{S.sampleCoverage(a,!!b)},Xb:(a,b,c)=>{S.samplerParameterf(nd[a],b,c)},Wb:(a,b,c)=>{S.samplerParameterf(nd[a],b,w[c>>2])},Zb:(a,b,c)=>{S.samplerParameteri(nd[a],b,c)},Yb:(a,b,c)=>{S.samplerParameteri(nd[a],b,r[c>>2])},ze:(a,b,c,d)=>S.scissor(a,b,c,d),ye:()=>{X||=1280},xe:(a,b,c,d)=>{for(var e="",g=0;g<b;++g)e+=Rb(u[c+g*4>>2],d?u[d+g*4>>2]:void 0);S.shaderSource(V[a],e)},we:(a,b,c)=>S.stencilFunc(a,
b,c),ve:(a,b,c,d)=>S.stencilFuncSeparate(a,b,c,d),ue:a=>S.stencilMask(a),te:(a,b)=>S.stencilMaskSeparate(a,b),se:(a,b,c)=>S.stencilOp(a,b,c),re:(a,b,c,d)=>S.stencilOpSeparate(a,b,c,d),qe:(a,b,c,d,e,g,f,k,m)=>{if(S.Gg)S.texImage2D(a,b,c,d,e,g,f,k,m);else if(m){var n=Vd(k);m>>>=31-Math.clz32(n.BYTES_PER_ELEMENT);S.texImage2D(a,b,c,d,e,g,f,k,n,m)}else n=m?Wd(k,f,d,e,m):null,S.texImage2D(a,b,c,d,e,g,f,k,n)},vd:(a,b,c,d,e,g,f,k,m,n)=>{if(S.Gg)S.texImage3D(a,b,c,d,e,g,f,k,m,n);else if(n){var t=Vd(m);S.texImage3D(a,
b,c,d,e,g,f,k,m,t,n>>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else S.texImage3D(a,b,c,d,e,g,f,k,m,null)},pe:(a,b,c)=>S.texParameterf(a,b,c),oe:(a,b,c)=>{S.texParameterf(a,b,w[c>>2])},ne:(a,b,c)=>S.texParameteri(a,b,c),me:(a,b,c)=>{S.texParameteri(a,b,r[c>>2])},Hb:(a,b,c,d,e)=>S.texStorage2D(a,b,c,d,e),Gb:(a,b,c,d,e,g)=>S.texStorage3D(a,b,c,d,e,g),le:(a,b,c,d,e,g,f,k,m)=>{if(S.Gg)S.texSubImage2D(a,b,c,d,e,g,f,k,m);else if(m){var n=Vd(k);S.texSubImage2D(a,b,c,d,e,g,f,k,n,m>>>31-Math.clz32(n.BYTES_PER_ELEMENT))}else m=
m?Wd(k,f,e,g,m):null,S.texSubImage2D(a,b,c,d,e,g,f,k,m)},ud:(a,b,c,d,e,g,f,k,m,n,t)=>{if(S.Gg)S.texSubImage3D(a,b,c,d,e,g,f,k,m,n,t);else if(t){var v=Vd(n);S.texSubImage3D(a,b,c,d,e,g,f,k,m,n,v,t>>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else S.texSubImage3D(a,b,c,d,e,g,f,k,m,n,null)},Rc:(a,b,c,d)=>{a=U[a];for(var e=[],g=0;g<b;g++)e.push(Rb(u[c+g*4>>2]));S.transformFeedbackVaryings(a,e,d)},ke:(a,b)=>{S.uniform1f(Z(S.kg,a),b)},je:(a,b,c)=>{b&&S.uniform1fv(Z(S.kg,a),w,c>>2,b)},ie:(a,b)=>{S.uniform1i(Z(S.kg,
a),b)},he:(a,b,c)=>{b&&S.uniform1iv(Z(S.kg,a),r,c>>2,b)},Gc:(a,b)=>{S.uniform1ui(Z(S.kg,a),b)},Cc:(a,b,c)=>{b&&S.uniform1uiv(Z(S.kg,a),u,c>>2,b)},ge:(a,b,c)=>{S.uniform2f(Z(S.kg,a),b,c)},fe:(a,b,c)=>{b&&S.uniform2fv(Z(S.kg,a),w,c>>2,b*2)},de:(a,b,c)=>{S.uniform2i(Z(S.kg,a),b,c)},ce:(a,b,c)=>{b&&S.uniform2iv(Z(S.kg,a),r,c>>2,b*2)},Fc:(a,b,c)=>{S.uniform2ui(Z(S.kg,a),b,c)},Bc:(a,b,c)=>{b&&S.uniform2uiv(Z(S.kg,a),u,c>>2,b*2)},be:(a,b,c,d)=>{S.uniform3f(Z(S.kg,a),b,c,d)},ae:(a,b,c)=>{b&&S.uniform3fv(Z(S.kg,
a),w,c>>2,b*3)},$d:(a,b,c,d)=>{S.uniform3i(Z(S.kg,a),b,c,d)},_d:(a,b,c)=>{b&&S.uniform3iv(Z(S.kg,a),r,c>>2,b*3)},Ec:(a,b,c,d)=>{S.uniform3ui(Z(S.kg,a),b,c,d)},Ac:(a,b,c)=>{b&&S.uniform3uiv(Z(S.kg,a),u,c>>2,b*3)},Zd:(a,b,c,d,e)=>{S.uniform4f(Z(S.kg,a),b,c,d,e)},Yd:(a,b,c)=>{b&&S.uniform4fv(Z(S.kg,a),w,c>>2,b*4)},Xd:(a,b,c,d,e)=>{S.uniform4i(Z(S.kg,a),b,c,d,e)},Wd:(a,b,c)=>{b&&S.uniform4iv(Z(S.kg,a),r,c>>2,b*4)},Dc:(a,b,c,d,e)=>{S.uniform4ui(Z(S.kg,a),b,c,d,e)},zc:(a,b,c)=>{b&&S.uniform4uiv(Z(S.kg,
a),u,c>>2,b*4)},nc:(a,b,c)=>{a=U[a];S.uniformBlockBinding(a,b,c)},Vd:(a,b,c,d)=>{b&&S.uniformMatrix2fv(Z(S.kg,a),!!c,w,d>>2,b*4)},hd:(a,b,c,d)=>{b&&S.uniformMatrix2x3fv(Z(S.kg,a),!!c,w,d>>2,b*6)},fd:(a,b,c,d)=>{b&&S.uniformMatrix2x4fv(Z(S.kg,a),!!c,w,d>>2,b*8)},Ud:(a,b,c,d)=>{b&&S.uniformMatrix3fv(Z(S.kg,a),!!c,w,d>>2,b*9)},gd:(a,b,c,d)=>{b&&S.uniformMatrix3x2fv(Z(S.kg,a),!!c,w,d>>2,b*6)},dd:(a,b,c,d)=>{b&&S.uniformMatrix3x4fv(Z(S.kg,a),!!c,w,d>>2,b*12)},Td:(a,b,c,d)=>{b&&S.uniformMatrix4fv(Z(S.kg,
a),!!c,w,d>>2,b*16)},ed:(a,b,c,d)=>{b&&S.uniformMatrix4x2fv(Z(S.kg,a),!!c,w,d>>2,b*8)},cd:(a,b,c,d)=>{b&&S.uniformMatrix4x3fv(Z(S.kg,a),!!c,w,d>>2,b*12)},Sd:a=>{a=U[a];S.useProgram(a);S.kg=a},Rd:a=>{S.validateProgram(U[a])},Qd:(a,b)=>S.vertexAttrib1f(a,b),Pd:(a,b)=>{S.vertexAttrib1f(a,w[b>>2])},Od:(a,b,c)=>S.vertexAttrib2f(a,b,c),Nd:(a,b)=>{S.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},Md:(a,b,c,d)=>S.vertexAttrib3f(a,b,c,d),Jd:(a,b)=>{S.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},Id:(a,b,c,d,e)=>S.vertexAttrib4f(a,
b,c,d,e),Hd:(a,b)=>{S.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Tb:Xd,za:Xd,Db:Xd,Bd:Xd,Eb:Xd,Mc:(a,b,c,d,e)=>S.vertexAttribI4i(a,b,c,d,e),Kc:(a,b)=>{S.vertexAttribI4i(a,r[b>>2],r[b+4>>2],r[b+8>>2],r[b+12>>2])},Lc:(a,b,c,d,e)=>S.vertexAttribI4ui(a,b,c,d,e),Jc:(a,b)=>{S.vertexAttribI4ui(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Pc:(a,b,c,d,e)=>{S.vertexAttribIPointer(a,b,c,d,e)},Gd:(a,b,c,d,e,g)=>{S.vertexAttribPointer(a,b,c,!!d,e,g)},Fd:(a,b,c,d)=>S.viewport(a,b,c,d),gc:(a,b,c)=>
{c=Number(c);S.waitSync(pd[a],b,c)},k:()=>0,Ta:(a,b,c)=>Yd(a,{Uh:r[c>>2],Ch:r[c+4>>2],Ei:r[c+8>>2],yi:b,mh:r[c+12>>2],ci:r[c+16>>2]}),J:(a,b)=>{a=Q(a);return a?a.requestPointerLock?Ec()?Xc(a):b?(Cc(Xc,2,[a]),1):-2:-1:-4},_a:a=>{var b=q.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-la.buffer.byteLength+65535)/65536|0;try{la.grow(d);ka();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},
s:Zd,u:(a,b,c)=>typeof onbeforeunload=="undefined"?-1:c!==1?-5:$d(a,b),G:(a,b,c,d)=>ae(a,b,c,d,12,"blur"),d:Oc,g:(a,b,c)=>{a=Q(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},H:(a,b,c,d)=>ae(a,b,c,d,13,"focus"),E:(a,b,c,d)=>{if(!P.fullscreenEnabled())return-1;a=Q(a);if(!a)return-4;be(a,b,c,d,"webkitfullscreenchange");return be(a,b,c,d,"fullscreenchange")},N:(a,b,c)=>Zd()?-1:ce(a,b,c,26,"gamepadconnected"),M:(a,b,c)=>Zd()?-1:ce(a,b,c,27,"gamepaddisconnected"),q:(a,b,c,d)=>de(a,
b,c,d,2,"keydown"),l:(a,b,c,d)=>de(a,b,c,d,1,"keypress"),n:(a,b,c,d)=>de(a,b,c,d,3,"keyup"),Va:(a,b,c)=>{a=R(a);yc(a,b,c)},e:nc,B:(a,b,c)=>window.screen&&screen.orientation?ee(a,b,c):-1,F:(a,b,c,d)=>document.body?.requestPointerLock?(a=Q(a))?fe(a,b,c,d):-4:-1,D:(a,b,c,d)=>ge(a,b,c,d),w:(a,b,c)=>he(a,b,c),C:(a,b,c,d)=>(a=Q(a))?typeof a.onwheel!="undefined"?ie(a,b,c,d):-1:-4,Wa:a=>document.title=a?A(q,a):"",j:()=>{z("Please compile your program with async support in order to use asynchronous operations like emscripten_sleep")},
Je:(a,b)=>{var c=b>>2;b={alpha:!!p[b+0],depth:!!p[b+1],stencil:!!p[b+2],antialias:!!p[b+3],premultipliedAlpha:!!p[b+4],preserveDrawingBuffer:!!p[b+5],powerPreference:je[r[c+2]],failIfMajorPerformanceCaveat:!!p[b+12],desynchronized:!!p[b+33],Pi:r[c+4],sj:r[c+5],ei:p[b+24],Bi:p[b+25],wj:r[c+7],zj:p[b+32]};a=Q(a);return!a||b.Bi?0:xd(a,b)},K:a=>{yd==a&&(yd=0);yd===md[a]&&(yd=null);typeof P=="object"&&P.Wi(md[a].Rg.canvas);md[a]?.Rg.canvas&&(md[a].Rg.canvas.Zg=void 0);md[a]=null},L:a=>{yd=md[a];h.ctx=
S=yd?.Rg;return!a||S?0:-5},xb:(a,b)=>{var c=0,d=0,e;for(e of me()){var g=b+c;u[a+d>>2]=g;c+=B(e,q,g,Infinity)+1;d+=4}return 0},yb:(a,b)=>{var c=me();u[a>>2]=c.length;a=0;for(var d of c)a+=Ja(d)+1;u[b>>2]=a;return 0},t:a=>{throw new wa(a);},h:function(a){try{var b=L(a);Ib(b);return 0}catch(c){if(typeof N=="undefined"||c.name!=="ErrnoError")throw c;return c.lg}},z:function(a,b,c,d){try{a:{var e=L(a);a=b;for(var g,f=b=0;f<c;f++){var k=u[a>>2],m=u[a+4>>2];a+=8;try{var n=e,t=k,v=m,C=g,D=p;if(v<0||C<0)throw new E(28);
if(n.fd===null)throw new E(8);if((n.flags&2097155)===1)throw new E(8);if(J(n.node.mode))throw new E(31);if(!n.ig.read)throw new E(28);var G=typeof C!="undefined";if(!G)C=n.position;else if(!n.seekable)throw new E(70);var I=n.ig.read(n,D,t,v,C);G||(n.position+=I);var H=I}catch(Y){if(b>0&&Y instanceof E&&(Y.lg==6||Y.lg==6))break;throw Y;}if(H<0){var T=-1;break a}b+=H;if(H<m)break;typeof g!="undefined"&&(g+=H)}T=b}u[d>>2]=T;return 0}catch(Y){if(typeof N=="undefined"||Y.name!=="ErrnoError")throw Y;return Y.lg}},
ib:function(a,b,c,d){b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;var e=L(a);Jb(e,b,c);y[d>>3]=BigInt(e.position);e.Sg&&!b&&c===0&&(e.Sg=null);return 0}catch(g){if(typeof N=="undefined"||g.name!=="ErrnoError")throw g;return g.lg}},lb:function(a){try{var b=L(a);return b.ig?.dh?.(b)}catch(c){if(typeof N=="undefined"||c.name!=="ErrnoError")throw c;return c.lg}},m:function(a,b,c,d){try{var e=L(a);a=b;if(c==1)var g=Kb(e,p,u[a>>2],u[a+4>>2]);else{for(var f=b=0,k=a;f<
c;f++,k+=8)b+=u[k+4>>2];var m=new Uint8Array(b);for(f=k=0;f<c;f++,a+=8){var n=u[a>>2],t=u[a+4>>2];m.set(q.subarray(n,n+t),k);k+=t}g=Kb(e,m,0,b)}u[d>>2]=g;return 0}catch(v){if(typeof N=="undefined"||v.name!=="ErrnoError")throw v;return v.lg}},Xa:He,Za:(a,b)=>Ea(q.subarray(a,a+b))};function He(a,b,c){var d=Lc();try{R(a)(b,c)}catch(e){Mc(d);if(!(e instanceof ia))throw e;Ge(1,0)}}
function Je(a=[]){var b=Fe;a.unshift("./this.program");var c=a.length,d=Jc((c+1)*4),e=d,g;for(g of a)u[e>>2]=Kc(g),e+=4;u[e>>2]=0;try{var f=b(c,d);throw new wa(f);}catch(k){oc(k)}}
async function Ke(){oa();Za&&await Ya();var a=h.setStatus;a&&(a("Running..."),await new Promise(b=>setTimeout(b,1)),setTimeout(a,1,""));ha||(h.noFSInit||kb||(kb=!0,Cb("/dev/tty","/dev/stdin"),Cb("/dev/tty","/dev/stdout"),Cb("/dev/tty1","/dev/stderr"),Hb("/dev/stdin",0),Hb("/dev/stdout",1),Hb("/dev/stderr",1)),Le.Jf(),lb=!1,Je(aa),qa())}var Le;
(async function(){var a={a:Ie};sa??=ca+"hello_world.wasm";a=Le=(await va(a)).instance.exports;Nd=h._malloc=a.Kf;h._free=a.Lf;Fe=h._main=a.Mf;xe=h._SDL_free=a.Nf;ue=h._SDL_malloc=a.Of;h._SDL_calloc=a.Pf;qe=h._Emscripten_force_free=a.Qf;h._SDL_realloc=a.Rf;h._CallSDLEmscriptenMainFunction=a.Sf;ye=h._Emscripten_HandlePointerEnter=a.Tf;ze=h._Emscripten_HandlePointerLeave=a.Uf;Ae=h._Emscripten_HandlePointerGeneric=a.Vf;we=h._Emscripten_HandleMouseButtonUpGlobal=a.Wf;Be=h._Emscripten_SendDragEvent=a.Xf;
Ee=h._Emscripten_SendDragCompleteEvent=a.Yf;Ce=h._Emscripten_SendDragTextEvent=a.Zf;De=h._Emscripten_SendDragFileEvent=a._f;ve=h._Emscripten_HandleLockKeysCheck=a.$f;te=h._Emscripten_SendSystemThemeChangedEvent=a.ag;re=h._requestFullscreenThroughSDL=a.bg;Ge=a.dg;Mc=a.eg;Jc=a.fg;Lc=a.gg;la=a.If;Sc=a.cg;ka();return Le})().then(()=>Ke());
