var h;h||=typeof Module != 'undefined' ? Module : {};h.expectedDataFileDownloads||(h.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a=typeof ENVIRONMENT_IS_WASM_WORKER!="undefined"&&ENVIRONMENT_IS_WASM_WORKER;typeof ENVIRONMENT_IS_PTHREAD!="undefined"&&ENVIRONMENT_IS_PTHREAD||a||async function(b){async function c(k,p){h.dataFileDownloads||(h.dataFileDownloads={});try{var q=await fetch(k)}catch(I){throw Error(`Network Error: ${k}`,{e:I});}if(!q.ok)throw Error(`${q.status}: ${q.url}`);var v=[];p=Number(q.headers.get("Content-Length")||p);var C=0;h.setStatus&&h.setStatus("Downloading data...");for(q=q.body.getReader();;){var D;
({done:D,value:G}=await q.read());if(D)break;v.push(G);C+=G.length;h.dataFileDownloads[k]={loaded:C,total:p};var G=D=0;for(var J of Object.values(h.dataFileDownloads))D+=J.loaded,G+=J.total;h.setStatus&&h.setStatus(`Downloading data... (${D}/${G})`)}k=new Uint8Array(v.map(I=>I.length).reduce((I,S)=>I+S,0));J=0;for(let I of v)k.set(I,J),J+=I.length;return k.buffer}async function d(k){k.addRunDependency("datafile_/Users/shenyiwen/projects/fountain2/bin/emscripten/nirvana/playground_nirvana.data");k.preloadResults||
(k.preloadResults={});k.preloadResults["/Users/shenyiwen/projects/fountain2/bin/emscripten/nirvana/playground_nirvana.data"]={ij:!1};m||=await g;await async function(p){if(!p)throw Error("Loading data file failed.");if(p.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+p.constructor.name);p=new Uint8Array(p);for(var q of b.files)k.FS_createDataFile(q.filename,null,p.subarray(q.start,q.end),!0,!0,!0);k.removeRunDependency("datafile_/Users/shenyiwen/projects/fountain2/bin/emscripten/nirvana/playground_nirvana.data")}(m)}
typeof window==="object"?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):typeof process==="undefined"&&typeof location!=="undefined"&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var e=h.locateFile?h.locateFile("playground_nirvana.data",""):"playground_nirvana.data",f=b.remote_package_size,g,m=h.getPreloadedPackage&&h.getPreloadedPackage(e,f);m||(g=c(e,f));h.FS_createPath?d(h):(h.preRun||(h.preRun=
[]),h.preRun.push(d))}({files:[{filename:"/assets.dat",start:0,end:804683}],remote_package_size:804683})})();var aa=[],ba="./this.program",ca=globalThis.document?.currentScript?.src,da="",ea;try{da=(new URL(".",ca)).href}catch{}ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),l=console.error.bind(console),ha,ia=!1,ja;
function ka(){var a=la.buffer;n=new Int8Array(a);ma=new Int16Array(a);r=new Uint8Array(a);na=new Uint16Array(a);t=new Int32Array(a);u=new Uint32Array(a);w=new Float32Array(a);x=new Float64Array(a);y=new BigInt64Array(a);new BigUint64Array(a)}function z(a){h.onAbort?.(a);a=`Aborted(${a})`;l(a);ia=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var pa;
async function qa(a){if(!ha)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==pa&&ha)a=new Uint8Array(ha);else throw"both async and sync fetching of the wasm failed";return a}async function ra(a,b){try{var c=await qa(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),z(d)}}
async function sa(a){var b=pa;if(!ha)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return ra(b,a)}class ta{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ma,t,y,n,w,x,na,u,r,ua=a=>{for(;a.length>0;)a.shift()(h)},va=[],wa=()=>{var a=h.postRun.shift();va.push(a)},xa=[],ya=()=>{var a=h.preRun.shift();xa.push(a)},za=!0;function Aa(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":n[a]=b;break;case "i8":n[a]=b;break;case "i16":ma[a>>1]=b;break;case "i32":t[a>>2]=b;break;case "i64":y[a>>3]=BigInt(b);break;case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":u[a>>2]=b;break;default:z(`invalid type for setValue: ${c}`)}}
class Ba{constructor(a){this.oh=a-24}init(a,b){u[this.oh+16>>2]=0;u[this.oh+4>>2]=a;u[this.oh+8>>2]=b}}
var Ca=0,Da=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ea=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=Da(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Fa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ga=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],
Ha=()=>a=>(crypto.getRandomValues(a),0),Ia=a=>(Ia=Ha())(a),Ja=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c=c.charAt(0)==="/"}b=Da(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ka=new TextDecoder,La=(a,b,c)=>{for(c=b+c;a[b]&&!(b>=c);)++b;return b},Ma=a=>{var b=La(a,0);return Ka.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},
Na=[],Oa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},A=(a,b,c,d)=>{if(!(d>0))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(c>=d)break;b[c++]=g}else if(g<=2047){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(g<=65535){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=
128|g&63;f++}}b[c]=0;return c-e},Pa=a=>{var b=Array(Oa(a)+1);a=A(a,b,0,b.length);b.length=a;return b},Qa=[];function Ra(a,b){Qa[a]={input:[],output:[],Fg:b};Sa(a,Ta)}
var Ta={open(a){var b=Qa[a.node.dh];if(!b)throw new B(43);a.hg=b;a.seekable=!1},close(a){a.hg.Fg.Yg(a.hg)},Yg(a){a.hg.Fg.Yg(a.hg)},read(a,b,c,d){if(!a.hg||!a.hg.Fg.$h)throw new B(60);for(var e=0,f=0;f<d;f++){try{var g=a.hg.Fg.$h(a.hg)}catch(m){throw new B(29);}if(g===void 0&&e===0)throw new B(6);if(g===null||g===void 0)break;e++;b[c+f]=g}e&&(a.node.Hg=Date.now());return e},write(a,b,c,d){if(!a.hg||!a.hg.Fg.Mh)throw new B(60);try{for(var e=0;e<d;e++)a.hg.Fg.Mh(a.hg,b[c+e])}catch(f){throw new B(29);
}d&&(a.node.rg=a.node.og=Date.now());return e}},Ua={$h(){a:{if(!Na.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}Na=Pa(a)}a=Na.shift()}return a},Mh(a,b){b===null||b===10?(fa(Ma(a.output)),a.output=[]):b!=0&&a.output.push(b)},Yg(a){a.output?.length>0&&(fa(Ma(a.output)),a.output=[])},Fi(){return{Yi:25856,$i:5,Xi:191,Zi:35387,Wi:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Gi(){return 0},Hi(){return[24,
80]}},Va={Mh(a,b){b===null||b===10?(l(Ma(a.output)),a.output=[]):b!=0&&a.output.push(b)},Yg(a){a.output?.length>0&&(l(Ma(a.output)),a.output=[])}},E={Cg:null,Eg(){return E.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||(c&61440)===4096)throw new B(63);E.Cg||(E.Cg={dir:{node:{ug:E.bg.ug,Gg:E.bg.Gg,ah:E.bg.ah,nh:E.bg.nh,ei:E.bg.ei,sh:E.bg.sh,qh:E.bg.qh,ph:E.bg.ph,rh:E.bg.rh},stream:{Bg:E.cg.Bg}},file:{node:{ug:E.bg.ug,Gg:E.bg.Gg},stream:{Bg:E.cg.Bg,read:E.cg.read,write:E.cg.write,
Jh:E.cg.Jh,ci:E.cg.ci}},link:{node:{ug:E.bg.ug,Gg:E.bg.Gg,Mg:E.bg.Mg},stream:{}},Xh:{node:{ug:E.bg.ug,Gg:E.bg.Gg},stream:Wa}});c=Xa(a,b,c,d);F(c.mode)?(c.bg=E.Cg.dir.node,c.cg=E.Cg.dir.stream,c.fg={}):(c.mode&61440)===32768?(c.bg=E.Cg.file.node,c.cg=E.Cg.file.stream,c.ng=0,c.fg=E.ti??(E.ti=new Uint8Array(0))):(c.mode&61440)===40960?(c.bg=E.Cg.link.node,c.cg=E.Cg.link.stream):(c.mode&61440)===8192&&(c.bg=E.Cg.Xh.node,c.cg=E.Cg.Xh.stream);c.Hg=c.rg=c.og=Date.now();a&&(a.fg[b]=c,a.Hg=a.rg=a.og=c.Hg);
return c},bg:{ug(a){var b={};b.si=(a.mode&61440)===8192?a.id:1;b.Di=a.id;b.mode=a.mode;b.Mi=1;b.uid=0;b.zi=0;b.dh=a.dh;F(a.mode)?b.size=4096:(a.mode&61440)===32768?b.size=a.ng:(a.mode&61440)===40960?b.size=a.link.length:b.size=0;b.Hg=new Date(a.Hg);b.rg=new Date(a.rg);b.og=new Date(a.og);b.ki=4096;b.li=Math.ceil(b.size/b.ki);return b},Gg(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.ng!=b&&(c=a.fg,a.fg=new Uint8Array(b),a.fg.set(c.subarray(0,
Math.min(b,a.ng))),a.ng=b))},ah(){E.yh||(E.yh=new B(44),E.yh.stack="<generic error, no stack>");throw E.yh;},nh(a,b,c,d){return E.createNode(a,b,c,d)},ei(a,b,c){try{var d=Ya(b,c)}catch(f){}if(d){if(F(a.mode))for(var e in d.fg)throw new B(55);Za(d)}delete a.parent.fg[a.name];b.fg[c]=a;a.name=c;b.og=b.rg=a.parent.og=a.parent.rg=Date.now()},sh(a,b){delete a.fg[b];a.og=a.rg=Date.now()},qh(a,b){var c=Ya(a,b),d;for(d in c.fg)throw new B(55);delete a.fg[b];a.og=a.rg=Date.now()},ph(a){return[".","..",...Object.keys(a.fg)]},
rh(a,b,c){a=E.createNode(a,b,41471,0);a.link=c;return a},Mg(a){if((a.mode&61440)!==40960)throw new B(28);return a.link}},cg:{read(a,b,c,d,e){if(e>=a.node.ng)return 0;d=Math.min(a.node.ng-e,d);b.set(a.node.fg.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===n.buffer&&(f=!1);if(!d)return 0;a=a.node;a.rg=a.og=Date.now();if(f)a.fg=b.subarray(c,c+d),a.ng=d;else if(a.ng===0&&e===0)a.fg=b.slice(c,c+d),a.ng=d;else{f=e+d;var g=a.fg.length;g>=f||(f=Math.max(f,g*(g<1048576?2:1.125)>>>0),g&&(f=Math.max(f,
256)),g=a.fg.subarray(0,a.ng),a.fg=new Uint8Array(f),a.fg.set(g));a.fg.set(b.subarray(c,c+d),e);a.ng=Math.max(a.ng,e+d)}return d},Bg(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&61440)===32768&&(b+=a.node.ng);if(b<0)throw new B(28);return b},Jh(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new B(43);a=a.node.fg;if(e&2||a.buffer!==n.buffer){d=!0;z();e=void 0;if(!e)throw new B(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);n.set(a,e)}}else d=
!1,e=a.byteOffset;return{oh:e,Ti:d}},ci(a,b,c,d){E.cg.write(a,b,0,d,c,!1);return 0}}},$a=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ab=async a=>{a=await ea(a);return new Uint8Array(a)},bb=0,cb=null,db=()=>{bb--;h.monitorRunDependencies?.(bb);if(bb==0&&cb){var a=cb;cb=null;a()}},eb=()=>{bb++;h.monitorRunDependencies?.(bb)},fb=[],ib=async(a,b)=>{typeof gb!="undefined"&&hb();for(var c of fb)if(c.canHandle(b))return c.handle(a,b);return a},jb=null,kb={},lb=[],mb=1,nb=null,ob=!1,pb=!0,B=class{name=
"ErrnoError";constructor(a){this.ig=a}},qb=class{shared={};node=null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},rb=class{bg={};cg={};Rg=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Eg=a.Eg;this.id=mb++;this.name=b;this.mode=c;this.dh=d;this.Hg=this.rg=this.og=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&
146)===146}set write(a){a?this.mode|=146:this.mode&=-147}get Ji(){return F(this.mode)}get Ii(){return(this.mode&61440)===8192}};
function H(a,b={}){if(!a)throw new B(44);b.Dh??(b.Dh=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(m=>!!m);for(var d=jb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if(a[f]!==".")if(a[f]==="..")if(e=Fa(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Ea(e+"/"+a[f]);try{d=Ya(d,a[f])}catch(m){if(m?.ig===44&&g&&b.Ni)return{path:e};throw m;}!d.Rg||g&&!b.Dh||(d=d.Rg.root);if((d.mode&61440)===40960&&(!g||b.Qg)){if(!d.bg.Mg)throw new B(52);
d=d.bg.Mg(d);d.charAt(0)==="/"||(d=Fa(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new B(32);}function sb(a){for(var b;;){if(a===a.parent)return a=a.Eg.bi,b?a[a.length-1]!=="/"?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function tb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%nb.length}
function Za(a){var b=tb(a.parent.id,a.name);if(nb[b]===a)nb[b]=a.Sg;else for(b=nb[b];b;){if(b.Sg===a){b.Sg=a.Sg;break}b=b.Sg}}function Ya(a,b){var c=F(a.mode)?(c=ub(a,"x"))?c:a.bg.ah?0:2:54;if(c)throw new B(c);for(c=nb[tb(a.id,b)];c;c=c.Sg){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.bg.ah(a,b)}function Xa(a,b,c,d){a=new rb(a,b,c,d);b=tb(a.parent.id,a.name);a.Sg=nb[b];return nb[b]=a}function F(a){return(a&61440)===16384}
function ub(a,b){return pb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function vb(a,b){if(!F(a.mode))return 54;try{return Ya(a,b),20}catch(c){}return ub(a,"wx")}function wb(a,b,c){try{var d=Ya(a,b)}catch(e){return e.ig}if(a=ub(a,"wx"))return a;if(c){if(!F(d.mode))return 54;if(d===d.parent||sb(d)==="/")return 10}else if(F(d.mode))return 31;return 0}function xb(a,b){if(!a)throw new B(b);return a}
function K(a){a=lb[a];if(!a)throw new B(8);return a}function yb(a,b=-1){a=Object.assign(new qb,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!lb[b])break a;throw new B(33);}a.fd=b;return lb[b]=a}function zb(a,b=-1){a=yb(a,b);a.cg?.gj?.(a);return a}function Ab(a,b){var c=void 0,d=c?null:a;c??=a.bg.Gg;xb(c,63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new B(22);throw e;}}var Wa={open(a){a.cg=kb[a.node.dh].cg;a.cg.open?.(a)},Bg(){throw new B(70);}};function Sa(a,b){kb[a]={cg:b}}
function Bb(a,b){var c=b==="/";if(c&&jb)throw new B(10);if(!c&&b){var d=H(b,{Dh:!1});b=d.path;d=d.node;if(d.Rg)throw new B(10);if(!F(d.mode))throw new B(54);}b={type:a,oj:{},bi:b,Li:[]};a=a.Eg(b);a.Eg=b;b.root=a;c?jb=a:d&&(d.Rg=b,d.Eg&&d.Eg.Li.push(b))}function Cb(a,b,c){var d=H(a,{parent:!0}).node;a=Ga(a);if(!a)throw new B(28);if(a==="."||a==="..")throw new B(20);var e=vb(d,a);if(e)throw new B(e);if(!d.bg.nh)throw new B(63);return d.bg.nh(d,a,b,c)}
function Db(a,b=438){return Cb(a,b&4095|32768,0)}function L(a,b=511){return Cb(a,b&1023|16384,0)}function Eb(a,b,c){typeof c=="undefined"&&(c=b,b=438);return Cb(a,b|8192,c)}function Fb(a,b){if(!Ja(a))throw new B(44);var c=H(b,{parent:!0}).node;if(!c)throw new B(44);b=Ga(b);var d=vb(c,b);if(d)throw new B(d);if(!c.bg.rh)throw new B(63);c.bg.rh(c,b,a)}
function Gb(a){var b=H(a,{parent:!0}).node;a=Ga(a);var c=Ya(b,a),d=wb(b,a,!0);if(d)throw new B(d);if(!b.bg.qh)throw new B(63);if(c.Rg)throw new B(10);b.bg.qh(b,a);Za(c)}function Hb(a){var b=H(a,{parent:!0}).node;if(!b)throw new B(44);a=Ga(a);var c=Ya(b,a),d=wb(b,a,!1);if(d)throw new B(d);if(!b.bg.sh)throw new B(63);if(c.Rg)throw new B(10);b.bg.sh(b,a);Za(c)}function Ib(a,b){a=H(a,{Qg:!b}).node;return xb(a.bg.ug,63)(a)}
function Jb(a,b){a=typeof a=="string"?H(a,{Qg:!0}).node:a;Ab(a,{mode:b&4095|a.mode&-4096,og:Date.now(),fj:void 0})}
function Kb(a,b,c=438){if(a==="")throw new B(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var f=H(a,{Qg:!(b&131072),Ni:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new B(20);}else{if(e)throw new B(31);d=Cb(a,c|511,0);f=!0}if(!d)throw new B(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&!F(d.mode))throw new B(54);
if(!f&&(d?(d.mode&61440)===40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=F(d.mode)&&(e!=="r"||b&576)?31:ub(d,e)):e=44,e))throw new B(e);if(b&512&&!f){e=d;e=typeof e=="string"?H(e,{Qg:!0}).node:e;if(F(e.mode))throw new B(31);if((e.mode&61440)!==32768)throw new B(28);if(a=ub(e,"w"))throw new B(a);Ab(e,{size:0,timestamp:Date.now()})}b=yb({node:d,path:sb(d),flags:b&-131713,seekable:!0,position:0,cg:d.cg,Ri:[],error:!1});b.cg.open&&b.cg.open(b);f&&Jb(d,c&511);return b}
function Lb(a){if(a.fd===null)throw new B(8);a.Lg&&(a.Lg=null);try{a.cg.close&&a.cg.close(a)}catch(b){throw b;}finally{lb[a.fd]=null}a.fd=null}function Mb(a,b,c){if(a.fd===null)throw new B(8);if(!a.seekable||!a.cg.Bg)throw new B(70);if(c!=0&&c!=1&&c!=2)throw new B(28);a.position=a.cg.Bg(a,b,c);a.Ri=[];return a.position}
function Nb(a,b,c,d,e,f){if(d<0||e<0)throw new B(28);if(a.fd===null)throw new B(8);if((a.flags&2097155)===0)throw new B(8);if(F(a.node.mode))throw new B(31);if(!a.cg.write)throw new B(28);a.seekable&&a.flags&1024&&Mb(a,0,2);var g=typeof e!="undefined";if(!g)e=a.position;else if(!a.seekable)throw new B(70);b=a.cg.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Ob(){var a,b,c;ob=!0;a??=h.stdin;b??=h.stdout;c??=h.stderr;a?Pb("/dev","stdin",a):Fb("/dev/tty","/dev/stdin");b?Pb("/dev","stdout",null,b):Fb("/dev/tty","/dev/stdout");c?Pb("/dev","stderr",null,c):Fb("/dev/tty1","/dev/stderr");Kb("/dev/stdin",0);Kb("/dev/stdout",1);Kb("/dev/stderr",1)}function Qb(a,b){a=typeof a=="string"?a:sb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ea(a+"/"+c);try{L(d)}catch(e){if(e.ig!=20)throw e;}a=d}}return d}
function Rb(a,b,c,d){a=Ea((typeof a=="string"?a:sb(a))+"/"+b);return Db(a,$a(c,d))}function Sb(a,b,c,d,e,f){var g=b;a&&(a=typeof a=="string"?a:sb(a),g=b?Ea(a+"/"+b):a);a=$a(d,e);g=Db(g,a);c&&(typeof c=="string"&&(c=Pa(c)),c.subarray||(c=new Uint8Array(c)),Jb(g,a|146),b=Kb(g,577),Nb(b,c,0,c.length,0,f),Lb(b),Jb(g,a))}
function Pb(a,b,c,d){a=Ea((typeof a=="string"?a:sb(a))+"/"+b);b=$a(!!c,!!d);Pb.ai??(Pb.ai=64);var e=Pb.ai++<<8|0;Sa(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,m,k){for(var p=0,q=0;q<k;q++){try{var v=c()}catch(C){throw new B(29);}if(v===void 0&&p===0)throw new B(6);if(v===null||v===void 0)break;p++;g[m+q]=v}p&&(f.node.Hg=Date.now());return p},write(f,g,m,k){for(var p=0;p<k;p++)try{d(g[m+p])}catch(q){throw new B(29);}k&&(f.node.rg=f.node.og=Date.now());return p}});return Eb(a,
b,e)}function Tb(a){if(!(a.Ii||a.Ji||a.link||a.fg))if(globalThis.XMLHttpRequest)z("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.fg=(void 0)(a.url)}catch(b){throw new B(29);}}
function Ub(a,b,c,d,e){class f{Dg=!1;kg=[];lg=void 0;Xg=0;Pg=0;get(p){if(!(p>this.length-1||p<0)){var q=p%this.$g;return this.lg(p/this.$g|0)[q]}}Ai(p){this.lg=p}Zg(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);p.status>=200&&p.status<300||p.status===304||z("Couldn't load "+c+". Status: "+p.status);var q=Number(p.getResponseHeader("Content-length")),v,C=(v=p.getResponseHeader("Accept-Ranges"))&&v==="bytes";p=(v=p.getResponseHeader("Content-Encoding"))&&v==="gzip";var D=1048576;C||(D=
q);var G=this;G.Ai(J=>{var I=J*D,S=(J+1)*D-1;S=Math.min(S,q-1);if(typeof G.kg[J]=="undefined"){var oa=G.kg;I>S&&z(`invalid range (${I}, ${S}) or no bytes requested!`);S>q-1&&z(`only ${q} bytes available! programmer error!`);var O=new XMLHttpRequest;O.open("GET",c,!1);q!==D&&O.setRequestHeader("Range","bytes="+I+"-"+S);O.responseType="arraybuffer";O.overrideMimeType&&O.overrideMimeType("text/plain; charset=x-user-defined");O.send(null);O.status>=200&&O.status<300||O.status===304||z("Couldn't load "+
c+". Status: "+O.status);I=O.response!==void 0?new Uint8Array(O.response||[]):Pa(O.responseText??"");oa[J]=I}typeof G.kg[J]=="undefined"&&z("doXHR failed!");return G.kg[J]});if(p||!q)D=q=1,D=q=this.lg(0).length,fa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Xg=q;this.Pg=D;this.Dg=!0}get length(){this.Dg||this.Zg();return this.Xg}get $g(){this.Dg||this.Zg();return this.Pg}}if(globalThis.XMLHttpRequest){z("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var g=new f;var m=void 0}else m=c,g=void 0;var k=Rb(a,b,d,e);g?k.fg=g:m&&(k.fg=null,k.url=m);Object.defineProperties(k,{ng:{get:function(){return this.fg.length}}});a={};for(let [p,q]of Object.entries(k.cg))a[p]=(...v)=>{Tb(k);return q(...v)};a.read=(p,q,v,C,D)=>{Tb(k);p=p.node.fg;if(D>=p.length)q=0;else{C=Math.min(p.length-D,C);if(p.slice)for(var G=0;G<C;G++)q[v+G]=p[D+G];else for(G=0;G<C;G++)q[v+G]=p.get(D+G);q=C}return q};a.Jh=()=>{Tb(k);z();throw new B(48);};k.cg=a;return k}
var M={},N=(a,b)=>a?Ka.decode(r.subarray(a,La(r,a,b))):"";function Vb(a,b,c){if(b.charAt(0)==="/")return b;a=a===-100?"/":K(a).path;if(b.length==0){if(!c)throw new B(44);return a}return a+"/"+b}
function Wb(a,b){u[a>>2]=b.si;u[a+4>>2]=b.mode;u[a+8>>2]=b.Mi;u[a+12>>2]=b.uid;u[a+16>>2]=b.zi;u[a+20>>2]=b.dh;y[a+24>>3]=BigInt(b.size);t[a+32>>2]=4096;t[a+36>>2]=b.li;var c=b.Hg.getTime(),d=b.rg.getTime(),e=b.og.getTime();y[a+40>>3]=BigInt(Math.floor(c/1E3));u[a+48>>2]=c%1E3*1E3*1E3;y[a+56>>3]=BigInt(Math.floor(d/1E3));u[a+64>>2]=d%1E3*1E3*1E3;y[a+72>>3]=BigInt(Math.floor(e/1E3));u[a+80>>2]=e%1E3*1E3*1E3;y[a+88>>3]=BigInt(b.Di);return 0}
var Xb=void 0,Yb=()=>{var a=t[+Xb>>2];Xb+=4;return a},Zb=0,$b=[0,31,60,91,121,152,182,213,244,274,305,335],ac=[0,31,59,90,120,151,181,212,243,273,304,334],bc={},cc=a=>{if(!(a instanceof ta||a=="unwind"))throw a;},dc=a=>{ja=a;za||Zb>0||(h.onExit?.(a),ia=!0);throw new ta(a);},ec=()=>{if(!(za||Zb>0))try{var a=ja;ja=a;dc(a)}catch(b){cc(b)}},fc=a=>{if(!ia)try{a()}catch(b){cc(b)}finally{ec()}},hc=[],ic=(a,b)=>{hc.length=0;for(var c;c=r[a++];){var d=c!=105;d&=c!=112;b+=d&&b%8?4:0;hc.push(c==112?u[b>>2]:
c==106?y[b>>3]:c==105?t[b>>2]:x[b>>3]);b+=d?8:4}return hc},kc=(a,b,c)=>{b=ic(b,c);return jc[a](...b)},uc=(a,b)=>{lc=a;mc=b;if(!nc)return 1;oc||=!0;if(a==0)pc=function(){setTimeout(qc,Math.max(0,rc+b-performance.now())|0)};else if(a==1)pc=function(){sc(qc)};else{if(!tc)if(globalThis.scheduler)tc=scheduler.postTask.bind(scheduler);else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);tc=d=>{c.push(d);postMessage("setimmediate","*")}}pc=function(){tc(qc)}}return 0},
Dc=(a,b,c,d,e)=>{function f(){return g<vc?(ec(),!1):!0}nc=a;wc=d;var g=vc;oc=!1;qc=function(){if(!ia)if(xc.length>0){var m=xc.shift();m.jj(m.Ui);if(yc){var k=yc,p=k%1==0?k-1:Math.floor(k);yc=m.bj?p:(8*k+(p+.5))/9}h.setStatus&&(m=h.statusMessage||"Please wait...",k=yc??0,p=zc.hj??0,k?k<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(m):h.setStatus(""));f()&&setTimeout(qc,0)}else if(f())if(Ac=Ac+1|0,lc==1&&mc>1&&Ac%mc!=0)pc();else{lc==0&&(rc=performance.now());a:if(!ia){for(m of Bc)if(m()===
!1)break a;fc(a);for(k of Cc)k()}f()&&pc()}};e||(b>0?uc(0,1E3/b):uc(1,1),pc());if(c)throw"unwind";},oc=!1,pc=null,vc=0,nc=null,wc=0,lc=0,mc=0,Ac=0,xc=[],Bc=[],Cc=[];function Ec(){pc=null;vc++}var Fc=0;function sc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(Fc===0)Fc=b+1E3/60;else for(;b+2>=Fc;)Fc+=1E3/60;setTimeout(a,Math.max(Fc-b,0))}}var zc={},rc,qc,tc,yc;function Gc(a){var b=P.pg[a];b.target.removeEventListener(b.mg,b.Zh,b.xg);P.pg.splice(a,1)}
function Hc(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of P.Ig)if(e.Oh==a&&d(e.Vh,c))return;P.Ig.push({Oh:a,di:b,Vh:c});P.Ig.sort((f,g)=>f.di-g.di)}function Ic(a){P.Ig=P.Ig.filter(b=>b.Oh!=a)}function Jc(){return navigator.userActivation?navigator.userActivation.isActive:P.Gh&&P.ni.Uh}function Kc(){if(Jc()){var a=P.Ig;P.Ig=[];for(var b of a)b.Oh(...b.Vh)}}
function Lc(a){if(!a.target)return-4;if(a.qg)a.Zh=function(c){++P.Gh;P.ni=a;Kc();a.Ag(c);Kc();--P.Gh},a.target.addEventListener(a.mg,a.Zh,a.xg),P.pg.push(a);else for(var b=0;b<P.pg.length;++b)P.pg[b].target==a.target&&P.pg[b].mg==a.mg&&Gc(b--);return 0}function Mc(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var P={Vi:0,Fh:0,Hh:0,mj:0,Th:0,Qh:0,Ch:0,dj:0,Kh:0,cj:0,Eh:0,Lh:0,Sh:0,uj:0,qj(){for(;P.pg.length;)Gc(P.pg.length-1);P.Ig=[]},Gh:0,Ig:[],pg:[],Pi:(a,b)=>{for(var c=0;c<P.pg.length;++c)P.pg[c].target!=a||b&&b!=P.pg[c].mg||Gc(c--)},rj(a){var b=!1;for(let c=0;c<P.pg.length;++c){let d=P.pg[c];d.target===a.target&&d.tg===a.tg&&d.qg===a.qg&&d.yg===a.yg&&(Gc(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Nc=[0,document,window],Q=a=>{a=
a>2?N(a):a;return Nc[a]||document.querySelector(a)},Pc=a=>{var b=Oa(a)+1,c=Oc(b);A(a,r,c,b);return c},Sc=a=>{var b=Qc(),c=Oc(8),d=c+4;a=Pc(a.id);if(a=Q(a))t[c>>2]=a.width,t[d>>2]=a.height;c=[t[c>>2],t[d>>2]];Rc(b);return c},Tc=(a,b,c)=>{a=Q(a);if(!a)return-4;a.width=b;a.height=c;return 0},Uc=(a,b,c)=>{if(a.aj){var d=Qc();a=Pc(a.id);Tc(a,b,c);Rc(d)}else a.width=b,a.height=c},Vc={},Xc=a=>{function b(){Wc()||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),Uc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,k||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=k,a.style.paddingLeft=p,a.style.paddingRight=q,a.style.paddingTop=v,a.style.paddingBottom=C,a.style.marginLeft=D,a.style.marginRight=G,a.style.marginTop=J,a.style.marginBottom=I,document.body.style.margin=S,document.documentElement.style.overflow=oa,document.body.scroll=O,a.style.imageRendering=ve,a.Tg&&a.Tg.Kg.viewport(0,0,d,e),Vc.fh&&R.get(Vc.fh)(37,
0,Vc.Wh))}var c=Sc(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,k=document.body.style.backgroundColor,p=a.style.paddingLeft,q=a.style.paddingRight,v=a.style.paddingTop,C=a.style.paddingBottom,D=a.style.marginLeft,G=a.style.marginRight,J=a.style.marginTop,I=a.style.marginBottom,S=document.body.style.margin,oa=document.documentElement.style.overflow,O=document.body.scroll,ve=a.style.imageRendering;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},Yc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Zc=a=>Nc.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},$c=(a,b)=>{if(b.Nh!=0||b.uh!=0){Xc(a);var c=b.Qi?innerWidth:screen.width,d=b.Qi?innerHeight:screen.height,e=Zc(a),f=e.width;e=e.height;var g=Sc(a),m=g[0];g=g[1];b.Nh==3?(Yc(a,(d-e)/2,(c-f)/2),c=f,d=e):b.Nh==2&&(c*g<m*d?(f=g*c/m,Yc(a,(d-f)/2,0),d=f):(f=m*d/g,Yc(a,0,(c-f)/2),c=f));var k;(k=a.style).backgroundColor||(k.backgroundColor=
"black");let p;(p=document.body.style).backgroundColor||(p.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";b.yi==1&&(a.style.imageRendering="optimizeSpeed",a.style.imageRendering="-moz-crisp-edges",a.style.imageRendering="-o-crisp-edges",a.style.imageRendering="-webkit-optimize-contrast",a.style.imageRendering="optimize-contrast",a.style.imageRendering="crisp-edges",a.style.imageRendering="pixelated");k=b.uh==2?devicePixelRatio:1;b.uh!=0&&(c=c*k|0,d=d*k|0,Uc(a,c,d),a.Tg&&a.Tg.Kg.viewport(0,
0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return P.fullscreenEnabled()?-3:-1;Vc=b;b.fh&&R.get(b.fh)(37,0,b.Wh);return 0},ad=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0};
function Wc(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}
var bd=a=>{var b=Wc(),c=!!b;n[a]=c;n[a+1]=P.fullscreenEnabled();var d=c?b:P.Oi,e=d?.id??"";A(Mc(d),r,a+2,128);A(e,r,a+130,128);t[a+260>>2]=d?.clientWidth??0;t[a+264>>2]=d?.clientHeight??0;t[a+268>>2]=screen.width;t[a+272>>2]=screen.height;c&&(P.Oi=b)},cd=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+c*8+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+c*8+528>>3]=typeof b.buttons[c]=="object"?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)n[a+c+1040]=typeof b.buttons[c]==
"object"?b.buttons[c].pressed:b.buttons[c]==1;n[a+1104]=b.connected;t[a+1108>>2]=b.index;t[a+8>>2]=b.axes.length;t[a+12>>2]=b.buttons.length;A(b.id,r,a+1112,64);A(b.mapping,r,a+1176,64)},dd=a=>{setTimeout(()=>{fc(a)},1E4)},ed=!1,fd=[];
function hb(){function a(){ed=document.pointerLockElement===h.canvas}if(!gd){gd=!0;fb.push({canHandle:c=>!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:hd(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:hd(d)}));var f=URL.createObjectURL(e);return new Promise((g,m)=>{var k=new Image;k.onload=()=>{var p=document.createElement("canvas");p.width=k.width;p.height=k.height;p.getContext("2d").drawImage(k,0,0);URL.revokeObjectURL(f);
g(c)};k.onerror=()=>{l(`Image ${f} could not be decoded`);m()};k.src=f})}});fb.push({canHandle:c=>!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,m=URL.createObjectURL(new Blob([c],{type:hd(d)})),k=new Audio;k.addEventListener("canplaythrough",()=>f(k),!1);k.onerror=()=>{if(!g){l(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var p="",q=0,v=0,C=0;C<c.length;C++)for(q=q<<
8|c[C],v+=8;v>=6;){var D=q>>v-6&63;v-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[D]}v==2?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(q&3)<<4],p+="=="):v==4&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(q&15)<<2],p+="=");k.src="data:audio/x-"+d.slice(-3)+";base64,"+p;f(k)}};k.src=m;dd(()=>{f(k)})})});var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!ed&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function jd(a){a=a.getContext("2d");if(!a)return null;h.ctx=a;fd.forEach(b=>b());hb();return a}function hd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var gb={},gd,T,kd=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");return a.getSupportedExtensions()?.filter(c=>
b.includes(c))??[]},ld=1,md=[],U=[],nd=[],od=[],pd=[],V=[],qd=[],rd=[],W=[],X=[],sd=[],td=[],ud={},vd={},wd=4,xd=0,yd=a=>{for(var b=ld++,c=a.length;c<b;c++)a[c]=null;return b},zd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=T[c](),g=f&&yd(d);f?(f.name=g,d[g]=f):Y||=1282;t[b+e*4>>2]=g}},Bd=(a,b)=>{a.$g||(a.$g=a.getContext,a.getContext=function(d,e){e=a.$g(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Ad(c,b):0},Ad=(a,b)=>{var c=yd(rd),d={handle:c,
attributes:b,version:b.Ki,Kg:a};a.canvas&&(a.canvas.Tg=d);rd[c]=d;if(typeof b.Yh=="undefined"||b.Yh)if((a=d)||(a=Cd),!a.Ci){a.Ci=!0;b=a.Kg;b.nj=b.getExtension("WEBGL_multi_draw");b.xi=b.getExtension("EXT_polygon_offset_clamp");b.wi=b.getExtension("EXT_clip_control");b.Si=b.getExtension("WEBGL_polygon_mode");b.ej=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.kj=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");a.version>=2&&(b.sg=b.getExtension("EXT_disjoint_timer_query_webgl2"));
if(a.version<2||!b.sg)b.sg=b.getExtension("EXT_disjoint_timer_query");for(var e of kd(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},Y,Cd,Dd=a=>{T.bindVertexArray(qd[a])},Ed=(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2];T.deleteVertexArray(qd[d]);qd[d]=null}},Fd=(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},Gd=[],Hd=(a,b)=>{for(var c=Gd[a],d=0;d<a;d++)c[d]=t[b+d*4>>2];T.drawBuffers(c)},Id=(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},Jd=(a,b)=>{zd(a,b,"createVertexArray",
qd)},Kd=(a,b,c,d,e,f,g,m)=>{b=U[b];if(a=T[a](b,c))d=m&&A(a.name,r,m,d),e&&(t[e>>2]=d),f&&(t[f>>2]=a.size),g&&(t[g>>2]=a.type)},Ld=(a,b)=>{u[a>>2]=b;u[a+4>>2]=(b-u[a>>2])/4294967296},Md=()=>{var a=kd(T);return a=a.concat(a.map(b=>"GL_"+b))},Nd=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:c!=0&&c!=1&&(Y||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=T.getParameter(34467);d=e?e.length:0;break;case 33309:if(Cd.version<2){Y||=1282;return}d=Md().length;break;case 33307:case 33308:if(Cd.version<
2){Y||=1280;return}d=a==33307?3:0}if(d===void 0)switch(e=T.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Y||=1280;return;case "object":if(e===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:Y||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||
e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+a*4>>2]=e[a];break;case 2:w[b+a*4>>2]=e[a];break;case 4:n[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){Y||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:Y||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:Ld(b,d);break;case 0:t[b>>
2]=d;break;case 2:w[b>>2]=d;break;case 4:n[b]=d?1:0}}else Y||=1281},Od=(a,b,c,d)=>{if(c){b=T.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(b===null)switch(a){case 35983:case 35368:a=0;break;default:Y||=1280;return}else if(b instanceof WebGLBuffer)a=b.name|0;else{Y||=1280;return}break;default:Y||=1280;return}switch(d){case 1:Ld(c,a);break;case 0:t[c>>2]=a;break;case 2:w[c>>2]=a;break;case 4:n[c]=a?1:0;break;default:z("internal emscriptenWebGLGetIndexed() error, bad type: "+
d)}}else Y||=1281},Pd=(a,b,c)=>{if(c){a=W[a];b=Cd.version<2?T.sg.getQueryObjectEXT(a,b):T.getQueryParameter(a,b);var d;typeof b=="boolean"?d=b?1:0:d=b;Ld(c,d)}else Y||=1281},Qd=(a,b,c)=>{if(c){a=T.sg.getQueryObjectEXT(W[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;t[c>>2]=d}else Y||=1281},Sd=a=>{var b=Oa(a)+1,c=Rd(b);c&&A(a,r,c,b);return c},Td=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),Ud=a=>{var b=a.eh,c=a.gi,d;if(!b){a.eh=b={};a.fi={};var e=T.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=T.getActiveUniform(a,
d);var g=f.name;f=f.size;var m=Td(g);m=m>0?g.slice(0,m):g;var k=a.Rh;a.Rh+=f;c[m]=[f,k];for(g=0;g<f;++g)b[k]=g,a.fi[k++]=m}}},Z=(a,b)=>{if(a){var c=a.eh[b];typeof c=="number"&&(a.eh[b]=c=T.getUniformLocation(a,a.fi[b]+(c>0?`[${c}]`:"")));return c}Y||=1282},Vd=(a,b,c,d)=>{if(c)if(a=U[a],Ud(a),a=T.getUniform(a,Z(a,b)),typeof a=="number"||typeof a=="boolean")switch(d){case 0:t[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+b*4>>2]=a[b];break;case 2:w[c+b*4>>2]=a[b]}else Y||=
1281},Wd=(a,b,c,d)=>{if(c)if(a=T.getVertexAttrib(a,b),b==34975)t[c>>2]=a&&a.name;else if(typeof a=="number"||typeof a=="boolean")switch(d){case 0:t[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:t[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+b*4>>2]=a[b];break;case 2:w[c+b*4>>2]=a[b];break;case 5:t[c+b*4>>2]=Math.fround(a[b])}else Y||=1281},Xd=(a,b,c)=>{Wd(a,b,c,0)},Yd=a=>(a=qd[a])?T.isVertexArray(a):0,Zd=a=>{a-=5120;return a==0?n:a==1?r:a==2?ma:a==4?t:a==6?w:a==5||a==28922||
a==28520||a==30779||a==30782?u:na},$d=(a,b,c,d,e)=>{a=Zd(a);b=d*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT*(xd||c)+wd-1&-wd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},ae=(a,b)=>{T.vertexAttribDivisor(a,b)},be=(a,b)=>{if(!P.fullscreenEnabled())return-1;a=Q(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Jc()?$c(a,b):b.ri?(Hc($c,1,[a,b]),1):-2:-3:-4},ce=()=>{try{if(navigator.getGamepads)return(P.ih=
navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},de=(a,b)=>{var c={target:Q(2),mg:"beforeunload",tg:28,yg:a,qg:b,Ag:d=>{var e=R.get(b)(28,0,a);e&&=N(e);if(e)return d.preventDefault(),d.returnValue=e},xg:!0};return Lc(c)},ee=(a,b,c,d,e,f)=>{P.Ch||(P.Ch=Rd(256));a={target:Q(a),mg:f,tg:e,yg:b,qg:d,Ag:g=>{var m=g.target.id??"",k=P.Ch;A(Mc(g.target),r,k+0,128);A(m,r,k+128,128);R.get(d)(e,k,b)&&g.preventDefault()},xg:c};return Lc(a)},fe=(a,b,c,d,e)=>{P.Eh||(P.Eh=Rd(276));return Lc({target:a,
mg:e,tg:19,yg:b,qg:d,Ag:f=>{var g=P.Eh;bd(g);R.get(d)(19,g,b)&&f.preventDefault()},xg:c})},ge=(a,b,c,d,e)=>{P.Fh||(P.Fh=Rd(1240));b={target:Q(2),Uh:!0,mg:e,tg:d,yg:a,qg:c,Ag:f=>{var g=P.Fh;cd(g,f.gamepad);R.get(c)(d,g,a)&&f.preventDefault()},xg:b};return Lc(b)},he=(a,b,c,d,e,f)=>{P.Hh||(P.Hh=Rd(160));a={target:Q(a),mg:f,tg:e,yg:b,qg:d,Ag:g=>{var m=P.Hh;x[m>>3]=g.timeStamp;var k=m>>2;t[k+2]=g.location;n[m+12]=g.ctrlKey;n[m+13]=g.shiftKey;n[m+14]=g.altKey;n[m+15]=g.metaKey;n[m+16]=g.repeat;t[k+5]=g.charCode;
t[k+6]=g.keyCode;t[k+7]=g.which;A(g.key??"",r,m+32,32);A(g.code??"",r,m+64,32);A(g.char??"",r,m+96,32);A(g.locale??"",r,m+128,32);R.get(d)(e,m,b)&&g.preventDefault()},xg:c};return Lc(a)},ie=(a,b,c)=>{var d=screen.orientation;P.Kh||(P.Kh=Rd(8));return Lc({target:d,mg:"change",tg:18,yg:a,qg:c,Ag:e=>{var f=P.Kh,g=["portrait-primary","portrait-secondary","landscape-primary","landscape-secondary"],m=["portrait","portrait","landscape","landscape"],k=0;var p=window.screen?screen.orientation||screen.mozOrientation||
screen.webkitOrientation:void 0;typeof p==="object"?(k=g.indexOf(p.type),k<0&&(k=m.indexOf(p.type)),k>=0&&(k=1<<k),g=p.angle):g=window.orientation;t[f>>2]=k;t[f+4>>2]=g;R.get(c)(18,f,a)&&e.preventDefault()},xg:b})},je=(a,b,c,d)=>{P.Lh||(P.Lh=Rd(257));return Lc({target:a,mg:"pointerlockchange",tg:20,yg:b,qg:d,Ag:e=>{var f=P.Lh,g=document.pointerLockElement;n[f]=!!g;var m=g?.id??"";A(Mc(g),r,f+1,128);A(m,r,f+129,128);R.get(d)(20,f,b)&&e.preventDefault()},xg:c})},ke=(a,b,c,d)=>{P.Qh||(P.Qh=Rd(36));a=
Q(a);return Lc({target:a,mg:"resize",tg:10,yg:b,qg:d,Ag:e=>{if(e.target==a){var f=document.body;if(f){var g=P.Qh;t[g>>2]=0;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+12>>2]=innerWidth;t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset|0;t[g+32>>2]=pageYOffset|0;R.get(d)(10,g,b)&&e.preventDefault()}}},xg:c})},le=(a,b,c)=>{var d=Nc[1];P.Sh||(P.Sh=Rd(8));return Lc({target:d,mg:"visibilitychange",tg:21,yg:a,qg:c,Ag:e=>{var f=P.Sh,g=["hidden","visible",
"prerender","unloaded"].indexOf(document.visibilityState);n[f]=document.hidden;t[f+4>>2]=g;R.get(c)(21,f,a)&&e.preventDefault()},xg:b})},me=(a,b,c,d)=>{P.Th||(P.Th=Rd(96));return Lc({target:a,Uh:!0,mg:"wheel",tg:9,yg:b,qg:d,Ag:e=>{var f=P.Th;x[f>>3]=e.timeStamp;var g=f>>2;t[g+2]=e.screenX;t[g+3]=e.screenY;t[g+4]=e.clientX;t[g+5]=e.clientY;n[f+24]=e.ctrlKey;n[f+25]=e.shiftKey;n[f+26]=e.altKey;n[f+27]=e.metaKey;ma[g*2+14]=e.button;ma[g*2+15]=e.buttons;t[g+8]=e.movementX;t[g+9]=e.movementY;var m=Zc(a);
t[g+10]=e.clientX-(m.left|0);t[g+11]=e.clientY-(m.top|0);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+80>>3]=e.deltaZ;t[f+88>>2]=e.deltaMode;R.get(d)(9,f,b)&&e.preventDefault()},xg:c})},ne=["default","low-power","high-performance"],oe={},qe=()=>{if(!pe){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ba},b;for(b in oe)oe[b]===void 0?delete a[b]:a[b]=oe[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);
pe=c}return pe},pe,re=(a,b=[])=>{R.get(a)(...b)},se=a=>{for(var b of["keydown","mousedown","touchstart"])for(var c of[document,document.getElementById("canvas")])c?.addEventListener(b,()=>{a.state==="suspended"&&a.resume()},{once:!0})};nb=Array(4096);Bb(E,"/");L("/tmp");L("/home");L("/home/web_user");
(function(){L("/dev");Sa(259,{read:()=>0,write:(d,e,f,g)=>g,Bg:()=>0});Eb("/dev/null",259);Ra(1280,Ua);Ra(1536,Va);Eb("/dev/tty",1280);Eb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b===0&&(Ia(a),b=a.byteLength);return a[--b]};Pb("/dev","random",c);Pb("/dev","urandom",c);L("/dev/shm");L("/dev/shm/tmp")})();
(function(){L("/proc");var a=L("/proc/self");L("/proc/self/fd");Bb({Eg(){var b=Xa(a,"fd",16895,73);b.cg={Bg:E.cg.Bg};b.bg={ah(c,d){c=+d;var e=K(c);c={parent:null,Eg:{bi:"fake"},bg:{Mg:()=>e.path},id:c+1};return c.parent=c},ph(){return Array.from(lb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.requestAnimationFrame=sc;h.pauseMainLoop=Ec;h.resumeMainLoop=function(){vc++;var a=lc,b=mc,c=nc;nc=null;Dc(c,0,!1,wc,!0);uc(a,b);pc()};h.preMainLoop&&Bc.push(h.preMainLoop);
h.postMainLoop&&Cc.push(h.postMainLoop);for(let a=0;a<32;++a)Gd.push(Array(a));h.noExitRuntime&&(za=h.noExitRuntime);h.preloadPlugins&&(fb=h.preloadPlugins);h.print&&(fa=h.print);h.printErr&&(l=h.printErr);h.wasmBinary&&(ha=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);if(h.preInit)for(typeof h.preInit=="function"&&(h.preInit=[h.preInit]);h.preInit.length>0;)h.preInit.shift()();h.addRunDependency=eb;h.removeRunDependency=db;
h.FS_preloadFile=async(a,b,c,d,e,f,g,m)=>{var k=b?Ja(Ea(a+"/"+b)):a,p=`cp ${k}`;eb(p);try{var q=c;typeof c=="string"&&(q=await ab(c));q=await ib(q,k);m?.();f||Sb(a,b,q,d,e,g)}finally{db(p)}};h.FS_unlink=(...a)=>Hb(...a);h.FS_createPath=(...a)=>Qb(...a);h.FS_createDevice=(...a)=>Pb(...a);h.FS_createDataFile=(...a)=>Sb(...a);h.FS_createLazyFile=(...a)=>Ub(...a);
var jc={291872:()=>{typeof h.SDL3==="undefined"&&(h.SDL3={});var a=h.SDL3;typeof a.Og==="undefined"&&(a.Og=function(b){return b});typeof a.th==="undefined"&&(a.th=function(b){return b>>>2})},292186:a=>{a=N(a)+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");a===null&&(a="i");return a.length===1?a.charCodeAt(0):-1},292401:()=>{h.SDL3.Vg={};h.SDL3.Vg.Jg=[];h.SDL3.Vg.Jg[0]=void 0;h.SDL3.Vg.Jg[1]=void 0},292578:(a,b,c,d,e)=>{var f=h.SDL3.Vg;f.Jg[a]!==void 0&&clearInterval(f.Jg[a]);
f.Jg[a]=setInterval(function(){re(d,[e])},b/c*1E3)},292770:a=>{var b=h.SDL3.Vg;b.Jg[a]!==void 0&&clearInterval(b.Jg[a]);b.Jg[a]=void 0},292901:a=>{var b=new URLSearchParams(window.location.search);for(let [d,e]of b)if(d.startsWith("SDL_")){b=Sd(d);var c=Sd(e);b!=0&&c!=0&&re(a,[b,c,1]);te(b);te(c)}},293242:()=>typeof AudioContext!=="undefined"||typeof webkitAudioContext!=="undefined"?!0:!1,293389:()=>typeof navigator.mediaDevices!=="undefined"&&typeof navigator.mediaDevices.getUserMedia!=="undefined"||
typeof navigator.webkitGetUserMedia!=="undefined"?!0:!1,293623:()=>{var a=h.SDL3;typeof a.gg==="undefined"&&(a.gg={});typeof a.dg==="undefined"&&(a.dg={});a.jg||(typeof AudioContext!=="undefined"?a.jg=new AudioContext:typeof webkitAudioContext!=="undefined"&&(a.jg=new webkitAudioContext),a.jg&&typeof navigator.userActivation==="undefined"&&se(a.jg));return a.jg!==void 0},294202:()=>h.SDL3.jg.sampleRate,294253:(a,b,c,d)=>{function e(){}function f(m){g.dg.wg!==void 0&&(clearInterval(g.dg.wg),g.dg.wg=
void 0,g.dg.Ng=void 0);g.dg.Ih=g.jg.createMediaStreamSource(m);g.dg.vg=g.jg.createScriptProcessor(b,a,1);g.dg.vg.onaudioprocess=function(k){g!==void 0&&g.dg!==void 0&&(k.outputBuffer.getChannelData(0).fill(0),g.dg.xh=k.inputBuffer,re(c,[d]))};g.dg.Ih.connect(g.dg.vg);g.dg.vg.connect(g.jg.destination);g.dg.stream=m}var g=h.SDL3;g.dg.Ng=g.jg.createBuffer(a,b,g.jg.sampleRate);g.dg.Ng.getChannelData(0).fill(0);g.dg.wg=setInterval(function(){g.dg.xh=g.dg.Ng;re(c,[d])},b/g.jg.sampleRate*1E3);navigator.mediaDevices!==
void 0&&navigator.mediaDevices.getUserMedia!==void 0?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):navigator.webkitGetUserMedia!==void 0&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},296094:(a,b,c,d)=>{var e=h.SDL3;e.gg.vg=e.jg.createScriptProcessor(b,0,a);e.gg.vg.onaudioprocess=function(f){e!==void 0&&e.gg!==void 0&&(e.gg.wg!==void 0&&(clearInterval(e.gg.wg),e.gg.wg=void 0,e.gg.Ng=void 0),e.gg.gh=f.outputBuffer,re(c,[d]))};e.gg.vg.connect(e.jg.destination);e.jg.state===
"suspended"&&(e.gg.Ng=e.jg.createBuffer(a,b,e.jg.sampleRate),e.gg.Ng.getChannelData(0).fill(0),e.gg.wg=setInterval(function(){typeof navigator.userActivation!=="undefined"&&navigator.userActivation.hasBeenActive&&e.jg.resume();e.gg.gh=e.gg.Ng;re(c,[d]);e.gg.gh=void 0},b/e.jg.sampleRate*1E3))},297410:a=>{var b=h.SDL3;if(a){b.dg.wg!==void 0&&clearInterval(b.dg.wg);if(b.dg.stream!==void 0){a=b.dg.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.dg.stream.removeTrack(a[c])}b.dg.vg!==void 0&&(b.dg.vg.onaudioprocess=
function(){},b.dg.vg.disconnect());b.dg.Ih!==void 0&&b.dg.Ih.disconnect();b.dg=void 0}else b.gg.vg!=void 0&&b.gg.vg.disconnect(),b.gg.wg!==void 0&&clearInterval(b.gg.wg),b.gg=void 0;b.jg!==void 0&&b.gg===void 0&&b.dg===void 0&&(b.jg.close(),b.jg=void 0)},298566:(a,b)=>{var c=h.SDL3;a=c.th(a);for(var d=c.gg.gh.numberOfChannels,e=0;e<d;++e){var f=c.gg.gh.getChannelData(e);if(f.length!=b)throw"Web Audio playback buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";
for(var g=0;g<b;++g)f[g]=w[a+(g*d+e)]}},299099:(a,b)=>{for(var c=h.SDL3,d=c.dg.xh.numberOfChannels,e=0;e<d;++e){var f=c.dg.xh.getChannelData(e);if(f.length!=b)throw"Web Audio recording buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(d==1)for(var g=0;g<b;++g)Aa(a+g*4,f[g]);else for(g=0;g<b;++g)Aa(a+(g*d+e)*4,f[g])}},299726:a=>(a=navigator.getGamepads()[a])&&a.vibrationActuator&&a.vibrationActuator.effects&&a.vibrationActuator.effects.includes("trigger-rumble")?
!0:!1,299972:a=>{a=navigator.getGamepads()[a];if(!a)return 0;if(a.id.indexOf("Vendor: ")>0){let b=a.id.indexOf("Vendor: ")+8;return parseInt(a.id.substr(b,4),16)}a=a.id.split("-");return a.length>1&&!isNaN(parseInt(a[0],16))?parseInt(a[0],16):0},300437:a=>{a=navigator.getGamepads()[a];if(!a)return 0;if(a.id.indexOf("Product: ")>0){let b=a.id.indexOf("Product: ")+9;return parseInt(a.id.substr(b,4),16)}a=a.id.split("-");return a.length>1&&!isNaN(parseInt(a[1],16))?parseInt(a[1],16):0},300909:a=>(a=
navigator.getGamepads()[a])?a.id.toLowerCase().indexOf("xinput")>=0:0,301052:()=>{var a=["Android","Linux","iPhone","Macintosh","Windows"],b=navigator.userAgent;for(let c=0;c<a.length;c++)if(b.indexOf(a[c])>=0)return c+1;return 0},301262:(a,b,c)=>{if(a=navigator.getGamepads()[a]){var d=a=a.id;a.indexOf(" (STANDARD GAMEPAD")>0?d=a.substr(0,a.indexOf(" (STANDARD GAMEPAD")):a.indexOf(" (Vendor:")>0?d=a.substr(0,a.indexOf(" (Vendor:")):a.indexOf(" (XInput")>0&&(d=a.substr(0,a.indexOf(" (XInput")));var e=
a.split("-");e.length>1&&!isNaN(parseInt(e[0],16))&&(d=a.indexOf("-",a.indexOf("-")+1)+1,d=a.substr(d));A(d.trim(),r,b,c)}else A("\x00",r,b,c)},301940:a=>(a=navigator.getGamepads()[a])&&a.vibrationActuator?!0:!1,302068:(a,b,c,d,e)=>{a=navigator.getGamepads()[a];if(!a)return!1;a.vibrationActuator.playEffect("dual-rumble",{startDelay:0,duration:3E3,weakMagnitude:b/65535,strongMagnitude:c/65535,leftTrigger:d/65535,rightTrigger:e/65535});return!0},302381:(a,b,c,d)=>{d=N(d);var e=document.querySelector(d);
d=h.SDL3;if(d.mi!==e){d.Ug=jd(e);if(!d.Ug)return!1;d.mi=e}if(d.w!==a||d.h!==b||d.Bi!==d.Ug)d.image=d.Ug.createImageData(a,b),d.w=a,d.h=b,d.Bi=d.Ug;a=d.image.data;c/=4;d.pi!==a&&(d.oi=new Int32Array(a.buffer),d.pi=a);a=d.oi;a.set(t.subarray(c,c+a.length));d.Ug.putImageData(d.image,0,0);return!0},303130:()=>{var a=h.SDL3;a.mouse_x=0;a.mouse_y=0;a.mouse_buttons=[];for(var b=0;b<5;++b)a.mouse_buttons[b]=!1;document.addEventListener("mousemove",function(c){var d=h.SDL3;d.mouse_x=c.clientX;d.mouse_y=c.clientY});
document.addEventListener("mousedown",function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!0)});document.addEventListener("mouseup",function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!1)})},303818:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);e/=4;b=new Int32Array(a.data.buffer);b.set(t.subarray(e,e+b.length));g.putImageData(a,0,
0);c=c===0&&d===0?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=ue(c.length+1);A(c,r,d,c.length+1);return d},304476:a=>{h.canvas&&(h.canvas.style.cursor=N(a))},304559:()=>{h.canvas&&(h.canvas.style.cursor="none")},304628:()=>h.SDL3.mouse_x,304666:()=>h.SDL3.mouse_y,304704:a=>h.SDL3.mouse_buttons[a],304752:a=>{document.kg&&document.removeEventListener("keydown",document.kg);document.kg=function(b){b.key!="CapsLock"&&b.key!="NumLock"&&b.key!="ScrollLock"&&we(h.SDL3.Og(a),
b.getModifierState("CapsLock"),b.getModifierState("NumLock"),b.getModifierState("ScrollLock"))};document.addEventListener("keydown",document.kg)},305306:()=>{document.removeEventListener("keydown",document.kg)},305390:a=>{var b=document;b&&(b.lg=function(c){var d=h.SDL3;c=d.bh(0,0,c);c!=0&&(xe(d.Og(a),c),ye(c))},b.addEventListener("pointerup",b.lg))},305751:a=>{var b=h.SDL3;b.bh===void 0&&(b.bh=function(c,d,e){if(e.pointerType=="mouse")var f=1;else if(e.pointerType=="touch")f=2;else if(e.pointerType==
"pen")f=3;else return 0;var g=ue(a);if(g!=0){var m=b.th(g);t[m++]=f;t[m++]=e.pointerId;t[m++]=typeof e.button!=="undefined"?e.button:-1;t[m++]=e.buttons;t[m++]=e.type=="pointerdown"?1:0;w[m++]=e.movementX;w[m++]=e.movementY;w[m++]=e.clientX-c;w[m++]=e.clientY-d;f==3&&(w[m++]=e.pressure,w[m++]=e.tangentialPressure,w[m++]=e.tiltX,w[m++]=e.tiltY,w[m++]=e.twist)}return g})},306743:a=>{a=N(a);try{var b=document.querySelector(a);if(b)return b===document.activeElement}catch(c){}return!1},306909:()=>document.hasFocus(),
306941:()=>{var a=document;a&&(a.removeEventListener("pointerup",a.lg),a.lg=void 0)},307123:()=>document.body.clientWidth,307161:()=>document.body.clientHeight,307200:()=>window.innerWidth,307230:()=>window.innerHeight,307261:()=>window.outerWidth,307291:()=>window.outerHeight,307322:()=>window.pageXOffset,307353:()=>window.pageYOffset,307384:(a,b)=>{var c=document.querySelector(N(b));if(c){var d=h.SDL3;c.Pg=function(e){var f=c.getBoundingClientRect();e=d.bh(f.left,f.top,e);e!=0&&(ze(d.Og(a),e),ye(e))};
c.Dg=function(e){var f=c.getBoundingClientRect();e=d.bh(f.left,f.top,e);e!=0&&(Ae(d.Og(a),e),ye(e))};c.lg=function(e){var f=c.getBoundingClientRect();e=d.bh(f.left,f.top,e);e!=0&&(Be(d.Og(a),e),ye(e))};c.style.touchAction="none";c.addEventListener("pointerenter",c.Pg);c.addEventListener("pointerleave",c.Dg);c.addEventListener("pointercancel",c.Dg);c.addEventListener("pointerdown",c.lg);c.addEventListener("pointermove",c.lg);c.addEventListener("pointerup",c.lg)}},308772:(a,b,c)=>{var d=document.querySelector(N(b));
if(d){var e=h.SDL3,f=function(g){var m=ue(c);if(m!=0){var k=m>>2,p=d.getBoundingClientRect();t[k++]=g.clientX-p.left;t[k++]=g.clientY-p.top}return m};e.zh=function(g){g.preventDefault();g=f(g);g!=0&&(Ce(a,g),ye(g))};d.addEventListener("dragover",e.zh);e.hh=0;try{L("/tmp/filedrop")}catch(g){}e.Ah=function(g){g.preventDefault();if(g.dataTransfer.types.includes("text/plain"))g=Sd(g.dataTransfer.getData("text/plain")),De(a,g),te(g);else if(g.dataTransfer.types.includes("Files")){let m=0,k=g.dataTransfer.files.length;
for(let p=0;p<k;p++){let q=g.dataTransfer.files.item(p),v=new FileReader;v.readAsArrayBuffer(q);v.onload=function(C){var D=`/tmp/filedrop/${e.hh}`;e.hh+=1;var G=`${D}/${q.name}`,J=Sd(G);C=new Uint8Array(C.target.result);try{L(D);var I=Kb(G,"w");Nb(I,C,0,C.length,0);Lb(I);Ee(a,J)}catch(S){}te(J);++m;m===k&&Fe(a)};v.onerror=function(){++m;m===k&&Fe(a)}}}Fe(a)};d.addEventListener("drop",e.Ah);e.Wg=function(g){g.preventDefault();Fe(a)};d.addEventListener("dragend",e.Wg);d.addEventListener("dragleave",
e.Wg)}},311139:a=>{if(a=document.querySelector(N(a))){var b=h.SDL3;a.removeEventListener("dragleave",b.Wg);a.removeEventListener("dragend",b.Wg);a.removeEventListener("drop",b.Ah);b.hh=void 0;"/tmp/filedrop";Gb("/tmp/filedrop");a.removeEventListener("dragover",b.zh);b.zh=void 0;b.Ah=void 0;b.Wg=void 0}},311969:a=>{if(a=document.querySelector(N(a)))a.removeEventListener("pointerenter",a.Pg),a.removeEventListener("pointerleave",a.Dg),a.removeEventListener("pointercancel",a.Dg),a.removeEventListener("pointerdown",
a.lg),a.removeEventListener("pointermove",a.lg),a.removeEventListener("pointerup",a.lg),a.style.touchAction="",a.Pg=void 0,a.Dg=void 0,a.lg=void 0},312703:()=>window.matchMedia?window.matchMedia("(prefers-color-scheme: light)").matches?0:window.matchMedia("(prefers-color-scheme: dark)").matches?1:-1:-1,312912:()=>{if(typeof h.SDL3!=="undefined"){var a=h.SDL3;a.Ph.removeEventListener("change",a.Bh);a.Ph=void 0;a.Bh=void 0}},313165:()=>window.innerWidth,313195:()=>window.innerHeight,313226:a=>{h.requestFullscreen=
function(){Ge(a)}},313335:(a,b)=>{a=URL.createObjectURL(new Blob([r.buffer instanceof ArrayBuffer?r.subarray(a,a+b):r.slice(a,a+b)],{type:"image/png"}));b=document.querySelector("link[rel~='icon']");b||(b=document.createElement("link"),b.rel="icon",b.type="image/png",document.head.appendChild(b));b.href&&b.href.startsWith("blob:")&&URL.revokeObjectURL(b.href);b.href=a},313828:()=>{h.requestFullscreen=function(){}},313902:()=>window.innerWidth,313932:()=>window.innerHeight,313963:a=>{a=document.querySelector(N(a));
a.ii=a.style.position;a.ji=a.style.top;a.hi=a.style.left;var b=document.createElement("div");b.id="SDL3_fill_document_background_elements";b.kg=a;b.Zg=a.parentNode;b.Xg=a.nextSibling;var c=Array.from(document.body.children),d;for(d of c)b.appendChild(d);document.body.appendChild(b);b.style.display="none";document.body.appendChild(a);a.style.position="fixed";a.style.top="0";a.style.left="0"},314661:()=>{var a=document.getElementById("SDL3_fill_document_background_elements");if(a){for(a.Xg?a.Zg.insertBefore(a.kg,
a.Xg):a.Zg.appendChild(a.kg);a.firstChild;)document.body.insertBefore(a.firstChild,a);a.kg.style.position=a.kg.ii;a.kg.style.top=a.kg.ji;a.kg.style.left=a.kg.hi;a.remove()}},315220:()=>{if(window.matchMedia){var a=h.SDL3;a.Bh=function(){He()};a.Ph=window.matchMedia("(prefers-color-scheme: dark)");a.Ph.addEventListener("change",a.Bh)}},315542:(a,b,c,d,e)=>{a=N(a);b=N(b);c=N(c);d=N(d);var f=N(e);e=document.createElement("dialog");e.classList.add("SDL3_messagebox");e.id=f;e.style.color=d;e.style.backgroundColor=
c;document.body.append(e);d=document.createElement("h1");d.innerText=a;e.append(d);a=document.createElement("p");a.innerText=b;e.append(a);e.showModal()},316083:(a,b,c,d,e,f,g,m)=>{a=N(a);b=N(b);f=N(f);var k=N(g),p=N(m),q=document.getElementById(a);if(!q)return!1;var v=document.createElement("button");v.innerText=b;v.style.borderColor=f;v.style.backgroundColor=k;q.addEventListener("keydown",function(C){d&&C.key==="Enter"?(C.preventDefault(),v.click()):e&&C.key==="Escape"&&(C.preventDefault(),v.click())});
q.addEventListener("cancel",function(C){C.preventDefault()});v.onmouseenter=function(){v.style.backgroundColor=p};v.onmouseleave=function(){v.style.backgroundColor=k};v.onclick=function(){q.close(c)};q.append(v);return!0},317092:a=>{a=N(a);return(a=document.getElementById(a))?a.open:!1},317230:a=>{a=N(a);a=document.getElementById(a);if(!a)return 0;try{return parseInt(a.returnValue)}catch(b){return 0}},317412:(a,b)=>{alert(N(a)+"\n\n"+N(b))}},Ie,ye,Rd,ue,te,ze,Ae,Be,xe,Ce,Fe,De,Ee,we,He,Ge,Je,Rc,Oc,
Qc,la,R,Ke={_a:(a,b)=>R.get(a)(b),c:(a,b,c)=>{(new Ba(a)).init(b,c);Ca++;z()},pb:function(a,b,c){try{b=N(b);b=Vb(a,b);if(c&-8)return-28;var d=H(b,{Qg:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&ub(d,a)?-2:0}catch(e){if(typeof M=="undefined"||e.name!=="ErrnoError")throw e;return-e.ig}},q:function(a,b,c){Xb=c;try{var d=K(a);switch(b){case 0:var e=Yb();if(e<0)break;for(;lb[e];)e++;return zb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Yb(),
d.flags=d.flags&-289793|e&289792,0;case 12:return e=Yb(),ma[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if(typeof M=="undefined"||f.name!=="ErrnoError")throw f;return-f.ig}},lb:function(a){try{return K(a),0}catch(b){if(typeof M=="undefined"||b.name!=="ErrnoError")throw b;return-b.ig}},jb:function(a,b){try{var c=K(a),d=c.node,e=c.cg.ug;a=e?c:d;e??=d.bg.ug;xb(e,63);var f=e(a);return Wb(b,f)}catch(g){if(typeof M=="undefined"||g.name!=="ErrnoError")throw g;return-g.ig}},Za:function(a,b,c){try{var d=
K(a);if(!d.Lg){var e=H(d.path,{Qg:!0}).node;var f=xb(e.bg.ph,54)(e);d.Lg=f}a=0;var g=Mb(d,0,1),m=Math.floor(g/280),k=Math.min(d.Lg.length,m+Math.floor(c/280));for(c=m;c<k;c++){var p=d.Lg[c];if(p==="."){var q=d.node.id;var v=4}else if(p==="..")q=H(d.path,{parent:!0}).node.id,v=4;else{try{var C=Ya(d.node,p)}catch(D){if(D?.ig===28)continue;throw D;}q=C.id;v=(C.mode&61440)===8192?2:F(C.mode)?4:(C.mode&61440)===40960?10:8}y[b+a>>3]=BigInt(q);y[b+a+8>>3]=BigInt((c+1)*280);ma[b+a+16>>1]=280;n[b+a+18]=v;
A(p,r,b+a+19,256);a+=280}Mb(d,c*280,0);return a}catch(D){if(typeof M=="undefined"||D.name!=="ErrnoError")throw D;return-D.ig}},kb:function(a,b,c){Xb=c;try{var d=K(a);switch(b){case 21509:return d.hg?0:-59;case 21505:if(!d.hg)return-59;if(d.hg.Fg.Fi){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Yb();t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>2]=35387;for(var f=0;f<32;f++)n[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.hg?0:-59;case 21506:case 21507:case 21508:if(!d.hg)return-59;
if(d.hg.Fg.Gi)for(e=Yb(),a=[],f=0;f<32;f++)a.push(n[e+f+17]);return 0;case 21519:if(!d.hg)return-59;e=Yb();return t[e>>2]=0;case 21520:return d.hg?-28:-59;case 21537:case 21531:e=Yb();if(!d.cg.Ei)throw new B(59);return d.cg.Ei(d,b,e);case 21523:if(!d.hg)return-59;d.hg.Fg.Hi&&(f=[24,80],e=Yb(),ma[e>>1]=f[0],ma[e+2>>1]=f[1]);return 0;case 21524:return d.hg?0:-59;case 21515:return d.hg?0:-59;default:return-28}}catch(g){if(typeof M=="undefined"||g.name!=="ErrnoError")throw g;return-g.ig}},hb:function(a,
b){try{return a=N(a),Wb(b,Ib(a,!0))}catch(c){if(typeof M=="undefined"||c.name!=="ErrnoError")throw c;return-c.ig}},db:function(a,b,c){try{return b=N(b),b=Vb(a,b),L(b,c&-19),0}catch(d){if(typeof M=="undefined"||d.name!=="ErrnoError")throw d;return-d.ig}},gb:function(a,b,c,d){try{b=N(b);var e=d&256;b=Vb(a,b,d&4096);return Wb(c,e?Ib(b,!0):Ib(b))}catch(f){if(typeof M=="undefined"||f.name!=="ErrnoError")throw f;return-f.ig}},y:function(a,b,c,d){Xb=d;try{b=N(b);b=Vb(a,b);var e=d?Yb():0;c&64&&(e&=-19);return Kb(b,
c,e).fd}catch(f){if(typeof M=="undefined"||f.name!=="ErrnoError")throw f;return-f.ig}},Ya:function(a,b,c,d){try{b=N(b);b=Vb(a,b);if(d<=0)return-28;var e=H(b).node;if(!e)throw new B(44);if(!e.bg.Mg)throw new B(28);var f=e.bg.Mg(e);var g=Math.min(d,Oa(f)),m=n[c+g];A(f,r,c,d+1);n[c+g]=m;return g}catch(k){if(typeof M=="undefined"||k.name!=="ErrnoError")throw k;return-k.ig}},Wa:function(a){try{return a=N(a),Gb(a),0}catch(b){if(typeof M=="undefined"||b.name!=="ErrnoError")throw b;return-b.ig}},ib:function(a,
b){try{return a=N(a),Wb(b,Ib(a))}catch(c){if(typeof M=="undefined"||c.name!=="ErrnoError")throw c;return-c.ig}},Xa:function(a,b,c){try{b=N(b);b=Vb(a,b);if(c)if(c===512)Gb(b);else return-28;else Hb(b);return 0}catch(d){if(typeof M=="undefined"||d.name!=="ErrnoError")throw d;return-d.ig}},qb:()=>z(""),nb:(a,b)=>{b=N(b);if(a&24){var c=b=b.replace(/\s+$/,"");b=b.length>0?"\n":"";var d=Error().stack.toString(),e=d.split("\n");d="";var f=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),g=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),
m;for(m of e){var k=g.exec(m);if(k?.length==5){e=k[1];var p=k[2];var q=k[3];k=k[4]}else if(k=f.exec(m),k?.length>=4)e=k[1],p=k[2],q=k[3],k=k[4]|0;else{d+=m+"\n";continue}e=="_emscripten_log"||e=="_emscripten_get_callstack"?d="":a&24&&(a&64&&(p=p.substring(p.replace(/\\/g,"/").lastIndexOf("/")+1)),d+=`    at ${e} (${p}:${q}:${k})\n`)}d=d.replace(/\s+$/,"");b=c+(b+d)}a&1?a&4?console.error(b):a&2?console.warn(b):a&512?console.info(b):a&256?console.debug(b):console.log(b):a&6?l(b):fa(b)},ab:()=>{za=!1;
Zb=0},bb:function(a){var b=new Date(t[a+20>>2]+1900,t[a+16>>2],t[a+12>>2],t[a+8>>2],t[a+4>>2],t[a>>2],0);if(isNaN(b.getTime()))a=-1;else{var c=t[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),g=Math.min(f,e);c<0?t[a+32>>2]=Number(e!=f&&g==d):c>0!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+((c>0?g:e)-d)*6E4));t[a+24>>2]=b.getDay();c=b.getFullYear();t[a+28>>2]=(c%4!==0||c%100===0&&c%400!==0?ac:$b)[b.getMonth()]+
b.getDate()-1|0;t[a>>2]=b.getSeconds();t[a+4>>2]=b.getMinutes();t[a+8>>2]=b.getHours();t[a+12>>2]=b.getDate();t[a+16>>2]=b.getMonth();t[a+20>>2]=b.getYear();a=b.getTime()/1E3}return BigInt(a)},Ta:(a,b)=>{bc[a]&&(clearTimeout(bc[a].id),delete bc[a]);if(!b)return 0;var c=setTimeout(()=>{delete bc[a];fc(()=>Je(a,performance.now()))},b);bc[a]={id:c,tj:b};return 0},cb:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();u[a>>2]=Math.max(f,
e)*60;t[b>>2]=Number(f!=e);b=g=>{var m=Math.abs(g);return`UTC${g>=0?"-":"+"}${String(Math.floor(m/60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(A(a,r,c,17),A(b,r,d,17)):(A(a,r,d,17),A(b,r,c,17))},ob:function(a,b,c){if(!(a>=0&&a<=3))return 28;y[c>>3]=BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},G:kc,h:(a,b,c)=>{b=ic(b,c);return jc[a](...b)},a:kc,Ed:(a,b,c)=>{b=ic(b,c);return jc[a](...b)},Bf:()=>{Ec();nc=null},mb:()=>Date.now(),Pa:()=>{if(!P.fullscreenEnabled())return-1;
Ic($c);var a=Nc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},jd:()=>{Ic(ad);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},g:()=>devicePixelRatio,b:(a,b,c)=>{a=Q(a);if(!a)return-4;a=Zc(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},Ra:a=>{if(!P.fullscreenEnabled())return-1;bd(a);return 0},s:(a,b)=>{if(a<0||a>=P.ih.length)return-5;if(!P.ih[a])return-7;
cd(b,P.ih[a]);return 0},Xe:(a,b)=>{a&&(t[a>>2]=lc);b&&(t[b>>2]=mc)},o:()=>performance.now(),ma:()=>P.ih.length,Zd:(a,b)=>{t[a>>2]=screen.width;t[b>>2]=screen.height},ua:a=>T.activeTexture(a),ta:(a,b)=>{T.attachShader(U[a],V[b])},dd:(a,b)=>{T.beginQuery(a,W[b])},La:(a,b)=>{T.sg.beginQueryEXT(a,W[b])},Mc:a=>T.beginTransformFeedback(a),sa:(a,b,c)=>{T.bindAttribLocation(U[a],b,N(c))},ra:(a,b)=>{a==35051?T.wh=b:a==35052&&(T.zg=b);T.bindBuffer(a,md[b])},Jc:(a,b,c)=>{T.bindBufferBase(a,b,md[c])},Kc:(a,b,
c,d,e)=>{T.bindBufferRange(a,b,md[c],d,e)},qa:(a,b)=>{T.bindFramebuffer(a,nd[b])},pa:(a,b)=>{T.bindRenderbuffer(a,od[b])},Rb:(a,b)=>{T.bindSampler(a,X[b])},oa:(a,b)=>{T.bindTexture(a,pd[b])},Ib:(a,b)=>{T.bindTransformFeedback(a,sd[b])},Rc:Dd,Ca:Dd,na:(a,b,c,d)=>T.blendColor(a,b,c,d),la:a=>T.blendEquation(a),ka:(a,b)=>T.blendEquationSeparate(a,b),ja:(a,b)=>T.blendFunc(a,b),ia:(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),Uc:(a,b,c,d,e,f,g,m,k,p)=>T.blitFramebuffer(a,b,c,d,e,f,g,m,k,p),ha:(a,b,c,d)=>{c&&
b?T.bufferData(a,r,d,c,b):T.bufferData(a,b,d)},ga:(a,b,c,d)=>{var e=r;c&&T.bufferSubData(a,b,e,d,c)},fa:a=>T.checkFramebufferStatus(a),ea:a=>T.clear(a),mc:(a,b,c,d)=>T.clearBufferfi(a,b,c,d),nc:(a,b,c)=>{T.clearBufferfv(a,b,w,c>>2)},pc:(a,b,c)=>{T.clearBufferiv(a,b,t,c>>2)},oc:(a,b,c)=>{T.clearBufferuiv(a,b,u,c>>2)},da:(a,b,c,d)=>T.clearColor(a,b,c,d),ca:a=>T.clearDepth(a),ba:a=>T.clearStencil(a),_b:(a,b,c)=>{c=Number(c);return T.clientWaitSync(td[a],b,c)},yd:(a,b)=>{T.wi.clipControlEXT(a,b)},aa:(a,
b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},$:a=>{T.compileShader(V[a])},_:(a,b,c,d,e,f,g,m)=>{T.zg||!g?T.compressedTexImage2D(a,b,c,d,e,f,g,m):T.compressedTexImage2D(a,b,c,d,e,f,r,m,g)},id:(a,b,c,d,e,f,g,m,k)=>{T.zg?T.compressedTexImage3D(a,b,c,d,e,f,g,m,k):T.compressedTexImage3D(a,b,c,d,e,f,g,r,k,m)},Z:(a,b,c,d,e,f,g,m,k)=>{T.zg||!m?T.compressedTexSubImage2D(a,b,c,d,e,f,g,m,k):T.compressedTexSubImage2D(a,b,c,d,e,f,g,r,k,m)},hd:(a,b,c,d,e,f,g,m,k,p,q)=>{T.zg?T.compressedTexSubImage3D(a,b,c,d,e,f,g,m,
k,p,q):T.compressedTexSubImage3D(a,b,c,d,e,f,g,m,k,r,q,p)},kc:(a,b,c,d,e)=>T.copyBufferSubData(a,b,c,d,e),Y:(a,b,c,d,e,f,g,m)=>T.copyTexImage2D(a,b,c,d,e,f,g,m),X:(a,b,c,d,e,f,g,m)=>T.copyTexSubImage2D(a,b,c,d,e,f,g,m),kd:(a,b,c,d,e,f,g,m,k)=>T.copyTexSubImage3D(a,b,c,d,e,f,g,m,k),W:()=>{var a=yd(U),b=T.createProgram();b.name=a;b.mh=b.jh=b.kh=0;b.Rh=1;U[a]=b;return a},V:a=>{var b=yd(V);V[b]=T.createShader(a);return b},U:a=>T.cullFace(a),T:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=md[d];e&&
(T.deleteBuffer(e),e.name=0,md[d]=null,d==T.wh&&(T.wh=0),d==T.zg&&(T.zg=0))}},S:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+c*4>>2],e=nd[d];e&&(T.deleteFramebuffer(e),e.name=0,nd[d]=null)}},R:a=>{if(a){var b=U[a];b?(T.deleteProgram(b),b.name=0,U[a]=null):Y||=1281}},fd:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=W[d];e&&(T.deleteQuery(e),W[d]=null)}},Na:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=W[d];e&&(T.sg.deleteQueryEXT(e),W[d]=null)}},Q:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=od[d];
e&&(T.deleteRenderbuffer(e),e.name=0,od[d]=null)}},Tb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=X[d];e&&(T.deleteSampler(e),e.name=0,X[d]=null)}},P:a=>{if(a){var b=V[a];b?(T.deleteShader(b),V[a]=null):Y||=1281}},$b:a=>{if(a){var b=td[a];b?(T.deleteSync(b),b.name=0,td[a]=null):Y||=1281}},O:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=pd[d];e&&(T.deleteTexture(e),e.name=0,pd[d]=null)}},Hb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=sd[d];e&&(T.deleteTransformFeedback(e),e.name=0,sd[d]=
null)}},Qc:Ed,Ba:Ed,N:a=>T.depthFunc(a),M:a=>{T.depthMask(!!a)},L:(a,b)=>T.depthRange(a,b),K:(a,b)=>{T.detachShader(U[a],V[b])},Af:a=>T.disable(a),zf:a=>{T.disableVertexAttribArray(a)},yf:(a,b,c)=>{T.drawArrays(a,b,c)},dc:Fd,xa:Fd,td:Fd,ud:Fd,tb:Fd,$c:Hd,pd:Hd,ya:Hd,xf:(a,b,c,d)=>{T.drawElements(a,b,c,d)},cc:Id,wa:Id,qd:Id,rd:Id,sd:Id,nd:(a,b,c,d,e,f)=>{T.drawElements(a,d,e,f)},wf:a=>T.enable(a),vf:a=>{T.enableVertexAttribArray(a)},cd:a=>T.endQuery(a),Ka:a=>{T.sg.endQueryEXT(a)},Lc:()=>T.endTransformFeedback(),
bc:(a,b)=>(a=T.fenceSync(a,b))?(b=yd(td),a.name=b,td[b]=a,b):0,uf:()=>T.finish(),tf:()=>T.flush(),sf:(a,b,c,d)=>{T.framebufferRenderbuffer(a,b,c,od[d])},rf:(a,b,c,d,e)=>{T.framebufferTexture2D(a,b,c,pd[d],e)},Sc:(a,b,c,d,e)=>{T.framebufferTextureLayer(a,b,pd[c],d,e)},qf:a=>T.frontFace(a),pf:(a,b)=>{zd(a,b,"createBuffer",md)},nf:(a,b)=>{zd(a,b,"createFramebuffer",nd)},gd:(a,b)=>{zd(a,b,"createQuery",W)},Oa:(a,b)=>{for(var c=0;c<a;c++){var d=T.sg.createQueryEXT();if(!d){for(Y||=1282;c<a;)t[b+c++*4>>
2]=0;break}var e=yd(W);d.name=e;W[e]=d;t[b+c*4>>2]=e}},mf:(a,b)=>{zd(a,b,"createRenderbuffer",od)},Ub:(a,b)=>{zd(a,b,"createSampler",X)},lf:(a,b)=>{zd(a,b,"createTexture",pd)},Gb:(a,b)=>{zd(a,b,"createTransformFeedback",sd)},Pc:Jd,Aa:Jd,of:a=>T.generateMipmap(a),kf:(a,b,c,d,e,f,g)=>Kd("getActiveAttrib",a,b,c,d,e,f,g),jf:(a,b,c,d,e,f,g)=>Kd("getActiveUniform",a,b,c,d,e,f,g),fc:(a,b,c,d,e)=>{a=U[a];if(a=T.getActiveUniformBlockName(a,b))e&&c>0?(c=A(a,r,e,c),d&&(t[d>>2]=c)):d&&(t[d>>2]=0)},gc:(a,b,c,
d)=>{if(d)if(a=U[a],c==35393)t[d>>2]=T.getActiveUniformBlockName(a,b).length+1;else{if(a=T.getActiveUniformBlockParameter(a,b,c),a!==null)if(c==35395)for(c=0;c<a.length;c++)t[d+c*4>>2]=a[c];else t[d>>2]=a}else Y||=1281},ic:(a,b,c,d,e)=>{if(e)if(b>0&&c==0)Y||=1281;else{a=U[a];for(var f=[],g=0;g<b;g++)f.push(t[c+g*4>>2]);if(a=T.getActiveUniforms(a,f,d))for(b=a.length,g=0;g<b;g++)t[e+g*4>>2]=a[g]}else Y||=1281},hf:(a,b,c,d)=>{a=T.getAttachedShaders(U[a]);var e=a.length;e>b&&(e=b);t[c>>2]=e;for(b=0;b<
e;++b)t[d+b*4>>2]=V.indexOf(a[b])},gf:(a,b)=>T.getAttribLocation(U[a],N(b)),ff:(a,b)=>Nd(a,b,4),Vb:(a,b,c)=>{c?Ld(c,T.getBufferParameter(a,b)):Y||=1281},ef:(a,b,c)=>{c?t[c>>2]=T.getBufferParameter(a,b):Y||=1281},df:()=>{var a=T.getError()||Y;Y=0;return a},cf:(a,b)=>Nd(a,b,2),yc:(a,b)=>T.getFragDataLocation(U[a],N(b)),bf:(a,b,c,d)=>{a=T.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;t[d>>2]=a},Wb:(a,b,c)=>Od(a,b,c,1),Yb:(a,b)=>{Nd(a,
b,1)},Nc:(a,b,c)=>Od(a,b,c,0),af:(a,b)=>Nd(a,b,0),vb:(a,b,c,d,e)=>{if(d<0)Y||=1281;else if(e){if(a=T.getInternalformatParameter(a,b,c),a!==null)for(b=0;b<a.length&&b<d;++b)t[e+b*4>>2]=a[b]}else Y||=1281},Cb:()=>{Y||=1282},_e:(a,b,c,d)=>{a=T.getProgramInfoLog(U[a]);a===null&&(a="(unknown error)");b=b>0&&d?A(a,r,d,b):0;c&&(t[c>>2]=b)},$e:(a,b,c)=>{if(c)if(a>=ld)Y||=1281;else if(a=U[a],b==35716)a=T.getProgramInfoLog(a),a===null&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(b==35719){if(!a.mh){var d=
T.getProgramParameter(a,35718);for(b=0;b<d;++b)a.mh=Math.max(a.mh,T.getActiveUniform(a,b).name.length+1)}t[c>>2]=a.mh}else if(b==35722){if(!a.jh)for(d=T.getProgramParameter(a,35721),b=0;b<d;++b)a.jh=Math.max(a.jh,T.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.jh}else if(b==35381){if(!a.kh)for(d=T.getProgramParameter(a,35382),b=0;b<d;++b)a.kh=Math.max(a.kh,T.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.kh}else t[c>>2]=T.getProgramParameter(a,b);else Y||=1281},Ea:Pd,Ga:Qd,Da:Pd,ad:(a,b,c)=>{if(c){a=
T.getQueryParameter(W[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;t[c>>2]=d}else Y||=1281},Fa:Qd,bd:(a,b,c)=>{c?t[c>>2]=T.getQuery(a,b):Y||=1281},Ia:(a,b,c)=>{c?t[c>>2]=T.sg.getQueryEXT(a,b):Y||=1281},Ze:(a,b,c)=>{c?t[c>>2]=T.getRenderbufferParameter(a,b):Y||=1281},Lb:(a,b,c)=>{c?w[c>>2]=T.getSamplerParameter(X[a],b):Y||=1281},Mb:(a,b,c)=>{c?t[c>>2]=T.getSamplerParameter(X[a],b):Y||=1281},We:(a,b,c,d)=>{a=T.getShaderInfoLog(V[a]);a===null&&(a="(unknown error)");b=b>0&&d?A(a,r,d,b):0;c&&(t[c>>2]=b)},
Ve:(a,b,c,d)=>{a=T.getShaderPrecisionFormat(a,b);t[c>>2]=a.rangeMin;t[c+4>>2]=a.rangeMax;t[d>>2]=a.precision},Ue:(a,b,c,d)=>{if(a=T.getShaderSource(V[a]))b=b>0&&d?A(a,r,d,b):0,c&&(t[c>>2]=b)},Ye:(a,b,c)=>{c?b==35716?(a=T.getShaderInfoLog(V[a]),a===null&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):b==35720?(a=T.getShaderSource(V[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=T.getShaderParameter(V[a],b):Y||=1281},Te:a=>{var b=ud[a];if(!b){switch(a){case 7939:b=Sd(Md().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
T.getParameter(a))||(Y||=1280);b=b?Sd(b):0;break;case 7938:b=Sd(`OpenGL ES 3.0 (${T.getParameter(7938)})`);break;case 35724:b=T.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);c!==null&&(c[1].length==3&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Sd(b);break;default:Y||=1280}ud[a]=b}return b},lc:(a,b)=>{if(Cd.version<2)return Y||=1282,0;var c=vd[a];if(c)return b<0||b>=c.length?(Y||=1281,0):c[b];switch(a){case 7939:return c=Md().map(Sd),c=vd[a]=c,b<0||b>=c.length?
(Y||=1281,0):c[b];default:return Y||=1280,0}},Xb:(a,b,c,d,e)=>{c<0?Y||=1281:e?(a=T.getSyncParameter(td[a],b),a!==null&&(t[e>>2]=a,d&&(t[d>>2]=1))):Y||=1281},Se:(a,b,c)=>{c?w[c>>2]=T.getTexParameter(a,b):Y||=1281},Re:(a,b,c)=>{c?t[c>>2]=T.getTexParameter(a,b):Y||=1281},Hc:(a,b,c,d,e,f,g)=>{a=U[a];if(a=T.getTransformFeedbackVarying(a,b))g&&c>0?(c=A(a.name,r,g,c),d&&(t[d>>2]=c)):d&&(t[d>>2]=0),e&&(t[e>>2]=a.size),f&&(t[f>>2]=a.type)},hc:(a,b)=>T.getUniformBlockIndex(U[a],N(b)),jc:(a,b,c,d)=>{if(d)if(b>
0&&(c==0||d==0))Y||=1281;else{a=U[a];for(var e=[],f=0;f<b;f++)e.push(N(u[c+f*4>>2]));if(a=T.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)t[d+f*4>>2]=a[f]}else Y||=1281},Oe:(a,b)=>{b=N(b);if(a=U[a]){Ud(a);var c=a.eh,d=0,e=b,f=Td(b);f>0&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.gi[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else Y||=1281;return-1},Qe:(a,b,c)=>{Vd(a,b,c,2)},Pe:(a,b,c)=>{Vd(a,b,c,0)},zc:(a,b,c)=>Vd(a,b,c,0),Fc:Xd,Ec:Xd,Ke:(a,b,c)=>{c?t[c>>2]=
T.getVertexAttribOffset(a,b):Y||=1281},Ne:(a,b,c)=>{Wd(a,b,c,2)},Le:(a,b,c)=>{Wd(a,b,c,5)},Je:(a,b)=>T.hint(a,b),zb:(a,b,c)=>{for(var d=Gd[b],e=0;e<b;e++)d[e]=t[c+e*4>>2];T.invalidateFramebuffer(a,d)},yb:(a,b,c,d,e,f,g)=>{for(var m=Gd[b],k=0;k<b;k++)m[k]=t[c+k*4>>2];T.invalidateSubFramebuffer(a,m,d,e,f,g)},Ie:a=>(a=md[a])?T.isBuffer(a):0,He:a=>T.isEnabled(a),Ge:a=>(a=nd[a])?T.isFramebuffer(a):0,Fe:a=>(a=U[a])?T.isProgram(a):0,ed:a=>(a=W[a])?T.isQuery(a):0,Ma:a=>(a=W[a])?T.sg.isQueryEXT(a):0,Ee:a=>
(a=od[a])?T.isRenderbuffer(a):0,Sb:a=>(a=X[a])?T.isSampler(a):0,De:a=>(a=V[a])?T.isShader(a):0,ac:a=>T.isSync(td[a]),Ce:a=>(a=pd[a])?T.isTexture(a):0,Fb:a=>T.isTransformFeedback(sd[a]),Oc:Yd,za:Yd,Be:a=>T.lineWidth(a),Ae:a=>{a=U[a];T.linkProgram(a);a.eh=0;a.gi={}},Eb:()=>T.pauseTransformFeedback(),ze:(a,b)=>{a==3317?wd=b:a==3314&&(xd=b);T.pixelStorei(a,b)},xd:(a,b)=>{T.Si.polygonModeWEBGL(a,b)},ye:(a,b)=>T.polygonOffset(a,b),zd:(a,b,c)=>{T.xi.polygonOffsetClampEXT(a,b,c)},Bb:()=>{Y||=1280},Ab:()=>
{Y||=1280},Ja:(a,b)=>{T.sg.queryCounterEXT(W[a],b)},od:a=>T.readBuffer(a),xe:(a,b,c,d,e,f,g)=>{if(T.wh)T.readPixels(a,b,c,d,e,f,g);else{var m=Zd(f);g>>>=31-Math.clz32(m.BYTES_PER_ELEMENT);T.readPixels(a,b,c,d,e,f,m,g)}},we:()=>{},ve:(a,b,c,d)=>T.renderbufferStorage(a,b,c,d),Tc:(a,b,c,d,e)=>T.renderbufferStorageMultisample(a,b,c,d,e),Db:()=>T.resumeTransformFeedback(),ue:(a,b)=>{T.sampleCoverage(a,!!b)},Ob:(a,b,c)=>{T.samplerParameterf(X[a],b,c)},Nb:(a,b,c)=>{T.samplerParameterf(X[a],b,w[c>>2])},Qb:(a,
b,c)=>{T.samplerParameteri(X[a],b,c)},Pb:(a,b,c)=>{T.samplerParameteri(X[a],b,t[c>>2])},te:(a,b,c,d)=>T.scissor(a,b,c,d),se:()=>{Y||=1280},re:(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=N(u[c+f*4>>2],d?u[d+f*4>>2]:void 0);T.shaderSource(V[a],e)},qe:(a,b,c)=>T.stencilFunc(a,b,c),pe:(a,b,c,d)=>T.stencilFuncSeparate(a,b,c,d),oe:a=>T.stencilMask(a),ne:(a,b)=>T.stencilMaskSeparate(a,b),me:(a,b,c)=>T.stencilOp(a,b,c),le:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),ke:(a,b,c,d,e,f,g,m,k)=>{if(T.zg)T.texImage2D(a,
b,c,d,e,f,g,m,k);else if(k){var p=Zd(m);k>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);T.texImage2D(a,b,c,d,e,f,g,m,p,k)}else p=k?$d(m,g,d,e,k):null,T.texImage2D(a,b,c,d,e,f,g,m,p)},md:(a,b,c,d,e,f,g,m,k,p)=>{if(T.zg)T.texImage3D(a,b,c,d,e,f,g,m,k,p);else if(p){var q=Zd(k);T.texImage3D(a,b,c,d,e,f,g,m,k,q,p>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else T.texImage3D(a,b,c,d,e,f,g,m,k,null)},je:(a,b,c)=>T.texParameterf(a,b,c),ie:(a,b,c)=>{T.texParameterf(a,b,w[c>>2])},he:(a,b,c)=>T.texParameteri(a,b,c),ge:(a,
b,c)=>{T.texParameteri(a,b,t[c>>2])},xb:(a,b,c,d,e)=>T.texStorage2D(a,b,c,d,e),wb:(a,b,c,d,e,f)=>T.texStorage3D(a,b,c,d,e,f),fe:(a,b,c,d,e,f,g,m,k)=>{if(T.zg)T.texSubImage2D(a,b,c,d,e,f,g,m,k);else if(k){var p=Zd(m);T.texSubImage2D(a,b,c,d,e,f,g,m,p,k>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else k=k?$d(m,g,e,f,k):null,T.texSubImage2D(a,b,c,d,e,f,g,m,k)},ld:(a,b,c,d,e,f,g,m,k,p,q)=>{if(T.zg)T.texSubImage3D(a,b,c,d,e,f,g,m,k,p,q);else if(q){var v=Zd(p);T.texSubImage3D(a,b,c,d,e,f,g,m,k,p,v,q>>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else T.texSubImage3D(a,
b,c,d,e,f,g,m,k,p,null)},Ic:(a,b,c,d)=>{a=U[a];for(var e=[],f=0;f<b;f++)e.push(N(u[c+f*4>>2]));T.transformFeedbackVaryings(a,e,d)},ee:(a,b)=>{T.uniform1f(Z(T.eg,a),b)},de:(a,b,c)=>{b&&T.uniform1fv(Z(T.eg,a),w,c>>2,b)},ce:(a,b)=>{T.uniform1i(Z(T.eg,a),b)},be:(a,b,c)=>{b&&T.uniform1iv(Z(T.eg,a),t,c>>2,b)},xc:(a,b)=>{T.uniform1ui(Z(T.eg,a),b)},tc:(a,b,c)=>{b&&T.uniform1uiv(Z(T.eg,a),u,c>>2,b)},ae:(a,b,c)=>{T.uniform2f(Z(T.eg,a),b,c)},$d:(a,b,c)=>{b&&T.uniform2fv(Z(T.eg,a),w,c>>2,b*2)},_d:(a,b,c)=>{T.uniform2i(Z(T.eg,
a),b,c)},Yd:(a,b,c)=>{b&&T.uniform2iv(Z(T.eg,a),t,c>>2,b*2)},wc:(a,b,c)=>{T.uniform2ui(Z(T.eg,a),b,c)},sc:(a,b,c)=>{b&&T.uniform2uiv(Z(T.eg,a),u,c>>2,b*2)},Xd:(a,b,c,d)=>{T.uniform3f(Z(T.eg,a),b,c,d)},Wd:(a,b,c)=>{b&&T.uniform3fv(Z(T.eg,a),w,c>>2,b*3)},Vd:(a,b,c,d)=>{T.uniform3i(Z(T.eg,a),b,c,d)},Ud:(a,b,c)=>{b&&T.uniform3iv(Z(T.eg,a),t,c>>2,b*3)},vc:(a,b,c,d)=>{T.uniform3ui(Z(T.eg,a),b,c,d)},rc:(a,b,c)=>{b&&T.uniform3uiv(Z(T.eg,a),u,c>>2,b*3)},Td:(a,b,c,d,e)=>{T.uniform4f(Z(T.eg,a),b,c,d,e)},Sd:(a,
b,c)=>{b&&T.uniform4fv(Z(T.eg,a),w,c>>2,b*4)},Rd:(a,b,c,d,e)=>{T.uniform4i(Z(T.eg,a),b,c,d,e)},Qd:(a,b,c)=>{b&&T.uniform4iv(Z(T.eg,a),t,c>>2,b*4)},uc:(a,b,c,d,e)=>{T.uniform4ui(Z(T.eg,a),b,c,d,e)},qc:(a,b,c)=>{b&&T.uniform4uiv(Z(T.eg,a),u,c>>2,b*4)},ec:(a,b,c)=>{a=U[a];T.uniformBlockBinding(a,b,c)},Pd:(a,b,c,d)=>{b&&T.uniformMatrix2fv(Z(T.eg,a),!!c,w,d>>2,b*4)},_c:(a,b,c,d)=>{b&&T.uniformMatrix2x3fv(Z(T.eg,a),!!c,w,d>>2,b*6)},Yc:(a,b,c,d)=>{b&&T.uniformMatrix2x4fv(Z(T.eg,a),!!c,w,d>>2,b*8)},Od:(a,
b,c,d)=>{b&&T.uniformMatrix3fv(Z(T.eg,a),!!c,w,d>>2,b*9)},Zc:(a,b,c,d)=>{b&&T.uniformMatrix3x2fv(Z(T.eg,a),!!c,w,d>>2,b*6)},Wc:(a,b,c,d)=>{b&&T.uniformMatrix3x4fv(Z(T.eg,a),!!c,w,d>>2,b*12)},Nd:(a,b,c,d)=>{b&&T.uniformMatrix4fv(Z(T.eg,a),!!c,w,d>>2,b*16)},Xc:(a,b,c,d)=>{b&&T.uniformMatrix4x2fv(Z(T.eg,a),!!c,w,d>>2,b*8)},Vc:(a,b,c,d)=>{b&&T.uniformMatrix4x3fv(Z(T.eg,a),!!c,w,d>>2,b*12)},Md:a=>{a=U[a];T.useProgram(a);T.eg=a},Ld:a=>{T.validateProgram(U[a])},Kd:(a,b)=>T.vertexAttrib1f(a,b),Jd:(a,b)=>
{T.vertexAttrib1f(a,w[b>>2])},Id:(a,b,c)=>T.vertexAttrib2f(a,b,c),Hd:(a,b)=>{T.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},Gd:(a,b,c,d)=>T.vertexAttrib3f(a,b,c,d),Fd:(a,b)=>{T.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},Dd:(a,b,c,d,e)=>T.vertexAttrib4f(a,b,c,d,e),Cd:(a,b)=>{T.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Jb:ae,va:ae,vd:ae,wd:ae,ub:ae,Dc:(a,b,c,d,e)=>T.vertexAttribI4i(a,b,c,d,e),Bc:(a,b)=>{T.vertexAttribI4i(a,t[b>>2],t[b+4>>2],t[b+8>>2],t[b+12>>2])},Cc:(a,b,c,d,e)=>T.vertexAttribI4ui(a,
b,c,d,e),Ac:(a,b)=>{T.vertexAttribI4ui(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Gc:(a,b,c,d,e)=>{T.vertexAttribIPointer(a,b,c,d,e)},Bd:(a,b,c,d,e,f)=>{T.vertexAttribPointer(a,b,c,!!d,e,f)},Ad:(a,b,c,d)=>T.viewport(a,b,c,d),Zb:(a,b,c)=>{c=Number(c);T.waitSync(td[a],b,c)},l:()=>0,Qa:(a,b,c)=>be(a,{Nh:t[c>>2],uh:t[c+4>>2],yi:t[c+8>>2],ri:b,fh:t[c+12>>2],Wh:t[c+16>>2]}),H:(a,b)=>{a=Q(a);return a?a.requestPointerLock?Jc()?ad(a):b?(Hc(ad,2,[a]),1):-2:-1:-4},Va:a=>{var b=r.length;a>>>=0;if(a>2147483648)return!1;
for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-la.buffer.byteLength+65535)/65536|0;try{la.grow(d);ka();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},t:ce,u:(a,b,c)=>typeof onbeforeunload=="undefined"?-1:c!==1?-5:de(a,b),E:(a,b,c,d)=>ee(a,b,c,d,12,"blur"),d:Tc,f:(a,b,c)=>{a=Q(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},F:(a,b,c,d)=>ee(a,b,c,d,13,"focus"),C:(a,b,c,d)=>{if(!P.fullscreenEnabled())return-1;
a=Q(a);if(!a)return-4;fe(a,b,c,d,"webkitfullscreenchange");return fe(a,b,c,d,"fullscreenchange")},i:(a,b,c)=>ce()?-1:ge(a,b,c,26,"gamepadconnected"),m:(a,b,c)=>ce()?-1:ge(a,b,c,27,"gamepaddisconnected"),r:(a,b,c,d)=>he(a,b,c,d,2,"keydown"),n:(a,b,c,d)=>he(a,b,c,d,1,"keypress"),p:(a,b,c,d)=>he(a,b,c,d,3,"keyup"),Kb:(a,b,c)=>{a=R.get(a);Dc(a,b,c)},e:uc,z:(a,b,c)=>window.screen&&screen.orientation?ie(a,b,c):-1,D:(a,b,c,d)=>document.body?.requestPointerLock?(a=Q(a))?je(a,b,c,d):-4:-1,B:(a,b,c,d)=>ke(a,
b,c,d),v:(a,b,c)=>le(a,b,c),A:(a,b,c,d)=>(a=Q(a))?typeof a.onwheel!="undefined"?me(a,b,c,d):-1:-4,Sa:a=>document.title=N(a),k:()=>{z("Please compile your program with async support in order to use asynchronous operations like emscripten_sleep")},Me:(a,b)=>{var c=b>>2;b={alpha:!!n[b+0],depth:!!n[b+1],stencil:!!n[b+2],antialias:!!n[b+3],premultipliedAlpha:!!n[b+4],preserveDrawingBuffer:!!n[b+5],powerPreference:ne[t[c+2]],failIfMajorPerformanceCaveat:!!n[b+12],Ki:t[c+4],lj:t[c+5],Yh:n[b+24],ui:n[b+25],
pj:t[c+7],sj:n[b+32]};a=Q(a);return!a||b.ui?0:Bd(a,b)},I:a=>{Cd==a&&(Cd=0);Cd===rd[a]&&(Cd=null);typeof P=="object"&&P.Pi(rd[a].Kg.canvas);rd[a]?.Kg.canvas&&(rd[a].Kg.canvas.Tg=void 0);rd[a]=null},J:a=>{Cd=rd[a];h.ctx=T=Cd?.Kg;return!a||T?0:-5},rb:(a,b)=>{var c=0,d=0,e;for(e of qe()){var f=b+c;u[a+d>>2]=f;c+=A(e,r,f,Infinity)+1;d+=4}return 0},sb:(a,b)=>{var c=qe();u[a>>2]=c.length;a=0;for(var d of c)a+=Oa(d)+1;u[b>>2]=a;return 0},Ha:a=>{ja=a;dc(a)},j:function(a){try{var b=K(a);Lb(b);return 0}catch(c){if(typeof M==
"undefined"||c.name!=="ErrnoError")throw c;return c.ig}},x:function(a,b,c,d){try{a:{var e=K(a);a=b;for(var f,g=b=0;g<c;g++){var m=u[a>>2],k=u[a+4>>2];a+=8;var p=e,q=m,v=k,C=f,D=n;if(v<0||C<0)throw new B(28);if(p.fd===null)throw new B(8);if((p.flags&2097155)===1)throw new B(8);if(F(p.node.mode))throw new B(31);if(!p.cg.read)throw new B(28);var G=typeof C!="undefined";if(!G)C=p.position;else if(!p.seekable)throw new B(70);var J=p.cg.read(p,D,q,v,C);G||(p.position+=J);var I=J;if(I<0){var S=-1;break a}b+=
I;if(I<k)break;typeof f!="undefined"&&(f+=I)}S=b}u[d>>2]=S;return 0}catch(oa){if(typeof M=="undefined"||oa.name!=="ErrnoError")throw oa;return oa.ig}},eb:function(a,b,c,d){b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;var e=K(a);Mb(e,b,c);y[d>>3]=BigInt(e.position);e.Lg&&b===0&&c===0&&(e.Lg=null);return 0}catch(f){if(typeof M=="undefined"||f.name!=="ErrnoError")throw f;return f.ig}},fb:function(a){try{var b=K(a);return b.cg?.Yg?.(b)}catch(c){if(typeof M=="undefined"||
c.name!=="ErrnoError")throw c;return c.ig}},w:function(a,b,c,d){try{a:{var e=K(a);a=b;for(var f,g=b=0;g<c;g++){var m=u[a>>2],k=u[a+4>>2];a+=8;var p=Nb(e,n,m,k,f);if(p<0){var q=-1;break a}b+=p;if(p<k)break;typeof f!="undefined"&&(f+=p)}q=b}u[d>>2]=q;return 0}catch(v){if(typeof M=="undefined"||v.name!=="ErrnoError")throw v;return v.ig}},$a:dc,Ua:(a,b)=>Ia(r.subarray(a,a+b))};
function Le(a=[]){var b=Ie;a.unshift(ba);var c=a.length,d=Oc((c+1)*4),e=d,f;for(f of a)u[e>>2]=Pc(f),e+=4;u[e>>2]=0;try{var g=b(c,d);ja=g;dc(g)}catch(m){cc(m)}}
async function Me(){var a=aa;if(h.preRun)for(typeof h.preRun=="function"&&(h.preRun=[h.preRun]);h.preRun.length;)ya();ua(xa);bb>0&&await new Promise(c=>cb=c);var b=h.setStatus;b&&(b("Running..."),await new Promise(c=>setTimeout(c,1)),setTimeout(b,1,""));if(!ia){h.noFSInit||ob||Ob();Ne.Df();pb=!1;h.onRuntimeInitialized?.();h.noInitialRun||Le(a);if(h.postRun)for(typeof h.postRun=="function"&&(h.postRun=[h.postRun]);h.postRun.length;)wa();ua(va)}}var Ne;
(async function(){function a(c){c=Ne=c.exports;Ie=h._main=c.Ef;ye=h._SDL_free=c.Ff;h._free=c.Gf;Rd=h._malloc=c.Hf;ue=h._SDL_malloc=c.Jf;h._SDL_calloc=c.Kf;te=h._Emscripten_force_free=c.Lf;h._SDL_realloc=c.Mf;h._CallSDLEmscriptenMainFunction=c.Nf;ze=h._Emscripten_HandlePointerEnter=c.Of;Ae=h._Emscripten_HandlePointerLeave=c.Pf;Be=h._Emscripten_HandlePointerGeneric=c.Qf;xe=h._Emscripten_HandleMouseButtonUpGlobal=c.Rf;Ce=h._Emscripten_SendDragEvent=c.Sf;Fe=h._Emscripten_SendDragCompleteEvent=c.Tf;De=
h._Emscripten_SendDragTextEvent=c.Uf;Ee=h._Emscripten_SendDragFileEvent=c.Vf;we=h._Emscripten_HandleLockKeysCheck=c.Wf;He=h._Emscripten_SendSystemThemeChangedEvent=c.Xf;Ge=h._requestFullscreenThroughSDL=c.Yf;Je=c.Zf;Rc=c._f;Oc=c.$f;Qc=c.ag;la=c.Cf;R=c.If;ka();return Ne}var b={a:Ke};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});pa??=h.locateFile?h.locateFile("playground_nirvana.wasm",da):da+"playground_nirvana.wasm";return function(c){return a(c.instance)}(await sa(b))})().then(()=>
Me());
