var h;h||=typeof Module != 'undefined' ? Module : {};h.expectedDataFileDownloads||(h.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a=typeof ENVIRONMENT_IS_WASM_WORKER!="undefined"&&ENVIRONMENT_IS_WASM_WORKER;typeof ENVIRONMENT_IS_PTHREAD!="undefined"&&ENVIRONMENT_IS_PTHREAD||a||async function(b){async function c(k,p){h.dataFileDownloads||(h.dataFileDownloads={});try{var q=await fetch(k)}catch(I){throw Error(`Network Error: ${k}`,{e:I});}if(!q.ok)throw Error(`${q.status}: ${q.url}`);var v=[];p=Number(q.headers.get("Content-Length")||p);var C=0;h.setStatus&&h.setStatus("Downloading data...");for(q=q.body.getReader();;){var D;
({done:D,value:F}=await q.read());if(D)break;v.push(F);C+=F.length;h.dataFileDownloads[k]={loaded:C,total:p};var F=D=0;for(var J of Object.values(h.dataFileDownloads))D+=J.loaded,F+=J.total;h.setStatus&&h.setStatus(`Downloading data... (${D}/${F})`)}k=new Uint8Array(v.map(I=>I.length).reduce((I,S)=>I+S,0));J=0;for(let I of v)k.set(I,J),J+=I.length;return k.buffer}async function d(k){k.addRunDependency("datafile_/Users/shenyiwen/projects/fountain2/bin/emscripten/nirvana/playground_nirvana.data");k.preloadResults||
(k.preloadResults={});k.preloadResults["/Users/shenyiwen/projects/fountain2/bin/emscripten/nirvana/playground_nirvana.data"]={hj:!1};m||=await g;await async function(p){if(!p)throw Error("Loading data file failed.");if(p.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+p.constructor.name);p=new Uint8Array(p);for(var q of b.files)k.FS_createDataFile(q.filename,null,p.subarray(q.start,q.end),!0,!0,!0);k.removeRunDependency("datafile_/Users/shenyiwen/projects/fountain2/bin/emscripten/nirvana/playground_nirvana.data")}(m)}
typeof window==="object"?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):typeof process==="undefined"&&typeof location!=="undefined"&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var e=h.locateFile?h.locateFile("playground_nirvana.data",""):"playground_nirvana.data",f=b.remote_package_size,g,m=h.getPreloadedPackage&&h.getPreloadedPackage(e,f);m||(g=c(e,f));h.FS_createPath?d(h):(h.preRun||(h.preRun=
[]),h.preRun.push(d))}({files:[{filename:"/assets.dat",start:0,end:804245}],remote_package_size:804245})})();var aa=[],ba="./this.program",ca=globalThis.document?.currentScript?.src,da="",ea;try{da=(new URL(".",ca)).href}catch{}ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),l=console.error.bind(console),ha,ia=!1,ja;
function ka(){var a=la.buffer;n=new Int8Array(a);ma=new Int16Array(a);r=new Uint8Array(a);na=new Uint16Array(a);t=new Int32Array(a);u=new Uint32Array(a);w=new Float32Array(a);x=new Float64Array(a);y=new BigInt64Array(a);new BigUint64Array(a)}function z(a){h.onAbort?.(a);a=`Aborted(${a})`;l(a);ia=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var pa;
async function qa(a){if(!ha)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==pa&&ha)a=new Uint8Array(ha);else throw"both async and sync fetching of the wasm failed";return a}async function ra(a,b){try{var c=await qa(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),z(d)}}
async function sa(a){var b=pa;if(!ha)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return ra(b,a)}class ta{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ma,t,y,n,w,x,na,u,r,ua=a=>{for(;a.length>0;)a.shift()(h)},va=[],wa=()=>{var a=h.postRun.shift();va.push(a)},xa=[],ya=()=>{var a=h.preRun.shift();xa.push(a)},za=!0;function Aa(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":n[a]=b;break;case "i8":n[a]=b;break;case "i16":ma[a>>1]=b;break;case "i32":t[a>>2]=b;break;case "i64":y[a>>3]=BigInt(b);break;case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":u[a>>2]=b;break;default:z(`invalid type for setValue: ${c}`)}}
class Ba{constructor(a){this.nh=a-24}init(a,b){u[this.nh+16>>2]=0;u[this.nh+4>>2]=a;u[this.nh+8>>2]=b}}
var Ca=0,Da=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ea=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=Da(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Fa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ga=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],
Ha=()=>a=>(crypto.getRandomValues(a),0),Ia=a=>(Ia=Ha())(a),Ja=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c=c.charAt(0)==="/"}b=Da(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ka=new TextDecoder,La=(a,b,c)=>{for(c=b+c;a[b]&&!(b>=c);)++b;return b},Ma=a=>{var b=La(a,0);return Ka.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},
Na=[],Oa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},A=(a,b,c,d)=>{if(!(d>0))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(c>=d)break;b[c++]=g}else if(g<=2047){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(g<=65535){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=
128|g&63;f++}}b[c]=0;return c-e},Pa=a=>{var b=Array(Oa(a)+1);a=A(a,b,0,b.length);b.length=a;return b},Qa=[];function Ra(a,b){Qa[a]={input:[],output:[],Eg:b};Sa(a,Ta)}
var Ta={open(a){var b=Qa[a.node.bh];if(!b)throw new B(43);a.gg=b;a.seekable=!1},close(a){a.gg.Eg.Yg(a.gg)},Yg(a){a.gg.Eg.Yg(a.gg)},read(a,b,c,d){if(!a.gg||!a.gg.Eg.Zh)throw new B(60);for(var e=0,f=0;f<d;f++){try{var g=a.gg.Eg.Zh(a.gg)}catch(m){throw new B(29);}if(g===void 0&&e===0)throw new B(6);if(g===null||g===void 0)break;e++;b[c+f]=g}e&&(a.node.Gg=Date.now());return e},write(a,b,c,d){if(!a.gg||!a.gg.Eg.Lh)throw new B(60);try{for(var e=0;e<d;e++)a.gg.Eg.Lh(a.gg,b[c+e])}catch(f){throw new B(29);
}d&&(a.node.qg=a.node.ng=Date.now());return e}},Ua={Zh(){a:{if(!Na.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}Na=Pa(a)}a=Na.shift()}return a},Lh(a,b){b===null||b===10?(fa(Ma(a.output)),a.output=[]):b!=0&&a.output.push(b)},Yg(a){a.output?.length>0&&(fa(Ma(a.output)),a.output=[])},Ei(){return{Xi:25856,Zi:5,Wi:191,Yi:35387,Vi:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Fi(){return 0},Gi(){return[24,
80]}},Va={Lh(a,b){b===null||b===10?(l(Ma(a.output)),a.output=[]):b!=0&&a.output.push(b)},Yg(a){a.output?.length>0&&(l(Ma(a.output)),a.output=[])}},E={Bg:null,Dg(){return E.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||(c&61440)===4096)throw new B(63);E.Bg||(E.Bg={dir:{node:{tg:E.ag.tg,Fg:E.ag.Fg,$g:E.ag.$g,mh:E.ag.mh,di:E.ag.di,rh:E.ag.rh,ph:E.ag.ph,oh:E.ag.oh,qh:E.ag.qh},stream:{Ag:E.bg.Ag}},file:{node:{tg:E.ag.tg,Fg:E.ag.Fg},stream:{Ag:E.bg.Ag,read:E.bg.read,write:E.bg.write,
Ih:E.bg.Ih,bi:E.bg.bi}},link:{node:{tg:E.ag.tg,Fg:E.ag.Fg,Lg:E.ag.Lg},stream:{}},Wh:{node:{tg:E.ag.tg,Fg:E.ag.Fg},stream:Wa}});c=Xa(a,b,c,d);G(c.mode)?(c.ag=E.Bg.dir.node,c.bg=E.Bg.dir.stream,c.eg={}):(c.mode&61440)===32768?(c.ag=E.Bg.file.node,c.bg=E.Bg.file.stream,c.mg=0,c.eg=E.si??(E.si=new Uint8Array(0))):(c.mode&61440)===40960?(c.ag=E.Bg.link.node,c.bg=E.Bg.link.stream):(c.mode&61440)===8192&&(c.ag=E.Bg.Wh.node,c.bg=E.Bg.Wh.stream);c.Gg=c.qg=c.ng=Date.now();a&&(a.eg[b]=c,a.Gg=a.qg=a.ng=c.Gg);
return c},ag:{tg(a){var b={};b.ri=(a.mode&61440)===8192?a.id:1;b.Ci=a.id;b.mode=a.mode;b.Li=1;b.uid=0;b.yi=0;b.bh=a.bh;G(a.mode)?b.size=4096:(a.mode&61440)===32768?b.size=a.mg:(a.mode&61440)===40960?b.size=a.link.length:b.size=0;b.Gg=new Date(a.Gg);b.qg=new Date(a.qg);b.ng=new Date(a.ng);b.ji=4096;b.ki=Math.ceil(b.size/b.ji);return b},Fg(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.mg!=b&&(c=a.eg,a.eg=new Uint8Array(b),a.eg.set(c.subarray(0,
Math.min(b,a.mg))),a.mg=b))},$g(){E.xh||(E.xh=new B(44),E.xh.stack="<generic error, no stack>");throw E.xh;},mh(a,b,c,d){return E.createNode(a,b,c,d)},di(a,b,c){try{var d=Ya(b,c)}catch(f){}if(d){if(G(a.mode))for(var e in d.eg)throw new B(55);Za(d)}delete a.parent.eg[a.name];b.eg[c]=a;a.name=c;b.ng=b.qg=a.parent.ng=a.parent.qg=Date.now()},rh(a,b){delete a.eg[b];a.ng=a.qg=Date.now()},ph(a,b){var c=Ya(a,b),d;for(d in c.eg)throw new B(55);delete a.eg[b];a.ng=a.qg=Date.now()},oh(a){return[".","..",...Object.keys(a.eg)]},
qh(a,b,c){a=E.createNode(a,b,41471,0);a.link=c;return a},Lg(a){if((a.mode&61440)!==40960)throw new B(28);return a.link}},bg:{read(a,b,c,d,e){if(e>=a.node.mg)return 0;d=Math.min(a.node.mg-e,d);b.set(a.node.eg.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===n.buffer&&(f=!1);if(!d)return 0;a=a.node;a.qg=a.ng=Date.now();if(f)a.eg=b.subarray(c,c+d),a.mg=d;else if(a.mg===0&&e===0)a.eg=b.slice(c,c+d),a.mg=d;else{f=e+d;var g=a.eg.length;g>=f||(f=Math.max(f,g*(g<1048576?2:1.125)>>>0),g&&(f=Math.max(f,
256)),g=a.eg.subarray(0,a.mg),a.eg=new Uint8Array(f),a.eg.set(g));a.eg.set(b.subarray(c,c+d),e);a.mg=Math.max(a.mg,e+d)}return d},Ag(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&61440)===32768&&(b+=a.node.mg);if(b<0)throw new B(28);return b},Ih(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new B(43);a=a.node.eg;if(e&2||a.buffer!==n.buffer){d=!0;z();e=void 0;if(!e)throw new B(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);n.set(a,e)}}else d=
!1,e=a.byteOffset;return{nh:e,Si:d}},bi(a,b,c,d){E.bg.write(a,b,0,d,c,!1);return 0}}},$a=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ab=async a=>{a=await ea(a);return new Uint8Array(a)},bb=0,cb=null,db=()=>{bb--;h.monitorRunDependencies?.(bb);if(bb==0&&cb){var a=cb;cb=null;a()}},eb=()=>{bb++;h.monitorRunDependencies?.(bb)},fb=[],ib=async(a,b)=>{typeof gb!="undefined"&&hb();for(var c of fb)if(c.canHandle(b))return c.handle(a,b);return a},jb=null,kb={},lb=[],mb=1,nb=null,ob=!1,pb=!0,B=class{name=
"ErrnoError";constructor(a){this.hg=a}},qb=class{shared={};node=null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},rb=class{ag={};bg={};Qg=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Dg=a.Dg;this.id=mb++;this.name=b;this.mode=c;this.bh=d;this.Gg=this.qg=this.ng=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&
146)===146}set write(a){a?this.mode|=146:this.mode&=-147}get Ii(){return G(this.mode)}get Hi(){return(this.mode&61440)===8192}};
function H(a,b={}){if(!a)throw new B(44);b.Ch??(b.Ch=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(m=>!!m);for(var d=jb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if(a[f]!==".")if(a[f]==="..")if(e=Fa(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Ea(e+"/"+a[f]);try{d=Ya(d,a[f])}catch(m){if(m?.hg===44&&g&&b.Mi)return{path:e};throw m;}!d.Qg||g&&!b.Ch||(d=d.Qg.root);if((d.mode&61440)===40960&&(!g||b.Pg)){if(!d.ag.Lg)throw new B(52);
d=d.ag.Lg(d);d.charAt(0)==="/"||(d=Fa(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new B(32);}function sb(a){for(var b;;){if(a===a.parent)return a=a.Dg.ai,b?a[a.length-1]!=="/"?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function tb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%nb.length}
function Za(a){var b=tb(a.parent.id,a.name);if(nb[b]===a)nb[b]=a.Rg;else for(b=nb[b];b;){if(b.Rg===a){b.Rg=a.Rg;break}b=b.Rg}}function Ya(a,b){var c=G(a.mode)?(c=ub(a,"x"))?c:a.ag.$g?0:2:54;if(c)throw new B(c);for(c=nb[tb(a.id,b)];c;c=c.Rg){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ag.$g(a,b)}function Xa(a,b,c,d){a=new rb(a,b,c,d);b=tb(a.parent.id,a.name);a.Rg=nb[b];return nb[b]=a}function G(a){return(a&61440)===16384}
function ub(a,b){return pb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function vb(a,b){if(!G(a.mode))return 54;try{return Ya(a,b),20}catch(c){}return ub(a,"wx")}function wb(a,b,c){try{var d=Ya(a,b)}catch(e){return e.hg}if(a=ub(a,"wx"))return a;if(c){if(!G(d.mode))return 54;if(d===d.parent||sb(d)==="/")return 10}else if(G(d.mode))return 31;return 0}function xb(a,b){if(!a)throw new B(b);return a}
function K(a){a=lb[a];if(!a)throw new B(8);return a}function yb(a,b=-1){a=Object.assign(new qb,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!lb[b])break a;throw new B(33);}a.fd=b;return lb[b]=a}function zb(a,b=-1){a=yb(a,b);a.bg?.fj?.(a);return a}function Ab(a,b){var c=void 0,d=c?null:a;c??=a.ag.Fg;xb(c,63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new B(22);throw e;}}var Wa={open(a){a.bg=kb[a.node.bh].bg;a.bg.open?.(a)},Ag(){throw new B(70);}};function Sa(a,b){kb[a]={bg:b}}
function Bb(a,b){var c=b==="/";if(c&&jb)throw new B(10);if(!c&&b){var d=H(b,{Ch:!1});b=d.path;d=d.node;if(d.Qg)throw new B(10);if(!G(d.mode))throw new B(54);}b={type:a,nj:{},ai:b,Ki:[]};a=a.Dg(b);a.Dg=b;b.root=a;c?jb=a:d&&(d.Qg=b,d.Dg&&d.Dg.Ki.push(b))}function Cb(a,b,c){var d=H(a,{parent:!0}).node;a=Ga(a);if(!a)throw new B(28);if(a==="."||a==="..")throw new B(20);var e=vb(d,a);if(e)throw new B(e);if(!d.ag.mh)throw new B(63);return d.ag.mh(d,a,b,c)}
function Db(a,b=438){return Cb(a,b&4095|32768,0)}function L(a,b=511){return Cb(a,b&1023|16384,0)}function Eb(a,b,c){typeof c=="undefined"&&(c=b,b=438);return Cb(a,b|8192,c)}function Fb(a,b){if(!Ja(a))throw new B(44);var c=H(b,{parent:!0}).node;if(!c)throw new B(44);b=Ga(b);var d=vb(c,b);if(d)throw new B(d);if(!c.ag.qh)throw new B(63);c.ag.qh(c,b,a)}
function Gb(a){var b=H(a,{parent:!0}).node;a=Ga(a);var c=Ya(b,a),d=wb(b,a,!0);if(d)throw new B(d);if(!b.ag.ph)throw new B(63);if(c.Qg)throw new B(10);b.ag.ph(b,a);Za(c)}function Hb(a){var b=H(a,{parent:!0}).node;if(!b)throw new B(44);a=Ga(a);var c=Ya(b,a),d=wb(b,a,!1);if(d)throw new B(d);if(!b.ag.rh)throw new B(63);if(c.Qg)throw new B(10);b.ag.rh(b,a);Za(c)}function Ib(a,b){a=H(a,{Pg:!b}).node;return xb(a.ag.tg,63)(a)}
function Jb(a,b){a=typeof a=="string"?H(a,{Pg:!0}).node:a;Ab(a,{mode:b&4095|a.mode&-4096,ng:Date.now(),ej:void 0})}
function Kb(a,b,c=438){if(a==="")throw new B(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var f=H(a,{Pg:!(b&131072),Mi:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new B(20);}else{if(e)throw new B(31);d=Cb(a,c|511,0);f=!0}if(!d)throw new B(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&!G(d.mode))throw new B(54);
if(!f&&(d?(d.mode&61440)===40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=G(d.mode)&&(e!=="r"||b&576)?31:ub(d,e)):e=44,e))throw new B(e);if(b&512&&!f){e=d;e=typeof e=="string"?H(e,{Pg:!0}).node:e;if(G(e.mode))throw new B(31);if((e.mode&61440)!==32768)throw new B(28);if(a=ub(e,"w"))throw new B(a);Ab(e,{size:0,timestamp:Date.now()})}b=yb({node:d,path:sb(d),flags:b&-131713,seekable:!0,position:0,bg:d.bg,Qi:[],error:!1});b.bg.open&&b.bg.open(b);f&&Jb(d,c&511);return b}
function Lb(a){if(a.fd===null)throw new B(8);a.Kg&&(a.Kg=null);try{a.bg.close&&a.bg.close(a)}catch(b){throw b;}finally{lb[a.fd]=null}a.fd=null}function Mb(a,b,c){if(a.fd===null)throw new B(8);if(!a.seekable||!a.bg.Ag)throw new B(70);if(c!=0&&c!=1&&c!=2)throw new B(28);a.position=a.bg.Ag(a,b,c);a.Qi=[];return a.position}
function Nb(a,b,c,d,e,f){if(d<0||e<0)throw new B(28);if(a.fd===null)throw new B(8);if((a.flags&2097155)===0)throw new B(8);if(G(a.node.mode))throw new B(31);if(!a.bg.write)throw new B(28);a.seekable&&a.flags&1024&&Mb(a,0,2);var g=typeof e!="undefined";if(!g)e=a.position;else if(!a.seekable)throw new B(70);b=a.bg.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Ob(){var a,b,c;ob=!0;a??=h.stdin;b??=h.stdout;c??=h.stderr;a?Pb("/dev","stdin",a):Fb("/dev/tty","/dev/stdin");b?Pb("/dev","stdout",null,b):Fb("/dev/tty","/dev/stdout");c?Pb("/dev","stderr",null,c):Fb("/dev/tty1","/dev/stderr");Kb("/dev/stdin",0);Kb("/dev/stdout",1);Kb("/dev/stderr",1)}function Qb(a,b){a=typeof a=="string"?a:sb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ea(a+"/"+c);try{L(d)}catch(e){if(e.hg!=20)throw e;}a=d}}return d}
function Rb(a,b,c,d){a=Ea((typeof a=="string"?a:sb(a))+"/"+b);return Db(a,$a(c,d))}function Sb(a,b,c,d,e,f){var g=b;a&&(a=typeof a=="string"?a:sb(a),g=b?Ea(a+"/"+b):a);a=$a(d,e);g=Db(g,a);c&&(typeof c=="string"&&(c=Pa(c)),c.subarray||(c=new Uint8Array(c)),Jb(g,a|146),b=Kb(g,577),Nb(b,c,0,c.length,0,f),Lb(b),Jb(g,a))}
function Pb(a,b,c,d){a=Ea((typeof a=="string"?a:sb(a))+"/"+b);b=$a(!!c,!!d);Pb.$h??(Pb.$h=64);var e=Pb.$h++<<8|0;Sa(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,m,k){for(var p=0,q=0;q<k;q++){try{var v=c()}catch(C){throw new B(29);}if(v===void 0&&p===0)throw new B(6);if(v===null||v===void 0)break;p++;g[m+q]=v}p&&(f.node.Gg=Date.now());return p},write(f,g,m,k){for(var p=0;p<k;p++)try{d(g[m+p])}catch(q){throw new B(29);}k&&(f.node.qg=f.node.ng=Date.now());return p}});return Eb(a,
b,e)}function Tb(a){if(!(a.Hi||a.Ii||a.link||a.eg))if(globalThis.XMLHttpRequest)z("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.eg=(void 0)(a.url)}catch(b){throw new B(29);}}
function Ub(a,b,c,d,e){class f{Cg=!1;jg=[];kg=void 0;Vg=0;Og=0;get(p){if(!(p>this.length-1||p<0)){var q=p%this.Zg;return this.kg(p/this.Zg|0)[q]}}zi(p){this.kg=p}Xg(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);p.status>=200&&p.status<300||p.status===304||z("Couldn't load "+c+". Status: "+p.status);var q=Number(p.getResponseHeader("Content-length")),v,C=(v=p.getResponseHeader("Accept-Ranges"))&&v==="bytes";p=(v=p.getResponseHeader("Content-Encoding"))&&v==="gzip";var D=1048576;C||(D=
q);var F=this;F.zi(J=>{var I=J*D,S=(J+1)*D-1;S=Math.min(S,q-1);if(typeof F.jg[J]=="undefined"){var oa=F.jg;I>S&&z(`invalid range (${I}, ${S}) or no bytes requested!`);S>q-1&&z(`only ${q} bytes available! programmer error!`);var O=new XMLHttpRequest;O.open("GET",c,!1);q!==D&&O.setRequestHeader("Range","bytes="+I+"-"+S);O.responseType="arraybuffer";O.overrideMimeType&&O.overrideMimeType("text/plain; charset=x-user-defined");O.send(null);O.status>=200&&O.status<300||O.status===304||z("Couldn't load "+
c+". Status: "+O.status);I=O.response!==void 0?new Uint8Array(O.response||[]):Pa(O.responseText??"");oa[J]=I}typeof F.jg[J]=="undefined"&&z("doXHR failed!");return F.jg[J]});if(p||!q)D=q=1,D=q=this.kg(0).length,fa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Vg=q;this.Og=D;this.Cg=!0}get length(){this.Cg||this.Xg();return this.Vg}get Zg(){this.Cg||this.Xg();return this.Og}}if(globalThis.XMLHttpRequest){z("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var g=new f;var m=void 0}else m=c,g=void 0;var k=Rb(a,b,d,e);g?k.eg=g:m&&(k.eg=null,k.url=m);Object.defineProperties(k,{mg:{get:function(){return this.eg.length}}});a={};for(let [p,q]of Object.entries(k.bg))a[p]=(...v)=>{Tb(k);return q(...v)};a.read=(p,q,v,C,D)=>{Tb(k);p=p.node.eg;if(D>=p.length)q=0;else{C=Math.min(p.length-D,C);if(p.slice)for(var F=0;F<C;F++)q[v+F]=p[D+F];else for(F=0;F<C;F++)q[v+F]=p.get(D+F);q=C}return q};a.Ih=()=>{Tb(k);z();throw new B(48);};k.bg=a;return k}
var M={},N=(a,b)=>a?Ka.decode(r.subarray(a,La(r,a,b))):"";function Vb(a,b,c){if(b.charAt(0)==="/")return b;a=a===-100?"/":K(a).path;if(b.length==0){if(!c)throw new B(44);return a}return a+"/"+b}
function Wb(a,b){u[a>>2]=b.ri;u[a+4>>2]=b.mode;u[a+8>>2]=b.Li;u[a+12>>2]=b.uid;u[a+16>>2]=b.yi;u[a+20>>2]=b.bh;y[a+24>>3]=BigInt(b.size);t[a+32>>2]=4096;t[a+36>>2]=b.ki;var c=b.Gg.getTime(),d=b.qg.getTime(),e=b.ng.getTime();y[a+40>>3]=BigInt(Math.floor(c/1E3));u[a+48>>2]=c%1E3*1E3*1E3;y[a+56>>3]=BigInt(Math.floor(d/1E3));u[a+64>>2]=d%1E3*1E3*1E3;y[a+72>>3]=BigInt(Math.floor(e/1E3));u[a+80>>2]=e%1E3*1E3*1E3;y[a+88>>3]=BigInt(b.Ci);return 0}
var Xb=void 0,Yb=()=>{var a=t[+Xb>>2];Xb+=4;return a},Zb=0,$b=[0,31,60,91,121,152,182,213,244,274,305,335],ac=[0,31,59,90,120,151,181,212,243,273,304,334],bc={},cc=a=>{if(!(a instanceof ta||a=="unwind"))throw a;},dc=a=>{ja=a;za||Zb>0||(h.onExit?.(a),ia=!0);throw new ta(a);},ec=()=>{if(!(za||Zb>0))try{var a=ja;ja=a;dc(a)}catch(b){cc(b)}},fc=a=>{if(!ia)try{a()}catch(b){cc(b)}finally{ec()}},hc=[],ic=(a,b)=>{hc.length=0;for(var c;c=r[a++];){var d=c!=105;d&=c!=112;b+=d&&b%8?4:0;hc.push(c==112?u[b>>2]:
c==106?y[b>>3]:c==105?t[b>>2]:x[b>>3]);b+=d?8:4}return hc},kc=(a,b,c)=>{b=ic(b,c);return jc[a](...b)},uc=(a,b)=>{lc=a;mc=b;if(!nc)return 1;oc||=!0;if(a==0)pc=function(){setTimeout(qc,Math.max(0,rc+b-performance.now())|0)};else if(a==1)pc=function(){sc(qc)};else{if(!tc)if(globalThis.scheduler)tc=scheduler.postTask.bind(scheduler);else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);tc=d=>{c.push(d);postMessage("setimmediate","*")}}pc=function(){tc(qc)}}return 0},
Dc=(a,b,c,d,e)=>{function f(){return g<vc?(ec(),!1):!0}nc=a;wc=d;var g=vc;oc=!1;qc=function(){if(!ia)if(xc.length>0){var m=xc.shift();m.ij(m.Ti);if(yc){var k=yc,p=k%1==0?k-1:Math.floor(k);yc=m.aj?p:(8*k+(p+.5))/9}h.setStatus&&(m=h.statusMessage||"Please wait...",k=yc??0,p=zc.gj??0,k?k<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(m):h.setStatus(""));f()&&setTimeout(qc,0)}else if(f())if(Ac=Ac+1|0,lc==1&&mc>1&&Ac%mc!=0)pc();else{lc==0&&(rc=performance.now());a:if(!ia){for(m of Bc)if(m()===
!1)break a;fc(a);for(k of Cc)k()}f()&&pc()}};e||(b>0?uc(0,1E3/b):uc(1,1),pc());if(c)throw"unwind";},oc=!1,pc=null,vc=0,nc=null,wc=0,lc=0,mc=0,Ac=0,xc=[],Bc=[],Cc=[];function Ec(){pc=null;vc++}var Fc=0;function sc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(Fc===0)Fc=b+1E3/60;else for(;b+2>=Fc;)Fc+=1E3/60;setTimeout(a,Math.max(Fc-b,0))}}var zc={},rc,qc,tc,yc;function Gc(a){var b=P.og[a];b.target.removeEventListener(b.lg,b.Yh,b.wg);P.og.splice(a,1)}
function Hc(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of P.Hg)if(e.Nh==a&&d(e.Uh,c))return;P.Hg.push({Nh:a,ci:b,Uh:c});P.Hg.sort((f,g)=>f.ci-g.ci)}function Ic(a){P.Hg=P.Hg.filter(b=>b.Nh!=a)}function Jc(){return navigator.userActivation?navigator.userActivation.isActive:P.Fh&&P.mi.Th}function Kc(){if(Jc()){var a=P.Hg;P.Hg=[];for(var b of a)b.Nh(...b.Uh)}}
function Lc(a){if(!a.target)return-4;if(a.pg)a.Yh=function(c){++P.Fh;P.mi=a;Kc();a.zg(c);Kc();--P.Fh},a.target.addEventListener(a.lg,a.Yh,a.wg),P.og.push(a);else for(var b=0;b<P.og.length;++b)P.og[b].target==a.target&&P.og[b].lg==a.lg&&Gc(b--);return 0}function Mc(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var P={Ui:0,Eh:0,Gh:0,lj:0,Sh:0,Ph:0,Bh:0,cj:0,Jh:0,bj:0,Dh:0,Kh:0,Rh:0,tj:0,pj(){for(;P.og.length;)Gc(P.og.length-1);P.Hg=[]},Fh:0,Hg:[],og:[],Oi:(a,b)=>{for(var c=0;c<P.og.length;++c)P.og[c].target!=a||b&&b!=P.og[c].lg||Gc(c--)},qj(a){var b=!1;for(let c=0;c<P.og.length;++c){let d=P.og[c];d.target===a.target&&d.sg===a.sg&&d.pg===a.pg&&d.xg===a.xg&&(Gc(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Nc=[0,document,window],Q=a=>{a=
a>2?N(a):a;return Nc[a]||document.querySelector(a)},Pc=a=>{var b=Oa(a)+1,c=Oc(b);A(a,r,c,b);return c},Sc=a=>{var b=Qc(),c=Oc(8),d=c+4;a=Pc(a.id);if(a=Q(a))t[c>>2]=a.width,t[d>>2]=a.height;c=[t[c>>2],t[d>>2]];Rc(b);return c},Tc=(a,b,c)=>{a=Q(a);if(!a)return-4;a.width=b;a.height=c;return 0},Uc=(a,b,c)=>{if(a.$i){var d=Qc();a=Pc(a.id);Tc(a,b,c);Rc(d)}else a.width=b,a.height=c},Vc={},Xc=a=>{function b(){Wc()||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),Uc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,k||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=k,a.style.paddingLeft=p,a.style.paddingRight=q,a.style.paddingTop=v,a.style.paddingBottom=C,a.style.marginLeft=D,a.style.marginRight=F,a.style.marginTop=J,a.style.marginBottom=I,document.body.style.margin=S,document.documentElement.style.overflow=oa,document.body.scroll=O,a.style.imageRendering=ve,a.Sg&&a.Sg.Jg.viewport(0,0,d,e),Vc.eh&&R.get(Vc.eh)(37,
0,Vc.Vh))}var c=Sc(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,k=document.body.style.backgroundColor,p=a.style.paddingLeft,q=a.style.paddingRight,v=a.style.paddingTop,C=a.style.paddingBottom,D=a.style.marginLeft,F=a.style.marginRight,J=a.style.marginTop,I=a.style.marginBottom,S=document.body.style.margin,oa=document.documentElement.style.overflow,O=document.body.scroll,ve=a.style.imageRendering;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},Yc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Zc=a=>Nc.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},$c=(a,b)=>{if(b.Mh!=0||b.th!=0){Xc(a);var c=b.Pi?innerWidth:screen.width,d=b.Pi?innerHeight:screen.height,e=Zc(a),f=e.width;e=e.height;var g=Sc(a),m=g[0];g=g[1];b.Mh==3?(Yc(a,(d-e)/2,(c-f)/2),c=f,d=e):b.Mh==2&&(c*g<m*d?(f=g*c/m,Yc(a,(d-f)/2,0),d=f):(f=m*d/g,Yc(a,0,(c-f)/2),c=f));var k;(k=a.style).backgroundColor||(k.backgroundColor=
"black");let p;(p=document.body.style).backgroundColor||(p.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";b.xi==1&&(a.style.imageRendering="optimizeSpeed",a.style.imageRendering="-moz-crisp-edges",a.style.imageRendering="-o-crisp-edges",a.style.imageRendering="-webkit-optimize-contrast",a.style.imageRendering="optimize-contrast",a.style.imageRendering="crisp-edges",a.style.imageRendering="pixelated");k=b.th==2?devicePixelRatio:1;b.th!=0&&(c=c*k|0,d=d*k|0,Uc(a,c,d),a.Sg&&a.Sg.Jg.viewport(0,
0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return P.fullscreenEnabled()?-3:-1;Vc=b;b.eh&&R.get(b.eh)(37,0,b.Vh);return 0},ad=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0};
function Wc(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}
var bd=a=>{var b=Wc(),c=!!b;n[a]=c;n[a+1]=P.fullscreenEnabled();var d=c?b:P.Ni,e=d?.id??"";A(Mc(d),r,a+2,128);A(e,r,a+130,128);t[a+260>>2]=d?.clientWidth??0;t[a+264>>2]=d?.clientHeight??0;t[a+268>>2]=screen.width;t[a+272>>2]=screen.height;c&&(P.Ni=b)},cd=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+c*8+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+c*8+528>>3]=typeof b.buttons[c]=="object"?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)n[a+c+1040]=typeof b.buttons[c]==
"object"?b.buttons[c].pressed:b.buttons[c]==1;n[a+1104]=b.connected;t[a+1108>>2]=b.index;t[a+8>>2]=b.axes.length;t[a+12>>2]=b.buttons.length;A(b.id,r,a+1112,64);A(b.mapping,r,a+1176,64)},dd=a=>{setTimeout(()=>{fc(a)},1E4)},ed=!1,fd=[];
function hb(){function a(){ed=document.pointerLockElement===h.canvas}if(!gd){gd=!0;fb.push({canHandle:c=>!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:hd(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:hd(d)}));var f=URL.createObjectURL(e);return new Promise((g,m)=>{var k=new Image;k.onload=()=>{var p=document.createElement("canvas");p.width=k.width;p.height=k.height;p.getContext("2d").drawImage(k,0,0);URL.revokeObjectURL(f);
g(c)};k.onerror=()=>{l(`Image ${f} could not be decoded`);m()};k.src=f})}});fb.push({canHandle:c=>!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,m=URL.createObjectURL(new Blob([c],{type:hd(d)})),k=new Audio;k.addEventListener("canplaythrough",()=>f(k),!1);k.onerror=()=>{if(!g){l(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var p="",q=0,v=0,C=0;C<c.length;C++)for(q=q<<
8|c[C],v+=8;v>=6;){var D=q>>v-6&63;v-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[D]}v==2?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(q&3)<<4],p+="=="):v==4&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(q&15)<<2],p+="=");k.src="data:audio/x-"+d.slice(-3)+";base64,"+p;f(k)}};k.src=m;dd(()=>{f(k)})})});var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!ed&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function jd(a){a=a.getContext("2d");if(!a)return null;h.ctx=a;fd.forEach(b=>b());hb();return a}function hd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var gb={},gd,T,kd=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");return a.getSupportedExtensions()?.filter(c=>
b.includes(c))??[]},ld=1,md=[],U=[],nd=[],od=[],pd=[],V=[],qd=[],rd=[],W=[],X=[],sd=[],td=[],ud={},vd={},wd=4,xd=0,yd=a=>{for(var b=ld++,c=a.length;c<b;c++)a[c]=null;return b},zd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=T[c](),g=f&&yd(d);f?(f.name=g,d[g]=f):Y||=1282;t[b+e*4>>2]=g}},Bd=(a,b)=>{a.Zg||(a.Zg=a.getContext,a.getContext=function(d,e){e=a.Zg(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Ad(c,b):0},Ad=(a,b)=>{var c=yd(rd),d={handle:c,
attributes:b,version:b.Ji,Jg:a};a.canvas&&(a.canvas.Sg=d);rd[c]=d;if(typeof b.Xh=="undefined"||b.Xh)if((a=d)||(a=Cd),!a.Bi){a.Bi=!0;b=a.Jg;b.mj=b.getExtension("WEBGL_multi_draw");b.wi=b.getExtension("EXT_polygon_offset_clamp");b.ui=b.getExtension("EXT_clip_control");b.Ri=b.getExtension("WEBGL_polygon_mode");b.dj=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.jj=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");a.version>=2&&(b.rg=b.getExtension("EXT_disjoint_timer_query_webgl2"));
if(a.version<2||!b.rg)b.rg=b.getExtension("EXT_disjoint_timer_query");for(var e of kd(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},Y,Cd,Dd=a=>{T.bindVertexArray(qd[a])},Ed=(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2];T.deleteVertexArray(qd[d]);qd[d]=null}},Fd=(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},Gd=[],Hd=(a,b)=>{for(var c=Gd[a],d=0;d<a;d++)c[d]=t[b+d*4>>2];T.drawBuffers(c)},Id=(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},Jd=(a,b)=>{zd(a,b,"createVertexArray",
qd)},Kd=(a,b,c,d,e,f,g,m)=>{b=U[b];if(a=T[a](b,c))d=m&&A(a.name,r,m,d),e&&(t[e>>2]=d),f&&(t[f>>2]=a.size),g&&(t[g>>2]=a.type)},Ld=(a,b)=>{u[a>>2]=b;u[a+4>>2]=(b-u[a>>2])/4294967296},Md=()=>{var a=kd(T);return a=a.concat(a.map(b=>"GL_"+b))},Nd=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:c!=0&&c!=1&&(Y||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=T.getParameter(34467);d=e?e.length:0;break;case 33309:if(Cd.version<2){Y||=1282;return}d=Md().length;break;case 33307:case 33308:if(Cd.version<
2){Y||=1280;return}d=a==33307?3:0}if(d===void 0)switch(e=T.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Y||=1280;return;case "object":if(e===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:Y||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||
e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+a*4>>2]=e[a];break;case 2:w[b+a*4>>2]=e[a];break;case 4:n[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){Y||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:Y||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:Ld(b,d);break;case 0:t[b>>
2]=d;break;case 2:w[b>>2]=d;break;case 4:n[b]=d?1:0}}else Y||=1281},Od=(a,b,c,d)=>{if(c){b=T.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(b===null)switch(a){case 35983:case 35368:a=0;break;default:Y||=1280;return}else if(b instanceof WebGLBuffer)a=b.name|0;else{Y||=1280;return}break;default:Y||=1280;return}switch(d){case 1:Ld(c,a);break;case 0:t[c>>2]=a;break;case 2:w[c>>2]=a;break;case 4:n[c]=a?1:0;break;default:z("internal emscriptenWebGLGetIndexed() error, bad type: "+
d)}}else Y||=1281},Pd=(a,b,c)=>{if(c){a=W[a];b=Cd.version<2?T.rg.getQueryObjectEXT(a,b):T.getQueryParameter(a,b);var d;typeof b=="boolean"?d=b?1:0:d=b;Ld(c,d)}else Y||=1281},Qd=(a,b,c)=>{if(c){a=T.rg.getQueryObjectEXT(W[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;t[c>>2]=d}else Y||=1281},Sd=a=>{var b=Oa(a)+1,c=Rd(b);c&&A(a,r,c,b);return c},Td=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),Ud=a=>{var b=a.dh,c=a.fi,d;if(!b){a.dh=b={};a.ei={};var e=T.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=T.getActiveUniform(a,
d);var g=f.name;f=f.size;var m=Td(g);m=m>0?g.slice(0,m):g;var k=a.Qh;a.Qh+=f;c[m]=[f,k];for(g=0;g<f;++g)b[k]=g,a.ei[k++]=m}}},Z=(a,b)=>{if(a){var c=a.dh[b];typeof c=="number"&&(a.dh[b]=c=T.getUniformLocation(a,a.ei[b]+(c>0?`[${c}]`:"")));return c}Y||=1282},Vd=(a,b,c,d)=>{if(c)if(a=U[a],Ud(a),a=T.getUniform(a,Z(a,b)),typeof a=="number"||typeof a=="boolean")switch(d){case 0:t[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+b*4>>2]=a[b];break;case 2:w[c+b*4>>2]=a[b]}else Y||=
1281},Wd=(a,b,c,d)=>{if(c)if(a=T.getVertexAttrib(a,b),b==34975)t[c>>2]=a&&a.name;else if(typeof a=="number"||typeof a=="boolean")switch(d){case 0:t[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:t[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+b*4>>2]=a[b];break;case 2:w[c+b*4>>2]=a[b];break;case 5:t[c+b*4>>2]=Math.fround(a[b])}else Y||=1281},Xd=(a,b,c)=>{Wd(a,b,c,0)},Yd=a=>(a=qd[a])?T.isVertexArray(a):0,Zd=a=>{a-=5120;return a==0?n:a==1?r:a==2?ma:a==4?t:a==6?w:a==5||a==28922||
a==28520||a==30779||a==30782?u:na},$d=(a,b,c,d,e)=>{a=Zd(a);b=d*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT*(xd||c)+wd-1&-wd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},ae=(a,b)=>{T.vertexAttribDivisor(a,b)},be=(a,b)=>{if(!P.fullscreenEnabled())return-1;a=Q(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Jc()?$c(a,b):b.pi?(Hc($c,1,[a,b]),1):-2:-3:-4},ce=()=>{try{if(navigator.getGamepads)return(P.hh=
navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},de=(a,b)=>{var c={target:Q(2),lg:"beforeunload",sg:28,xg:a,pg:b,zg:d=>{var e=R.get(b)(28,0,a);e&&=N(e);if(e)return d.preventDefault(),d.returnValue=e},wg:!0};return Lc(c)},ee=(a,b,c,d,e,f)=>{P.Bh||(P.Bh=Rd(256));a={target:Q(a),lg:f,sg:e,xg:b,pg:d,zg:g=>{var m=g.target.id??"",k=P.Bh;A(Mc(g.target),r,k+0,128);A(m,r,k+128,128);R.get(d)(e,k,b)&&g.preventDefault()},wg:c};return Lc(a)},fe=(a,b,c,d,e)=>{P.Dh||(P.Dh=Rd(276));return Lc({target:a,
lg:e,sg:19,xg:b,pg:d,zg:f=>{var g=P.Dh;bd(g);R.get(d)(19,g,b)&&f.preventDefault()},wg:c})},ge=(a,b,c,d,e)=>{P.Eh||(P.Eh=Rd(1240));b={target:Q(2),Th:!0,lg:e,sg:d,xg:a,pg:c,zg:f=>{var g=P.Eh;cd(g,f.gamepad);R.get(c)(d,g,a)&&f.preventDefault()},wg:b};return Lc(b)},he=(a,b,c,d,e,f)=>{P.Gh||(P.Gh=Rd(160));a={target:Q(a),lg:f,sg:e,xg:b,pg:d,zg:g=>{var m=P.Gh;x[m>>3]=g.timeStamp;var k=m>>2;t[k+2]=g.location;n[m+12]=g.ctrlKey;n[m+13]=g.shiftKey;n[m+14]=g.altKey;n[m+15]=g.metaKey;n[m+16]=g.repeat;t[k+5]=g.charCode;
t[k+6]=g.keyCode;t[k+7]=g.which;A(g.key??"",r,m+32,32);A(g.code??"",r,m+64,32);A(g.char??"",r,m+96,32);A(g.locale??"",r,m+128,32);R.get(d)(e,m,b)&&g.preventDefault()},wg:c};return Lc(a)},ie=(a,b,c)=>{var d=screen.orientation;P.Jh||(P.Jh=Rd(8));return Lc({target:d,lg:"change",sg:18,xg:a,pg:c,zg:e=>{var f=P.Jh,g=["portrait-primary","portrait-secondary","landscape-primary","landscape-secondary"],m=["portrait","portrait","landscape","landscape"],k=0;var p=window.screen?screen.orientation||screen.mozOrientation||
screen.webkitOrientation:void 0;typeof p==="object"?(k=g.indexOf(p.type),k<0&&(k=m.indexOf(p.type)),k>=0&&(k=1<<k),g=p.angle):g=window.orientation;t[f>>2]=k;t[f+4>>2]=g;R.get(c)(18,f,a)&&e.preventDefault()},wg:b})},je=(a,b,c,d)=>{P.Kh||(P.Kh=Rd(257));return Lc({target:a,lg:"pointerlockchange",sg:20,xg:b,pg:d,zg:e=>{var f=P.Kh,g=document.pointerLockElement;n[f]=!!g;var m=g?.id??"";A(Mc(g),r,f+1,128);A(m,r,f+129,128);R.get(d)(20,f,b)&&e.preventDefault()},wg:c})},ke=(a,b,c,d)=>{P.Ph||(P.Ph=Rd(36));a=
Q(a);return Lc({target:a,lg:"resize",sg:10,xg:b,pg:d,zg:e=>{if(e.target==a){var f=document.body;if(f){var g=P.Ph;t[g>>2]=0;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+12>>2]=innerWidth;t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset|0;t[g+32>>2]=pageYOffset|0;R.get(d)(10,g,b)&&e.preventDefault()}}},wg:c})},le=(a,b,c)=>{var d=Nc[1];P.Rh||(P.Rh=Rd(8));return Lc({target:d,lg:"visibilitychange",sg:21,xg:a,pg:c,zg:e=>{var f=P.Rh,g=["hidden","visible",
"prerender","unloaded"].indexOf(document.visibilityState);n[f]=document.hidden;t[f+4>>2]=g;R.get(c)(21,f,a)&&e.preventDefault()},wg:b})},me=(a,b,c,d)=>{P.Sh||(P.Sh=Rd(96));return Lc({target:a,Th:!0,lg:"wheel",sg:9,xg:b,pg:d,zg:e=>{var f=P.Sh;x[f>>3]=e.timeStamp;var g=f>>2;t[g+2]=e.screenX;t[g+3]=e.screenY;t[g+4]=e.clientX;t[g+5]=e.clientY;n[f+24]=e.ctrlKey;n[f+25]=e.shiftKey;n[f+26]=e.altKey;n[f+27]=e.metaKey;ma[g*2+14]=e.button;ma[g*2+15]=e.buttons;t[g+8]=e.movementX;t[g+9]=e.movementY;var m=Zc(a);
t[g+10]=e.clientX-(m.left|0);t[g+11]=e.clientY-(m.top|0);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+80>>3]=e.deltaZ;t[f+88>>2]=e.deltaMode;R.get(d)(9,f,b)&&e.preventDefault()},wg:c})},ne=["default","low-power","high-performance"],oe={},qe=()=>{if(!pe){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ba},b;for(b in oe)oe[b]===void 0?delete a[b]:a[b]=oe[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);
pe=c}return pe},pe,re=(a,b=[])=>{R.get(a)(...b)},se=a=>{for(var b of["keydown","mousedown","touchstart"])for(var c of[document,document.getElementById("canvas")])c?.addEventListener(b,()=>{a.state==="suspended"&&a.resume()},{once:!0})};nb=Array(4096);Bb(E,"/");L("/tmp");L("/home");L("/home/web_user");
(function(){L("/dev");Sa(259,{read:()=>0,write:(d,e,f,g)=>g,Ag:()=>0});Eb("/dev/null",259);Ra(1280,Ua);Ra(1536,Va);Eb("/dev/tty",1280);Eb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b===0&&(Ia(a),b=a.byteLength);return a[--b]};Pb("/dev","random",c);Pb("/dev","urandom",c);L("/dev/shm");L("/dev/shm/tmp")})();
(function(){L("/proc");var a=L("/proc/self");L("/proc/self/fd");Bb({Dg(){var b=Xa(a,"fd",16895,73);b.bg={Ag:E.bg.Ag};b.ag={$g(c,d){c=+d;var e=K(c);c={parent:null,Dg:{ai:"fake"},ag:{Lg:()=>e.path},id:c+1};return c.parent=c},oh(){return Array.from(lb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.requestAnimationFrame=sc;h.pauseMainLoop=Ec;h.resumeMainLoop=function(){vc++;var a=lc,b=mc,c=nc;nc=null;Dc(c,0,!1,wc,!0);uc(a,b);pc()};h.preMainLoop&&Bc.push(h.preMainLoop);
h.postMainLoop&&Cc.push(h.postMainLoop);for(let a=0;a<32;++a)Gd.push(Array(a));h.noExitRuntime&&(za=h.noExitRuntime);h.preloadPlugins&&(fb=h.preloadPlugins);h.print&&(fa=h.print);h.printErr&&(l=h.printErr);h.wasmBinary&&(ha=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);if(h.preInit)for(typeof h.preInit=="function"&&(h.preInit=[h.preInit]);h.preInit.length>0;)h.preInit.shift()();h.addRunDependency=eb;h.removeRunDependency=db;
h.FS_preloadFile=async(a,b,c,d,e,f,g,m)=>{var k=b?Ja(Ea(a+"/"+b)):a,p=`cp ${k}`;eb(p);try{var q=c;typeof c=="string"&&(q=await ab(c));q=await ib(q,k);m?.();f||Sb(a,b,q,d,e,g)}finally{db(p)}};h.FS_unlink=(...a)=>Hb(...a);h.FS_createPath=(...a)=>Qb(...a);h.FS_createDevice=(...a)=>Pb(...a);h.FS_createDataFile=(...a)=>Sb(...a);h.FS_createLazyFile=(...a)=>Ub(...a);
var jc={287624:()=>{typeof h.SDL3==="undefined"&&(h.SDL3={});var a=h.SDL3;typeof a.Ng==="undefined"&&(a.Ng=function(b){return b});typeof a.sh==="undefined"&&(a.sh=function(b){return b>>>2})},287938:a=>{a=N(a)+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");a===null&&(a="i");return a.length===1?a.charCodeAt(0):-1},288153:()=>{h.SDL3.Ug={};h.SDL3.Ug.Ig=[];h.SDL3.Ug.Ig[0]=void 0;h.SDL3.Ug.Ig[1]=void 0},288330:(a,b,c,d,e)=>{var f=h.SDL3.Ug;f.Ig[a]!==void 0&&clearInterval(f.Ig[a]);
f.Ig[a]=setInterval(function(){re(d,[e])},b/c*1E3)},288522:a=>{var b=h.SDL3.Ug;b.Ig[a]!==void 0&&clearInterval(b.Ig[a]);b.Ig[a]=void 0},288653:a=>{var b=new URLSearchParams(window.location.search);for(let [d,e]of b)if(d.startsWith("SDL_")){b=Sd(d);var c=Sd(e);b!=0&&c!=0&&re(a,[b,c,1]);te(b);te(c)}},288994:()=>typeof AudioContext!=="undefined"||typeof webkitAudioContext!=="undefined"?!0:!1,289141:()=>typeof navigator.mediaDevices!=="undefined"&&typeof navigator.mediaDevices.getUserMedia!=="undefined"||
typeof navigator.webkitGetUserMedia!=="undefined"?!0:!1,289375:()=>{var a=h.SDL3;typeof a.fg==="undefined"&&(a.fg={});typeof a.cg==="undefined"&&(a.cg={});a.ig||(typeof AudioContext!=="undefined"?a.ig=new AudioContext:typeof webkitAudioContext!=="undefined"&&(a.ig=new webkitAudioContext),a.ig&&typeof navigator.userActivation==="undefined"&&se(a.ig));return a.ig!==void 0},289954:()=>h.SDL3.ig.sampleRate,290005:(a,b,c,d)=>{function e(){}function f(m){g.cg.vg!==void 0&&(clearInterval(g.cg.vg),g.cg.vg=
void 0,g.cg.Mg=void 0);g.cg.Hh=g.ig.createMediaStreamSource(m);g.cg.ug=g.ig.createScriptProcessor(b,a,1);g.cg.ug.onaudioprocess=function(k){g!==void 0&&g.cg!==void 0&&(k.outputBuffer.getChannelData(0).fill(0),g.cg.wh=k.inputBuffer,re(c,[d]))};g.cg.Hh.connect(g.cg.ug);g.cg.ug.connect(g.ig.destination);g.cg.stream=m}var g=h.SDL3;g.cg.Mg=g.ig.createBuffer(a,b,g.ig.sampleRate);g.cg.Mg.getChannelData(0).fill(0);g.cg.vg=setInterval(function(){g.cg.wh=g.cg.Mg;re(c,[d])},b/g.ig.sampleRate*1E3);navigator.mediaDevices!==
void 0&&navigator.mediaDevices.getUserMedia!==void 0?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):navigator.webkitGetUserMedia!==void 0&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},291846:(a,b,c,d)=>{var e=h.SDL3;e.fg.ug=e.ig.createScriptProcessor(b,0,a);e.fg.ug.onaudioprocess=function(f){e!==void 0&&e.fg!==void 0&&(e.fg.vg!==void 0&&(clearInterval(e.fg.vg),e.fg.vg=void 0,e.fg.Mg=void 0),e.fg.fh=f.outputBuffer,re(c,[d]))};e.fg.ug.connect(e.ig.destination);e.ig.state===
"suspended"&&(e.fg.Mg=e.ig.createBuffer(a,b,e.ig.sampleRate),e.fg.Mg.getChannelData(0).fill(0),e.fg.vg=setInterval(function(){typeof navigator.userActivation!=="undefined"&&navigator.userActivation.hasBeenActive&&e.ig.resume();e.fg.fh=e.fg.Mg;re(c,[d]);e.fg.fh=void 0},b/e.ig.sampleRate*1E3))},293162:a=>{var b=h.SDL3;if(a){b.cg.vg!==void 0&&clearInterval(b.cg.vg);if(b.cg.stream!==void 0){a=b.cg.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.cg.stream.removeTrack(a[c])}b.cg.ug!==void 0&&(b.cg.ug.onaudioprocess=
function(){},b.cg.ug.disconnect());b.cg.Hh!==void 0&&b.cg.Hh.disconnect();b.cg=void 0}else b.fg.ug!=void 0&&b.fg.ug.disconnect(),b.fg.vg!==void 0&&clearInterval(b.fg.vg),b.fg=void 0;b.ig!==void 0&&b.fg===void 0&&b.cg===void 0&&(b.ig.close(),b.ig=void 0)},294318:(a,b)=>{var c=h.SDL3;a=c.sh(a);for(var d=c.fg.fh.numberOfChannels,e=0;e<d;++e){var f=c.fg.fh.getChannelData(e);if(f.length!=b)throw"Web Audio playback buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";
for(var g=0;g<b;++g)f[g]=w[a+(g*d+e)]}},294851:(a,b)=>{for(var c=h.SDL3,d=c.cg.wh.numberOfChannels,e=0;e<d;++e){var f=c.cg.wh.getChannelData(e);if(f.length!=b)throw"Web Audio recording buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(d==1)for(var g=0;g<b;++g)Aa(a+g*4,f[g]);else for(g=0;g<b;++g)Aa(a+(g*d+e)*4,f[g])}},295478:a=>{a=navigator.getGamepads()[a];if(!a)return 0;if(a.id.indexOf("Vendor: ")>0){let b=a.id.indexOf("Vendor: ")+8;return parseInt(a.id.substr(b,
4),16)}a=a.id.split("-");return a.length>1&&!isNaN(parseInt(a[0],16))?parseInt(a[0],16):0},295943:a=>{a=navigator.getGamepads()[a];if(!a)return 0;if(a.id.indexOf("Product: ")>0){let b=a.id.indexOf("Product: ")+9;return parseInt(a.id.substr(b,4),16)}a=a.id.split("-");return a.length>1&&!isNaN(parseInt(a[1],16))?parseInt(a[1],16):0},296415:a=>(a=navigator.getGamepads()[a])?a.id.toLowerCase().indexOf("xinput")>=0:0,296558:a=>{var b=navigator.getGamepads();return b?(a=b[a])&&a.vibrationActuator?1:0:0},
296733:(a,b,c)=>{var d=navigator.getGamepads();if(!d)return 0;a=d[a];if(!a||!a.vibrationActuator)return 0;a.vibrationActuator.playEffect("dual-rumble",{startDelay:0,duration:3E3,weakMagnitude:c/65535,strongMagnitude:b/65535});return 1},297069:(a,b,c,d)=>{d=N(d);var e=document.querySelector(d);d=h.SDL3;if(d.li!==e){d.Tg=jd(e);if(!d.Tg)return!1;d.li=e}if(d.w!==a||d.h!==b||d.Ai!==d.Tg)d.image=d.Tg.createImageData(a,b),d.w=a,d.h=b,d.Ai=d.Tg;a=d.image.data;c/=4;d.oi!==a&&(d.ni=new Int32Array(a.buffer),
d.oi=a);a=d.ni;a.set(t.subarray(c,c+a.length));d.Tg.putImageData(d.image,0,0);return!0},297818:()=>{var a=h.SDL3;a.mouse_x=0;a.mouse_y=0;a.mouse_buttons=[];for(var b=0;b<5;++b)a.mouse_buttons[b]=!1;document.addEventListener("mousemove",function(c){var d=h.SDL3;d.mouse_x=c.clientX;d.mouse_y=c.clientY});document.addEventListener("mousedown",function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!0)});document.addEventListener("mouseup",function(c){var d=h.SDL3;
0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!1)})},298506:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);e/=4;b=new Int32Array(a.data.buffer);b.set(t.subarray(e,e+b.length));g.putImageData(a,0,0);c=c===0&&d===0?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=ue(c.length+1);A(c,r,d,c.length+1);return d},299164:a=>{h.canvas&&(h.canvas.style.cursor=N(a))},299247:()=>{h.canvas&&
(h.canvas.style.cursor="none")},299316:()=>h.SDL3.mouse_x,299354:()=>h.SDL3.mouse_y,299392:a=>h.SDL3.mouse_buttons[a],299440:a=>{document.kg=function(b){b.key!="CapsLock"&&b.key!="NumLock"&&b.key!="ScrollLock"&&we(h.SDL3.Ng(a),b.getModifierState("CapsLock"),b.getModifierState("NumLock"),b.getModifierState("ScrollLock"))};document.addEventListener("keydown",document.kg)},299867:()=>{document.removeEventListener("keydown",document.kg)},299951:a=>{var b=document;b&&(b.jg=function(c){var d=h.SDL3;c=d.ah(0,
0,c);c!=0&&(xe(d.Ng(a),c),ye(c))},b.addEventListener("pointerup",b.jg))},300312:a=>{var b=h.SDL3;b.ah===void 0&&(b.ah=function(c,d,e){if(e.pointerType=="mouse")var f=1;else if(e.pointerType=="touch")f=2;else if(e.pointerType=="pen")f=3;else return 0;var g=ue(a);if(g!=0){var m=b.sh(g);t[m++]=f;t[m++]=e.pointerId;t[m++]=typeof e.button!=="undefined"?e.button:-1;t[m++]=e.buttons;t[m++]=e.type=="pointerdown"?1:0;w[m++]=e.movementX;w[m++]=e.movementY;w[m++]=e.clientX-c;w[m++]=e.clientY-d;f==3&&(w[m++]=
e.pressure,w[m++]=e.tangentialPressure,w[m++]=e.tiltX,w[m++]=e.tiltY,w[m++]=e.twist)}return g})},301304:a=>{a=N(a);try{var b=document.querySelector(a);if(b)return b===document.activeElement}catch(c){}return!1},301470:()=>document.hasFocus(),301502:()=>{var a=document;a&&(a.removeEventListener("pointerup",a.jg),a.jg=void 0)},301684:()=>document.body.clientWidth,301722:()=>document.body.clientHeight,301761:()=>window.innerWidth,301791:()=>window.innerHeight,301822:()=>window.outerWidth,301852:()=>window.outerHeight,
301883:()=>window.pageXOffset,301914:()=>window.pageYOffset,301945:(a,b)=>{var c=document.querySelector(N(b));if(c){var d=h.SDL3;c.Og=function(e){var f=c.getBoundingClientRect();e=d.ah(f.left,f.top,e);e!=0&&(ze(d.Ng(a),e),ye(e))};c.Cg=function(e){var f=c.getBoundingClientRect();e=d.ah(f.left,f.top,e);e!=0&&(Ae(d.Ng(a),e),ye(e))};c.kg=function(e){var f=c.getBoundingClientRect();e=d.ah(f.left,f.top,e);e!=0&&(Be(d.Ng(a),e),ye(e))};c.style.touchAction="none";c.addEventListener("pointerenter",c.Og);c.addEventListener("pointerleave",
c.Cg);c.addEventListener("pointercancel",c.Cg);c.addEventListener("pointerdown",c.kg);c.addEventListener("pointermove",c.kg);c.addEventListener("pointerup",c.kg)}},303333:(a,b,c)=>{var d=document.querySelector(N(b));if(d){var e=h.SDL3,f=function(g){var m=ue(c);if(m!=0){var k=m>>2,p=d.getBoundingClientRect();t[k++]=g.clientX-p.left;t[k++]=g.clientY-p.top}return m};e.yh=function(g){g.preventDefault();g=f(g);g!=0&&(Ce(a,g),ye(g))};d.addEventListener("dragover",e.yh);e.gh=0;try{L("/tmp/filedrop")}catch(g){}e.zh=
function(g){g.preventDefault();if(g.dataTransfer.types.includes("text/plain"))g=Sd(g.dataTransfer.getData("text/plain")),De(a,g),te(g);else if(g.dataTransfer.types.includes("Files")){let m=0,k=g.dataTransfer.files.length;for(let p=0;p<k;p++){let q=g.dataTransfer.files.item(p),v=new FileReader;v.readAsArrayBuffer(q);v.onload=function(C){var D=`/tmp/filedrop/${e.gh}`;e.gh+=1;var F=`${D}/${q.name}`,J=Sd(F);C=new Uint8Array(C.target.result);try{L(D);var I=Kb(F,"w");Nb(I,C,0,C.length,0);Lb(I);Ee(a,J)}catch(S){}te(J);
++m;m===k&&Fe(a)};v.onerror=function(){++m;m===k&&Fe(a)}}}Fe(a)};d.addEventListener("drop",e.zh);e.Wg=function(g){g.preventDefault();Fe(a)};d.addEventListener("dragend",e.Wg);d.addEventListener("dragleave",e.Wg)}},305700:a=>{if(a=document.querySelector(N(a))){var b=h.SDL3;a.removeEventListener("dragleave",b.Wg);a.removeEventListener("dragend",b.Wg);a.removeEventListener("drop",b.zh);b.gh=void 0;"/tmp/filedrop";Gb("/tmp/filedrop");a.removeEventListener("dragover",b.yh);b.yh=void 0;b.zh=void 0;b.Wg=
void 0}},306530:a=>{if(a=document.querySelector(N(a)))a.removeEventListener("pointerenter",a.Og),a.removeEventListener("pointerleave",a.Cg),a.removeEventListener("pointercancel",a.Cg),a.removeEventListener("pointerdown",a.kg),a.removeEventListener("pointermove",a.kg),a.removeEventListener("pointerup",a.kg),a.style.touchAction="",a.Og=void 0,a.Cg=void 0,a.kg=void 0},307264:()=>window.matchMedia?window.matchMedia("(prefers-color-scheme: light)").matches?0:window.matchMedia("(prefers-color-scheme: dark)").matches?
1:-1:-1,307473:()=>{if(typeof h.SDL3!=="undefined"){var a=h.SDL3;a.Oh.removeEventListener("change",a.Ah);a.Oh=void 0;a.Ah=void 0}},307726:()=>window.innerWidth,307756:()=>window.innerHeight,307787:a=>{h.requestFullscreen=function(){Ge(a)}},307896:(a,b)=>{a=URL.createObjectURL(new Blob([r.buffer instanceof ArrayBuffer?r.subarray(a,a+b):r.slice(a,a+b)],{type:"image/png"}));b=document.querySelector("link[rel~='icon']");b||(b=document.createElement("link"),b.rel="icon",b.type="image/png",document.head.appendChild(b));
b.href&&b.href.startsWith("blob:")&&URL.revokeObjectURL(b.href);b.href=a},308389:()=>{h.requestFullscreen=function(){}},308463:()=>window.innerWidth,308493:()=>window.innerHeight,308524:a=>{a=document.querySelector(N(a));a.hi=a.style.position;a.ii=a.style.top;a.gi=a.style.left;var b=document.createElement("div");b.id="SDL3_fill_document_background_elements";b.jg=a;b.Xg=a.parentNode;b.Vg=a.nextSibling;var c=Array.from(document.body.children),d;for(d of c)b.appendChild(d);document.body.appendChild(b);
b.style.display="none";document.body.appendChild(a);a.style.position="fixed";a.style.top="0";a.style.left="0"},309222:()=>{var a=document.getElementById("SDL3_fill_document_background_elements");if(a){for(a.Vg?a.Xg.insertBefore(a.jg,a.Vg):a.Xg.appendChild(a.jg);a.firstChild;)document.body.insertBefore(a.firstChild,a);a.jg.style.position=a.jg.hi;a.jg.style.top=a.jg.ii;a.jg.style.left=a.jg.gi;a.remove()}},309781:()=>{if(window.matchMedia){var a=h.SDL3;a.Ah=function(){He()};a.Oh=window.matchMedia("(prefers-color-scheme: dark)");
a.Oh.addEventListener("change",a.Ah)}},310103:(a,b,c,d,e)=>{a=N(a);b=N(b);c=N(c);d=N(d);var f=N(e);e=document.createElement("dialog");e.classList.add("SDL3_messagebox");e.id=f;e.style.color=d;e.style.backgroundColor=c;document.body.append(e);d=document.createElement("h1");d.innerText=a;e.append(d);a=document.createElement("p");a.innerText=b;e.append(a);e.showModal()},310644:(a,b,c,d,e,f,g,m)=>{a=N(a);b=N(b);f=N(f);var k=N(g),p=N(m),q=document.getElementById(a);if(!q)return!1;var v=document.createElement("button");
v.innerText=b;v.style.borderColor=f;v.style.backgroundColor=k;q.addEventListener("keydown",function(C){d&&C.key==="Enter"?(C.preventDefault(),v.click()):e&&C.key==="Escape"&&(C.preventDefault(),v.click())});q.addEventListener("cancel",function(C){C.preventDefault()});v.onmouseenter=function(){v.style.backgroundColor=p};v.onmouseleave=function(){v.style.backgroundColor=k};v.onclick=function(){q.close(c)};q.append(v);return!0},311653:a=>{a=N(a);return(a=document.getElementById(a))?a.open:!1},311791:a=>
{a=N(a);a=document.getElementById(a);if(!a)return 0;try{return parseInt(a.returnValue)}catch(b){return 0}},311973:(a,b)=>{alert(N(a)+"\n\n"+N(b))}},Ie,ye,Rd,ue,te,ze,Ae,Be,xe,Ce,Fe,De,Ee,we,He,Ge,Je,Rc,Oc,Qc,la,R,Ke={Za:(a,b)=>R.get(a)(b),d:(a,b,c)=>{(new Ba(a)).init(b,c);Ca++;z()},ob:function(a,b,c){try{b=N(b);b=Vb(a,b);if(c&-8)return-28;var d=H(b,{Pg:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&ub(d,a)?-2:0}catch(e){if(typeof M=="undefined"||e.name!=="ErrnoError")throw e;
return-e.hg}},o:function(a,b,c){Xb=c;try{var d=K(a);switch(b){case 0:var e=Yb();if(e<0)break;for(;lb[e];)e++;return zb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Yb(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=Yb(),ma[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if(typeof M=="undefined"||f.name!=="ErrnoError")throw f;return-f.hg}},kb:function(a){try{return K(a),0}catch(b){if(typeof M=="undefined"||b.name!=="ErrnoError")throw b;return-b.hg}},ib:function(a,
b){try{var c=K(a),d=c.node,e=c.bg.tg;a=e?c:d;e??=d.ag.tg;xb(e,63);var f=e(a);return Wb(b,f)}catch(g){if(typeof M=="undefined"||g.name!=="ErrnoError")throw g;return-g.hg}},Ya:function(a,b,c){try{var d=K(a);if(!d.Kg){var e=H(d.path,{Pg:!0}).node;var f=xb(e.ag.oh,54)(e);d.Kg=f}a=0;var g=Mb(d,0,1),m=Math.floor(g/280),k=Math.min(d.Kg.length,m+Math.floor(c/280));for(c=m;c<k;c++){var p=d.Kg[c];if(p==="."){var q=d.node.id;var v=4}else if(p==="..")q=H(d.path,{parent:!0}).node.id,v=4;else{try{var C=Ya(d.node,
p)}catch(D){if(D?.hg===28)continue;throw D;}q=C.id;v=(C.mode&61440)===8192?2:G(C.mode)?4:(C.mode&61440)===40960?10:8}y[b+a>>3]=BigInt(q);y[b+a+8>>3]=BigInt((c+1)*280);ma[b+a+16>>1]=280;n[b+a+18]=v;A(p,r,b+a+19,256);a+=280}Mb(d,c*280,0);return a}catch(D){if(typeof M=="undefined"||D.name!=="ErrnoError")throw D;return-D.hg}},jb:function(a,b,c){Xb=c;try{var d=K(a);switch(b){case 21509:return d.gg?0:-59;case 21505:if(!d.gg)return-59;if(d.gg.Eg.Ei){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0];var e=Yb();t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>2]=35387;for(var f=0;f<32;f++)n[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.gg?0:-59;case 21506:case 21507:case 21508:if(!d.gg)return-59;if(d.gg.Eg.Fi)for(e=Yb(),a=[],f=0;f<32;f++)a.push(n[e+f+17]);return 0;case 21519:if(!d.gg)return-59;e=Yb();return t[e>>2]=0;case 21520:return d.gg?-28:-59;case 21537:case 21531:e=Yb();if(!d.bg.Di)throw new B(59);return d.bg.Di(d,b,e);case 21523:if(!d.gg)return-59;
d.gg.Eg.Gi&&(f=[24,80],e=Yb(),ma[e>>1]=f[0],ma[e+2>>1]=f[1]);return 0;case 21524:return d.gg?0:-59;case 21515:return d.gg?0:-59;default:return-28}}catch(g){if(typeof M=="undefined"||g.name!=="ErrnoError")throw g;return-g.hg}},gb:function(a,b){try{return a=N(a),Wb(b,Ib(a,!0))}catch(c){if(typeof M=="undefined"||c.name!=="ErrnoError")throw c;return-c.hg}},cb:function(a,b,c){try{return b=N(b),b=Vb(a,b),L(b,c&-19),0}catch(d){if(typeof M=="undefined"||d.name!=="ErrnoError")throw d;return-d.hg}},fb:function(a,
b,c,d){try{b=N(b);var e=d&256;b=Vb(a,b,d&4096);return Wb(c,e?Ib(b,!0):Ib(b))}catch(f){if(typeof M=="undefined"||f.name!=="ErrnoError")throw f;return-f.hg}},x:function(a,b,c,d){Xb=d;try{b=N(b);b=Vb(a,b);var e=d?Yb():0;c&64&&(e&=-19);return Kb(b,c,e).fd}catch(f){if(typeof M=="undefined"||f.name!=="ErrnoError")throw f;return-f.hg}},Xa:function(a,b,c,d){try{b=N(b);b=Vb(a,b);if(d<=0)return-28;var e=H(b).node;if(!e)throw new B(44);if(!e.ag.Lg)throw new B(28);var f=e.ag.Lg(e);var g=Math.min(d,Oa(f)),m=n[c+
g];A(f,r,c,d+1);n[c+g]=m;return g}catch(k){if(typeof M=="undefined"||k.name!=="ErrnoError")throw k;return-k.hg}},Va:function(a){try{return a=N(a),Gb(a),0}catch(b){if(typeof M=="undefined"||b.name!=="ErrnoError")throw b;return-b.hg}},hb:function(a,b){try{return a=N(a),Wb(b,Ib(a))}catch(c){if(typeof M=="undefined"||c.name!=="ErrnoError")throw c;return-c.hg}},Wa:function(a,b,c){try{b=N(b);b=Vb(a,b);if(c)if(c===512)Gb(b);else return-28;else Hb(b);return 0}catch(d){if(typeof M=="undefined"||d.name!=="ErrnoError")throw d;
return-d.hg}},pb:()=>z(""),mb:(a,b)=>{b=N(b);if(a&24){var c=b=b.replace(/\s+$/,"");b=b.length>0?"\n":"";var d=Error().stack.toString(),e=d.split("\n");d="";var f=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),g=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),m;for(m of e){var k=g.exec(m);if(k?.length==5){e=k[1];var p=k[2];var q=k[3];k=k[4]}else if(k=f.exec(m),k?.length>=4)e=k[1],p=k[2],q=k[3],k=k[4]|0;else{d+=m+"\n";continue}e=="_emscripten_log"||e=="_emscripten_get_callstack"?d="":a&24&&(a&64&&(p=p.substring(p.replace(/\\/g,
"/").lastIndexOf("/")+1)),d+=`    at ${e} (${p}:${q}:${k})\n`)}d=d.replace(/\s+$/,"");b=c+(b+d)}a&1?a&4?console.error(b):a&2?console.warn(b):a&512?console.info(b):a&256?console.debug(b):console.log(b):a&6?l(b):fa(b)},$a:()=>{za=!1;Zb=0},ab:function(a){var b=new Date(t[a+20>>2]+1900,t[a+16>>2],t[a+12>>2],t[a+8>>2],t[a+4>>2],t[a>>2],0);if(isNaN(b.getTime()))a=-1;else{var c=t[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),
g=Math.min(f,e);c<0?t[a+32>>2]=Number(e!=f&&g==d):c>0!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+((c>0?g:e)-d)*6E4));t[a+24>>2]=b.getDay();c=b.getFullYear();t[a+28>>2]=(c%4!==0||c%100===0&&c%400!==0?ac:$b)[b.getMonth()]+b.getDate()-1|0;t[a>>2]=b.getSeconds();t[a+4>>2]=b.getMinutes();t[a+8>>2]=b.getHours();t[a+12>>2]=b.getDate();t[a+16>>2]=b.getMonth();t[a+20>>2]=b.getYear();a=b.getTime()/1E3}return BigInt(a)},Ta:(a,b)=>{bc[a]&&(clearTimeout(bc[a].id),delete bc[a]);if(!b)return 0;var c=setTimeout(()=>
{delete bc[a];fc(()=>Je(a,performance.now()))},b);bc[a]={id:c,sj:b};return 0},bb:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();u[a>>2]=Math.max(f,e)*60;t[b>>2]=Number(f!=e);b=g=>{var m=Math.abs(g);return`UTC${g>=0?"-":"+"}${String(Math.floor(m/60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(A(a,r,c,17),A(b,r,d,17)):(A(a,r,d,17),A(b,r,c,17))},nb:function(a,b,c){if(!(a>=0&&a<=3))return 28;y[c>>3]=
BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},G:kc,h:(a,b,c)=>{b=ic(b,c);return jc[a](...b)},a:kc,Dd:(a,b,c)=>{b=ic(b,c);return jc[a](...b)},Af:()=>{Ec();nc=null},lb:()=>Date.now(),Pa:()=>{if(!P.fullscreenEnabled())return-1;Ic($c);var a=Nc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},id:()=>{Ic(ad);if(!document.exitPointerLock)return-1;document.exitPointerLock();
return 0},g:()=>devicePixelRatio,b:(a,b,c)=>{a=Q(a);if(!a)return-4;a=Zc(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},Ra:a=>{if(!P.fullscreenEnabled())return-1;bd(a);return 0},p:(a,b)=>{if(a<0||a>=P.hh.length)return-5;if(!P.hh[a])return-7;cd(b,P.hh[a]);return 0},We:(a,b)=>{a&&(t[a>>2]=lc);b&&(t[b>>2]=mc)},n:()=>performance.now(),ma:()=>P.hh.length,Yd:(a,b)=>{t[a>>2]=screen.width;t[b>>2]=screen.height},ua:a=>T.activeTexture(a),ta:(a,b)=>{T.attachShader(U[a],V[b])},cd:(a,b)=>{T.beginQuery(a,W[b])},
La:(a,b)=>{T.rg.beginQueryEXT(a,W[b])},Lc:a=>T.beginTransformFeedback(a),sa:(a,b,c)=>{T.bindAttribLocation(U[a],b,N(c))},ra:(a,b)=>{a==35051?T.uh=b:a==35052&&(T.yg=b);T.bindBuffer(a,md[b])},Ic:(a,b,c)=>{T.bindBufferBase(a,b,md[c])},Jc:(a,b,c,d,e)=>{T.bindBufferRange(a,b,md[c],d,e)},qa:(a,b)=>{T.bindFramebuffer(a,nd[b])},pa:(a,b)=>{T.bindRenderbuffer(a,od[b])},Qb:(a,b)=>{T.bindSampler(a,X[b])},oa:(a,b)=>{T.bindTexture(a,pd[b])},Hb:(a,b)=>{T.bindTransformFeedback(a,sd[b])},Qc:Dd,Ca:Dd,na:(a,b,c,d)=>
T.blendColor(a,b,c,d),la:a=>T.blendEquation(a),ka:(a,b)=>T.blendEquationSeparate(a,b),ja:(a,b)=>T.blendFunc(a,b),ia:(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),Tc:(a,b,c,d,e,f,g,m,k,p)=>T.blitFramebuffer(a,b,c,d,e,f,g,m,k,p),ha:(a,b,c,d)=>{c&&b?T.bufferData(a,r,d,c,b):T.bufferData(a,b,d)},ga:(a,b,c,d)=>{var e=r;c&&T.bufferSubData(a,b,e,d,c)},fa:a=>T.checkFramebufferStatus(a),ea:a=>T.clear(a),lc:(a,b,c,d)=>T.clearBufferfi(a,b,c,d),mc:(a,b,c)=>{T.clearBufferfv(a,b,w,c>>2)},oc:(a,b,c)=>{T.clearBufferiv(a,
b,t,c>>2)},nc:(a,b,c)=>{T.clearBufferuiv(a,b,u,c>>2)},da:(a,b,c,d)=>T.clearColor(a,b,c,d),ca:a=>T.clearDepth(a),ba:a=>T.clearStencil(a),Zb:(a,b,c)=>{c=Number(c);return T.clientWaitSync(td[a],b,c)},xd:(a,b)=>{T.ui.clipControlEXT(a,b)},aa:(a,b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},$:a=>{T.compileShader(V[a])},_:(a,b,c,d,e,f,g,m)=>{T.yg||!g?T.compressedTexImage2D(a,b,c,d,e,f,g,m):T.compressedTexImage2D(a,b,c,d,e,f,r,m,g)},hd:(a,b,c,d,e,f,g,m,k)=>{T.yg?T.compressedTexImage3D(a,b,c,d,e,f,g,m,k):T.compressedTexImage3D(a,
b,c,d,e,f,g,r,k,m)},Z:(a,b,c,d,e,f,g,m,k)=>{T.yg||!m?T.compressedTexSubImage2D(a,b,c,d,e,f,g,m,k):T.compressedTexSubImage2D(a,b,c,d,e,f,g,r,k,m)},gd:(a,b,c,d,e,f,g,m,k,p,q)=>{T.yg?T.compressedTexSubImage3D(a,b,c,d,e,f,g,m,k,p,q):T.compressedTexSubImage3D(a,b,c,d,e,f,g,m,k,r,q,p)},jc:(a,b,c,d,e)=>T.copyBufferSubData(a,b,c,d,e),Y:(a,b,c,d,e,f,g,m)=>T.copyTexImage2D(a,b,c,d,e,f,g,m),X:(a,b,c,d,e,f,g,m)=>T.copyTexSubImage2D(a,b,c,d,e,f,g,m),jd:(a,b,c,d,e,f,g,m,k)=>T.copyTexSubImage3D(a,b,c,d,e,f,g,m,
k),W:()=>{var a=yd(U),b=T.createProgram();b.name=a;b.kh=b.ih=b.jh=0;b.Qh=1;U[a]=b;return a},V:a=>{var b=yd(V);V[b]=T.createShader(a);return b},U:a=>T.cullFace(a),T:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=md[d];e&&(T.deleteBuffer(e),e.name=0,md[d]=null,d==T.uh&&(T.uh=0),d==T.yg&&(T.yg=0))}},S:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+c*4>>2],e=nd[d];e&&(T.deleteFramebuffer(e),e.name=0,nd[d]=null)}},R:a=>{if(a){var b=U[a];b?(T.deleteProgram(b),b.name=0,U[a]=null):Y||=1281}},ed:(a,b)=>{for(var c=
0;c<a;c++){var d=t[b+c*4>>2],e=W[d];e&&(T.deleteQuery(e),W[d]=null)}},Na:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=W[d];e&&(T.rg.deleteQueryEXT(e),W[d]=null)}},Q:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=od[d];e&&(T.deleteRenderbuffer(e),e.name=0,od[d]=null)}},Sb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=X[d];e&&(T.deleteSampler(e),e.name=0,X[d]=null)}},P:a=>{if(a){var b=V[a];b?(T.deleteShader(b),V[a]=null):Y||=1281}},_b:a=>{if(a){var b=td[a];b?(T.deleteSync(b),b.name=0,td[a]=
null):Y||=1281}},O:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=pd[d];e&&(T.deleteTexture(e),e.name=0,pd[d]=null)}},Gb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=sd[d];e&&(T.deleteTransformFeedback(e),e.name=0,sd[d]=null)}},Pc:Ed,Ba:Ed,N:a=>T.depthFunc(a),M:a=>{T.depthMask(!!a)},L:(a,b)=>T.depthRange(a,b),K:(a,b)=>{T.detachShader(U[a],V[b])},zf:a=>T.disable(a),yf:a=>{T.disableVertexAttribArray(a)},xf:(a,b,c)=>{T.drawArrays(a,b,c)},cc:Fd,xa:Fd,sd:Fd,td:Fd,sb:Fd,_c:Hd,od:Hd,ya:Hd,wf:(a,b,
c,d)=>{T.drawElements(a,b,c,d)},bc:Id,wa:Id,pd:Id,qd:Id,rd:Id,md:(a,b,c,d,e,f)=>{T.drawElements(a,d,e,f)},vf:a=>T.enable(a),uf:a=>{T.enableVertexAttribArray(a)},bd:a=>T.endQuery(a),Ka:a=>{T.rg.endQueryEXT(a)},Kc:()=>T.endTransformFeedback(),ac:(a,b)=>(a=T.fenceSync(a,b))?(b=yd(td),a.name=b,td[b]=a,b):0,tf:()=>T.finish(),sf:()=>T.flush(),rf:(a,b,c,d)=>{T.framebufferRenderbuffer(a,b,c,od[d])},qf:(a,b,c,d,e)=>{T.framebufferTexture2D(a,b,c,pd[d],e)},Rc:(a,b,c,d,e)=>{T.framebufferTextureLayer(a,b,pd[c],
d,e)},pf:a=>T.frontFace(a),of:(a,b)=>{zd(a,b,"createBuffer",md)},mf:(a,b)=>{zd(a,b,"createFramebuffer",nd)},fd:(a,b)=>{zd(a,b,"createQuery",W)},Oa:(a,b)=>{for(var c=0;c<a;c++){var d=T.rg.createQueryEXT();if(!d){for(Y||=1282;c<a;)t[b+c++*4>>2]=0;break}var e=yd(W);d.name=e;W[e]=d;t[b+c*4>>2]=e}},lf:(a,b)=>{zd(a,b,"createRenderbuffer",od)},Tb:(a,b)=>{zd(a,b,"createSampler",X)},kf:(a,b)=>{zd(a,b,"createTexture",pd)},Fb:(a,b)=>{zd(a,b,"createTransformFeedback",sd)},Oc:Jd,Aa:Jd,nf:a=>T.generateMipmap(a),
jf:(a,b,c,d,e,f,g)=>Kd("getActiveAttrib",a,b,c,d,e,f,g),hf:(a,b,c,d,e,f,g)=>Kd("getActiveUniform",a,b,c,d,e,f,g),ec:(a,b,c,d,e)=>{a=U[a];if(a=T.getActiveUniformBlockName(a,b))e&&c>0?(c=A(a,r,e,c),d&&(t[d>>2]=c)):d&&(t[d>>2]=0)},fc:(a,b,c,d)=>{if(d)if(a=U[a],c==35393)t[d>>2]=T.getActiveUniformBlockName(a,b).length+1;else{if(a=T.getActiveUniformBlockParameter(a,b,c),a!==null)if(c==35395)for(c=0;c<a.length;c++)t[d+c*4>>2]=a[c];else t[d>>2]=a}else Y||=1281},hc:(a,b,c,d,e)=>{if(e)if(b>0&&c==0)Y||=1281;
else{a=U[a];for(var f=[],g=0;g<b;g++)f.push(t[c+g*4>>2]);if(a=T.getActiveUniforms(a,f,d))for(b=a.length,g=0;g<b;g++)t[e+g*4>>2]=a[g]}else Y||=1281},gf:(a,b,c,d)=>{a=T.getAttachedShaders(U[a]);var e=a.length;e>b&&(e=b);t[c>>2]=e;for(b=0;b<e;++b)t[d+b*4>>2]=V.indexOf(a[b])},ff:(a,b)=>T.getAttribLocation(U[a],N(b)),ef:(a,b)=>Nd(a,b,4),Ub:(a,b,c)=>{c?Ld(c,T.getBufferParameter(a,b)):Y||=1281},df:(a,b,c)=>{c?t[c>>2]=T.getBufferParameter(a,b):Y||=1281},cf:()=>{var a=T.getError()||Y;Y=0;return a},bf:(a,b)=>
Nd(a,b,2),xc:(a,b)=>T.getFragDataLocation(U[a],N(b)),af:(a,b,c,d)=>{a=T.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;t[d>>2]=a},Vb:(a,b,c)=>Od(a,b,c,1),Xb:(a,b)=>{Nd(a,b,1)},Mc:(a,b,c)=>Od(a,b,c,0),$e:(a,b)=>Nd(a,b,0),ub:(a,b,c,d,e)=>{if(d<0)Y||=1281;else if(e){if(a=T.getInternalformatParameter(a,b,c),a!==null)for(b=0;b<a.length&&b<d;++b)t[e+b*4>>2]=a[b]}else Y||=1281},Bb:()=>{Y||=1282},Ze:(a,b,c,d)=>{a=T.getProgramInfoLog(U[a]);
a===null&&(a="(unknown error)");b=b>0&&d?A(a,r,d,b):0;c&&(t[c>>2]=b)},_e:(a,b,c)=>{if(c)if(a>=ld)Y||=1281;else if(a=U[a],b==35716)a=T.getProgramInfoLog(a),a===null&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(b==35719){if(!a.kh){var d=T.getProgramParameter(a,35718);for(b=0;b<d;++b)a.kh=Math.max(a.kh,T.getActiveUniform(a,b).name.length+1)}t[c>>2]=a.kh}else if(b==35722){if(!a.ih)for(d=T.getProgramParameter(a,35721),b=0;b<d;++b)a.ih=Math.max(a.ih,T.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.ih}else if(b==
35381){if(!a.jh)for(d=T.getProgramParameter(a,35382),b=0;b<d;++b)a.jh=Math.max(a.jh,T.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.jh}else t[c>>2]=T.getProgramParameter(a,b);else Y||=1281},Ea:Pd,Ga:Qd,Da:Pd,$c:(a,b,c)=>{if(c){a=T.getQueryParameter(W[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;t[c>>2]=d}else Y||=1281},Fa:Qd,ad:(a,b,c)=>{c?t[c>>2]=T.getQuery(a,b):Y||=1281},Ia:(a,b,c)=>{c?t[c>>2]=T.rg.getQueryEXT(a,b):Y||=1281},Ye:(a,b,c)=>{c?t[c>>2]=T.getRenderbufferParameter(a,b):Y||=1281},Kb:(a,
b,c)=>{c?w[c>>2]=T.getSamplerParameter(X[a],b):Y||=1281},Lb:(a,b,c)=>{c?t[c>>2]=T.getSamplerParameter(X[a],b):Y||=1281},Ve:(a,b,c,d)=>{a=T.getShaderInfoLog(V[a]);a===null&&(a="(unknown error)");b=b>0&&d?A(a,r,d,b):0;c&&(t[c>>2]=b)},Ue:(a,b,c,d)=>{a=T.getShaderPrecisionFormat(a,b);t[c>>2]=a.rangeMin;t[c+4>>2]=a.rangeMax;t[d>>2]=a.precision},Te:(a,b,c,d)=>{if(a=T.getShaderSource(V[a]))b=b>0&&d?A(a,r,d,b):0,c&&(t[c>>2]=b)},Xe:(a,b,c)=>{c?b==35716?(a=T.getShaderInfoLog(V[a]),a===null&&(a="(unknown error)"),
t[c>>2]=a?a.length+1:0):b==35720?(a=T.getShaderSource(V[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=T.getShaderParameter(V[a],b):Y||=1281},Se:a=>{var b=ud[a];if(!b){switch(a){case 7939:b=Sd(Md().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=T.getParameter(a))||(Y||=1280);b=b?Sd(b):0;break;case 7938:b=Sd(`OpenGL ES 3.0 (${T.getParameter(7938)})`);break;case 35724:b=T.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);c!==null&&(c[1].length==3&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);
b=Sd(b);break;default:Y||=1280}ud[a]=b}return b},kc:(a,b)=>{if(Cd.version<2)return Y||=1282,0;var c=vd[a];if(c)return b<0||b>=c.length?(Y||=1281,0):c[b];switch(a){case 7939:return c=Md().map(Sd),c=vd[a]=c,b<0||b>=c.length?(Y||=1281,0):c[b];default:return Y||=1280,0}},Wb:(a,b,c,d,e)=>{c<0?Y||=1281:e?(a=T.getSyncParameter(td[a],b),a!==null&&(t[e>>2]=a,d&&(t[d>>2]=1))):Y||=1281},Re:(a,b,c)=>{c?w[c>>2]=T.getTexParameter(a,b):Y||=1281},Qe:(a,b,c)=>{c?t[c>>2]=T.getTexParameter(a,b):Y||=1281},Gc:(a,b,c,
d,e,f,g)=>{a=U[a];if(a=T.getTransformFeedbackVarying(a,b))g&&c>0?(c=A(a.name,r,g,c),d&&(t[d>>2]=c)):d&&(t[d>>2]=0),e&&(t[e>>2]=a.size),f&&(t[f>>2]=a.type)},gc:(a,b)=>T.getUniformBlockIndex(U[a],N(b)),ic:(a,b,c,d)=>{if(d)if(b>0&&(c==0||d==0))Y||=1281;else{a=U[a];for(var e=[],f=0;f<b;f++)e.push(N(u[c+f*4>>2]));if(a=T.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)t[d+f*4>>2]=a[f]}else Y||=1281},Ne:(a,b)=>{b=N(b);if(a=U[a]){Ud(a);var c=a.dh,d=0,e=b,f=Td(b);f>0&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,
f));if((e=a.fi[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else Y||=1281;return-1},Pe:(a,b,c)=>{Vd(a,b,c,2)},Oe:(a,b,c)=>{Vd(a,b,c,0)},yc:(a,b,c)=>Vd(a,b,c,0),Ec:Xd,Dc:Xd,Je:(a,b,c)=>{c?t[c>>2]=T.getVertexAttribOffset(a,b):Y||=1281},Me:(a,b,c)=>{Wd(a,b,c,2)},Ke:(a,b,c)=>{Wd(a,b,c,5)},Ie:(a,b)=>T.hint(a,b),yb:(a,b,c)=>{for(var d=Gd[b],e=0;e<b;e++)d[e]=t[c+e*4>>2];T.invalidateFramebuffer(a,d)},xb:(a,b,c,d,e,f,g)=>{for(var m=Gd[b],k=0;k<b;k++)m[k]=t[c+k*4>>2];T.invalidateSubFramebuffer(a,
m,d,e,f,g)},He:a=>(a=md[a])?T.isBuffer(a):0,Ge:a=>T.isEnabled(a),Fe:a=>(a=nd[a])?T.isFramebuffer(a):0,Ee:a=>(a=U[a])?T.isProgram(a):0,dd:a=>(a=W[a])?T.isQuery(a):0,Ma:a=>(a=W[a])?T.rg.isQueryEXT(a):0,De:a=>(a=od[a])?T.isRenderbuffer(a):0,Rb:a=>(a=X[a])?T.isSampler(a):0,Ce:a=>(a=V[a])?T.isShader(a):0,$b:a=>T.isSync(td[a]),Be:a=>(a=pd[a])?T.isTexture(a):0,Eb:a=>T.isTransformFeedback(sd[a]),Nc:Yd,za:Yd,Ae:a=>T.lineWidth(a),ze:a=>{a=U[a];T.linkProgram(a);a.dh=0;a.fi={}},Db:()=>T.pauseTransformFeedback(),
ye:(a,b)=>{a==3317?wd=b:a==3314&&(xd=b);T.pixelStorei(a,b)},wd:(a,b)=>{T.Ri.polygonModeWEBGL(a,b)},xe:(a,b)=>T.polygonOffset(a,b),yd:(a,b,c)=>{T.wi.polygonOffsetClampEXT(a,b,c)},Ab:()=>{Y||=1280},zb:()=>{Y||=1280},Ja:(a,b)=>{T.rg.queryCounterEXT(W[a],b)},nd:a=>T.readBuffer(a),we:(a,b,c,d,e,f,g)=>{if(T.uh)T.readPixels(a,b,c,d,e,f,g);else{var m=Zd(f);g>>>=31-Math.clz32(m.BYTES_PER_ELEMENT);T.readPixels(a,b,c,d,e,f,m,g)}},ve:()=>{},ue:(a,b,c,d)=>T.renderbufferStorage(a,b,c,d),Sc:(a,b,c,d,e)=>T.renderbufferStorageMultisample(a,
b,c,d,e),Cb:()=>T.resumeTransformFeedback(),te:(a,b)=>{T.sampleCoverage(a,!!b)},Nb:(a,b,c)=>{T.samplerParameterf(X[a],b,c)},Mb:(a,b,c)=>{T.samplerParameterf(X[a],b,w[c>>2])},Pb:(a,b,c)=>{T.samplerParameteri(X[a],b,c)},Ob:(a,b,c)=>{T.samplerParameteri(X[a],b,t[c>>2])},se:(a,b,c,d)=>T.scissor(a,b,c,d),re:()=>{Y||=1280},qe:(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=N(u[c+f*4>>2],d?u[d+f*4>>2]:void 0);T.shaderSource(V[a],e)},pe:(a,b,c)=>T.stencilFunc(a,b,c),oe:(a,b,c,d)=>T.stencilFuncSeparate(a,b,c,d),ne:a=>
T.stencilMask(a),me:(a,b)=>T.stencilMaskSeparate(a,b),le:(a,b,c)=>T.stencilOp(a,b,c),ke:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),je:(a,b,c,d,e,f,g,m,k)=>{if(T.yg)T.texImage2D(a,b,c,d,e,f,g,m,k);else if(k){var p=Zd(m);k>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);T.texImage2D(a,b,c,d,e,f,g,m,p,k)}else p=k?$d(m,g,d,e,k):null,T.texImage2D(a,b,c,d,e,f,g,m,p)},ld:(a,b,c,d,e,f,g,m,k,p)=>{if(T.yg)T.texImage3D(a,b,c,d,e,f,g,m,k,p);else if(p){var q=Zd(k);T.texImage3D(a,b,c,d,e,f,g,m,k,q,p>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else T.texImage3D(a,
b,c,d,e,f,g,m,k,null)},ie:(a,b,c)=>T.texParameterf(a,b,c),he:(a,b,c)=>{T.texParameterf(a,b,w[c>>2])},ge:(a,b,c)=>T.texParameteri(a,b,c),fe:(a,b,c)=>{T.texParameteri(a,b,t[c>>2])},wb:(a,b,c,d,e)=>T.texStorage2D(a,b,c,d,e),vb:(a,b,c,d,e,f)=>T.texStorage3D(a,b,c,d,e,f),ee:(a,b,c,d,e,f,g,m,k)=>{if(T.yg)T.texSubImage2D(a,b,c,d,e,f,g,m,k);else if(k){var p=Zd(m);T.texSubImage2D(a,b,c,d,e,f,g,m,p,k>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else k=k?$d(m,g,e,f,k):null,T.texSubImage2D(a,b,c,d,e,f,g,m,k)},kd:(a,
b,c,d,e,f,g,m,k,p,q)=>{if(T.yg)T.texSubImage3D(a,b,c,d,e,f,g,m,k,p,q);else if(q){var v=Zd(p);T.texSubImage3D(a,b,c,d,e,f,g,m,k,p,v,q>>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else T.texSubImage3D(a,b,c,d,e,f,g,m,k,p,null)},Hc:(a,b,c,d)=>{a=U[a];for(var e=[],f=0;f<b;f++)e.push(N(u[c+f*4>>2]));T.transformFeedbackVaryings(a,e,d)},de:(a,b)=>{T.uniform1f(Z(T.dg,a),b)},ce:(a,b,c)=>{b&&T.uniform1fv(Z(T.dg,a),w,c>>2,b)},be:(a,b)=>{T.uniform1i(Z(T.dg,a),b)},ae:(a,b,c)=>{b&&T.uniform1iv(Z(T.dg,a),t,c>>2,b)},wc:(a,
b)=>{T.uniform1ui(Z(T.dg,a),b)},sc:(a,b,c)=>{b&&T.uniform1uiv(Z(T.dg,a),u,c>>2,b)},$d:(a,b,c)=>{T.uniform2f(Z(T.dg,a),b,c)},_d:(a,b,c)=>{b&&T.uniform2fv(Z(T.dg,a),w,c>>2,b*2)},Zd:(a,b,c)=>{T.uniform2i(Z(T.dg,a),b,c)},Xd:(a,b,c)=>{b&&T.uniform2iv(Z(T.dg,a),t,c>>2,b*2)},vc:(a,b,c)=>{T.uniform2ui(Z(T.dg,a),b,c)},rc:(a,b,c)=>{b&&T.uniform2uiv(Z(T.dg,a),u,c>>2,b*2)},Wd:(a,b,c,d)=>{T.uniform3f(Z(T.dg,a),b,c,d)},Vd:(a,b,c)=>{b&&T.uniform3fv(Z(T.dg,a),w,c>>2,b*3)},Ud:(a,b,c,d)=>{T.uniform3i(Z(T.dg,a),b,c,
d)},Td:(a,b,c)=>{b&&T.uniform3iv(Z(T.dg,a),t,c>>2,b*3)},uc:(a,b,c,d)=>{T.uniform3ui(Z(T.dg,a),b,c,d)},qc:(a,b,c)=>{b&&T.uniform3uiv(Z(T.dg,a),u,c>>2,b*3)},Sd:(a,b,c,d,e)=>{T.uniform4f(Z(T.dg,a),b,c,d,e)},Rd:(a,b,c)=>{b&&T.uniform4fv(Z(T.dg,a),w,c>>2,b*4)},Qd:(a,b,c,d,e)=>{T.uniform4i(Z(T.dg,a),b,c,d,e)},Pd:(a,b,c)=>{b&&T.uniform4iv(Z(T.dg,a),t,c>>2,b*4)},tc:(a,b,c,d,e)=>{T.uniform4ui(Z(T.dg,a),b,c,d,e)},pc:(a,b,c)=>{b&&T.uniform4uiv(Z(T.dg,a),u,c>>2,b*4)},dc:(a,b,c)=>{a=U[a];T.uniformBlockBinding(a,
b,c)},Od:(a,b,c,d)=>{b&&T.uniformMatrix2fv(Z(T.dg,a),!!c,w,d>>2,b*4)},Zc:(a,b,c,d)=>{b&&T.uniformMatrix2x3fv(Z(T.dg,a),!!c,w,d>>2,b*6)},Xc:(a,b,c,d)=>{b&&T.uniformMatrix2x4fv(Z(T.dg,a),!!c,w,d>>2,b*8)},Nd:(a,b,c,d)=>{b&&T.uniformMatrix3fv(Z(T.dg,a),!!c,w,d>>2,b*9)},Yc:(a,b,c,d)=>{b&&T.uniformMatrix3x2fv(Z(T.dg,a),!!c,w,d>>2,b*6)},Vc:(a,b,c,d)=>{b&&T.uniformMatrix3x4fv(Z(T.dg,a),!!c,w,d>>2,b*12)},Md:(a,b,c,d)=>{b&&T.uniformMatrix4fv(Z(T.dg,a),!!c,w,d>>2,b*16)},Wc:(a,b,c,d)=>{b&&T.uniformMatrix4x2fv(Z(T.dg,
a),!!c,w,d>>2,b*8)},Uc:(a,b,c,d)=>{b&&T.uniformMatrix4x3fv(Z(T.dg,a),!!c,w,d>>2,b*12)},Ld:a=>{a=U[a];T.useProgram(a);T.dg=a},Kd:a=>{T.validateProgram(U[a])},Jd:(a,b)=>T.vertexAttrib1f(a,b),Id:(a,b)=>{T.vertexAttrib1f(a,w[b>>2])},Hd:(a,b,c)=>T.vertexAttrib2f(a,b,c),Gd:(a,b)=>{T.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},Fd:(a,b,c,d)=>T.vertexAttrib3f(a,b,c,d),Ed:(a,b)=>{T.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},Cd:(a,b,c,d,e)=>T.vertexAttrib4f(a,b,c,d,e),Bd:(a,b)=>{T.vertexAttrib4f(a,w[b>>2],w[b+
4>>2],w[b+8>>2],w[b+12>>2])},Ib:ae,va:ae,ud:ae,vd:ae,tb:ae,Cc:(a,b,c,d,e)=>T.vertexAttribI4i(a,b,c,d,e),Ac:(a,b)=>{T.vertexAttribI4i(a,t[b>>2],t[b+4>>2],t[b+8>>2],t[b+12>>2])},Bc:(a,b,c,d,e)=>T.vertexAttribI4ui(a,b,c,d,e),zc:(a,b)=>{T.vertexAttribI4ui(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Fc:(a,b,c,d,e)=>{T.vertexAttribIPointer(a,b,c,d,e)},Ad:(a,b,c,d,e,f)=>{T.vertexAttribPointer(a,b,c,!!d,e,f)},zd:(a,b,c,d)=>T.viewport(a,b,c,d),Yb:(a,b,c)=>{c=Number(c);T.waitSync(td[a],b,c)},l:()=>0,Qa:(a,b,
c)=>be(a,{Mh:t[c>>2],th:t[c+4>>2],xi:t[c+8>>2],pi:b,eh:t[c+12>>2],Vh:t[c+16>>2]}),H:(a,b)=>{a=Q(a);return a?a.requestPointerLock?Jc()?ad(a):b?(Hc(ad,2,[a]),1):-2:-1:-4},Ua:a=>{var b=r.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-la.buffer.byteLength+65535)/65536|0;try{la.grow(d);ka();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},q:ce,r:(a,b,c)=>typeof onbeforeunload==
"undefined"?-1:c!==1?-5:de(a,b),E:(a,b,c,d)=>ee(a,b,c,d,12,"blur"),c:Tc,f:(a,b,c)=>{a=Q(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},F:(a,b,c,d)=>ee(a,b,c,d,13,"focus"),C:(a,b,c,d)=>{if(!P.fullscreenEnabled())return-1;a=Q(a);if(!a)return-4;fe(a,b,c,d,"webkitfullscreenchange");return fe(a,b,c,d,"fullscreenchange")},i:(a,b,c)=>ce()?-1:ge(a,b,c,26,"gamepadconnected"),m:(a,b,c)=>ce()?-1:ge(a,b,c,27,"gamepaddisconnected"),y:(a,b,c,d)=>he(a,b,c,d,2,"keydown"),t:(a,b,c,d)=>he(a,
b,c,d,1,"keypress"),v:(a,b,c,d)=>he(a,b,c,d,3,"keyup"),Jb:(a,b,c)=>{a=R.get(a);Dc(a,b,c)},e:uc,z:(a,b,c)=>window.screen&&screen.orientation?ie(a,b,c):-1,D:(a,b,c,d)=>document.body?.requestPointerLock?(a=Q(a))?je(a,b,c,d):-4:-1,B:(a,b,c,d)=>ke(a,b,c,d),s:(a,b,c)=>le(a,b,c),A:(a,b,c,d)=>(a=Q(a))?typeof a.onwheel!="undefined"?me(a,b,c,d):-1:-4,Sa:a=>document.title=N(a),k:()=>{z("Please compile your program with async support in order to use asynchronous operations like emscripten_sleep")},Le:(a,b)=>
{var c=b>>2;b={alpha:!!n[b+0],depth:!!n[b+1],stencil:!!n[b+2],antialias:!!n[b+3],premultipliedAlpha:!!n[b+4],preserveDrawingBuffer:!!n[b+5],powerPreference:ne[t[c+2]],failIfMajorPerformanceCaveat:!!n[b+12],Ji:t[c+4],kj:t[c+5],Xh:n[b+24],ti:n[b+25],oj:t[c+7],rj:n[b+32]};a=Q(a);return!a||b.ti?0:Bd(a,b)},I:a=>{Cd==a&&(Cd=0);Cd===rd[a]&&(Cd=null);typeof P=="object"&&P.Oi(rd[a].Jg.canvas);rd[a]?.Jg.canvas&&(rd[a].Jg.canvas.Sg=void 0);rd[a]=null},J:a=>{Cd=rd[a];h.ctx=T=Cd?.Jg;return!a||T?0:-5},qb:(a,b)=>
{var c=0,d=0,e;for(e of qe()){var f=b+c;u[a+d>>2]=f;c+=A(e,r,f,Infinity)+1;d+=4}return 0},rb:(a,b)=>{var c=qe();u[a>>2]=c.length;a=0;for(var d of c)a+=Oa(d)+1;u[b>>2]=a;return 0},Ha:a=>{ja=a;dc(a)},j:function(a){try{var b=K(a);Lb(b);return 0}catch(c){if(typeof M=="undefined"||c.name!=="ErrnoError")throw c;return c.hg}},w:function(a,b,c,d){try{a:{var e=K(a);a=b;for(var f,g=b=0;g<c;g++){var m=u[a>>2],k=u[a+4>>2];a+=8;var p=e,q=m,v=k,C=f,D=n;if(v<0||C<0)throw new B(28);if(p.fd===null)throw new B(8);
if((p.flags&2097155)===1)throw new B(8);if(G(p.node.mode))throw new B(31);if(!p.bg.read)throw new B(28);var F=typeof C!="undefined";if(!F)C=p.position;else if(!p.seekable)throw new B(70);var J=p.bg.read(p,D,q,v,C);F||(p.position+=J);var I=J;if(I<0){var S=-1;break a}b+=I;if(I<k)break;typeof f!="undefined"&&(f+=I)}S=b}u[d>>2]=S;return 0}catch(oa){if(typeof M=="undefined"||oa.name!=="ErrnoError")throw oa;return oa.hg}},db:function(a,b,c,d){b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;
var e=K(a);Mb(e,b,c);y[d>>3]=BigInt(e.position);e.Kg&&b===0&&c===0&&(e.Kg=null);return 0}catch(f){if(typeof M=="undefined"||f.name!=="ErrnoError")throw f;return f.hg}},eb:function(a){try{var b=K(a);return b.bg?.Yg?.(b)}catch(c){if(typeof M=="undefined"||c.name!=="ErrnoError")throw c;return c.hg}},u:function(a,b,c,d){try{a:{var e=K(a);a=b;for(var f,g=b=0;g<c;g++){var m=u[a>>2],k=u[a+4>>2];a+=8;var p=Nb(e,n,m,k,f);if(p<0){var q=-1;break a}b+=p;if(p<k)break;typeof f!="undefined"&&(f+=p)}q=b}u[d>>2]=
q;return 0}catch(v){if(typeof M=="undefined"||v.name!=="ErrnoError")throw v;return v.hg}},_a:dc};function Le(a=[]){var b=Ie;a.unshift(ba);var c=a.length,d=Oc((c+1)*4),e=d,f;for(f of a)u[e>>2]=Pc(f),e+=4;u[e>>2]=0;try{var g=b(c,d);ja=g;dc(g)}catch(m){cc(m)}}
async function Me(){var a=aa;if(h.preRun)for(typeof h.preRun=="function"&&(h.preRun=[h.preRun]);h.preRun.length;)ya();ua(xa);bb>0&&await new Promise(c=>cb=c);var b=h.setStatus;b&&(b("Running..."),await new Promise(c=>setTimeout(c,1)),setTimeout(b,1,""));if(!ia){h.noFSInit||ob||Ob();Ne.Cf();pb=!1;h.onRuntimeInitialized?.();h.noInitialRun||Le(a);if(h.postRun)for(typeof h.postRun=="function"&&(h.postRun=[h.postRun]);h.postRun.length;)wa();ua(va)}}var Ne;
(async function(){function a(c){c=Ne=c.exports;Ie=h._main=c.Df;ye=h._SDL_free=c.Ef;h._free=c.Ff;Rd=h._malloc=c.Gf;ue=h._SDL_malloc=c.If;h._SDL_calloc=c.Jf;te=h._Emscripten_force_free=c.Kf;h._SDL_realloc=c.Lf;h._CallSDLEmscriptenMainFunction=c.Mf;ze=h._Emscripten_HandlePointerEnter=c.Nf;Ae=h._Emscripten_HandlePointerLeave=c.Of;Be=h._Emscripten_HandlePointerGeneric=c.Pf;xe=h._Emscripten_HandleMouseButtonUpGlobal=c.Qf;Ce=h._Emscripten_SendDragEvent=c.Rf;Fe=h._Emscripten_SendDragCompleteEvent=c.Sf;De=
h._Emscripten_SendDragTextEvent=c.Tf;Ee=h._Emscripten_SendDragFileEvent=c.Uf;we=h._Emscripten_HandleLockKeysCheck=c.Vf;He=h._Emscripten_SendSystemThemeChangedEvent=c.Wf;Ge=h._requestFullscreenThroughSDL=c.Xf;Je=c.Yf;Rc=c.Zf;Oc=c._f;Qc=c.$f;la=c.Bf;R=c.Hf;ka();return Ne}var b={a:Ke};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});pa??=h.locateFile?h.locateFile("playground_nirvana.wasm",da):da+"playground_nirvana.wasm";return function(c){return a(c.instance)}(await sa(b))})().then(()=>
Me());
