var h;h||=typeof Module != 'undefined' ? Module : {};h.expectedDataFileDownloads||(h.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a=typeof ENVIRONMENT_IS_WASM_WORKER!="undefined"&&ENVIRONMENT_IS_WASM_WORKER;typeof ENVIRONMENT_IS_PTHREAD!="undefined"&&ENVIRONMENT_IS_PTHREAD||a||async function(b){async function c(m,n){h.dataFileDownloads||(h.dataFileDownloads={});try{var t=await fetch(m)}catch(I){throw Error(`Network Error: ${m}`,{e:I});}if(!t.ok)throw Error(`${t.status}: ${t.url}`);var w=[];n=Number(t.headers.get("Content-Length")||n);var C=0;h.setStatus&&h.setStatus("Downloading data...");for(t=t.body.getReader();;){var D;
({done:D,value:G}=await t.read());if(D)break;w.push(G);C+=G.length;h.dataFileDownloads[m]={loaded:C,total:n};var G=D=0;for(var J of Object.values(h.dataFileDownloads))D+=J.loaded,G+=J.total;h.setStatus&&h.setStatus(`Downloading data... (${D}/${G})`)}m=new Uint8Array(w.map(I=>I.length).reduce((I,R)=>I+R,0));J=0;for(let I of w)m.set(I,J),J+=I.length;return m.buffer}async function d(m){m.addRunDependency("datafile_/Users/shenyiwen/projects/fountain2/bin/emscripten/model_viewer/playground_model_viewer.data");
m.preloadResults||(m.preloadResults={});m.preloadResults["/Users/shenyiwen/projects/fountain2/bin/emscripten/model_viewer/playground_model_viewer.data"]={hj:!1};k||=await f;await async function(n){if(!n)throw Error("Loading data file failed.");if(n.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+n.constructor.name);n=new Uint8Array(n);for(var t of b.files)m.FS_createDataFile(t.filename,null,n.subarray(t.start,t.end),!0,!0,!0);m.removeRunDependency("datafile_/Users/shenyiwen/projects/fountain2/bin/emscripten/model_viewer/playground_model_viewer.data")}(k)}
typeof window==="object"?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):typeof process==="undefined"&&typeof location!=="undefined"&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var e=h.locateFile?h.locateFile("playground_model_viewer.data",""):"playground_model_viewer.data",g=b.remote_package_size,f,k=h.getPreloadedPackage&&h.getPreloadedPackage(e,g);k||(f=c(e,g));h.FS_createPath?d(h):(h.preRun||
(h.preRun=[]),h.preRun.push(d))}({files:[{filename:"/assets.dat",start:0,end:85794927}],remote_package_size:85794927})})();var aa=[],ba=globalThis.document?.currentScript?.src,ca="",da;try{ca=(new URL(".",ba)).href}catch{}da=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var ea=console.log.bind(console),l=console.error.bind(console),fa,ha=!1;
function ia(){if(!p?.buffer?.resizable){var a=ja.buffer;p=new Int8Array(a);ka=new Int16Array(a);q=new Uint8Array(a);la=new Uint16Array(a);r=new Int32Array(a);u=new Uint32Array(a);v=new Float32Array(a);x=new Float64Array(a);y=new BigInt64Array(a)}}function ma(){var a=h.preRun;a&&(typeof a=="function"&&(a=[a]),na.push(...a));for(a=na;a.length>0;)a.shift()(h)}function oa(){var a=h.postRun;a&&(typeof a=="function"&&(a=[a]),pa.push(...a));for(a=pa;a.length>0;)a.shift()(h)}
function z(a){a=`Aborted(${a})`;l(a);ha=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var qa;async function ra(a){if(!fa)try{var b=await da(a);return new Uint8Array(b)}catch{}if(a==qa&&fa)a=new Uint8Array(fa);else throw"both async and sync fetching of the wasm failed";return a}async function sa(a,b){try{var c=await ra(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),z(d)}}
async function ta(a){var b=qa;if(!fa)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return sa(b,a)}class ua{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var p,pa=[],na=[],u;class va{constructor(a){this.mh=a-24}init(a,b){u[this.mh+16>>2]=0;u[this.mh+4>>2]=a;u[this.mh+8>>2]=b}}
var wa=0,xa=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},ya=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=xa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},za=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Aa=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],
Ba=()=>a=>(crypto.getRandomValues(a),0),Ca=a=>(Ca=Ba())(a),Da=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c=c.charAt(0)==="/"}b=xa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ea=globalThis.TextDecoder&&new TextDecoder,A=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(d-b>16&&a.buffer&&Ea)return Ea.decode(a.subarray(b,d));for(c="";b<d;){var e=
a[b++];if(e&128){var g=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=(e&240)==224?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Fa=[],Ga=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},B=(a,b,c,d)=>{if(!(d>0))return 0;var e=c;d=c+d-1;for(var g=
0;g<a.length;++g){var f=a.codePointAt(g);if(f<=127){if(c>=d)break;b[c++]=f}else if(f<=2047){if(c+1>=d)break;b[c++]=192|f>>6;b[c++]=128|f&63}else if(f<=65535){if(c+2>=d)break;b[c++]=224|f>>12;b[c++]=128|f>>6&63;b[c++]=128|f&63}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63;b[c++]=128|f>>6&63;b[c++]=128|f&63;g++}}b[c]=0;return c-e},Ha=a=>{var b=Array(Ga(a)+1);a=B(a,b,0,b.length);b.length=a;return b},Ia=[];function Ja(a,b){Ia[a]={input:[],output:[],Dg:b};Ka(a,La)}
var La={open(a){var b=Ia[a.node.ah];if(!b)throw new E(43);a.gg=b;a.seekable=!1},close(a){a.gg.Dg.Yg(a.gg)},Yg(a){a.gg.Dg.Yg(a.gg)},read(a,b,c,d){if(!a.gg||!a.gg.Dg.Yh)throw new E(60);for(var e=0,g=0;g<d;g++){try{var f=a.gg.Dg.Yh(a.gg)}catch(k){throw new E(29);}if(f===void 0&&!e)throw new E(6);if(f===null||f===void 0)break;e++;b[c+g]=f}e&&(a.node.Fg=Date.now());return e},write(a,b,c,d){if(!a.gg||!a.gg.Dg.Kh)throw new E(60);try{for(var e=0;e<d;e++)a.gg.Dg.Kh(a.gg,b[c+e])}catch(g){throw new E(29);}d&&
(a.node.pg=a.node.mg=Date.now());return e}},Ma={Yh(){a:{if(!Fa.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}Fa=Ha(a)}a=Fa.shift()}return a},Kh(a,b){b===null||b===10?(ea(A(a.output)),a.output=[]):b!=0&&a.output.push(b)},Yg(a){a.output?.length>0&&(ea(A(a.output)),a.output=[])},Di(){return{Xi:25856,Zi:5,Wi:191,Yi:35387,Vi:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ei(){return 0},Fi(){return[24,
80]}},Na={Kh(a,b){b===null||b===10?(l(A(a.output)),a.output=[]):b!=0&&a.output.push(b)},Yg(a){a.output?.length>0&&(l(A(a.output)),a.output=[])}},F={Ag:null,Cg(){return F.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||(c&61440)===4096)throw new E(63);F.Ag||(F.Ag={dir:{node:{sg:F.$f.sg,Eg:F.$f.Eg,Zg:F.$f.Zg,kh:F.$f.kh,ci:F.$f.ci,qh:F.$f.qh,oh:F.$f.oh,nh:F.$f.nh,ph:F.$f.ph},stream:{zg:F.ag.zg}},file:{node:{sg:F.$f.sg,Eg:F.$f.Eg},stream:{zg:F.ag.zg,read:F.ag.read,write:F.ag.write,
Hh:F.ag.Hh,ai:F.ag.ai}},link:{node:{sg:F.$f.sg,Eg:F.$f.Eg,Kg:F.$f.Kg},stream:{}},Vh:{node:{sg:F.$f.sg,Eg:F.$f.Eg},stream:Oa}});c=Pa(a,b,c,d);H(c.mode)?(c.$f=F.Ag.dir.node,c.ag=F.Ag.dir.stream,c.dg={}):(c.mode&61440)===32768?(c.$f=F.Ag.file.node,c.ag=F.Ag.file.stream,c.lg=0,c.dg=F.ri??(F.ri=new Uint8Array(0))):(c.mode&61440)===40960?(c.$f=F.Ag.link.node,c.ag=F.Ag.link.stream):(c.mode&61440)===8192&&(c.$f=F.Ag.Vh.node,c.ag=F.Ag.Vh.stream);c.Fg=c.pg=c.mg=Date.now();a&&(a.dg[b]=c,a.Fg=a.pg=a.mg=c.Fg);
return c},$f:{sg(a){var b={};b.pi=(a.mode&61440)===8192?a.id:1;b.Bi=a.id;b.mode=a.mode;b.Ki=1;b.uid=0;b.yi=0;b.ah=a.ah;H(a.mode)?b.size=4096:(a.mode&61440)===32768?b.size=a.lg:(a.mode&61440)===40960?b.size=a.link.length:b.size=0;b.Fg=new Date(a.Fg);b.pg=new Date(a.pg);b.mg=new Date(a.mg);b.ii=4096;b.ji=Math.ceil(b.size/b.ii);return b},Eg(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.lg!=b&&(c=a.dg,a.dg=new Uint8Array(b),a.dg.set(c.subarray(0,
Math.min(b,a.lg))),a.lg=b))},Zg(){F.wh||(F.wh=new E(44),F.wh.stack="<generic error, no stack>");throw F.wh;},kh(a,b,c,d){return F.createNode(a,b,c,d)},ci(a,b,c){try{var d=Qa(b,c)}catch(g){}if(d){if(H(a.mode))for(var e in d.dg)throw new E(55);Ra(d)}delete a.parent.dg[a.name];b.dg[c]=a;a.name=c;b.mg=b.pg=a.parent.mg=a.parent.pg=Date.now()},qh(a,b){delete a.dg[b];a.mg=a.pg=Date.now()},oh(a,b){var c=Qa(a,b),d;for(d in c.dg)throw new E(55);delete a.dg[b];a.mg=a.pg=Date.now()},nh(a){return[".","..",...Object.keys(a.dg)]},
ph(a,b,c){a=F.createNode(a,b,41471,0);a.link=c;return a},Kg(a){if((a.mode&61440)!==40960)throw new E(28);return a.link}},ag:{read(a,b,c,d,e){if(e>=a.node.lg)return 0;d=Math.min(a.node.lg-e,d);b.set(a.node.dg.subarray(e,e+d),c);return d},write(a,b,c,d,e,g){b.buffer===p.buffer&&(g=!1);if(!d)return 0;a=a.node;a.pg=a.mg=Date.now();if(g)a.dg=b.subarray(c,c+d),a.lg=d;else if(a.lg||e){g=e+d;var f=a.dg.length;f>=g||(g=Math.max(g,f*(f<1048576?2:1.125)>>>0),f&&(g=Math.max(g,256)),f=a.dg.subarray(0,a.lg),a.dg=
new Uint8Array(g),a.dg.set(f));a.dg.set(b.subarray(c,c+d),e);a.lg=Math.max(a.lg,e+d)}else a.dg=b.slice(c,c+d),a.lg=d;return d},zg(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&61440)===32768&&(b+=a.node.lg);if(b<0)throw new E(28);return b},Hh(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new E(43);a=a.node.dg;if(e&2||a.buffer!==p.buffer){d=!0;z();e=void 0;if(!e)throw new E(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);p.set(a,e)}}else d=!1,
e=a.byteOffset;return{mh:e,Si:d}},ai(a,b,c,d){F.ag.write(a,b,0,d,c,!1);return 0}}},Sa=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ta=async a=>{a=await da(a);return new Uint8Array(a)},Ua=null,Va=async()=>Ua,Wa=0,Xa=null,Ya=()=>{Wa||(Ua=new Promise(a=>Xa=a));Wa++},Za=[],bb=async(a,b)=>{typeof $a!="undefined"&&ab();for(var c of Za)if(c.canHandle(b))return c.handle(a,b);return a},cb=null,db={},eb=[],fb=1,gb=null,hb=!1,ib=!0,E=class{name="ErrnoError";constructor(a){this.eg=a}},jb=class{shared={};node=
null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},kb=class{$f={};ag={};Pg=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Cg=a.Cg;this.id=fb++;this.name=b;this.mode=c;this.ah=d;this.Fg=this.pg=this.mg=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?this.mode|=146:this.mode&=-147}get Hi(){return H(this.mode)}get Gi(){return(this.mode&
61440)===8192}Mi(){}};
function K(a,b={}){if(!a)throw new E(44);b.Bh??(b.Bh=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(k=>!!k);for(var d=cb,e="/",g=0;g<a.length;g++){var f=g===a.length-1;if(f&&b.parent)break;if(a[g]!==".")if(a[g]==="..")if(e=za(e),d===d.parent){a=e+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{e=ya(e+"/"+a[g]);try{d=Qa(d,a[g])}catch(k){if(k?.eg===44&&f&&b.Li)return{path:e};throw k;}!d.Pg||f&&!b.Bh||(d=d.Pg.root);if((d.mode&61440)===40960&&(!f||b.Og)){if(!d.$f.Kg)throw new E(52);
d=d.$f.Kg(d);d.charAt(0)==="/"||(d=za(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new E(32);}function lb(a){for(var b;;){if(a===a.parent)return a=a.Cg.$h,b?a[a.length-1]!=="/"?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function mb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%gb.length}
function Ra(a){var b=mb(a.parent.id,a.name);if(gb[b]===a)gb[b]=a.Qg;else for(b=gb[b];b;){if(b.Qg===a){b.Qg=a.Qg;break}b=b.Qg}}function Qa(a,b){var c=H(a.mode)?(c=nb(a,"x"))?c:a.$f.Zg?0:2:54;if(c)throw new E(c);for(c=gb[mb(a.id,b)];c;c=c.Qg){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.$f.Zg(a,b)}function Pa(a,b,c,d){a=new kb(a,b,c,d);b=mb(a.parent.id,a.name);a.Qg=gb[b];return gb[b]=a}function H(a){return(a&61440)===16384}
function nb(a,b){return ib?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function ob(a,b){if(!H(a.mode))return 54;try{return Qa(a,b),20}catch(c){}return nb(a,"wx")}function pb(a,b,c){try{var d=Qa(a,b)}catch(e){return e.eg}if(a=nb(a,"wx"))return a;if(c){if(!H(d.mode))return 54;if(d===d.parent||lb(d)==="/")return 10}else if(H(d.mode))return 31;return 0}function qb(a,b){if(!a)throw new E(b);return a}
function L(a){a=eb[a];if(!a)throw new E(8);return a}function rb(a,b=-1){a=Object.assign(new jb,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!eb[b])break a;throw new E(33);}a.fd=b;return eb[b]=a}function sb(a,b=-1){a=rb(a,b);a.ag?.fj?.(a);return a}function tb(a,b){var c=void 0,d=c?null:a;c??=a.$f.Eg;qb(c,63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new E(22);throw e;}}var Oa={open(a){a.ag=db[a.node.ah].ag;a.ag.open?.(a)},zg(){throw new E(70);}};function Ka(a,b){db[a]={ag:b}}
function ub(a,b){var c=b==="/";if(c&&cb)throw new E(10);if(!c&&b){var d=K(b,{Bh:!1});b=d.path;d=d.node;if(d.Pg)throw new E(10);if(!H(d.mode))throw new E(54);}b={type:a,nj:{},$h:b,Ji:[]};a=a.Cg(b);a.Cg=b;b.root=a;c?cb=a:d&&(d.Pg=b,d.Cg&&d.Cg.Ji.push(b))}function vb(a,b,c){var d=K(a,{parent:!0}).node;a=Aa(a);if(!a)throw new E(28);if(a==="."||a==="..")throw new E(20);var e=ob(d,a);if(e)throw new E(e);if(!d.$f.kh)throw new E(63);return d.$f.kh(d,a,b,c)}
function wb(a,b=438){return vb(a,b&4095|32768,0)}function M(a,b=511){return vb(a,b&1023|16384,0)}function xb(a,b,c){typeof c=="undefined"&&(c=b,b=438);return vb(a,b|8192,c)}function yb(a,b){if(!Da(a))throw new E(44);var c=K(b,{parent:!0}).node;if(!c)throw new E(44);b=Aa(b);var d=ob(c,b);if(d)throw new E(d);if(!c.$f.ph)throw new E(63);c.$f.ph(c,b,a)}
function zb(a){var b=K(a,{parent:!0}).node;a=Aa(a);var c=Qa(b,a),d=pb(b,a,!0);if(d)throw new E(d);if(!b.$f.oh)throw new E(63);if(c.Pg)throw new E(10);b.$f.oh(b,a);Ra(c)}function Ab(a){var b=K(a,{parent:!0}).node;if(!b)throw new E(44);a=Aa(a);var c=Qa(b,a),d=pb(b,a,!1);if(d)throw new E(d);if(!b.$f.qh)throw new E(63);if(c.Pg)throw new E(10);b.$f.qh(b,a);Ra(c)}function Bb(a,b){a=K(a,{Og:!b}).node;return qb(a.$f.sg,63)(a)}
function Cb(a,b){a=typeof a=="string"?K(a,{Og:!0}).node:a;tb(a,{mode:b&4095|a.mode&-4096,mg:Date.now(),ej:void 0})}
function Db(a,b,c=438){if(a==="")throw new E(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var g=K(a,{Og:!(b&131072),Li:!0});d=g.node;a=g.path}g=!1;if(b&64)if(d){if(b&128)throw new E(20);}else{if(e)throw new E(31);d=vb(a,c|511,0);g=!0}if(!d)throw new E(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&!H(d.mode))throw new E(54);
if(!g&&(d?(d.mode&61440)===40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=H(d.mode)&&(e!=="r"||b&576)?31:nb(d,e)):e=44,e))throw new E(e);if(b&512&&!g){e=d;e=typeof e=="string"?K(e,{Og:!0}).node:e;if(H(e.mode))throw new E(31);if((e.mode&61440)!==32768)throw new E(28);if(a=nb(e,"w"))throw new E(a);tb(e,{size:0,timestamp:Date.now()})}b=rb({node:d,path:lb(d),flags:b&-131713,seekable:!0,position:0,ag:d.ag,Qi:[],error:!1});b.ag.open&&b.ag.open(b);g&&Cb(d,c&511);return b}
function Eb(a){if(a.fd===null)throw new E(8);a.Jg&&(a.Jg=null);a.node?.Mi();try{a.ag.close&&a.ag.close(a)}catch(b){throw b;}finally{eb[a.fd]=null}a.fd=null}function Fb(a,b,c){if(a.fd===null)throw new E(8);if(!a.seekable||!a.ag.zg)throw new E(70);if(c!=0&&c!=1&&c!=2)throw new E(28);a.position=a.ag.zg(a,b,c);a.Qi=[];return a.position}
function Gb(a,b,c,d,e,g){if(d<0||e<0)throw new E(28);if(a.fd===null)throw new E(8);if((a.flags&2097155)===0)throw new E(8);if(H(a.node.mode))throw new E(31);if(!a.ag.write)throw new E(28);a.seekable&&a.flags&1024&&Fb(a,0,2);var f=typeof e!="undefined";if(!f)e=a.position;else if(!a.seekable)throw new E(70);b=a.ag.write(a,b,c,d,e,g);f||(a.position+=b);return b}
function Hb(a,b){a=typeof a=="string"?a:lb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=ya(a+"/"+c);try{M(d)}catch(e){if(e.eg!=20)throw e;}a=d}}return d}function Ib(a,b,c,d){a=ya((typeof a=="string"?a:lb(a))+"/"+b);return wb(a,Sa(c,d))}function Jb(a,b,c,d,e,g){var f=b;a&&(a=typeof a=="string"?a:lb(a),f=b?ya(a+"/"+b):a);a=Sa(d,e);f=wb(f,a);c&&(typeof c=="string"&&(c=Ha(c)),c.subarray||(c=new Uint8Array(c)),Cb(f,a|146),b=Db(f,577),Gb(b,c,0,c.length,0,g),Eb(b),Cb(f,a))}
function Kb(a,b,c,d){a=ya((typeof a=="string"?a:lb(a))+"/"+b);b=Sa(!!c,!!d);Kb.Zh??(Kb.Zh=64);var e=Kb.Zh++<<8|0;Ka(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,f,k,m){for(var n=0,t=0;t<m;t++){try{var w=c()}catch(C){throw new E(29);}if(w===void 0&&!n)throw new E(6);if(w===null||w===void 0)break;n++;f[k+t]=w}n&&(g.node.Fg=Date.now());return n},write(g,f,k,m){for(var n=0;n<m;n++)try{d(f[k+n])}catch(t){throw new E(29);}m&&(g.node.pg=g.node.mg=Date.now());return n}});return xb(a,
b,e)}function Lb(a){if(!(a.Gi||a.Hi||a.link||a.dg))if(globalThis.XMLHttpRequest)z("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.dg=(void 0)(a.url)}catch(b){throw new E(29);}}
function Mb(a,b,c,d,e){class g{Bg=!1;ig=[];jg=void 0;Tg=0;Ng=0;get(n){if(!(n>this.length-1||n<0)){var t=n%this.Xg;return this.jg(n/this.Xg|0)[t]}}xi(n){this.jg=n}Vg(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);n.status>=200&&n.status<300||n.status===304||z(`Couldn't load ${c}. Status: ${n.status}`);var t=Number(n.getResponseHeader("Content-length")),w,C=(w=n.getResponseHeader("Accept-Ranges"))&&w==="bytes";n=(w=n.getResponseHeader("Content-Encoding"))&&w==="gzip";var D=1048576;C||(D=
t);var G=this;G.xi(J=>{var I=J*D,R=(J+1)*D-1;R=Math.min(R,t-1);if(typeof G.ig[J]=="undefined"){var X=G.ig;I>R&&z(`invalid range (${I}, ${R}) or no bytes requested!`);R>t-1&&z(`only ${t} bytes available! programmer error!`);var N=new XMLHttpRequest;N.open("GET",c,!1);t!==D&&N.setRequestHeader("Range",`bytes=${I}-${R}`);N.responseType="arraybuffer";N.overrideMimeType&&N.overrideMimeType("text/plain; charset=x-user-defined");N.send(null);N.status>=200&&N.status<300||N.status===304||z(`Couldn't load ${c}. Status: ${N.status}`);
I=N.response!==void 0?new Uint8Array(N.response||[]):Ha(N.responseText??"");X[J]=I}typeof G.ig[J]=="undefined"&&z("doXHR failed!");return G.ig[J]});if(n||!t)D=t=1,D=t=this.jg(0).length,ea("LazyFiles on gzip forces download of the whole file when length is accessed");this.Tg=t;this.Ng=D;this.Bg=!0}get length(){this.Bg||this.Vg();return this.Tg}get Xg(){this.Bg||this.Vg();return this.Ng}}if(globalThis.XMLHttpRequest){z("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var f=new g;var k=void 0}else k=c,f=void 0;var m=Ib(a,b,d,e);f?m.dg=f:k&&(m.dg=null,m.url=k);Object.defineProperties(m,{lg:{get:function(){return this.dg.length}}});a={};for(let [n,t]of Object.entries(m.ag))a[n]=(...w)=>{Lb(m);return t(...w)};a.read=(n,t,w,C,D)=>{Lb(m);n=n.node.dg;if(D>=n.length)t=0;else{C=Math.min(n.length-D,C);if(n.slice)for(var G=0;G<C;G++)t[w+G]=n[D+G];else for(G=0;G<C;G++)t[w+G]=n.get(D+G);t=C}return t};a.Hh=()=>{Lb(m);z();throw new E(48);};m.ag=a;return m}
var O={},q,Nb=(a,b)=>a?A(q,a,b):"",r,y;function Ob(a,b,c){if(b.charAt(0)==="/")return b;a=a===-100?"/":L(a).path;if(b.length==0){if(!c)throw new E(44);return a}return a+"/"+b}
function Pb(a,b){u[a>>2]=b.pi;u[a+4>>2]=b.mode;u[a+8>>2]=b.Ki;u[a+12>>2]=b.uid;u[a+16>>2]=b.yi;u[a+20>>2]=b.ah;y[a+24>>3]=BigInt(b.size);r[a+32>>2]=4096;r[a+36>>2]=b.ji;var c=b.Fg.getTime(),d=b.pg.getTime(),e=b.mg.getTime();y[a+40>>3]=BigInt(Math.floor(c/1E3));u[a+48>>2]=c%1E3*1E3*1E3;y[a+56>>3]=BigInt(Math.floor(d/1E3));u[a+64>>2]=d%1E3*1E3*1E3;y[a+72>>3]=BigInt(Math.floor(e/1E3));u[a+80>>2]=e%1E3*1E3*1E3;y[a+88>>3]=BigInt(b.Bi);return 0}
var Rb=void 0,Sb=()=>{var a=r[+Rb>>2];Rb+=4;return a},ka,Tb=a=>{var b=Error().stack.toString(),c=b.split("\n");b="";var d=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),e=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),g;for(g of c){var f=e.exec(g);if(f?.length==5){c=f[1];var k=f[2];var m=f[3];f=f[4]}else if(f=d.exec(g),f?.length>=4)c=f[1],k=f[2],m=f[3],f=f[4]|0;else{b+=g+"\n";continue}c=="_emscripten_log"||c=="_emscripten_get_callstack"?b="":a&24&&(a&64&&(k=k.substring(k.replace(/\\/g,"/").lastIndexOf("/")+
1)),b+=`    at ${c} (${k}:${m}:${f})\n`)}return b=b.replace(/\s+$/,"")},Ub=[0,31,60,91,121,152,182,213,244,274,305,335],Vb=[0,31,59,90,120,151,181,212,243,273,304,334],Wb=[],x,Xb=(a,b)=>{Wb.length=0;for(var c;c=q[a++];){var d=c!=105;d&=c!=112;b+=d&&b%8?4:0;Wb.push(c==112?u[b>>2]:c==106?y[b>>3]:c==105?r[b>>2]:x[b>>3]);b+=d?8:4}return Wb},Zb=(a,b,c)=>{b=Xb(b,c);return Yb[a](...b)},ic=(a,b)=>{$b=a;ac=b;if(!bc)return 1;if(a==0)cc=function(){setTimeout(dc,Math.max(0,ec+b-performance.now())|0)};else if(a==
1)cc=function(){fc(dc)};else{if(!hc)if(globalThis.scheduler)hc=scheduler.postTask.bind(scheduler);else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);hc=d=>{c.push(d);postMessage("setimmediate","*")}}cc=function(){hc(dc)}}return 0},jc=a=>{if(!(a instanceof ua||a=="unwind"))throw a;},tc=(a,b,c,d,e)=>{bc=a;kc=d;var g=lc;dc=function(){if(!ha)if(mc.length>0){var f=mc.shift();f.ij(f.Ti);if(nc){var k=nc,m=k%1==0?k-1:Math.floor(k);nc=f.aj?m:(8*k+(m+
.5))/9}h.setStatus&&(f=h.statusMessage||"Please wait...",k=nc??0,m=oc.gj??0,k?k<m?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(f):h.setStatus(""));g<lc||setTimeout(dc,0)}else if(!(g<lc))if(pc=pc+1|0,$b==1&&ac>1&&pc%ac!=0)cc();else{$b==0&&(ec=performance.now());a:if(!ha){for(f of qc)if(f()===!1)break a;rc(a);for(k of sc)k()}g<lc||cc()}};e||(b>0?ic(0,1E3/b):ic(1,1),cc());if(c)throw"unwind";},rc=a=>{if(!ha)try{a()}catch(b){jc(b)}finally{}},bc=null,cc=null,lc=0,kc=0,$b=0,ac=
0,pc=0,mc=[],qc=[],sc=[];function uc(){cc&&(cc=null,lc++)}var vc=0;function fc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(vc)for(;b+2>=vc;)vc+=1E3/60;else vc=b+1E3/60;setTimeout(a,Math.max(vc-b,0))}}var oc={},ec,dc,hc,nc;function wc(a){var b=P.ng[a];b.target.removeEventListener(b.kg,b.Xh,b.vg);P.ng.splice(a,1)}
function xc(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var k=0;k<g.length;k++)if(g[k]!=f[k])return!1;return!0}for(var e of P.Gg)if(e.Mh==a&&d(e.Th,c))return;P.Gg.push({Mh:a,bi:b,Th:c});P.Gg.sort((g,f)=>g.bi-f.bi)}function yc(a){P.Gg=P.Gg.filter(b=>b.Mh!=a)}function zc(){return navigator.userActivation?navigator.userActivation.isActive:P.Eh&&P.li.Sh}function Ac(){if(zc()){var a=P.Gg;P.Gg=[];for(var b of a)b.Mh(...b.Th)}}
function Bc(a){if(!a.target)return-4;if(a.og)a.Xh=function(c){++P.Eh;P.li=a;Ac();a.yg(c);Ac();--P.Eh},a.target.addEventListener(a.kg,a.Xh,a.vg),P.ng.push(a);else for(var b=0;b<P.ng.length;++b)P.ng[b].target==a.target&&P.ng[b].kg==a.kg&&wc(b--);return 0}function Cc(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var P={Ui:0,Dh:0,Fh:0,lj:0,Rh:0,Oh:0,Ah:0,cj:0,Ih:0,bj:0,Ch:0,Jh:0,Qh:0,sj:0,pj(){for(;P.ng.length;)wc(P.ng.length-1);P.Gg=[]},Eh:0,Gg:[],ng:[],Oi:(a,b)=>{for(var c=0;c<P.ng.length;++c)P.ng[c].target!=a||b&&b!=P.ng[c].kg||wc(c--)},qj(a){var b=!1;for(let c=0;c<P.ng.length;++c){let d=P.ng[c];d.target===a.target&&d.rg===a.rg&&d.og===a.og&&d.wg===a.wg&&(wc(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled??document.webkitFullscreenEnabled}},Dc=[0,document,window],Q=a=>{a=
a>2?a?A(q,a):"":a;return Dc[a]||document.querySelector(a)},Fc=a=>{var b=Ga(a)+1,c=Ec(b);B(a,q,c,b);return c},Ic=a=>{var b=Gc(),c=Ec(8),d=c+4;a=Fc(a.id);if(a=Q(a))r[c>>2]=a.width,r[d>>2]=a.height;c=[r[c>>2],r[d>>2]];Hc(b);return c},Jc=(a,b,c)=>{a=Q(a);if(!a)return-4;a.width=b;a.height=c;return 0},Kc=(a,b,c)=>{if(a.$i){var d=Gc();a=Fc(a.id);Jc(a,b,c);Hc(d)}else a.width=b,a.height=c},Lc=0,Mc=[],S=a=>{var b=Mc[a];b||(Mc[a]=b=Nc.get(a));return b},Oc=a=>{function b(){if(!(document.fullscreenElement??document.webkitFullscreenElement)){document.removeEventListener("fullscreenchange",
b);document.removeEventListener("webkitfullscreenchange",b);Kc(a,d,e);a.style.width=g;a.style.height=f;a.style.backgroundColor=k;m||(document.body.style.backgroundColor="white");document.body.style.backgroundColor=m;a.style.paddingLeft=n;a.style.paddingRight=t;a.style.paddingTop=w;a.style.paddingBottom=C;a.style.marginLeft=D;a.style.marginRight=G;a.style.marginTop=J;a.style.marginBottom=I;document.body.style.margin=R;document.documentElement.style.overflow=X;document.body.scroll=N;a.style.imageRendering=
me;a.Rg&&a.Rg.Ig.viewport(0,0,d,e);var Qb=Lc;Qb.dh&&S(Qb.dh)(37,0,Qb.Uh)}}var c=Ic(a),d=c[0],e=c[1],g=a.style.width,f=a.style.height,k=a.style.backgroundColor,m=document.body.style.backgroundColor,n=a.style.paddingLeft,t=a.style.paddingRight,w=a.style.paddingTop,C=a.style.paddingBottom,D=a.style.marginLeft,G=a.style.marginRight,J=a.style.marginTop,I=a.style.marginBottom,R=document.body.style.margin,X=document.documentElement.style.overflow,N=document.body.scroll,me=a.style.imageRendering;document.addEventListener("fullscreenchange",
b);document.addEventListener("webkitfullscreenchange",b)},Pc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Qc=a=>Dc.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},Rc=(a,b)=>{if(b.Lh!=0||b.sh!=0){Oc(a);var c=b.Pi?innerWidth:screen.width,d=b.Pi?innerHeight:screen.height,e=Qc(a),g=e.width;e=e.height;var f=Ic(a),k=f[0];f=f[1];b.Lh==3?(Pc(a,(d-e)/2,(c-g)/2),c=g,d=e):b.Lh==2&&(c*f<k*d?(g=f*c/k,Pc(a,(d-g)/2,0),d=g):(g=k*d/f,Pc(a,0,(c-g)/
2),c=g));var m;(m=a.style).backgroundColor||(m.backgroundColor="black");let n;(n=document.body.style).backgroundColor||(n.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";b.wi==1&&(a.style.imageRendering="optimizeSpeed",a.style.imageRendering="-moz-crisp-edges",a.style.imageRendering="-o-crisp-edges",a.style.imageRendering="-webkit-optimize-contrast",a.style.imageRendering="optimize-contrast",a.style.imageRendering="crisp-edges",a.style.imageRendering="pixelated");m=b.sh==2?devicePixelRatio:
1;b.sh!=0&&(c=c*m|0,d=d*m|0,Kc(a,c,d),a.Rg&&a.Rg.Ig.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return P.fullscreenEnabled()?-3:-1;Lc=b;b.dh&&S(b.dh)(37,0,b.Uh);return 0},Sc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Tc=a=>{var b=document.fullscreenElement??document.webkitFullscreenElement,c=!!b;p[a]=c;p[a+1]=P.fullscreenEnabled();
var d=c?b:P.Ni,e=d?.id??"";B(Cc(d),q,a+2,128);B(e,q,a+130,128);r[a+260>>2]=d?.clientWidth??0;r[a+264>>2]=d?.clientHeight??0;r[a+268>>2]=screen.width;r[a+272>>2]=screen.height;c&&(P.Ni=b)},Uc=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+c*8+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)p[a+c+1040]=b.buttons[c].pressed,x[a+c*8+528>>3]=b.buttons[c].value;p[a+1104]=b.connected;r[a+1108>>2]=b.index;r[a+8>>2]=b.axes.length;r[a+12>>2]=b.buttons.length;B(b.id,q,a+1112,64);B(b.mapping,
q,a+1176,64)},Vc=a=>{setTimeout(()=>{rc(a)},1E4)},Wc=[];
function ab(){function a(){}Xc||(Xc=!0,Za.push({canHandle:b=>!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(b),handle:async(b,c)=>{var d=new Blob([b],{type:Yc(c)});d.size!==b.length&&(d=new Blob([(new Uint8Array(b)).buffer],{type:Yc(c)}));var e=URL.createObjectURL(d);return new Promise((g,f)=>{var k=new Image;k.onload=()=>{var m=document.createElement("canvas");m.width=k.width;m.height=k.height;m.getContext("2d").drawImage(k,0,0);URL.revokeObjectURL(e);g(b)};k.onerror=()=>{l(`Image ${e} could not be decoded`);
f()};k.src=e})}}),Za.push({canHandle:b=>!h.noAudioDecoding&&b.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(b,c)=>new Promise(d=>{function e(){g||(g=!0,d(b))}var g=!1,f=URL.createObjectURL(new Blob([b],{type:Yc(c)})),k=new Audio;k.addEventListener("canplaythrough",()=>e(k));k.onerror=()=>{if(!g){l(`warning: browser could not fully decode audio ${c}, trying slower base64 approach`);var m="data:audio/x-"+c.slice(-3)+";base64,",n="",t=0,w=0,C;for(C of b)for(t=t<<8|C,w+=8;w>=6;){var D=t>>w-6&63;
w-=6;n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[D]}w==2?(n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],n+="=="):w==4&&(n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],n+="=");k.src=m+n;e(k)}};k.src=f;Vc(()=>{e(k)})})}),h.canvas&&document.addEventListener("pointerlockchange",a))}function Zc(a){a=a.getContext("2d");if(!a)return null;h.ctx=a;Wc.forEach(b=>b());ab();return a}
function Yc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var $a={},Xc,T,$c=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");return a.getSupportedExtensions()?.filter(c=>
b.includes(c))??[]},ad=1,bd=[],U=[],cd=[],dd=[],ed=[],V=[],fd=[],gd=[],W=[],hd=[],jd=[],kd=[],ld={},md={},nd=4,od=0,pd=a=>{for(var b=ad++,c=a.length;c<b;c++)a[c]=null;return b},qd=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=T[c](),f=g&&pd(d);g?(g.name=f,d[f]=g):Y||=1282;r[b+e*4>>2]=f}},sd=(a,b)=>{a.Xg||(a.Xg=a.getContext,a.getContext=function(d,e){e=a.Xg(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?rd(c,b):0},rd=(a,b)=>{var c=pd(gd),d={handle:c,
attributes:b,version:b.Ii,Ig:a};a.canvas&&(a.canvas.Rg=d);gd[c]=d;if(typeof b.Wh=="undefined"||b.Wh)if((a=d)||(a=td),!a.Ai){a.Ai=!0;b=a.Ig;b.mj=b.getExtension("WEBGL_multi_draw");b.ui=b.getExtension("EXT_polygon_offset_clamp");b.ti=b.getExtension("EXT_clip_control");b.Ri=b.getExtension("WEBGL_polygon_mode");b.dj=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.jj=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");a.version>=2&&(b.qg=b.getExtension("EXT_disjoint_timer_query_webgl2"));
if(a.version<2||!b.qg)b.qg=b.getExtension("EXT_disjoint_timer_query");for(var e of $c(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},Y,td,ud=a=>{T.bindVertexArray(fd[a])},v,vd=(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2];T.deleteVertexArray(fd[d]);fd[d]=null}},wd=(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},xd=[],yd=(a,b)=>{for(var c=xd[a],d=0;d<a;d++)c[d]=r[b+d*4>>2];T.drawBuffers(c)},zd=(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},Ad=(a,b)=>{qd(a,b,"createVertexArray",
fd)},Bd=(a,b,c,d,e,g,f,k)=>{b=U[b];if(a=T[a](b,c))d=k&&B(a.name,q,k,d),e&&(r[e>>2]=d),g&&(r[g>>2]=a.size),f&&(r[f>>2]=a.type)},Cd=(a,b)=>{u[a>>2]=b;u[a+4>>2]=(b-u[a>>2])/4294967296},Dd=()=>{var a=$c(T);return a=a.concat(a.map(b=>"GL_"+b))},Ed=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:c!=0&&c!=1&&(Y||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=T.getParameter(34467);d=e?e.length:0;break;case 33309:if(td.version<2){Y||=1282;return}d=Dd().length;break;case 33307:case 33308:if(td.version<
2){Y||=1280;return}d=a==33307?3:0}if(d===void 0)switch(e=T.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Y||=1280;return;case "object":if(e===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:Y||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||
e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:r[b+a*4>>2]=e[a];break;case 2:v[b+a*4>>2]=e[a];break;case 4:p[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){Y||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:Y||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:Cd(b,d);break;case 0:r[b>>
2]=d;break;case 2:v[b>>2]=d;break;case 4:p[b]=d?1:0}}else Y||=1281},Fd=(a,b,c,d)=>{if(c){b=T.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(b===null)switch(a){case 35983:case 35368:a=0;break;default:Y||=1280;return}else if(b instanceof WebGLBuffer)a=b.name|0;else{Y||=1280;return}break;default:Y||=1280;return}switch(d){case 1:Cd(c,a);break;case 0:r[c>>2]=a;break;case 2:v[c>>2]=a;break;case 4:p[c]=a?1:0;break;default:z("internal emscriptenWebGLGetIndexed() error, bad type: "+
d)}}else Y||=1281},Gd=(a,b,c)=>{if(c){a=W[a];b=td.version<2?T.qg.getQueryObjectEXT(a,b):T.getQueryParameter(a,b);var d;typeof b=="boolean"?d=b?1:0:d=b;Cd(c,d)}else Y||=1281},Hd=(a,b,c)=>{if(c){a=T.qg.getQueryObjectEXT(W[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;r[c>>2]=d}else Y||=1281},Jd=a=>{var b=Ga(a)+1,c=Id(b);c&&B(a,q,c,b);return c},Kd=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),Ld=a=>{var b=a.bh,c=a.ei,d;if(!b){a.bh=b={};a.di={};var e=T.getProgramParameter(a,35718);for(d=0;d<e;++d){var g=T.getActiveUniform(a,
d);var f=g.name;g=g.size;var k=Kd(f);k=k>0?f.slice(0,k):f;var m=a.Ph;a.Ph+=g;c[k]=[g,m];for(f=0;f<g;++f)b[m]=f,a.di[m++]=k}}},Z=(a,b)=>{if(a){var c=a.bh[b];typeof c=="number"&&(a.bh[b]=c=T.getUniformLocation(a,a.di[b]+(c>0?`[${c}]`:"")));return c}Y||=1282},Md=(a,b,c,d)=>{if(c)if(a=U[a],Ld(a),a=T.getUniform(a,Z(a,b)),typeof a=="number"||typeof a=="boolean")switch(d){case 0:r[c>>2]=a;break;case 2:v[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+b*4>>2]=a[b];break;case 2:v[c+b*4>>2]=a[b]}else Y||=
1281},Nd=(a,b,c,d)=>{if(c)if(a=T.getVertexAttrib(a,b),b==34975)r[c>>2]=a&&a.name;else if(typeof a=="number"||typeof a=="boolean")switch(d){case 0:r[c>>2]=a;break;case 2:v[c>>2]=a;break;case 5:r[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+b*4>>2]=a[b];break;case 2:v[c+b*4>>2]=a[b];break;case 5:r[c+b*4>>2]=Math.fround(a[b])}else Y||=1281},Od=(a,b,c)=>{Nd(a,b,c,0)},Pd=a=>(a=fd[a])?T.isVertexArray(a):0,la,Qd=a=>{a-=5120;return a==0?p:a==1?q:a==2?ka:a==4?r:a==6?v:a==5||a==28922||
a==28520||a==30779||a==30782?u:la},Rd=(a,b,c,d,e)=>{a=Qd(a);b=d*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT*(od||c)+nd-1&-nd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Sd=(a,b)=>{T.vertexAttribDivisor(a,b)},Td=(a,b)=>{if(!P.fullscreenEnabled())return-1;a=Q(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?zc()?Rc(a,b):b.oi?(xc(Rc,1,[a,b]),1):-2:-3:-4},Ud=()=>{try{if(navigator.getGamepads)return(P.gh=
navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Vd=(a,b)=>{var c={target:Q(2),kg:"beforeunload",rg:28,wg:a,og:b,yg:d=>{var e=S(b)(28,0,a);e&&=e?A(q,e):"";if(e)return d.preventDefault(),d.returnValue=e},vg:!0};return Bc(c)},Wd=(a,b,c,d,e,g)=>{P.Ah||(P.Ah=Id(256));a={target:Q(a),kg:g,rg:e,wg:b,og:d,yg:f=>{var k=f.target.id??"",m=P.Ah;B(Cc(f.target),q,m+0,128);B(k,q,m+128,128);S(d)(e,m,b)&&f.preventDefault()},vg:c};return Bc(a)},Xd=(a,b,c,d,e)=>{P.Ch||(P.Ch=Id(276));return Bc({target:a,
kg:e,rg:19,wg:b,og:d,yg:g=>{var f=P.Ch;Tc(f);S(d)(19,f,b)&&g.preventDefault()},vg:c})},Yd=(a,b,c,d,e)=>{P.Dh||(P.Dh=Id(1240));b={target:Q(2),Sh:!0,kg:e,rg:d,wg:a,og:c,yg:g=>{var f=P.Dh;Uc(f,g.gamepad);S(c)(d,f,a)&&g.preventDefault()},vg:b};return Bc(b)},Zd=(a,b,c,d,e,g)=>{P.Fh||(P.Fh=Id(160));a={target:Q(a),kg:g,rg:e,wg:b,og:d,yg:f=>{var k=P.Fh;x[k>>3]=f.timeStamp;var m=k>>2;r[m+2]=f.location;p[k+12]=f.ctrlKey;p[k+13]=f.shiftKey;p[k+14]=f.altKey;p[k+15]=f.metaKey;p[k+16]=f.repeat;r[m+5]=f.charCode;
r[m+6]=f.keyCode;r[m+7]=f.which;B(f.key??"",q,k+32,32);B(f.code??"",q,k+64,32);B(f.char??"",q,k+96,32);B(f.locale??"",q,k+128,32);S(d)(e,k,b)&&f.preventDefault()},vg:c};return Bc(a)},$d=(a,b,c)=>{var d=screen.orientation;P.Ih||(P.Ih=Id(8));return Bc({target:d,kg:"change",rg:18,wg:a,og:c,yg:e=>{var g=P.Ih,f=["portrait-primary","portrait-secondary","landscape-primary","landscape-secondary"],k=["portrait","portrait","landscape","landscape"],m=0,n=window.screen?.orientation;n?(m=f.indexOf(n.type),m<0&&
(m=k.indexOf(n.type)),m>=0&&(m=1<<m),f=n.angle):f=window.orientation;r[g>>2]=m;r[g+4>>2]=f;S(c)(18,g,a)&&e.preventDefault()},vg:b})},ae=(a,b,c,d)=>{P.Jh||(P.Jh=Id(257));return Bc({target:a,kg:"pointerlockchange",rg:20,wg:b,og:d,yg:e=>{var g=P.Jh,f=document.pointerLockElement;p[g]=!!f;var k=f?.id??"";B(Cc(f),q,g+1,128);B(k,q,g+129,128);S(d)(20,g,b)&&e.preventDefault()},vg:c})},be=(a,b,c,d)=>{P.Oh||(P.Oh=Id(36));a=Q(a);return Bc({target:a,kg:"resize",rg:10,wg:b,og:d,yg:e=>{if(e.target==a){var g=document.body;
if(g){var f=P.Oh;r[f>>2]=0;r[f+4>>2]=g.clientWidth;r[f+8>>2]=g.clientHeight;r[f+12>>2]=innerWidth;r[f+16>>2]=innerHeight;r[f+20>>2]=outerWidth;r[f+24>>2]=outerHeight;r[f+28>>2]=pageXOffset|0;r[f+32>>2]=pageYOffset|0;S(d)(10,f,b)&&e.preventDefault()}}},vg:c})},ce=(a,b,c)=>{var d=Dc[1];P.Qh||(P.Qh=Id(8));return Bc({target:d,kg:"visibilitychange",rg:21,wg:a,og:c,yg:e=>{var g=P.Qh,f=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);p[g]=document.hidden;r[g+4>>2]=f;S(c)(21,
g,a)&&e.preventDefault()},vg:b})},de=(a,b,c,d)=>{P.Rh||(P.Rh=Id(96));return Bc({target:a,Sh:!0,kg:"wheel",rg:9,wg:b,og:d,yg:e=>{var g=P.Rh;x[g>>3]=e.timeStamp;var f=g>>2;r[f+2]=e.screenX;r[f+3]=e.screenY;r[f+4]=e.clientX;r[f+5]=e.clientY;p[g+24]=e.ctrlKey;p[g+25]=e.shiftKey;p[g+26]=e.altKey;p[g+27]=e.metaKey;ka[f*2+14]=e.button;ka[f*2+15]=e.buttons;r[f+8]=e.movementX;r[f+9]=e.movementY;var k=Qc(a);r[f+10]=e.clientX-(k.left|0);r[f+11]=e.clientY-(k.top|0);x[g+64>>3]=e.deltaX;x[g+72>>3]=e.deltaY;x[g+
80>>3]=e.deltaZ;r[g+88>>2]=e.deltaMode;S(d)(9,g,b)&&e.preventDefault()},vg:c})},ee=["default","low-power","high-performance"],fe={},he=()=>{if(!ge){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in fe)fe[b]===void 0?delete a[b]:a[b]=fe[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);ge=c}return ge},ge,ie=(a,b=[])=>{S(a)(...b)},je=a=>{for(var b of["keydown","mousedown","touchstart"])for(var c of[document,
document.getElementById("canvas")])c?.addEventListener(b,()=>{a.state==="suspended"&&a.resume()},{once:!0})};function ke(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":p[a]=b;break;case "i8":p[a]=b;break;case "i16":ka[a>>1]=b;break;case "i32":r[a>>2]=b;break;case "i64":y[a>>3]=BigInt(b);break;case "float":v[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":u[a>>2]=b;break;default:z(`invalid type for setValue: ${c}`)}}gb=Array(4096);ub(F,"/");M("/tmp");M("/home");M("/home/web_user");
(function(){M("/dev");Ka(259,{read:()=>0,write:(d,e,g,f)=>f,zg:()=>0});xb("/dev/null",259);Ja(1280,Ma);Ja(1536,Na);xb("/dev/tty",1280);xb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b||(Ca(a),b=a.byteLength);return a[--b]};Kb("/dev","random",c);Kb("/dev","urandom",c);M("/dev/shm");M("/dev/shm/tmp")})();
(function(){M("/proc");var a=M("/proc/self");M("/proc/self/fd");ub({Cg(){var b=Pa(a,"fd",16895,73);b.ag={zg:F.ag.zg};b.$f={Zg(c,d){c=+d;var e=L(c);c={parent:null,Cg:{$h:"fake"},$f:{Kg:()=>e.path},id:c+1};return c.parent=c},nh(){return Array.from(eb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.requestAnimationFrame=fc;h.pauseMainLoop=uc;h.resumeMainLoop=function(){lc++;var a=$b,b=ac,c=bc;bc=null;tc(c,0,!1,kc,!0);ic(a,b);cc()};for(let a=0;a<32;++a)xd.push(Array(a));
h.wasmBinary&&(fa=h.wasmBinary);h.addRunDependency=Ya;h.removeRunDependency=()=>{Wa--;Wa||Xa()};h.FS_preloadFile=async(a,b,c,d,e,g,f,k)=>{var m=b?Da(ya(a+"/"+b)):a;Ya(`cp ${m}`);try{var n=c;typeof c=="string"&&(n=await Ta(c));n=await bb(n,m);k?.();g||Jb(a,b,n,d,e,f)}finally{Wa--,Wa||Xa()}};h.FS_unlink=(...a)=>Ab(...a);h.FS_createPath=(...a)=>Hb(...a);h.FS_createDevice=(...a)=>Kb(...a);h.FS_createDataFile=(...a)=>Jb(...a);h.FS_createLazyFile=(...a)=>Mb(...a);
var Yb={380296:()=>{typeof h.SDL3==="undefined"&&(h.SDL3={});var a=h.SDL3;typeof a.Mg==="undefined"&&(a.Mg=function(b){return b});typeof a.rh==="undefined"&&(a.rh=function(b){return b>>>2})},380610:()=>{h.SDL3.Ug={};h.SDL3.Ug.Hg=[];h.SDL3.Ug.Hg[0]=void 0;h.SDL3.Ug.Hg[1]=void 0},380787:(a,b,c,d,e)=>{var g=h.SDL3.Ug;g.Hg[a]!==void 0&&clearInterval(g.Hg[a]);g.Hg[a]=setInterval(function(){ie(d,[e])},b/c*1E3)},380979:a=>{var b=h.SDL3.Ug;b.Hg[a]!==void 0&&clearInterval(b.Hg[a]);b.Hg[a]=void 0},381110:a=>
{var b=new URLSearchParams(window.location.search);for(let [d,e]of b)if(d.startsWith("SDL_")){b=Jd(d);var c=Jd(e);b!=0&&c!=0&&ie(a,[b,c,1]);le(b);le(c)}},381451:()=>typeof AudioContext!=="undefined"||typeof webkitAudioContext!=="undefined"?!0:!1,381598:()=>typeof navigator.mediaDevices!=="undefined"&&typeof navigator.mediaDevices.getUserMedia!=="undefined"||typeof navigator.webkitGetUserMedia!=="undefined"?!0:!1,381832:()=>{var a=h.SDL3;typeof a.fg==="undefined"&&(a.fg={});typeof a.bg==="undefined"&&
(a.bg={});a.hg||(typeof AudioContext!=="undefined"?a.hg=new AudioContext:typeof webkitAudioContext!=="undefined"&&(a.hg=new webkitAudioContext),a.hg&&typeof navigator.userActivation==="undefined"&&je(a.hg));return a.hg!==void 0},382411:()=>h.SDL3.hg.sampleRate,382462:(a,b,c,d)=>{function e(){}function g(k){f.bg.ug!==void 0&&(clearInterval(f.bg.ug),f.bg.ug=void 0,f.bg.Lg=void 0);f.bg.Gh=f.hg.createMediaStreamSource(k);f.bg.tg=f.hg.createScriptProcessor(b,a,1);f.bg.tg.onaudioprocess=function(m){f!==
void 0&&f.bg!==void 0&&(m.outputBuffer.getChannelData(0).fill(0),f.bg.uh=m.inputBuffer,ie(c,[d]))};f.bg.Gh.connect(f.bg.tg);f.bg.tg.connect(f.hg.destination);f.bg.stream=k}var f=h.SDL3;f.bg.Lg=f.hg.createBuffer(a,b,f.hg.sampleRate);f.bg.Lg.getChannelData(0).fill(0);f.bg.ug=setInterval(function(){f.bg.uh=f.bg.Lg;ie(c,[d])},b/f.hg.sampleRate*1E3);navigator.mediaDevices!==void 0&&navigator.mediaDevices.getUserMedia!==void 0?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):navigator.webkitGetUserMedia!==
void 0&&navigator.webkitGetUserMedia({audio:!0,video:!1},g,e)},384303:(a,b,c,d)=>{var e=h.SDL3;e.fg.tg=e.hg.createScriptProcessor(b,0,a);e.fg.tg.onaudioprocess=function(g){e!==void 0&&e.fg!==void 0&&(e.fg.ug!==void 0&&(clearInterval(e.fg.ug),e.fg.ug=void 0,e.fg.Lg=void 0),e.fg.eh=g.outputBuffer,ie(c,[d]))};e.fg.tg.connect(e.hg.destination);e.hg.state==="suspended"&&(e.fg.Lg=e.hg.createBuffer(a,b,e.hg.sampleRate),e.fg.Lg.getChannelData(0).fill(0),e.fg.ug=setInterval(function(){typeof navigator.userActivation!==
"undefined"&&navigator.userActivation.hasBeenActive&&e.hg.resume();e.fg.eh=e.fg.Lg;ie(c,[d]);e.fg.eh=void 0},b/e.hg.sampleRate*1E3))},385619:a=>{var b=h.SDL3;if(a){b.bg.ug!==void 0&&clearInterval(b.bg.ug);if(b.bg.stream!==void 0){a=b.bg.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.bg.stream.removeTrack(a[c])}b.bg.tg!==void 0&&(b.bg.tg.onaudioprocess=function(){},b.bg.tg.disconnect());b.bg.Gh!==void 0&&b.bg.Gh.disconnect();b.bg=void 0}else b.fg.tg!=void 0&&b.fg.tg.disconnect(),b.fg.ug!==void 0&&
clearInterval(b.fg.ug),b.fg=void 0;b.hg!==void 0&&b.fg===void 0&&b.bg===void 0&&(b.hg.close(),b.hg=void 0)},386775:(a,b)=>{var c=h.SDL3;a=c.rh(a);for(var d=c.fg.eh.numberOfChannels,e=0;e<d;++e){var g=c.fg.eh.getChannelData(e);if(g.length!=b)throw"Web Audio playback buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var f=0;f<b;++f)g[f]=v[a+(f*d+e)]}},387308:(a,b)=>{for(var c=h.SDL3,d=c.bg.uh.numberOfChannels,e=0;e<d;++e){var g=c.bg.uh.getChannelData(e);
if(g.length!=b)throw"Web Audio recording buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(d==1)for(var f=0;f<b;++f)ke(a+f*4,g[f]);else for(f=0;f<b;++f)ke(a+(f*d+e)*4,g[f])}},387935:a=>(a=navigator.getGamepads()[a])&&a.vibrationActuator&&a.vibrationActuator.effects&&a.vibrationActuator.effects.includes("trigger-rumble")?!0:!1,388181:a=>{a=navigator.getGamepads()[a];if(!a)return 0;if(a.id.indexOf("Vendor: ")>0){let b=a.id.indexOf("Vendor: ")+8;return parseInt(a.id.substr(b,
4),16)}a=a.id.split("-");return a.length>1&&!isNaN(parseInt(a[0],16))?parseInt(a[0],16):0},388646:a=>{a=navigator.getGamepads()[a];if(!a)return 0;if(a.id.indexOf("Product: ")>0){let b=a.id.indexOf("Product: ")+9;return parseInt(a.id.substr(b,4),16)}a=a.id.split("-");return a.length>1&&!isNaN(parseInt(a[1],16))?parseInt(a[1],16):0},389118:a=>(a=navigator.getGamepads()[a])?a.id.toLowerCase().indexOf("xinput")>=0:0,389261:()=>{var a=["Android","Linux","iPhone","Macintosh","Windows"],b=navigator.userAgent;
for(let c=0;c<a.length;c++)if(b.indexOf(a[c])>=0)return c+1;return 0},389471:(a,b,c)=>{if(a=navigator.getGamepads()[a]){var d=a=a.id;a.indexOf(" (STANDARD GAMEPAD")>0?d=a.substr(0,a.indexOf(" (STANDARD GAMEPAD")):a.indexOf(" (Vendor:")>0?d=a.substr(0,a.indexOf(" (Vendor:")):a.indexOf(" (XInput")>0&&(d=a.substr(0,a.indexOf(" (XInput")));var e=a.split("-");e.length>1&&!isNaN(parseInt(e[0],16))&&(d=a.indexOf("-",a.indexOf("-")+1)+1,d=a.substr(d));B(d.trim(),q,b,c)}else B("\x00",q,b,c)},390149:a=>(a=
navigator.getGamepads()[a])&&a.vibrationActuator?!0:!1,390277:(a,b,c,d,e)=>{a=navigator.getGamepads()[a];if(!a)return!1;a.vibrationActuator.playEffect("dual-rumble",{startDelay:0,duration:3E3,weakMagnitude:b/65535,strongMagnitude:c/65535,leftTrigger:d/65535,rightTrigger:e/65535});return!0},390590:()=>window.matchMedia?window.matchMedia("(prefers-color-scheme: light)").matches?0:window.matchMedia("(prefers-color-scheme: dark)").matches?1:-1:-1,390799:()=>{if(typeof h.SDL3!=="undefined"){var a=h.SDL3;
a.Nh.removeEventListener("change",a.zh);a.Nh=void 0;a.zh=void 0}},391052:()=>window.innerWidth,391082:()=>window.innerHeight,391113:a=>{h.requestFullscreen=function(){ne(a)}},391222:(a,b)=>{a=URL.createObjectURL(new Blob([q.buffer instanceof ArrayBuffer?q.subarray(a,a+b):q.slice(a,a+b)],{type:"image/png"}));b=document.querySelector("link[rel~='icon']");b||(b=document.createElement("link"),b.rel="icon",b.type="image/png",document.head.appendChild(b));b.href&&b.href.startsWith("blob:")&&URL.revokeObjectURL(b.href);
b.href=a},391715:()=>{h.requestFullscreen=function(){}},391789:()=>window.innerWidth,391819:()=>window.innerHeight,391850:a=>{a=document.querySelector(a?A(q,a):"");a.gi=a.style.position;a.hi=a.style.top;a.fi=a.style.left;var b=document.createElement("div");b.id="SDL3_fill_document_background_elements";b.ig=a;b.Vg=a.parentNode;b.Tg=a.nextSibling;var c=Array.from(document.body.children),d;for(d of c)b.appendChild(d);document.body.appendChild(b);b.style.display="none";document.body.appendChild(a);a.style.position=
"fixed";a.style.top="0";a.style.left="0"},392548:()=>{var a=document.getElementById("SDL3_fill_document_background_elements");if(a){for(a.Tg?a.Vg.insertBefore(a.ig,a.Tg):a.Vg.appendChild(a.ig);a.firstChild;)document.body.insertBefore(a.firstChild,a);a.ig.style.position=a.ig.gi;a.ig.style.top=a.ig.hi;a.ig.style.left=a.ig.fi;a.remove()}},393107:()=>{if(window.matchMedia){var a=h.SDL3;a.zh=function(){oe()};a.Nh=window.matchMedia("(prefers-color-scheme: dark)");a.Nh.addEventListener("change",a.zh)}},
393429:(a,b,c,d,e)=>{a=a?A(q,a):"";b=b?A(q,b):"";c=c?A(q,c):"";d=d?A(q,d):"";var g=e?A(q,e):"";e=document.createElement("dialog");e.classList.add("SDL3_messagebox");e.id=g;e.style.color=d;e.style.backgroundColor=c;document.body.append(e);d=document.createElement("h1");d.innerText=a;e.append(d);a=document.createElement("p");a.innerText=b;e.append(a);e.showModal()},393970:(a,b,c,d,e,g,f,k)=>{a=a?A(q,a):"";b=b?A(q,b):"";g=g?A(q,g):"";var m=f?A(q,f):"",n=k?A(q,k):"",t=document.getElementById(a);if(!t)return!1;
var w=document.createElement("button");w.innerText=b;w.style.borderColor=g;w.style.backgroundColor=m;t.addEventListener("keydown",function(C){d&&C.key==="Enter"?(C.preventDefault(),w.click()):e&&C.key==="Escape"&&(C.preventDefault(),w.click())});t.addEventListener("cancel",function(C){C.preventDefault()});w.onmouseenter=function(){w.style.backgroundColor=n};w.onmouseleave=function(){w.style.backgroundColor=m};w.onclick=function(){t.close(c)};t.append(w);return!0},394979:a=>{a=a?A(q,a):"";return(a=
document.getElementById(a))?a.open:!1},395117:a=>{a=a?A(q,a):"";a=document.getElementById(a);if(!a)return 0;try{return parseInt(a.returnValue)}catch(b){return 0}},395299:(a,b)=>{alert((a?A(q,a):"")+"\n\n"+(b?A(q,b):""))},395356:(a,b,c,d)=>{d=d?A(q,d):"";var e=document.querySelector(d);d=h.SDL3;if(d.ki!==e){d.Sg=Zc(e);if(!d.Sg)return!1;d.ki=e}if(d.w!==a||d.h!==b||d.zi!==d.Sg)d.image=d.Sg.createImageData(a,b),d.w=a,d.h=b,d.zi=d.Sg;a=d.image.data;c/=4;d.ni!==a&&(d.mi=new Int32Array(a.buffer),d.ni=a);
a=d.mi;a.set(r.subarray(c,c+a.length));d.Sg.putImageData(d.image,0,0);return!0},396105:()=>{var a=h.SDL3;a.mouse_x=0;a.mouse_y=0;a.mouse_buttons=[];for(var b=0;b<5;++b)a.mouse_buttons[b]=!1;document.addEventListener("mousemove",function(c){var d=h.SDL3;d.mouse_x=c.clientX;d.mouse_y=c.clientY});document.addEventListener("mousedown",function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!0)});document.addEventListener("mouseup",function(c){var d=h.SDL3;0<=
c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!1)})},396793:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var f=g.getContext("2d");a=f.createImageData(a,b);e/=4;b=new Int32Array(a.data.buffer);b.set(r.subarray(e,e+b.length));f.putImageData(a,0,0);c=c===0&&d===0?"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=pe(c.length+1);B(c,q,d,c.length+1);return d},397451:a=>{h.canvas&&(h.canvas.style.cursor=a?A(q,a):"")},397534:()=>
{h.canvas&&(h.canvas.style.cursor="none")},397603:()=>h.SDL3.mouse_x,397641:()=>h.SDL3.mouse_y,397679:a=>h.SDL3.mouse_buttons[a],397727:a=>{document.ig&&document.removeEventListener("keydown",document.ig);document.ig=function(b){b.key!="CapsLock"&&b.key!="NumLock"&&b.key!="ScrollLock"&&qe(h.SDL3.Mg(a),b.getModifierState("CapsLock"),b.getModifierState("NumLock"),b.getModifierState("ScrollLock"))};document.addEventListener("keydown",document.ig)},398281:()=>{document.removeEventListener("keydown",document.ig)},
398365:a=>{var b=document;b&&(b.jg=function(c){var d=h.SDL3;c=d.$g(0,0,c);c!=0&&(re(d.Mg(a),c),se(c))},b.addEventListener("pointerup",b.jg))},398726:a=>{var b=h.SDL3;b.$g===void 0&&(b.$g=function(c,d,e){if(e.pointerType=="mouse")var g=1;else if(e.pointerType=="touch")g=2;else if(e.pointerType=="pen")g=3;else return 0;var f=pe(a);if(f!=0){var k=b.rh(f);r[k++]=g;r[k++]=e.pointerId;r[k++]=typeof e.button!=="undefined"?e.button:-1;r[k++]=e.buttons;r[k++]=e.type=="pointerdown"?1:0;v[k++]=e.movementX;v[k++]=
e.movementY;v[k++]=e.clientX-c;v[k++]=e.clientY-d;g==3&&(v[k++]=e.pressure,v[k++]=e.tangentialPressure,v[k++]=e.tiltX,v[k++]=e.tiltY,v[k++]=e.twist)}return f})},399718:a=>{a=a?A(q,a):"";try{var b=document.querySelector(a);if(b)return b===document.activeElement}catch(c){}return!1},399884:()=>document.hasFocus(),399916:()=>{var a=document;a&&(a.removeEventListener("pointerup",a.jg),a.jg=void 0)},400098:()=>document.body.clientWidth,400136:()=>document.body.clientHeight,400175:()=>window.innerWidth,
400205:()=>window.innerHeight,400236:()=>window.outerWidth,400266:()=>window.outerHeight,400297:()=>window.pageXOffset,400328:()=>window.pageYOffset,400359:(a,b)=>{var c=document.querySelector(b?A(q,b):"");if(c){var d=h.SDL3;c.Ng=function(e){var g=c.getBoundingClientRect();e=d.$g(g.left,g.top,e);e!=0&&(te(d.Mg(a),e),se(e))};c.Bg=function(e){var g=c.getBoundingClientRect();e=d.$g(g.left,g.top,e);e!=0&&(ue(d.Mg(a),e),se(e))};c.jg=function(e){var g=c.getBoundingClientRect();e=d.$g(g.left,g.top,e);e!=
0&&(ve(d.Mg(a),e),se(e))};c.style.touchAction="none";c.addEventListener("pointerenter",c.Ng);c.addEventListener("pointerleave",c.Bg);c.addEventListener("pointercancel",c.Bg);c.addEventListener("pointerdown",c.jg);c.addEventListener("pointermove",c.jg);c.addEventListener("pointerup",c.jg)}},401747:(a,b,c)=>{var d=document.querySelector(b?A(q,b):"");if(d){var e=h.SDL3,g=function(f){var k=pe(c);if(k!=0){var m=k>>2,n=d.getBoundingClientRect();r[m++]=f.clientX-n.left;r[m++]=f.clientY-n.top}return k};e.xh=
function(f){f.preventDefault();f=g(f);f!=0&&(we(a,f),se(f))};d.addEventListener("dragover",e.xh);e.fh=0;try{M("/tmp/filedrop")}catch(f){}e.yh=function(f){f.preventDefault();if(f.dataTransfer.types.includes("text/plain"))f=Jd(f.dataTransfer.getData("text/plain")),xe(a,f),le(f);else if(f.dataTransfer.types.includes("Files")){let k=0,m=f.dataTransfer.files.length;for(let n=0;n<m;n++){let t=f.dataTransfer.files.item(n),w=new FileReader;w.readAsArrayBuffer(t);w.onload=function(C){var D=`/tmp/filedrop/${e.fh}`;
e.fh+=1;var G=`${D}/${t.name}`,J=Jd(G);C=new Uint8Array(C.target.result);try{M(D);var I=Db(G,"w");Gb(I,C,0,C.length,0);Eb(I);ye(a,J)}catch(R){}le(J);++k;k===m&&ze(a)};w.onerror=function(){++k;k===m&&ze(a)}}}ze(a)};d.addEventListener("drop",e.yh);e.Wg=function(f){f.preventDefault();ze(a)};d.addEventListener("dragend",e.Wg);d.addEventListener("dragleave",e.Wg)}},404114:a=>{if(a=document.querySelector(a?A(q,a):"")){var b=h.SDL3;a.removeEventListener("dragleave",b.Wg);a.removeEventListener("dragend",
b.Wg);a.removeEventListener("drop",b.yh);b.fh=void 0;"/tmp/filedrop";zb("/tmp/filedrop");a.removeEventListener("dragover",b.xh);b.xh=void 0;b.yh=void 0;b.Wg=void 0}},404944:a=>{if(a=document.querySelector(a?A(q,a):""))a.removeEventListener("pointerenter",a.Ng),a.removeEventListener("pointerleave",a.Bg),a.removeEventListener("pointercancel",a.Bg),a.removeEventListener("pointerdown",a.jg),a.removeEventListener("pointermove",a.jg),a.removeEventListener("pointerup",a.jg),a.style.touchAction="",a.Ng=void 0,
a.Bg=void 0,a.jg=void 0}},Id,Ae,se,pe,le,te,ue,ve,re,we,ze,xe,ye,qe,oe,ne,Hc,Ec,Gc,ja,Nc,Be={b:(a,b,c)=>{(new va(a)).init(b,c);wa++;z()},nb:function(a,b,c){try{b=b?A(q,b):"";b=Ob(a,b);if(c&-8)return-28;var d=K(b,{Og:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&nb(d,a)?-2:0}catch(e){if(typeof O=="undefined"||e.name!=="ErrnoError")throw e;return-e.eg}},v:function(a,b,c){Rb=c;try{var d=L(a);switch(b){case 0:var e=Sb();if(e<0)break;for(;eb[e];)e++;return sb(d,e).fd;
case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Sb(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=Sb(),ka[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(g){if(typeof O=="undefined"||g.name!=="ErrnoError")throw g;return-g.eg}},kb:function(a){try{return L(a),0}catch(b){if(typeof O=="undefined"||b.name!=="ErrnoError")throw b;return-b.eg}},ib:function(a,b){try{var c=L(a),d=c.node,e=c.ag.sg;a=e?c:d;e??=d.$f.sg;qb(e,63);var g=e(a);return Pb(b,g)}catch(f){if(typeof O=="undefined"||
f.name!=="ErrnoError")throw f;return-f.eg}},db:function(a,b){try{if(!b)return-28;var c=Ga("/")+1;if(b<c)return-68;B("/",q,a,b);return c}catch(d){if(typeof O=="undefined"||d.name!=="ErrnoError")throw d;return-d.eg}},Za:function(a,b,c){try{var d=L(a);if(!d.Jg){var e=K(d.path,{Og:!0}).node;var g=qb(e.$f.nh,54)(e);d.Jg=g}a=0;var f=Fb(d,0,1),k=Math.floor(f/280),m=Math.min(d.Jg.length,k+Math.floor(c/280));for(c=k;c<m;c++){var n=d.Jg[c];if(n==="."){var t=d.node.id;var w=4}else if(n==="..")t=K(d.path,{parent:!0}).node.id,
w=4;else{try{var C=Qa(d.node,n)}catch(D){if(D?.eg===28)continue;throw D;}t=C.id;w=(C.mode&61440)===8192?2:H(C.mode)?4:(C.mode&61440)===40960?10:8}y[b+a>>3]=BigInt(t);y[b+a+8>>3]=BigInt((c+1)*280);ka[b+a+16>>1]=280;p[b+a+18]=w;B(n,q,b+a+19,256);a+=280}Fb(d,c*280,0);return a}catch(D){if(typeof O=="undefined"||D.name!=="ErrnoError")throw D;return-D.eg}},cb:()=>0,jb:function(a,b,c){Rb=c;try{var d=L(a);switch(b){case 21509:return d.gg?0:-59;case 21505:if(!d.gg)return-59;if(d.gg.Dg.Di){a=[3,28,127,21,4,
0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Sb();r[e>>2]=25856;r[e+4>>2]=5;r[e+8>>2]=191;r[e+12>>2]=35387;for(var g=0;g<32;g++)p[e+g+17]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.gg?0:-59;case 21506:case 21507:case 21508:if(!d.gg)return-59;if(d.gg.Dg.Ei)for(e=Sb(),a=[],g=0;g<32;g++)a.push(p[e+g+17]);return 0;case 21519:if(!d.gg)return-59;e=Sb();return r[e>>2]=0;case 21520:return d.gg?-28:-59;case 21537:case 21531:e=Sb();if(!d.ag.Ci)throw new E(59);return d.ag.Ci(d,
b,e);case 21523:if(!d.gg)return-59;d.gg.Dg.Fi&&(g=[24,80],e=Sb(),ka[e>>1]=g[0],ka[e+2>>1]=g[1]);return 0;case 21524:return d.gg?0:-59;case 21515:return d.gg?0:-59;default:return-28}}catch(f){if(typeof O=="undefined"||f.name!=="ErrnoError")throw f;return-f.eg}},fb:function(a,b){try{return a=a?A(q,a):"",Pb(b,Bb(a,!0))}catch(c){if(typeof O=="undefined"||c.name!=="ErrnoError")throw c;return-c.eg}},ab:function(a,b,c){try{return b=b?A(q,b):"",b=Ob(a,b),M(b,c&-19),0}catch(d){if(typeof O=="undefined"||d.name!==
"ErrnoError")throw d;return-d.eg}},gb:function(a,b,c,d){try{b=b?A(q,b):"";var e=d&256;b=Ob(a,b,d&4096);return Pb(c,e?Bb(b,!0):Bb(b))}catch(g){if(typeof O=="undefined"||g.name!=="ErrnoError")throw g;return-g.eg}},w:function(a,b,c,d){Rb=d;try{b=b?A(q,b):"";b=Ob(a,b);var e=d?Sb():0;c&64&&(e&=-19);return Db(b,c,e).fd}catch(g){if(typeof O=="undefined"||g.name!=="ErrnoError")throw g;return-g.eg}},Va:function(a,b,c,d){try{b=b?A(q,b):"";b=Ob(a,b);if(d<=0)return-28;var e=K(b).node;if(!e)throw new E(44);if(!e.$f.Kg)throw new E(28);
var g=e.$f.Kg(e);var f=Math.min(d,Ga(g)),k=p[c+f];B(g,q,c,d+1);p[c+f]=k;return f}catch(m){if(typeof O=="undefined"||m.name!=="ErrnoError")throw m;return-m.eg}},Xa:function(a){try{return a=a?A(q,a):"",zb(a),0}catch(b){if(typeof O=="undefined"||b.name!=="ErrnoError")throw b;return-b.eg}},hb:function(a,b){try{return a=a?A(q,a):"",Pb(b,Bb(a))}catch(c){if(typeof O=="undefined"||c.name!=="ErrnoError")throw c;return-c.eg}},Ya:function(a,b,c){try{b=b?A(q,b):"";b=Ob(a,b);if(c)if(c===512)zb(b);else return-28;
else Ab(b);return 0}catch(d){if(typeof O=="undefined"||d.name!=="ErrnoError")throw d;return-d.eg}},ob:()=>z(""),mb:(a,b)=>{b=b?A(q,b):"";a&24&&(b=b.replace(/\s+$/,""),b+=(b.length>0?"\n":"")+Tb(a));a&1?a&4?console.error(b):a&2?console.warn(b):a&512?console.info(b):a&256?console.debug(b):console.log(b):a&6?l(b):ea(b)},_a:function(a){var b=(()=>{var c=new Date(r[a+20>>2]+1900,r[a+16>>2],r[a+12>>2],r[a+8>>2],r[a+4>>2],r[a>>2],0);if(isNaN(c.getTime()))return-1;var d=r[a+32>>2],e=c.getTimezoneOffset(),
g=(new Date(c.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(c.getFullYear(),0,1)).getTimezoneOffset(),k=Math.min(f,g);if(d<0)d=Number(g!=f&&k==e);else if(d>0!=(k==e)&&(g=Math.max(f,g),c.setTime(c.getTime()+((d>0?k:g)-e)*6E4),isNaN(c.getTime())))return-1;r[a+32>>2]=d;r[a+24>>2]=c.getDay();d=c.getFullYear();r[a+28>>2]=(d%4!==0||d%100===0&&d%400!==0?Vb:Ub)[c.getMonth()]+c.getDate()-1|0;r[a>>2]=c.getSeconds();r[a+4>>2]=c.getMinutes();r[a+8>>2]=c.getHours();r[a+12>>2]=c.getDate();r[a+16>>2]=c.getMonth();
r[a+20>>2]=c.getYear();return c.getTime()/1E3})();return BigInt(b)},$a:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();u[a>>2]=Math.max(g,e)*60;r[b>>2]=Number(g!=e);b=f=>{var k=Math.abs(f);return`UTC${f>=0?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(B(a,q,c,17),B(b,q,d,17)):(B(a,q,d,17),B(b,q,c,17))},E:Zb,f:(a,b,c)=>{b=Xb(b,c);return Yb[a](...b)},a:Zb,Cd:(a,b,c)=>
{b=Xb(b,c);return Yb[a](...b)},Dd:()=>{uc();bc=null},lb:()=>Date.now(),Pa:()=>{if(!P.fullscreenEnabled())return-1;yc(Rc);var a=Dc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},hd:()=>{yc(Sc);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},K:(a,b,c)=>{a=Tb(a);return!b||c<=0?Ga(a)+1:B(a,q,b,c)+1},h:()=>devicePixelRatio,c:(a,b,c)=>{a=Q(a);if(!a)return-4;
a=Qc(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},Ra:a=>{if(!P.fullscreenEnabled())return-1;Tc(a);return 0},p:(a,b)=>{if(a<0||a>=P.gh.length)return-5;if(!P.gh[a])return-7;Uc(b,P.gh[a]);return 0},Me:(a,b)=>{a&&(r[a>>2]=$b);b&&(r[b>>2]=ac)},t:()=>performance.now(),da:()=>P.gh.length,Yd:(a,b)=>{r[a>>2]=screen.width;r[b>>2]=screen.height},ua:a=>T.activeTexture(a),ta:(a,b)=>{T.attachShader(U[a],V[b])},ed:(a,b)=>{T.beginQuery(a,W[b])},La:(a,b)=>{T.qg.beginQueryEXT(a,W[b])},Nc:a=>T.beginTransformFeedback(a),
sa:(a,b,c)=>{T.bindAttribLocation(U[a],b,c?A(q,c):"")},ra:(a,b)=>{a==35051?T.th=b:a==35052&&(T.xg=b);T.bindBuffer(a,bd[b])},Kc:(a,b,c)=>{T.bindBufferBase(a,b,bd[c])},Lc:(a,b,c,d,e)=>{T.bindBufferRange(a,b,bd[c],d,e)},qa:(a,b)=>{T.bindFramebuffer(a,cd[b])},pa:(a,b)=>{T.bindRenderbuffer(a,dd[b])},Sb:(a,b)=>{T.bindSampler(a,hd[b])},oa:(a,b)=>{T.bindTexture(a,ed[b])},Kb:(a,b)=>{T.bindTransformFeedback(a,jd[b])},Sc:ud,Da:ud,na:(a,b,c,d)=>T.blendColor(a,b,c,d),ma:a=>T.blendEquation(a),la:(a,b)=>T.blendEquationSeparate(a,
b),ka:(a,b)=>T.blendFunc(a,b),ja:(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),Vc:(a,b,c,d,e,g,f,k,m,n)=>T.blitFramebuffer(a,b,c,d,e,g,f,k,m,n),ia:(a,b,c,d)=>{c&&b?T.bufferData(a,q,d,c,b):T.bufferData(a,b,d)},ha:(a,b,c,d)=>{var e=q;c&&T.bufferSubData(a,b,e,d,c)},ga:a=>T.checkFramebufferStatus(a),fa:a=>T.clear(a),nc:(a,b,c,d)=>T.clearBufferfi(a,b,c,d),oc:(a,b,c)=>{T.clearBufferfv(a,b,v,c>>2)},qc:(a,b,c)=>{T.clearBufferiv(a,b,r,c>>2)},pc:(a,b,c)=>{T.clearBufferuiv(a,b,u,c>>2)},ea:(a,b,c,d)=>T.clearColor(a,
b,c,d),ca:a=>T.clearDepth(a),ba:a=>T.clearStencil(a),$b:(a,b,c)=>{c=Number(c);return T.clientWaitSync(kd[a],b,c)},vd:(a,b)=>{T.ti.clipControlEXT(a,b)},aa:(a,b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},$:a=>{T.compileShader(V[a])},_:(a,b,c,d,e,g,f,k)=>{T.xg||!f?T.compressedTexImage2D(a,b,c,d,e,g,f,k):T.compressedTexImage2D(a,b,c,d,e,g,q,k,f)},kd:(a,b,c,d,e,g,f,k,m)=>{T.xg?T.compressedTexImage3D(a,b,c,d,e,g,f,k,m):T.compressedTexImage3D(a,b,c,d,e,g,f,q,m,k)},Z:(a,b,c,d,e,g,f,k,m)=>{T.xg||!k?T.compressedTexSubImage2D(a,
b,c,d,e,g,f,k,m):T.compressedTexSubImage2D(a,b,c,d,e,g,f,q,m,k)},jd:(a,b,c,d,e,g,f,k,m,n,t)=>{T.xg?T.compressedTexSubImage3D(a,b,c,d,e,g,f,k,m,n,t):T.compressedTexSubImage3D(a,b,c,d,e,g,f,k,m,q,t,n)},lc:(a,b,c,d,e)=>T.copyBufferSubData(a,b,c,d,e),Y:(a,b,c,d,e,g,f,k)=>T.copyTexImage2D(a,b,c,d,e,g,f,k),X:(a,b,c,d,e,g,f,k)=>T.copyTexSubImage2D(a,b,c,d,e,g,f,k),ld:(a,b,c,d,e,g,f,k,m)=>T.copyTexSubImage3D(a,b,c,d,e,g,f,k,m),W:()=>{var a=pd(U),b=T.createProgram();b.name=a;b.jh=b.hh=b.ih=0;b.Ph=1;U[a]=b;
return a},V:a=>{var b=pd(V);V[b]=T.createShader(a);return b},U:a=>T.cullFace(a),T:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=bd[d];e&&(T.deleteBuffer(e),e.name=0,bd[d]=null,d==T.th&&(T.th=0),d==T.xg&&(T.xg=0))}},S:(a,b)=>{for(var c=0;c<a;++c){var d=r[b+c*4>>2],e=cd[d];e&&(T.deleteFramebuffer(e),e.name=0,cd[d]=null)}},R:a=>{if(a){var b=U[a];b?(T.deleteProgram(b),b.name=0,U[a]=null):Y||=1281}},gd:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=W[d];e&&(T.deleteQuery(e),W[d]=null)}},Na:(a,b)=>
{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=W[d];e&&(T.qg.deleteQueryEXT(e),W[d]=null)}},Q:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=dd[d];e&&(T.deleteRenderbuffer(e),e.name=0,dd[d]=null)}},Ub:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=hd[d];e&&(T.deleteSampler(e),e.name=0,hd[d]=null)}},P:a=>{if(a){var b=V[a];b?(T.deleteShader(b),V[a]=null):Y||=1281}},ac:a=>{if(a){var b=kd[a];b?(T.deleteSync(b),b.name=0,kd[a]=null):Y||=1281}},O:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=ed[d];e&&
(T.deleteTexture(e),e.name=0,ed[d]=null)}},Jb:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=jd[d];e&&(T.deleteTransformFeedback(e),e.name=0,jd[d]=null)}},Rc:vd,Ca:vd,N:a=>T.depthFunc(a),M:a=>{T.depthMask(!!a)},L:(a,b)=>T.depthRange(a,b),zf:(a,b)=>{T.detachShader(U[a],V[b])},yf:a=>T.disable(a),xf:a=>{T.disableVertexAttribArray(a)},wf:(a,b,c)=>{T.drawArrays(a,b,c)},ec:wd,xa:wd,tb:wd,sd:wd,ub:wd,ad:yd,qd:yd,za:yd,vf:(a,b,c,d)=>{T.drawElements(a,b,c,d)},dc:zd,wa:zd,rb:zd,sb:zd,rd:zd,od:(a,b,c,d,e,
g)=>{T.drawElements(a,d,e,g)},uf:a=>T.enable(a),tf:a=>{T.enableVertexAttribArray(a)},dd:a=>T.endQuery(a),Ka:a=>{T.qg.endQueryEXT(a)},Mc:()=>T.endTransformFeedback(),cc:(a,b)=>(a=T.fenceSync(a,b))?(b=pd(kd),a.name=b,kd[b]=a,b):0,sf:()=>T.finish(),rf:()=>T.flush(),qf:(a,b,c,d)=>{T.framebufferRenderbuffer(a,b,c,dd[d])},pf:(a,b,c,d,e)=>{T.framebufferTexture2D(a,b,c,ed[d],e)},Tc:(a,b,c,d,e)=>{T.framebufferTextureLayer(a,b,ed[c],d,e)},of:a=>T.frontFace(a),nf:(a,b)=>{qd(a,b,"createBuffer",bd)},lf:(a,b)=>
{qd(a,b,"createFramebuffer",cd)},id:(a,b)=>{qd(a,b,"createQuery",W)},Oa:(a,b)=>{for(var c=0;c<a;c++){var d=T.qg.createQueryEXT();if(!d){for(Y||=1282;c<a;)r[b+c++*4>>2]=0;break}var e=pd(W);d.name=e;W[e]=d;r[b+c*4>>2]=e}},kf:(a,b)=>{qd(a,b,"createRenderbuffer",dd)},Vb:(a,b)=>{qd(a,b,"createSampler",hd)},jf:(a,b)=>{qd(a,b,"createTexture",ed)},Ib:(a,b)=>{qd(a,b,"createTransformFeedback",jd)},Qc:Ad,Ba:Ad,mf:a=>T.generateMipmap(a),hf:(a,b,c,d,e,g,f)=>Bd("getActiveAttrib",a,b,c,d,e,g,f),gf:(a,b,c,d,e,g,
f)=>Bd("getActiveUniform",a,b,c,d,e,g,f),gc:(a,b,c,d,e)=>{a=U[a];if(a=T.getActiveUniformBlockName(a,b))e&&c>0?(c=B(a,q,e,c),d&&(r[d>>2]=c)):d&&(r[d>>2]=0)},hc:(a,b,c,d)=>{if(d)if(a=U[a],c==35393)r[d>>2]=T.getActiveUniformBlockName(a,b).length+1;else{if(a=T.getActiveUniformBlockParameter(a,b,c),a!==null)if(c==35395)for(c=0;c<a.length;c++)r[d+c*4>>2]=a[c];else r[d>>2]=a}else Y||=1281},jc:(a,b,c,d,e)=>{if(e)if(b>0&&c==0)Y||=1281;else{a=U[a];for(var g=[],f=0;f<b;f++)g.push(r[c+f*4>>2]);if(a=T.getActiveUniforms(a,
g,d))for(b=a.length,f=0;f<b;f++)r[e+f*4>>2]=a[f]}else Y||=1281},ff:(a,b,c,d)=>{a=T.getAttachedShaders(U[a]);var e=a.length;e>b&&(e=b);r[c>>2]=e;for(b=0;b<e;++b)r[d+b*4>>2]=V.indexOf(a[b])},ef:(a,b)=>T.getAttribLocation(U[a],b?A(q,b):""),df:(a,b)=>Ed(a,b,4),Wb:(a,b,c)=>{c?Cd(c,T.getBufferParameter(a,b)):Y||=1281},cf:(a,b,c)=>{c?r[c>>2]=T.getBufferParameter(a,b):Y||=1281},bf:()=>{var a=T.getError()||Y;Y=0;return a},af:(a,b)=>Ed(a,b,2),zc:(a,b)=>T.getFragDataLocation(U[a],b?A(q,b):""),$e:(a,b,c,d)=>
{a=T.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;r[d>>2]=a},Xb:(a,b,c)=>Fd(a,b,c,1),Zb:(a,b)=>{Ed(a,b,1)},Oc:(a,b,c)=>Fd(a,b,c,0),_e:(a,b)=>Ed(a,b,0),xb:(a,b,c,d,e)=>{if(d<0)Y||=1281;else if(e){if(a=T.getInternalformatParameter(a,b,c),a!==null)for(b=0;b<a.length&&b<d;++b)r[e+b*4>>2]=a[b]}else Y||=1281},Eb:()=>{Y||=1282},Ye:(a,b,c,d)=>{a=T.getProgramInfoLog(U[a]);a===null&&(a="(unknown error)");b=b>0&&d?B(a,q,d,b):0;c&&(r[c>>2]=b)},
Ze:(a,b,c)=>{if(c)if(a>=ad)Y||=1281;else if(a=U[a],b==35716)a=T.getProgramInfoLog(a),a===null&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(b==35719){if(!a.jh){var d=T.getProgramParameter(a,35718);for(b=0;b<d;++b)a.jh=Math.max(a.jh,T.getActiveUniform(a,b).name.length+1)}r[c>>2]=a.jh}else if(b==35722){if(!a.hh)for(d=T.getProgramParameter(a,35721),b=0;b<d;++b)a.hh=Math.max(a.hh,T.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.hh}else if(b==35381){if(!a.ih)for(d=T.getProgramParameter(a,35382),b=0;b<
d;++b)a.ih=Math.max(a.ih,T.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.ih}else r[c>>2]=T.getProgramParameter(a,b);else Y||=1281},Fa:Gd,Ha:Hd,Ea:Gd,bd:(a,b,c)=>{if(c){a=T.getQueryParameter(W[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;r[c>>2]=d}else Y||=1281},Ga:Hd,cd:(a,b,c)=>{c?r[c>>2]=T.getQuery(a,b):Y||=1281},Ia:(a,b,c)=>{c?r[c>>2]=T.qg.getQueryEXT(a,b):Y||=1281},Xe:(a,b,c)=>{c?r[c>>2]=T.getRenderbufferParameter(a,b):Y||=1281},Mb:(a,b,c)=>{c?v[c>>2]=T.getSamplerParameter(hd[a],b):Y||=1281},
Nb:(a,b,c)=>{c?r[c>>2]=T.getSamplerParameter(hd[a],b):Y||=1281},Ve:(a,b,c,d)=>{a=T.getShaderInfoLog(V[a]);a===null&&(a="(unknown error)");b=b>0&&d?B(a,q,d,b):0;c&&(r[c>>2]=b)},Ue:(a,b,c,d)=>{a=T.getShaderPrecisionFormat(a,b);r[c>>2]=a.rangeMin;r[c+4>>2]=a.rangeMax;r[d>>2]=a.precision},Te:(a,b,c,d)=>{if(a=T.getShaderSource(V[a]))b=b>0&&d?B(a,q,d,b):0,c&&(r[c>>2]=b)},We:(a,b,c)=>{c?b==35716?(a=T.getShaderInfoLog(V[a]),a===null&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):b==35720?(a=T.getShaderSource(V[a]),
r[c>>2]=a?a.length+1:0):r[c>>2]=T.getShaderParameter(V[a],b):Y||=1281},Se:a=>{var b=ld[a];if(!b){switch(a){case 7939:b=Jd(Dd().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=T.getParameter(a))||(Y||=1280);b=b?Jd(b):0;break;case 7938:b=Jd(`OpenGL ES 3.0 (${T.getParameter(7938)})`);break;case 35724:b=T.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);c!==null&&(c[1].length==3&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Jd(b);break;default:Y||=
1280}ld[a]=b}return b},mc:(a,b)=>{if(td.version<2)return Y||=1282,0;var c=md[a];if(c)return b<0||b>=c.length?(Y||=1281,0):c[b];switch(a){case 7939:return c=Dd().map(Jd),c=md[a]=c,b<0||b>=c.length?(Y||=1281,0):c[b];default:return Y||=1280,0}},Yb:(a,b,c,d,e)=>{c<0?Y||=1281:e?(a=T.getSyncParameter(kd[a],b),a!==null&&(r[e>>2]=a,d&&(r[d>>2]=1))):Y||=1281},Re:(a,b,c)=>{c?v[c>>2]=T.getTexParameter(a,b):Y||=1281},Qe:(a,b,c)=>{c?r[c>>2]=T.getTexParameter(a,b):Y||=1281},Ic:(a,b,c,d,e,g,f)=>{a=U[a];if(a=T.getTransformFeedbackVarying(a,
b))f&&c>0?(c=B(a.name,q,f,c),d&&(r[d>>2]=c)):d&&(r[d>>2]=0),e&&(r[e>>2]=a.size),g&&(r[g>>2]=a.type)},ic:(a,b)=>T.getUniformBlockIndex(U[a],b?A(q,b):""),kc:(a,b,c,d)=>{if(d)if(b>0&&(c==0||d==0))Y||=1281;else{a=U[a];for(var e=[],g=0;g<b;g++)e.push(Nb(u[c+g*4>>2]));if(a=T.getUniformIndices(a,e))for(b=a.length,g=0;g<b;g++)r[d+g*4>>2]=a[g]}else Y||=1281},Ne:(a,b)=>{b=b?A(q,b):"";if(a=U[a]){Ld(a);var c=a.bh,d=0,e=b,g=Kd(b);g>0&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.ei[e])&&d<e[0]&&(d+=e[1],
c[d]=c[d]||T.getUniformLocation(a,b)))return d}else Y||=1281;return-1},Pe:(a,b,c)=>{Md(a,b,c,2)},Oe:(a,b,c)=>{Md(a,b,c,0)},Ac:(a,b,c)=>Md(a,b,c,0),Gc:Od,Fc:Od,Je:(a,b,c)=>{c?r[c>>2]=T.getVertexAttribOffset(a,b):Y||=1281},Le:(a,b,c)=>{Nd(a,b,c,2)},Ke:(a,b,c)=>{Nd(a,b,c,5)},Ie:(a,b)=>T.hint(a,b),Bb:(a,b,c)=>{for(var d=xd[b],e=0;e<b;e++)d[e]=r[c+e*4>>2];T.invalidateFramebuffer(a,d)},Ab:(a,b,c,d,e,g,f)=>{for(var k=xd[b],m=0;m<b;m++)k[m]=r[c+m*4>>2];T.invalidateSubFramebuffer(a,k,d,e,g,f)},He:a=>(a=bd[a])?
T.isBuffer(a):0,Ge:a=>T.isEnabled(a),Fe:a=>(a=cd[a])?T.isFramebuffer(a):0,Ee:a=>(a=U[a])?T.isProgram(a):0,fd:a=>(a=W[a])?T.isQuery(a):0,Ma:a=>(a=W[a])?T.qg.isQueryEXT(a):0,De:a=>(a=dd[a])?T.isRenderbuffer(a):0,Tb:a=>(a=hd[a])?T.isSampler(a):0,Ce:a=>(a=V[a])?T.isShader(a):0,bc:a=>T.isSync(kd[a]),Ae:a=>(a=ed[a])?T.isTexture(a):0,Hb:a=>T.isTransformFeedback(jd[a]),Pc:Pd,Aa:Pd,ze:a=>T.lineWidth(a),ye:a=>{a=U[a];T.linkProgram(a);a.bh=0;a.ei={}},Gb:()=>T.pauseTransformFeedback(),xe:(a,b)=>{a==3317?nd=b:
a==3314&&(od=b);T.pixelStorei(a,b)},ud:(a,b)=>{T.Ri.polygonModeWEBGL(a,b)},we:(a,b)=>T.polygonOffset(a,b),wd:(a,b,c)=>{T.ui.polygonOffsetClampEXT(a,b,c)},Db:()=>{Y||=1280},Cb:()=>{Y||=1280},Ja:(a,b)=>{T.qg.queryCounterEXT(W[a],b)},pd:a=>T.readBuffer(a),ve:(a,b,c,d,e,g,f)=>{if(T.th)T.readPixels(a,b,c,d,e,g,f);else{var k=Qd(g);f>>>=31-Math.clz32(k.BYTES_PER_ELEMENT);T.readPixels(a,b,c,d,e,g,k,f)}},ue:()=>{},te:(a,b,c,d)=>T.renderbufferStorage(a,b,c,d),Uc:(a,b,c,d,e)=>T.renderbufferStorageMultisample(a,
b,c,d,e),Fb:()=>T.resumeTransformFeedback(),se:(a,b)=>{T.sampleCoverage(a,!!b)},Pb:(a,b,c)=>{T.samplerParameterf(hd[a],b,c)},Ob:(a,b,c)=>{T.samplerParameterf(hd[a],b,v[c>>2])},Rb:(a,b,c)=>{T.samplerParameteri(hd[a],b,c)},Qb:(a,b,c)=>{T.samplerParameteri(hd[a],b,r[c>>2])},re:(a,b,c,d)=>T.scissor(a,b,c,d),qe:()=>{Y||=1280},pe:(a,b,c,d)=>{for(var e="",g=0;g<b;++g)e+=Nb(u[c+g*4>>2],d?u[d+g*4>>2]:void 0);T.shaderSource(V[a],e)},oe:(a,b,c)=>T.stencilFunc(a,b,c),ne:(a,b,c,d)=>T.stencilFuncSeparate(a,b,c,
d),me:a=>T.stencilMask(a),le:(a,b)=>T.stencilMaskSeparate(a,b),ke:(a,b,c)=>T.stencilOp(a,b,c),je:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),ie:(a,b,c,d,e,g,f,k,m)=>{if(T.xg)T.texImage2D(a,b,c,d,e,g,f,k,m);else if(m){var n=Qd(k);m>>>=31-Math.clz32(n.BYTES_PER_ELEMENT);T.texImage2D(a,b,c,d,e,g,f,k,n,m)}else n=m?Rd(k,f,d,e,m):null,T.texImage2D(a,b,c,d,e,g,f,k,n)},nd:(a,b,c,d,e,g,f,k,m,n)=>{if(T.xg)T.texImage3D(a,b,c,d,e,g,f,k,m,n);else if(n){var t=Qd(m);T.texImage3D(a,b,c,d,e,g,f,k,m,t,n>>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else T.texImage3D(a,
b,c,d,e,g,f,k,m,null)},he:(a,b,c)=>T.texParameterf(a,b,c),ge:(a,b,c)=>{T.texParameterf(a,b,v[c>>2])},fe:(a,b,c)=>T.texParameteri(a,b,c),ee:(a,b,c)=>{T.texParameteri(a,b,r[c>>2])},zb:(a,b,c,d,e)=>T.texStorage2D(a,b,c,d,e),yb:(a,b,c,d,e,g)=>T.texStorage3D(a,b,c,d,e,g),de:(a,b,c,d,e,g,f,k,m)=>{if(T.xg)T.texSubImage2D(a,b,c,d,e,g,f,k,m);else if(m){var n=Qd(k);T.texSubImage2D(a,b,c,d,e,g,f,k,n,m>>>31-Math.clz32(n.BYTES_PER_ELEMENT))}else m=m?Rd(k,f,e,g,m):null,T.texSubImage2D(a,b,c,d,e,g,f,k,m)},md:(a,
b,c,d,e,g,f,k,m,n,t)=>{if(T.xg)T.texSubImage3D(a,b,c,d,e,g,f,k,m,n,t);else if(t){var w=Qd(n);T.texSubImage3D(a,b,c,d,e,g,f,k,m,n,w,t>>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else T.texSubImage3D(a,b,c,d,e,g,f,k,m,n,null)},Jc:(a,b,c,d)=>{a=U[a];for(var e=[],g=0;g<b;g++)e.push(Nb(u[c+g*4>>2]));T.transformFeedbackVaryings(a,e,d)},ce:(a,b)=>{T.uniform1f(Z(T.cg,a),b)},be:(a,b,c)=>{b&&T.uniform1fv(Z(T.cg,a),v,c>>2,b)},ae:(a,b)=>{T.uniform1i(Z(T.cg,a),b)},$d:(a,b,c)=>{b&&T.uniform1iv(Z(T.cg,a),r,c>>2,b)},yc:(a,
b)=>{T.uniform1ui(Z(T.cg,a),b)},uc:(a,b,c)=>{b&&T.uniform1uiv(Z(T.cg,a),u,c>>2,b)},_d:(a,b,c)=>{T.uniform2f(Z(T.cg,a),b,c)},Zd:(a,b,c)=>{b&&T.uniform2fv(Z(T.cg,a),v,c>>2,b*2)},Xd:(a,b,c)=>{T.uniform2i(Z(T.cg,a),b,c)},Wd:(a,b,c)=>{b&&T.uniform2iv(Z(T.cg,a),r,c>>2,b*2)},xc:(a,b,c)=>{T.uniform2ui(Z(T.cg,a),b,c)},tc:(a,b,c)=>{b&&T.uniform2uiv(Z(T.cg,a),u,c>>2,b*2)},Vd:(a,b,c,d)=>{T.uniform3f(Z(T.cg,a),b,c,d)},Ud:(a,b,c)=>{b&&T.uniform3fv(Z(T.cg,a),v,c>>2,b*3)},Td:(a,b,c,d)=>{T.uniform3i(Z(T.cg,a),b,c,
d)},Sd:(a,b,c)=>{b&&T.uniform3iv(Z(T.cg,a),r,c>>2,b*3)},wc:(a,b,c,d)=>{T.uniform3ui(Z(T.cg,a),b,c,d)},sc:(a,b,c)=>{b&&T.uniform3uiv(Z(T.cg,a),u,c>>2,b*3)},Rd:(a,b,c,d,e)=>{T.uniform4f(Z(T.cg,a),b,c,d,e)},Qd:(a,b,c)=>{b&&T.uniform4fv(Z(T.cg,a),v,c>>2,b*4)},Pd:(a,b,c,d,e)=>{T.uniform4i(Z(T.cg,a),b,c,d,e)},Od:(a,b,c)=>{b&&T.uniform4iv(Z(T.cg,a),r,c>>2,b*4)},vc:(a,b,c,d,e)=>{T.uniform4ui(Z(T.cg,a),b,c,d,e)},rc:(a,b,c)=>{b&&T.uniform4uiv(Z(T.cg,a),u,c>>2,b*4)},fc:(a,b,c)=>{a=U[a];T.uniformBlockBinding(a,
b,c)},Nd:(a,b,c,d)=>{b&&T.uniformMatrix2fv(Z(T.cg,a),!!c,v,d>>2,b*4)},$c:(a,b,c,d)=>{b&&T.uniformMatrix2x3fv(Z(T.cg,a),!!c,v,d>>2,b*6)},Zc:(a,b,c,d)=>{b&&T.uniformMatrix2x4fv(Z(T.cg,a),!!c,v,d>>2,b*8)},Md:(a,b,c,d)=>{b&&T.uniformMatrix3fv(Z(T.cg,a),!!c,v,d>>2,b*9)},_c:(a,b,c,d)=>{b&&T.uniformMatrix3x2fv(Z(T.cg,a),!!c,v,d>>2,b*6)},Xc:(a,b,c,d)=>{b&&T.uniformMatrix3x4fv(Z(T.cg,a),!!c,v,d>>2,b*12)},Ld:(a,b,c,d)=>{b&&T.uniformMatrix4fv(Z(T.cg,a),!!c,v,d>>2,b*16)},Yc:(a,b,c,d)=>{b&&T.uniformMatrix4x2fv(Z(T.cg,
a),!!c,v,d>>2,b*8)},Wc:(a,b,c,d)=>{b&&T.uniformMatrix4x3fv(Z(T.cg,a),!!c,v,d>>2,b*12)},Kd:a=>{a=U[a];T.useProgram(a);T.cg=a},Jd:a=>{T.validateProgram(U[a])},Id:(a,b)=>T.vertexAttrib1f(a,b),Hd:(a,b)=>{T.vertexAttrib1f(a,v[b>>2])},Gd:(a,b,c)=>T.vertexAttrib2f(a,b,c),Fd:(a,b)=>{T.vertexAttrib2f(a,v[b>>2],v[b+4>>2])},Ed:(a,b,c,d)=>T.vertexAttrib3f(a,b,c,d),Bd:(a,b)=>{T.vertexAttrib3f(a,v[b>>2],v[b+4>>2],v[b+8>>2])},Ad:(a,b,c,d,e)=>T.vertexAttrib4f(a,b,c,d,e),zd:(a,b)=>{T.vertexAttrib4f(a,v[b>>2],v[b+
4>>2],v[b+8>>2],v[b+12>>2])},Lb:Sd,va:Sd,vb:Sd,td:Sd,wb:Sd,Ec:(a,b,c,d,e)=>T.vertexAttribI4i(a,b,c,d,e),Cc:(a,b)=>{T.vertexAttribI4i(a,r[b>>2],r[b+4>>2],r[b+8>>2],r[b+12>>2])},Dc:(a,b,c,d,e)=>T.vertexAttribI4ui(a,b,c,d,e),Bc:(a,b)=>{T.vertexAttribI4ui(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Hc:(a,b,c,d,e)=>{T.vertexAttribIPointer(a,b,c,d,e)},yd:(a,b,c,d,e,g)=>{T.vertexAttribPointer(a,b,c,!!d,e,g)},xd:(a,b,c,d)=>T.viewport(a,b,c,d),_b:(a,b,c)=>{c=Number(c);T.waitSync(kd[a],b,c)},k:()=>0,Qa:(a,b,
c)=>Td(a,{Lh:r[c>>2],sh:r[c+4>>2],wi:r[c+8>>2],oi:b,dh:r[c+12>>2],Uh:r[c+16>>2]}),F:(a,b)=>{a=Q(a);return a?a.requestPointerLock?zc()?Sc(a):b?(xc(Sc,2,[a]),1):-2:-1:-4},Wa:a=>{var b=q.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-ja.buffer.byteLength+65535)/65536|0;try{ja.grow(d);ia();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},q:Ud,r:(a,b,c)=>typeof onbeforeunload==
"undefined"?-1:c!==1?-5:Vd(a,b),C:(a,b,c,d)=>Wd(a,b,c,d,12,"blur"),d:Jc,g:(a,b,c)=>{a=Q(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},D:(a,b,c,d)=>Wd(a,b,c,d,13,"focus"),A:(a,b,c,d)=>{if(!P.fullscreenEnabled())return-1;a=Q(a);if(!a)return-4;Xd(a,b,c,d,"webkitfullscreenchange");return Xd(a,b,c,d,"fullscreenchange")},J:(a,b,c)=>Ud()?-1:Yd(a,b,c,26,"gamepadconnected"),I:(a,b,c)=>Ud()?-1:Yd(a,b,c,27,"gamepaddisconnected"),o:(a,b,c,d)=>Zd(a,b,c,d,2,"keydown"),l:(a,b,c,d)=>Zd(a,
b,c,d,1,"keypress"),m:(a,b,c,d)=>Zd(a,b,c,d,3,"keyup"),Sa:(a,b,c)=>{a=S(a);tc(a,b,c)},e:ic,x:(a,b,c)=>window.screen&&screen.orientation?$d(a,b,c):-1,B:(a,b,c,d)=>document.body?.requestPointerLock?(a=Q(a))?ae(a,b,c,d):-4:-1,z:(a,b,c,d)=>be(a,b,c,d),s:(a,b,c)=>ce(a,b,c),y:(a,b,c,d)=>(a=Q(a))?typeof a.onwheel!="undefined"?de(a,b,c,d):-1:-4,Ta:a=>document.title=a?A(q,a):"",j:()=>{z("Please compile your program with async support in order to use asynchronous operations like emscripten_sleep")},Be:(a,b)=>
{var c=b>>2;b={alpha:!!p[b+0],depth:!!p[b+1],stencil:!!p[b+2],antialias:!!p[b+3],premultipliedAlpha:!!p[b+4],preserveDrawingBuffer:!!p[b+5],powerPreference:ee[r[c+2]],failIfMajorPerformanceCaveat:!!p[b+12],desynchronized:!!p[b+33],Ii:r[c+4],kj:r[c+5],Wh:p[b+24],si:p[b+25],oj:r[c+7],rj:p[b+32]};a=Q(a);return!a||b.si?0:sd(a,b)},G:a=>{td==a&&(td=0);td===gd[a]&&(td=null);typeof P=="object"&&P.Oi(gd[a].Ig.canvas);gd[a]?.Ig.canvas&&(gd[a].Ig.canvas.Rg=void 0);gd[a]=null},H:a=>{td=gd[a];h.ctx=T=td?.Ig;return!a||
T?0:-5},pb:(a,b)=>{var c=0,d=0,e;for(e of he()){var g=b+c;u[a+d>>2]=g;c+=B(e,q,g,Infinity)+1;d+=4}return 0},qb:(a,b)=>{var c=he();u[a>>2]=c.length;a=0;for(var d of c)a+=Ga(d)+1;u[b>>2]=a;return 0},ya:a=>{throw new ua(a);},i:function(a){try{var b=L(a);Eb(b);return 0}catch(c){if(typeof O=="undefined"||c.name!=="ErrnoError")throw c;return c.eg}},u:function(a,b,c,d){try{a:{var e=L(a);a=b;for(var g,f=b=0;f<c;f++){var k=u[a>>2],m=u[a+4>>2];a+=8;try{var n=e,t=k,w=m,C=g,D=p;if(w<0||C<0)throw new E(28);if(n.fd===
null)throw new E(8);if((n.flags&2097155)===1)throw new E(8);if(H(n.node.mode))throw new E(31);if(!n.ag.read)throw new E(28);var G=typeof C!="undefined";if(!G)C=n.position;else if(!n.seekable)throw new E(70);var J=n.ag.read(n,D,t,w,C);G||(n.position+=J);var I=J}catch(X){if(b>0&&X instanceof E&&(X.eg==6||X.eg==6))break;throw X;}if(I<0){var R=-1;break a}b+=I;if(I<m)break;typeof g!="undefined"&&(g+=I)}R=b}u[d>>2]=R;return 0}catch(X){if(typeof O=="undefined"||X.name!=="ErrnoError")throw X;return X.eg}},
bb:function(a,b,c,d){b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;var e=L(a);Fb(e,b,c);y[d>>3]=BigInt(e.position);e.Jg&&!b&&c===0&&(e.Jg=null);return 0}catch(g){if(typeof O=="undefined"||g.name!=="ErrnoError")throw g;return g.eg}},eb:function(a){try{var b=L(a);return b.ag?.Yg?.(b)}catch(c){if(typeof O=="undefined"||c.name!=="ErrnoError")throw c;return c.eg}},n:function(a,b,c,d){try{var e=L(a);a=b;if(c==1)var g=Gb(e,p,u[a>>2],u[a+4>>2]);else{for(var f=b=0,k=a;f<
c;f++,k+=8)b+=u[k+4>>2];var m=new Uint8Array(b);for(f=k=0;f<c;f++,a+=8){var n=u[a>>2],t=u[a+4>>2];m.set(q.subarray(n,n+t),k);k+=t}g=Gb(e,m,0,b)}u[d>>2]=g;return 0}catch(w){if(typeof O=="undefined"||w.name!=="ErrnoError")throw w;return w.eg}},Ua:(a,b)=>Ca(q.subarray(a,a+b))};function Ce(a=[]){var b=Ae;a.unshift("./this.program");var c=a.length,d=Ec((c+1)*4),e=d,g;for(g of a)u[e>>2]=Fc(g),e+=4;u[e>>2]=0;try{var f=b(c,d);throw new ua(f);}catch(k){jc(k)}}
async function De(){ma();Wa&&await Va();var a=h.setStatus;a&&(a("Running..."),await new Promise(b=>setTimeout(b,1)),setTimeout(a,1,""));ha||(h.noFSInit||hb||(hb=!0,yb("/dev/tty","/dev/stdin"),yb("/dev/tty","/dev/stdout"),yb("/dev/tty1","/dev/stderr"),Db("/dev/stdin",0),Db("/dev/stdout",1),Db("/dev/stderr",1)),Ee.Bf(),ib=!1,Ce(aa),oa())}var Ee;
(async function(){var a={a:Be};qa??=ca+"playground_model_viewer.wasm";a=Ee=(await ta(a)).instance.exports;Id=h._malloc=a.Cf;h._free=a.Df;Ae=h._main=a.Ef;se=h._SDL_free=a.Ff;pe=h._SDL_malloc=a.Gf;h._SDL_calloc=a.Hf;le=h._Emscripten_force_free=a.If;h._SDL_realloc=a.Jf;h._CallSDLEmscriptenMainFunction=a.Kf;te=h._Emscripten_HandlePointerEnter=a.Lf;ue=h._Emscripten_HandlePointerLeave=a.Mf;ve=h._Emscripten_HandlePointerGeneric=a.Nf;re=h._Emscripten_HandleMouseButtonUpGlobal=a.Of;we=h._Emscripten_SendDragEvent=
a.Pf;ze=h._Emscripten_SendDragCompleteEvent=a.Qf;xe=h._Emscripten_SendDragTextEvent=a.Rf;ye=h._Emscripten_SendDragFileEvent=a.Sf;qe=h._Emscripten_HandleLockKeysCheck=a.Tf;oe=h._Emscripten_SendSystemThemeChangedEvent=a.Uf;ne=h._requestFullscreenThroughSDL=a.Vf;Hc=a.Xf;Ec=a.Yf;Gc=a.Zf;ja=a.Af;Nc=a.Wf;ia();return Ee})().then(()=>De());
